n2p2 - A neural network potential package: nnp::SymFncExpRadWeighted Class Reference
nnp::SymFncExpRadWeighted Class Reference
Weighted radial symmetry function (type 12)
#include <SymFncExpRadWeighted.h>
Public Member Functions
SymFncExpRadWeighted (ElementMap const &elementMap)
Constructor, sets type = 12.
virtual bool operator== (SymFnc const &rhs) const
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const
Overload < operator.
virtual void setParameters (std::string const &parameterString)
Set symmetry function parameters.
virtual void changeLengthUnit (double convLength)
Change length unit.
virtual std::string getSettingsLine () const
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
virtual std::string parameterLine () const
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
double getEta () const
Get private eta member variable.
double getRs () const
Get private rs member variable.
virtual double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
Public Member Functions inherited from nnp::SymFncBaseCutoff
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
double getCutoffAlpha () const
Get private cutoffAlpha member variable.
std::string getSubtype () const
Get private subtype member variable.
CutoffFunction::CutoffType getCutoffType () const
Get private cutoffType member variable.
Public Member Functions inherited from nnp::SymFnc
virtual ~SymFnc ()
Virtual destructor.
virtual bool operator== (SymFnc const &rhs) const =0
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const =0
Overload < operator.
bool operator!= (SymFnc const &rhs) const
Overload != operator.
bool operator> (SymFnc const &rhs) const
Overload > operator.
bool operator<= (SymFnc const &rhs) const
Overload <= operator.
bool operator>= (SymFnc const &rhs) const
Overload >= operator.
virtual void setParameters (std::string const &parameterString)=0
Set parameters.
virtual void changeLengthUnit (double convLength)=0
Change length unit.
virtual std::string getSettingsLine () const =0
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate symmetry function for one atom.
virtual std::string parameterLine () const =0
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getConvLength () const
Get private convLength member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
virtual double calculateRadialPart (double distance) const =0
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const =0
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const =0
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
void addCacheIndex (std::size_t element, std::size_t cacheIndex, std::string cacheIdentifier)
Add one cache index for given neighbor element and check identifier.
std::vector< std::vector< std::size_t > > getCacheIndices () const
Getter for cacheIndices.
Private Attributes
double eta
Width \(\eta\) of gaussian.
double rs
Shift \(r_s\) of gaussian.
Additional Inherited Members
Public Types inherited from nnp::SymFnc
enum ScalingType {
ST_NONE , ST_SCALE , ST_CENTER , ST_SCALECENTER ,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymFnc
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymFncBaseCutoff
SymFncBaseCutoff (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFnc
SymFnc (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymFnc
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymFncBaseCutoff
double cutoffAlpha
Cutoff parameter \(\alpha\).
std::string subtype
Subtype string (specifies cutoff type).
CutoffFunction fc
Cutoff function used by this symmetry function.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function.
Protected Attributes inherited from nnp::SymFnc
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius \(r_c\).
double scalingFactor
Scaling factor.
double convLength
Data set normalization length conversion factor.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
std::vector< std::vector< std::size_t > > cacheIndices
Cache indices for each element.
Static Protected Attributes inherited from nnp::SymFnc
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Weighted radial symmetry function (type 12)
\[ G^{12}_i = \sum_{j \neq i} Z_j \, \mathrm{e}^{-\eta(r_{ij} - r_\mathrm{s})^2} f_c(r_{ij}) \]
Parameter string:
<element-central> 12 <eta> <rshift> <rcutoff>
where
<element-central> .... element symbol of central atom
<eta> ................ \(\eta\)
<rshift> ............. \(r_\mathrm{s}\)
<rcutoff> ............ \(r_c\)
Definition at line 48 of file SymFncExpRadWeighted.h.
Constructor & Destructor Documentation
SymFncExpRadWeighted()
SymFncExpRadWeighted::SymFncExpRadWeighted (ElementMap const & elementMap)
Constructor, sets type = 12.
Definition at line 29 of file SymFncExpRadWeighted.cpp.
                                                                       :
    SymFncBaseCutoff(12, elementMap),
    eta             (0.0),
    rs              (0.0)
{
    minNeighbors = 1;
    parameters.insert("eta");
    parameters.insert("rs/rl");
}
References nnp::SymFnc::minNeighbors, and nnp::SymFnc::parameters.
Member Function Documentation
operator==()
bool SymFncExpRadWeighted::operator== (SymFnc const & rhs) const virtual
Overload == operator.
Implements nnp::SymFnc.
Definition at line 39 of file SymFncExpRadWeighted.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymFncExpRadWeighted const& c =
        dynamic_cast<SymFncExpRadWeighted const&>(rhs);
    if (cutoffType  != c.cutoffType ) return false;
    if (cutoffAlpha != c.cutoffAlpha) return false;
    if (rc          != c.rc         ) return false;
    if (eta         != c.eta        ) return false;
    if (rs          != c.rs         ) return false;
    return true;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFncBaseCutoff::cutoffType, nnp::SymFnc::ec, eta, nnp::SymFnc::getEc(), nnp::SymFnc::getType(), nnp::SymFnc::rc, rs, and nnp::SymFnc::type.
operator<()
bool SymFncExpRadWeighted::operator< (SymFnc const & rhs) const virtual
Overload < operator.
Implements nnp::SymFnc.
Definition at line 53 of file SymFncExpRadWeighted.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymFncExpRadWeighted const& c =
        dynamic_cast<SymFncExpRadWeighted const&>(rhs);
    if      (cutoffType  < c.cutoffType ) return true;
    else if (cutoffType  > c.cutoffType ) return false;
    if      (cutoffAlpha < c.cutoffAlpha) return true;
    else if (cutoffAlpha > c.cutoffAlpha) return false;
    if      (rc          < c.rc         ) return true;
    else if (rc          > c.rc         ) return false;
    if      (eta         < c.eta        ) return true;
    else if (eta         > c.eta        ) return false;
    if      (rs          < c.rs         ) return true;
    else if (rs          > c.rs         ) return false;
    return false;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFncBaseCutoff::cutoffType, nnp::SymFnc::ec, eta, nnp::SymFnc::getEc(), nnp::SymFnc::getType(), nnp::SymFnc::rc, rs, and nnp::SymFnc::type.
setParameters()
void SymFncExpRadWeighted::setParameters (std::string const & parameterString) virtual
Set symmetry function parameters.
Parameters
[in] parameterString String containing weighted radial symmetry function parameters.
Implements nnp::SymFnc.
Definition at line 74 of file SymFncExpRadWeighted.cpp.
{
    vector<string> splitLine = split(reduce(parameterString));
    if (type != (size_t)atoi(splitLine.at(1).c_str()))
    {
        throw runtime_error("ERROR: Incorrect symmetry function type.\n");
    }
    ec   = elementMap[splitLine.at(0)];
    eta  = atof(splitLine.at(2).c_str());
    rs   = atof(splitLine.at(3).c_str());
    rc   = atof(splitLine.at(4).c_str());
    fc.setCutoffRadius(rc);
    fc.setCutoffParameter(cutoffAlpha);
    return;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFnc::ec, nnp::SymFnc::elementMap, eta, nnp::SymFncBaseCutoff::fc, nnp::SymFnc::rc, nnp::reduce(), rs, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::split(), and nnp::SymFnc::type.
changeLengthUnit()
void SymFncExpRadWeighted::changeLengthUnit (double convLength) virtual
Change length unit.
Parameters
[in] convLength Multiplicative length unit conversion factor.
Implements nnp::SymFnc.
Definition at line 94 of file SymFncExpRadWeighted.cpp.
{
    this->convLength = convLength;
    eta /= convLength * convLength;
    rs *= convLength;
    rc *= convLength;
    fc.setCutoffRadius(rc);
    fc.setCutoffParameter(cutoffAlpha);
    return;
}
References nnp::SymFnc::convLength, nnp::SymFncBaseCutoff::cutoffAlpha, eta, nnp::SymFncBaseCutoff::fc, nnp::SymFnc::rc, rs, nnp::CutoffFunction::setCutoffParameter(), and nnp::CutoffFunction::setCutoffRadius().
getSettingsLine()
string SymFncExpRadWeighted::getSettingsLine () const virtual
Get settings file line from currently set parameters.
Returns
Settings file string ("symfunction_short ...").
Implements nnp::SymFnc.
Definition at line 107 of file SymFncExpRadWeighted.cpp.
{
    string s = strpr("symfunction_short %2s %2zu %16.8E %16.8E %16.8E\n",
                     elementMap[ec].c_str(),
                     type,
                     eta * convLength * convLength,
                     rs / convLength,
                     rc / convLength);
    return s;
}
References nnp::SymFnc::convLength, nnp::SymFnc::ec, nnp::SymFnc::elementMap, eta, nnp::SymFnc::rc, rs, nnp::strpr(), and nnp::SymFnc::type.
calculate()
void SymFncExpRadWeighted::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymFnc.
Definition at line 119 of file SymFncExpRadWeighted.cpp.
{
    double result = 0.0;
    for (size_t j = 0; j < atom.numNeighbors; ++j)
    {
        Atom::Neighbor& n = atom.neighbors[j];
        if (n.d < rc)
        {
            // Energy calculation.
            size_t const ne = n.element;
            double const rij = n.d;
            double const pexp = elementMap.atomicNumber(n.element)
                              * exp(-eta * (rij - rs) * (rij - rs));
            // Calculate cutoff function and derivative.
            double pfc;
            double pdfc;
#ifndef N2P2_NO_SF_CACHE
            if (cacheIndices[ne].size() == 0) fc.fdf(rij, pfc, pdfc);
            else
            {
                double& cfc = n.cache[cacheIndices[ne][0]];
                double& cdfc = n.cache[cacheIndices[ne][1]];
                if (cfc < 0) fc.fdf(rij, cfc, cdfc);
                pfc = cfc;
                pdfc = cdfc;
            }
#else
            fc.fdf(rij, pfc, pdfc);
#endif
            result += pexp * pfc;
            // Force calculation.
            if (!derivatives) continue;
            double const p1 = scalingFactor
                * (pdfc - 2.0 * eta * (rij - rs)
                * pfc) * pexp / rij;
            Vec3D dij = p1 * n.dr;
            // Save force contributions in Atom storage.
            atom.dGdr[index] += dij;
#ifndef N2P2_FULL_SFD_MEMORY
            n.dGdr[indexPerElement[ne]] -= dij;
#else
            n.dGdr[index] -= dij;
#endif
        }
    }
    atom.G[index] = scale(result);
    return;
}
References nnp::ElementMap::atomicNumber(), nnp::Atom::Neighbor::cache, nnp::SymFnc::cacheIndices, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::Atom::Neighbor::element, nnp::SymFnc::elementMap, eta, nnp::SymFncBaseCutoff::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymFnc::index, nnp::SymFnc::indexPerElement, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::SymFnc::rc, rs, nnp::SymFnc::scale(), and nnp::SymFnc::scalingFactor.
parameterLine()
string SymFncExpRadWeighted::parameterLine () const virtual
Give symmetry function parameters in one line.
Returns
String containing symmetry function parameter values.
Implements nnp::SymFnc.
Definition at line 172 of file SymFncExpRadWeighted.cpp.
{
    return strpr(getPrintFormat().c_str(),
                 index + 1,
                 elementMap[ec].c_str(),
                 type,
                 subtype.c_str(),
                 eta * convLength * convLength,
                 rs / convLength,
                 rc / convLength,
                 cutoffAlpha,
                 lineNumber + 1);
}
References nnp::SymFnc::convLength, nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFnc::ec, nnp::SymFnc::elementMap, eta, nnp::SymFnc::getPrintFormat(), nnp::SymFnc::index, nnp::SymFnc::lineNumber, nnp::SymFnc::rc, rs, nnp::strpr(), nnp::SymFncBaseCutoff::subtype, and nnp::SymFnc::type.
parameterInfo()
vector< string > SymFncExpRadWeighted::parameterInfo () const virtual
Get description with parameter names and values.
Returns
Vector of parameter description strings.
Reimplemented from nnp::SymFncBaseCutoff.
Definition at line 186 of file SymFncExpRadWeighted.cpp.
{
    vector<string> v = SymFncBaseCutoff::parameterInfo();
    string s;
    size_t w = sfinfoWidth;
    s = "eta";
    v.push_back(strpr((pad(s, w) + "%14.8E").c_str(),
                      eta * convLength * convLength));
    s = "rs";
    v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), rs / convLength));
    return v;
}
References nnp::SymFnc::convLength, eta, nnp::pad(), nnp::SymFncBaseCutoff::parameterInfo(), rs, nnp::SymFnc::sfinfoWidth, and nnp::strpr().
getEta()
double nnp::SymFncExpRadWeighted::getEta () const inline
Get private eta member variable.
Definition at line 140 of file SymFncExpRadWeighted.h.
{ return eta; }
References eta.
getRs()
double nnp::SymFncExpRadWeighted::getRs () const inline
Get private rs member variable.
Definition at line 141 of file SymFncExpRadWeighted.h.
{ return rs; }
References rs.
calculateRadialPart()
double SymFncExpRadWeighted::calculateRadialPart (double distance) const virtual
Calculate (partial) symmetry function value for one given distance.
Parameters
[in] distance Distance between two atoms.
Returns
\(e^{-\eta (r - r_s)^2} f_c(r)\)
Implements nnp::SymFnc.
Definition at line 201 of file SymFncExpRadWeighted.cpp.
{
    double const& r = distance * convLength;
    return exp(-eta * (r - rs) * (r - rs)) * fc.f(r);
}
References nnp::SymFnc::convLength, eta, nnp::CutoffFunction::f(), nnp::SymFncBaseCutoff::fc, and rs.
calculateAngularPart()
double SymFncExpRadWeighted::calculateAngularPart (double angle) const virtual
Calculate (partial) symmetry function value for one given angle.
Parameters
[in] angle Angle between triplet of atoms (in radians).
Returns
\(1\)
Implements nnp::SymFnc.
Definition at line 208 of file SymFncExpRadWeighted.cpp.
{
    return 1.0;
}
checkRelevantElement()
bool SymFncExpRadWeighted::checkRelevantElement (std::size_t index) const virtual
Check whether symmetry function is relevant for given element.
Parameters
[in] index Index of given element.
Returns
True if symmetry function is sensitive to given element, false otherwise.
Implements nnp::SymFnc.
Definition at line 213 of file SymFncExpRadWeighted.cpp.
{
    return true;
}
getCacheIdentifiers()
vector< string > SymFncExpRadWeighted::getCacheIdentifiers () const virtual
Get unique cache identifiers.
Returns
Vector of string identifying the type of cache this symmetry function requires.
Reimplemented from nnp::SymFnc.
Definition at line 219 of file SymFncExpRadWeighted.cpp.
{
    vector<string> v;
    string s("");
    s += subtype;
    s += " ";
    s += strpr("alpha = %16.8E", cutoffAlpha);
    s += " ";
    s += strpr("rc = %16.8E", rc / convLength);
    for (size_t i = 0; i < elementMap.size(); ++i)
    {
        v.push_back(strpr("%zu f ", i) + s);
        v.push_back(strpr("%zu df ", i) + s);
    }
    return v;
}
References nnp::SymFnc::convLength, nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFnc::elementMap, nnp::SymFnc::rc, nnp::ElementMap::size(), nnp::strpr(), and nnp::SymFncBaseCutoff::subtype.
Member Data Documentation
eta
double nnp::SymFncExpRadWeighted::eta private
Width \(\eta\) of gaussian.
Definition at line 131 of file SymFncExpRadWeighted.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getEta(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
rs
double nnp::SymFncExpRadWeighted::rs private
Shift \(r_s\) of gaussian.
Definition at line 133 of file SymFncExpRadWeighted.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getRs(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncExpRadWeighted.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncExpRadWeighted.cpp