n2p2 - A neural network potential package: nnp::Prediction Class Reference
nnp::Prediction Class Reference
#include <Prediction.h>
Public Member Functions
Prediction ()
void readStructureFromFile (std::string const &fileName="input.data")
void setup ()
void predict ()
Public Member Functions inherited from nnp::Mode
Mode ()
void initialize ()
Write welcome message with version information.
void loadSettingsFile (std::string const &fileName="input.nn")
Open settings file and load all keywords into memory.
void setupGeneric (bool skipNormalize=false)
Combine multiple setup routines and provide a basic NNP setup.
void setupNormalization (bool standalone=true)
Set up normalization.
virtual void setupElementMap ()
Set up the element map.
virtual void setupElements ()
Set up all Element instances.
void setupCutoff ()
Set up cutoff function for all symmetry functions.
virtual void setupSymmetryFunctions ()
Set up all symmetry functions.
void setupSymmetryFunctionScalingNone ()
Set up "empy" symmetry function scaling.
virtual void setupSymmetryFunctionScaling (std::string const &fileName="scaling.data")
Set up symmetry function scaling from file.
virtual void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
virtual void setupSymmetryFunctionCache (bool verbose=false)
Set up symmetry function cache.
void setupSymmetryFunctionMemory (bool verbose=false)
Extract required memory dimensions for symmetry function derivatives.
void setupSymmetryFunctionStatistics (bool collectStatistics, bool collectExtrapolationWarnings, bool writeExtrapolationWarnings, bool stopOnExtrapolationWarnings)
Set up symmetry function statistics collection.
virtual void setupNeuralNetwork ()
Set up neural networks for all elements.
virtual void setupNeuralNetworkWeights (std::string const &fileNameFormatShort="weights.%03zu.data", std::string const &fileNameFormatCharge="weightse.%03zu.data")
Set up neural network weights from files.
void calculateSymmetryFunctions (Structure &structure, bool const derivatives)
Calculate all symmetry functions for all atoms in given structure.
void calculateSymmetryFunctionGroups (Structure &structure, bool const derivatives)
Calculate all symmetry function groups for all atoms in given structure.
void calculateAtomicNeuralNetworks (Structure &structure, bool const derivatives)
Calculate a single atomic neural network for a given atom and nn type.
void calculateEnergy (Structure &structure) const
Calculate potential energy for a given structure.
void calculateCharge (Structure &structure) const
Calculate total charge for a given structure.
void calculateForces (Structure &structure) const
Calculate forces for all atoms in given structure.
void addEnergyOffset (Structure &structure, bool ref=true)
Add atomic energy offsets to reference energy.
void removeEnergyOffset (Structure &structure, bool ref=true)
Remove atomic energy offsets from reference energy.
double getEnergyOffset (Structure const &structure) const
Get atomic energy offset for given structure.
double getEnergyWithOffset (Structure const &structure, bool ref=true) const
Add atomic energy offsets and return energy.
double normalized (std::string const &property, double value) const
Apply normalization to given property.
double normalizedEnergy (Structure const &structure, bool ref=true) const
Apply normalization to given energy of structure.
double physical (std::string const &property, double value) const
Undo normalization for a given property.
double physicalEnergy (Structure const &structure, bool ref=true) const
Undo normalization for a given energy of structure.
void convertToNormalizedUnits (Structure &structure) const
Convert one structure to normalized units.
void convertToPhysicalUnits (Structure &structure) const
Convert one structure to physical units.
std::size_t getNumExtrapolationWarnings () const
Count total number of extrapolation warnings encountered for all elements and symmetry functions.
void resetExtrapolationWarnings ()
Erase all extrapolation warnings and reset counters.
NNPType getNnpType () const
Getter for Mode::nnpType.
double getMeanEnergy () const
Getter for Mode::meanEnergy.
double getConvEnergy () const
Getter for Mode::convEnergy.
double getConvLength () const
Getter for Mode::convLength.
double getMaxCutoffRadius () const
Getter for Mode::maxCutoffRadius.
std::size_t getNumElements () const
Getter for Mode::numElements.
std::vector< std::size_t > getNumSymmetryFunctions () const
Get number of symmetry functions per element.
bool useNormalization () const
Check if normalization is enabled.
bool settingsKeywordExists (std::string const &keyword) const
Check if keyword was found in settings file.
std::string settingsGetValue (std::string const &keyword) const
Get value for given keyword in Settings instance.
std::vector< std::size_t > pruneSymmetryFunctionsRange (double threshold)
Prune symmetry functions according to their range and write settings file.
std::vector< std::size_t > pruneSymmetryFunctionsSensitivity (double threshold, std::vector< std::vector< double > > sensitivity)
Prune symmetry functions with sensitivity analysis data.
void writePrunedSettingsFile (std::vector< std::size_t > prune, std::string fileName="output.nn") const
Copy settings file but comment out lines provided.
void writeSettingsFile (std::ofstream *const &file) const
Write complete settings file.
Public Attributes
std::string fileNameSettings
std::string fileNameScaling
std::string formatWeightsFilesShort
std::string formatWeightsFilesCharge
Structure structure
Public Attributes inherited from nnp::Mode
ElementMap elementMap
Global element map, populated by setupElementMap().
Log log
Global log file.
Additional Inherited Members
Public Types inherited from nnp::Mode
enum NNPType { NNPType::SHORT_ONLY, NNPType::SHORT_CHARGE_NN }
Protected Member Functions inherited from nnp::Mode
void readNeuralNetworkWeights (std::string const &type, std::string const &fileName)
Read in weights for a specific type of neural network.
Protected Attributes inherited from nnp::Mode
NNPType nnpType
bool normalize
bool checkExtrapolationWarnings
bool useChargeNN
std::size_t numElements
std::vector< std::size_t > minNeighbors
std::vector< double > minCutoffRadius
double maxCutoffRadius
double cutoffAlpha
double meanEnergy
double convEnergy
double convLength
Settings settings
SymFnc::ScalingType scalingType
CutoffFunction::CutoffType cutoffType
std::vector< Element > elements
Detailed Description
Definition at line 27 of file Prediction.h.
Constructor & Destructor Documentation
Prediction()
Prediction::Prediction ()
Definition at line 25 of file Prediction.cpp.
                        : Mode(),
                            fileNameSettings        ("input.nn"          ),
                            fileNameScaling         ("scaling.data"      ),
                            formatWeightsFilesShort ("weights.%03zu.data" ),
                            formatWeightsFilesCharge("weightse.%03zu.data")
 {
 }
Member Function Documentation
readStructureFromFile()
void Prediction::readStructureFromFile (std::string const & fileName = "input.data")
Definition at line 44 of file Prediction.cpp.
 {
     ifstream file;
     file.open(fileName.c_str());
     structure.reset();
     structure.setElementMap(elementMap);
     structure.readFromFile(fileName);
     removeEnergyOffset(structure);
     if (normalize)
     {
         structure.toNormalizedUnits(meanEnergy, convEnergy, convLength);
     }
     file.close();
     return;
 }
References nnp::Mode::convEnergy, nnp::Mode::convLength, nnp::Mode::elementMap, nnp::Mode::meanEnergy, nnp::Mode::normalize, nnp::Structure::readFromFile(), nnp::Mode::removeEnergyOffset(), nnp::Structure::reset(), nnp::Structure::setElementMap(), structure, and nnp::Structure::toNormalizedUnits().
Referenced by main().
setup()
void Prediction::setup ()
Definition at line 33 of file Prediction.cpp.
 {
     initialize();
     loadSettingsFile(fileNameSettings);
     setupGeneric();
     setupSymmetryFunctionScaling(fileNameScaling);
     setupNeuralNetworkWeights(formatWeightsFilesShort,
                               formatWeightsFilesCharge);
     setupSymmetryFunctionStatistics(false, false, true, false);
 }
References fileNameScaling, fileNameSettings, formatWeightsFilesCharge, formatWeightsFilesShort, nnp::Mode::initialize(), nnp::Mode::loadSettingsFile(), nnp::Mode::setupGeneric(), nnp::Mode::setupNeuralNetworkWeights(), nnp::Mode::setupSymmetryFunctionScaling(), and nnp::Mode::setupSymmetryFunctionStatistics().
Referenced by main().
predict()
void Prediction::predict ()
Definition at line 61 of file Prediction.cpp.
 {
     structure.calculateNeighborList(maxCutoffRadius);
 #ifdef N2P2_NO_SF_GROUPS
     calculateSymmetryFunctions(structure, true);
 #else
     calculateSymmetryFunctionGroups(structure, true);
 #endif
     calculateAtomicNeuralNetworks(structure, true);
     calculateEnergy(structure);
     if (nnpType == NNPType::SHORT_CHARGE_NN) calculateCharge(structure);
     calculateForces(structure);
     if (normalize)
     {
         structure.toPhysicalUnits(meanEnergy, convEnergy, convLength);
     }
     addEnergyOffset(structure, false);
     addEnergyOffset(structure, true);
     return;
 }
References nnp::Mode::addEnergyOffset(), nnp::Mode::calculateAtomicNeuralNetworks(), nnp::Mode::calculateCharge(), nnp::Mode::calculateEnergy(), nnp::Mode::calculateForces(), nnp::Structure::calculateNeighborList(), nnp::Mode::calculateSymmetryFunctionGroups(), nnp::Mode::calculateSymmetryFunctions(), nnp::Mode::convEnergy, nnp::Mode::convLength, nnp::Mode::maxCutoffRadius, nnp::Mode::meanEnergy, nnp::Mode::nnpType, nnp::Mode::normalize, nnp::Mode::SHORT_CHARGE_NN, structure, and nnp::Structure::toPhysicalUnits().
Referenced by main().
Member Data Documentation
fileNameSettings
std::string nnp::Prediction::fileNameSettings
Definition at line 35 of file Prediction.h.
Referenced by setup().
fileNameScaling
std::string nnp::Prediction::fileNameScaling
Definition at line 36 of file Prediction.h.
Referenced by setup().
formatWeightsFilesShort
std::string nnp::Prediction::formatWeightsFilesShort
Definition at line 37 of file Prediction.h.
Referenced by setup().
formatWeightsFilesCharge
std::string nnp::Prediction::formatWeightsFilesCharge
Definition at line 38 of file Prediction.h.
Referenced by setup().
structure
Structure nnp::Prediction::structure
Definition at line 39 of file Prediction.h.
Referenced by main(), predict(), and readStructureFromFile().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/Prediction.h
/home/runner/work/n2p2/n2p2/src/libnnp/Prediction.cpp