n2p2 - A neural network potential package: nnp::settings::Settings Class Reference
nnp::settings::Settings Class Reference
Reads and analyzes settings file and stores parameters.
#include <Settings.h>
Public Types
typedef std::multimap< std::string, std::pair< std::string, std::size_t > > KeyMap
typedef std::pair< KeyMap::const_iterator, KeyMap::const_iterator > KeyRange
typedef std::map< std::string, std::shared_ptr< Key > > const KeywordList
Public Member Functions
std::string operator[] (std::string const &keyword) const
Overload [] operator.
std::size_t loadFile (std::string const &fileName="input.nn")
Load a file with settings.
bool keywordExists (Key const &key, bool const exact=false) const override
bool keywordExists (std::string const &keyword, bool exact=false) const
Check if keyword is present in settings file.
std::string keywordCheck (std::string const &keyword) const
Check for keyword and alternatives, throw exception if not present.
std::string getValue (Key const &key) const override
std::string getValue (std::string const &keyword) const
Get value for given keyword.
KeyRange getValues (std::string const &keyword) const
Get all keyword-value pairs for given keyword.
std::vector< std::string > info () const
Get logged information about settings file.
std::vector< std::string > getSettingsLines () const
Get complete settings file.
void writeSettingsFile (std::ofstream *const &file, std::map< std::size_t, std::string > const &replacements={}) const
Write complete settings file.
virtual bool keywordExists (Key const &key, bool const exact=false) const =0
virtual std::string getValue (Key const &key) const =0
Private Member Functions
void readFile ()
Read file once and save all lines in lines vector.
std::size_t parseLines ()
Parse lines and create contents map.
std::pair< std::size_t, std::size_t > sanityCheck ()
Check if all keywords are in known-keywords database and for duplicates.
Private Attributes
std::vector< std::string > lines
Vector of all lines in settings file.
std::vector< std::string > log
Vector with log lines.
KeyMap contents
Map containing all keyword-value pairs.
std::string fileName
Settings file name.
Static Private Attributes
static KeywordList knownKeywords = createKnownKeywordsMap()
Map containing all known keywords and a description.
Detailed Description
Reads and analyzes settings file and stores parameters.
Definition at line 37 of file Settings.h.
Member Typedef Documentation
KeyMap
typedef std::multimap<std::string, std::pair<std::string, std::size_t> > nnp::settings::Settings::KeyMap
Definition at line 42 of file Settings.h.
KeyRange
typedef std::pair<KeyMap::const_iterator, KeyMap::const_iterator> nnp::settings::Settings::KeyRange
Definition at line 44 of file Settings.h.
KeywordList
typedef std::map<std::string, std::shared_ptr<Key> > const nnp::settings::Settings::KeywordList
Definition at line 46 of file Settings.h.
Member Function Documentation
operator[]()
string Settings::operator[] (std::string const & keyword) const
Overload [] operator.
Parameters
[in] keyword Keyword string.
Returns
Value string corresponding to keyword.
Internally calls getValue().
Definition at line 181 of file Settings.cpp.
{
    return getValue(keyword);
}
References getValue().
loadFile()
size_t Settings::loadFile (std::string const & fileName = "input.nn")
Load a file with settings.
Parameters
[in] fileName Name of file containing settings.
Returns
Number of critical problems detected.
Definition at line 187 of file Settings.cpp.
{
    this->fileName = fileName;
    readFile();
    return parseLines();
}
References fileName, parseLines(), and readFile().
Referenced by nnp::Mode::loadSettingsFile().
keywordExists() [1/2]
bool Settings::keywordExists (Key const & key, bool const exact = false) const override virtual
Implements nnp::settings::ISettings.
Definition at line 194 of file Settings.cpp.
{
    return keywordExists(key.getMainKeyword(), exact);
}
References nnp::settings::Key::getMainKeyword(), and keywordExists().
Referenced by nnp::Training::dataSetNormalization(), nnp::Training::initializeWeights(), keywordCheck(), keywordExists(), nnp::Mode::loadSettingsFile(), nnp::Training::randomizeNeuralNetworkWeights(), nnp::Training::setStage(), nnp::Mode::settingsKeywordExists(), nnp::Mode::setupElectrostatics(), nnp::Mode::setupElements(), nnp::Training::setupFileOutput(), nnp::Mode::setupNeuralNetwork(), nnp::Mode::setupNormalization(), nnp::Training::setupSelectionMode(), nnp::Mode::setupSymmetryFunctionScaling(), nnp::Training::setupTraining(), and nnp::Training::setupUpdatePlan().
keywordExists() [2/2]
bool Settings::keywordExists (std::string const & keyword, bool exact = false) const
Check if keyword is present in settings file.
Parameters
[in] keyword Keyword string.
[in] exact If True check only for exact spelling, no alternative keywords allowed.
Returns
True if keyword exists, False otherwise.
Note
This throws an error if the keyword is not in the list of known keywords.
Definition at line 199 of file Settings.cpp.
{
    if (knownKeywords.find(keyword) == knownKeywords.end())
    {
        throw runtime_error("ERROR: Not in the list of allowed keyword: \"" +
                            keyword + "\".\n");
    }
    if (exact || knownKeywords.at(keyword)->hasUniqueKeyword())
    {
        return (contents.find(keyword) != contents.end());
    }
    else
    {
        for (auto alternative : *knownKeywords.at(keyword))
        {
            if (contents.find(alternative) != contents.end()) return true;
        }
    }
    return false;
}
References contents, and knownKeywords.
keywordCheck()
string Settings::keywordCheck (std::string const & keyword) const
Check for keyword and alternatives, throw exception if not present.
Parameters
[in] keyword Original keyword for which alternatives should be searched.
Returns
Keyword or alternative found in file contents.
Definition at line 221 of file Settings.cpp.
{
    bool exists = keywordExists(keyword, false);
    bool unique = knownKeywords.at(keyword)->hasUniqueKeyword();
    if (!exists)
    {
        if (unique)
        {
            throw std::runtime_error("ERROR: Keyword \"" + keyword
                                     + "\" not found.\n");
        }
        else
        {
            throw std::runtime_error("ERROR: Neither keyword \"" + keyword
                                     + "\" nor alternative keywords found.\n");
        }
    }
    bool exact = keywordExists(keyword, true);
    if (!exact)
    {
        for (auto const& alt : *knownKeywords.at(keyword))
        {
            if (contents.find(alt) != contents.end()) return alt;
        }
    }
    return keyword;
}
References contents, keywordExists(), and knownKeywords.
Referenced by getValue(), and getValues().
getValue() [1/2]
string Settings::getValue (Key const & key) const override virtual
Implements nnp::settings::ISettings.
Definition at line 251 of file Settings.cpp.
{
    return contents.find(key.getMainKeyword())->second.first;
}
References contents, and nnp::settings::Key::getMainKeyword().
Referenced by operator[](), and nnp::Mode::settingsGetValue().
getValue() [2/2]
string Settings::getValue (std::string const & keyword) const
Get value for given keyword.
Parameters
[in] keyword Keyword string.
Returns
Value string corresponding to keyword.
If keyword is present multiple times only the value of the first keyword-value pair is returned (use getValues() instead).
Definition at line 256 of file Settings.cpp.
{
    return contents.find(keywordCheck(keyword))->second.first;
}
References contents, and keywordCheck().
getValues()
Settings::KeyRange Settings::getValues (std::string const & keyword) const
Get all keyword-value pairs for given keyword.
Parameters
[in] keyword Keyword string.
Returns
Pair with begin and end values for iteration.
Useful if keyword appears multiple times. Returns a pair representing begin and end for an iterator over all corresponding keyword-value pairs. Use like this:
Settings* s = new Settings("input.nn");
Settings::KeyRange r = s->getValues("symfunction_short");
for (Settings::KeyMap::const_iterator i = r.first; i != r.second; i++)
{
    cout << "keyword: " << i->first
         << " value: " << i->second.first
         << " line : " << i->second.second << "\n";
}
Definition at line 261 of file Settings.cpp.
{
    return contents.equal_range(keywordCheck(keyword));
}
References contents, and keywordCheck().
Referenced by nnp::Mode::setupElectrostatics(), nnp::Mode::setupElements(), nnp::Mode::setupNeuralNetwork(), and nnp::Mode::setupSymmetryFunctions().
info()
vector< string > Settings::info () const
Get logged information about settings file.
Returns
Vector with log lines.
Definition at line 266 of file Settings.cpp.
{
    return log;
}
References log.
Referenced by nnp::Mode::loadSettingsFile().
getSettingsLines()
vector< string > Settings::getSettingsLines () const
Get complete settings file.
Returns
Vector with settings file lines.
Definition at line 271 of file Settings.cpp.
{
    return lines;
}
References lines.
Referenced by nnp::Training::dataSetNormalization(), and nnp::Mode::writePrunedSettingsFile().
writeSettingsFile()
void Settings::writeSettingsFile (std::ofstream *const & file, std::map< std::size_t, std::string > const & replacements = {}) const
Write complete settings file.
Parameters
[in,out] file Settings file.
[in] replacements Map of line numbers with alternative content.
Definition at line 301 of file Settings.cpp.
{
    if (!file->is_open())
    {
        runtime_error("ERROR: Could not write to file.\n");
    }
    size_t i = 0;
    for (auto const& l : lines)
    {
        if (replacements.find(i) != replacements.end())
        {
            (*file) << replacements.at(i);
        }
        else (*file) << l << '\n';
        i++;
    }
    return;
}
References lines.
Referenced by nnp::Training::dataSetNormalization(), and nnp::Mode::writeSettingsFile().
readFile()
void Settings::readFile () private
Read file once and save all lines in lines vector.
Definition at line 276 of file Settings.cpp.
{
    ifstream file;
    string   line;
    log.push_back(strpr("Settings file name: %s\n", fileName.c_str()));
    file.open(fileName.c_str());
    if (!file.is_open())
    {
        throw runtime_error("ERROR: Could not open file: \"" + fileName
                            + "\".\n");
    }
    while (getline(file, line))
    {
        lines.push_back(line);
    }
    file.close();
    log.push_back(strpr("Read %zu lines.\n", lines.size()));
    return;
}
References fileName, lines, log, and nnp::strpr().
Referenced by loadFile().
parseLines()
size_t Settings::parseLines () private
Parse lines and create contents map.
Returns
Number of critical problems detected.
Definition at line 323 of file Settings.cpp.
{
    for (size_t i = 0; i < lines.size(); ++i)
    {
        string line = lines.at(i);
        // ignore empty and comment lines
        if (line.empty())
        {
            continue;
        }
        // check for empty lines in Windows format
        if (line == "\r")
        {
            continue;
        }
        if (line.find('#') != string::npos)
        {
            line.erase(line.find('#'));
        }
        if (line.find('!') != string::npos)
        {
            line.erase(line.find('!'));
        }
        if (line.find_first_not_of(' ') == string::npos)
        {
            continue;
        }
        // remove leading and trailing whitespaces and trim separating spaces
        line = reduce(line);
        // find separator position
        size_t const separatorPosition = line.find_first_of(" ");
        string key;
        pair<string, size_t> value;
        if (separatorPosition == string::npos)
        {
            // first check for single keyword without value
            key = line;
            value = pair<string, size_t>("", i);
        }
        else
        {
            // one or more arguments
            key = line.substr(0, separatorPosition);
            value = pair<string, size_t>(line.erase(0, separatorPosition + 1),
                                         i);
        }
        contents.insert(pair<string, pair<string, size_t> >(key, value));
    }
    size_t numProblems = 0;
    size_t numCritical = 0;
    tie(numProblems, numCritical) = sanityCheck();
    if (numProblems > 0)
    {
        log.push_back(strpr("WARNING: %zu problems detected (%zu critical).\n",
                            numProblems, numCritical));
    }
    log.push_back(strpr("Found %zu lines with keywords.\n", contents.size()));
    return numCritical;
}
References contents, lines, log, nnp::reduce(), sanityCheck(), and nnp::strpr().
Referenced by loadFile().
sanityCheck()
pair< size_t, size_t > Settings::sanityCheck () private
Check if all keywords are in known-keywords database and for duplicates.
Returns
Number of detected/critical problems.
Definition at line 391 of file Settings.cpp.
{
    size_t countProblems = 0;
    size_t countCritical = 0;
    // check for unknown keywords
    for (multimap<string, pair<string, size_t> >::const_iterator
         it = contents.begin(); it != contents.end(); ++it)
    {
        if (knownKeywords.find((*it).first) == knownKeywords.end())
        {
            countProblems++;
            log.push_back(strpr(
                "WARNING: Unknown keyword \"%s\" at line %zu.\n",
                (*it).first.c_str(),
                (*it).second.second + 1));
        }
    }
    // check for multiple instances of known keywords (with exceptions)
    for (KeywordList::const_iterator it = knownKeywords.begin();
         it != knownKeywords.end(); ++it)
    {
        if (contents.count((*it).first) > 1
            && (*it).first != "symfunction"
            && (*it).first != "symfunction_short"
            && (*it).first != "atom_energy"
            && (*it).first != "element_nodes_short"
            && (*it).first != "fixed_gausswidth"
            && (*it).first != "initial_hardness")
        {
            countProblems++;
            countCritical++;
            log.push_back(strpr(
                "WARNING (CRITICAL): Multiple instances of \"%s\" detected.\n",
                (*it).first.c_str()));
        }
    }
    // Check for usage of multiple keyword versions.
    for (KeywordList::const_iterator it = knownKeywords.begin();
         it != knownKeywords.end(); ++it)
    {
        if (it->second->hasUniqueKeyword()) continue;
        vector<string> duplicates;
        for (auto keyword : *it->second)
        {
            if (contents.find(keyword) != contents.end())
            {
                duplicates.push_back(keyword);
            }
        }
        if (duplicates.size() > 1)
        {
            countProblems++;
            countCritical++;
            log.push_back(strpr(
                "WARNING (CRITICAL): Multiple alternative versions of keyword "
                "\"%s\" detected:.\n", (*it).first.c_str()));
            for (auto d : duplicates)
            {
                log.push_back(strpr(
                    "                    - \"%s\"\n", d.c_str()));
            }
        }
    }
    return make_pair(countProblems, countCritical);
}
References contents, d, knownKeywords, log, and nnp::strpr().
Referenced by parseLines().
Member Data Documentation
lines
std::vector<std::string> nnp::settings::Settings::lines private
Vector of all lines in settings file.
Definition at line 143 of file Settings.h.
Referenced by getSettingsLines(), parseLines(), readFile(), and writeSettingsFile().
log
std::vector<std::string> nnp::settings::Settings::log private
Vector with log lines.
Definition at line 145 of file Settings.h.
Referenced by info(), parseLines(), readFile(), and sanityCheck().
contents
KeyMap nnp::settings::Settings::contents private
Map containing all keyword-value pairs.
Definition at line 147 of file Settings.h.
Referenced by getValue(), getValues(), keywordCheck(), keywordExists(), parseLines(), and sanityCheck().
knownKeywords
Settings::KeywordList Settings::knownKeywords = createKnownKeywordsMap() static private
Map containing all known keywords and a description.
Definition at line 149 of file Settings.h.
Referenced by keywordCheck(), keywordExists(), and sanityCheck().
fileName
std::string nnp::settings::Settings::fileName private
Settings file name.
Definition at line 151 of file Settings.h.
Referenced by loadFile(), and readFile().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/Settings.h
/home/runner/work/n2p2/n2p2/src/libnnp/Settings.cpp