n2p2 - A neural network potential package: nnp::ElementMap Class Reference
nnp::ElementMap Class Reference
Contains element map.
#include <ElementMap.h>
Public Member Functions
std::string operator[] (std::size_t const index) const
Overload [] operator for index search.
std::size_t operator[] (std::string const symbol) const
Overload [] operator for symbol search.
std::size_t size () const
Get element map size.
std::string getElementsString () const
Get sorted list of elements in one string (space separated).
std::size_t index (std::string const &symbol) const
Get index of given element.
std::string symbol (std::size_t const index) const
Get element symbol for given element index.
std::size_t atomicNumber (std::size_t index) const
Get atomic number from element index.
std::size_t registerElements (std::string const &elementLine)
Extract all elements and store in element map.
void deregisterElements ()
Clear element map.
std::vector< std::string > info () const
Get map information as a vector of strings.
Static Public Member Functions
static std::string symbolFromAtomicNumber (std::size_t const atomicNumber)
Get element symbol from atomic number.
static std::size_t atomicNumber (std::string const &symbol)
Get atomic number from element string.
Static Private Member Functions
static bool compareAtomicNumber (std::string const &symbol1, std::string const &symbol2)
Check if arguments are sorted according to atomic number.
Private Attributes
std::map< std::string, std::size_t > forwardMap
Map of elements present and corresponding index number.
std::map< std::size_t, std::string > reverseMap
Reverse element map.
Static Private Attributes
static std::string const knownElements []
List of element symbols (e.g. "He" for Helium).
Detailed Description
Contains element map.
Definition at line 29 of file ElementMap.h.
Member Function Documentation
operator[]() [1/2]
std::string nnp::ElementMap::operator[] (std::size_t const index) const inline
Overload [] operator for index search.
Parameters
[in] index Element index.
Returns
Symbol of element in map.
Definition at line 130 of file ElementMap.h.
{
    return symbol(index);
}
References index(), and symbol().
operator[]() [2/2]
std::size_t nnp::ElementMap::operator[] (std::string const symbol) const inline
Overload [] operator for symbol search.
Parameters
[in] symbol Element symbol.
Returns
Index of element in map.
Definition at line 135 of file ElementMap.h.
{
    return index(symbol);
}
References index(), and symbol().
size()
std::size_t nnp::ElementMap::size () const inline
Get element map size.
Returns
Number of elements registered.
Definition at line 140 of file ElementMap.h.
{
    return forwardMap.size();
}
References forwardMap.
Referenced by nnp::Structure::addAtom(), nnp::SymFnc::addCacheIndex(), nnp::SymFncBaseCompAngWeighted::getCacheIdentifiers(), nnp::SymFncCompRadWeighted::getCacheIdentifiers(), nnp::SymFncExpAngnWeighted::getCacheIdentifiers(), nnp::SymFncExpRadWeighted::getCacheIdentifiers(), getElementsString(), nnp::InterfaceLammps::initialize(), nnp::Structure::reset(), nnp::Structure::setElementMap(), nnp::Mode::setupElementMap(), nnp::Mode::setupElements(), nnp::Element::setupSymmetryFunctionMemory(), nnp::SymFnc::SymFnc(), and nnp::Structure::writeToFilePoscar().
getElementsString()
string ElementMap::getElementsString () const
Get sorted list of elements in one string (space separated).
Returns
Element string.
Definition at line 56 of file ElementMap.cpp.
{
    string elements = "";
    if (size() == 0) return elements;
    elements += symbol(0);
    if (size() == 1) return elements;
    for (size_t i = 1; i < size(); ++i)
    {
        elements += strpr(" %s", symbol(i).c_str());
    }
    return elements;
}
References size(), nnp::strpr(), and symbol().
Referenced by nnp::Structure::writeToFilePoscar().
index()
size_t ElementMap::index (std::string const & symbol) const
Get index of given element.
Parameters
[in] symbol Element symbol.
Returns
Element index.
Definition at line 71 of file ElementMap.cpp.
{
    return safeFind(forwardMap, symbol);
}
References forwardMap, nnp::safeFind(), and symbol().
Referenced by atomicNumber(), operator[](), and symbol().
symbol()
string ElementMap::symbol (std::size_t const index) const
Get element symbol for given element index.
Parameters
[in] index Element index.
Returns
Element symbol.
Definition at line 76 of file ElementMap.cpp.
{
    return safeFind(reverseMap, index);
}
References index(), reverseMap, and nnp::safeFind().
Referenced by atomicNumber(), getElementsString(), index(), and operator[]().
atomicNumber() [1/2]
std::size_t nnp::ElementMap::atomicNumber (std::size_t index) const inline
Get atomic number from element index.
Parameters
[in] index Element index in map.
Returns
Atomic number (proton number Z) of element.
Definition at line 145 of file ElementMap.h.
{
    return atomicNumber(symbol(index));
}
References atomicNumber(), index(), and symbol().
Referenced by atomicNumber(), nnp::SymFncCompAngnWeighted::calculate(), nnp::SymFncCompAngwWeighted::calculate(), nnp::SymFncCompRadWeighted::calculate(), nnp::SymFncExpAngnWeighted::calculate(), nnp::SymFncExpRadWeighted::calculate(), nnp::SymGrpCompAngnWeighted::calculate(), nnp::SymGrpCompAngwWeighted::calculate(), nnp::SymGrpCompRadWeighted::calculate(), nnp::SymGrpExpAngnWeighted::calculate(), nnp::SymGrpExpRadWeighted::calculate(), compareAtomicNumber(), nnp::InterfaceLammps::initialize(), main(), nnp::Mode::setupElementMap(), symbolFromAtomicNumber(), nnp::Dataset::writeNeighborLists(), nnp::Dataset::writeSymmetryFunctionFile(), nnp::Dataset::writeSymmetryFunctionHistograms(), and nnp::Training::writeUpdaterStatus().
registerElements()
size_t ElementMap::registerElements (std::string const & elementLine)
Extract all elements and store in element map.
Parameters
[in] elementLine String containing all elements, e.g. "Cd S Zn", separated by whitespaces.
Returns
Number of registered elements.
Sorts all elements according to their atomic number and populates forwardMap and reverseMap with the symbol and the corresponding index number.
Definition at line 36 of file ElementMap.cpp.
{
    vector<string> elements = split(reduce(elementLine));
    sort(elements.begin(), elements.end(), compareAtomicNumber);
    if (!forwardMap.empty())
    {
        throw runtime_error("ERROR: Element map not empty.\n");
    }
    for (size_t i = 0; i < elements.size(); i++)
    {
        forwardMap[elements[i]] = i;
        reverseMap[i] = elements[i];
    }
    return forwardMap.size();
}
References compareAtomicNumber(), forwardMap, nnp::reduce(), reverseMap, and nnp::split().
Referenced by main(), and nnp::Mode::setupElementMap().
deregisterElements()
void ElementMap::deregisterElements ()
Clear element map.
Definition at line 81 of file ElementMap.cpp.
{
    forwardMap.clear();
    reverseMap.clear();
    return;
}
References forwardMap, and reverseMap.
symbolFromAtomicNumber()
string ElementMap::symbolFromAtomicNumber (std::size_t const atomicNumber) static
Get element symbol from atomic number.
Parameters
[in] atomicNumber Atomic number of element.
Returns
Element symbol.
Definition at line 106 of file ElementMap.cpp.
{
    size_t numKnownElements = sizeof(knownElements) / sizeof(*knownElements);
    if (atomicNumber >= numKnownElements)
    {
        throw runtime_error(strpr("ERROR: Only the first %zu elements are "
                                  "known to this library.\n",
                                  numKnownElements));
    }
    else if (atomicNumber == 0)
    {
        throw runtime_error("ERROR: Invalid atomic number.\n");
    }
    atomicNumber--;
    return knownElements[atomicNumber];
}
References atomicNumber(), knownElements, and nnp::strpr().
atomicNumber() [2/2]
size_t ElementMap::atomicNumber (std::string const & symbol) static
Get atomic number from element string.
Parameters
[in] symbol Element symbol (e.g. "He" for Helium).
Returns
Atomic number (proton number Z) of element.
Definition at line 89 of file ElementMap.cpp.
{
    size_t numKnownElements = sizeof(knownElements) / sizeof(*knownElements);
    for (size_t i = 0; i < numKnownElements; i++)
    {
        if (knownElements[i] == symbol)
        {
            return i + 1;
        }
    }
    throw runtime_error("ERROR: Element \"" + symbol + "\" unknown.\n");
    return 0;
}
References knownElements, and symbol().
info()
vector< string > ElementMap::info () const
Get map information as a vector of strings.
Returns
Lines with map information.
Definition at line 125 of file ElementMap.cpp.
{
    vector<string> v;
    v.push_back(strpr("********************************\n"));
    v.push_back(strpr("ELEMENT MAP                     \n"));
    v.push_back(strpr("********************************\n"));
    v.push_back(strpr("--------------------------------\n"));
    v.push_back(strpr("forwardMap                 [*] : %d\n", forwardMap.size()));
    v.push_back(strpr("--------------------------------\n"));
    for (map<string, size_t>::const_iterator it = forwardMap.begin();
         it != forwardMap.end(); ++it)
    {
        v.push_back(strpr("%29s  : %d\n", it->first.c_str(), it->second));
    }
    v.push_back(strpr("--------------------------------\n"));
    v.push_back(strpr("--------------------------------\n"));
    v.push_back(strpr("reverseMap                 [*] : %d\n", reverseMap.size()));
    v.push_back(strpr("--------------------------------\n"));
    for (map<size_t, string>::const_iterator it = reverseMap.begin();
         it != reverseMap.end(); ++it)
    {
        v.push_back(strpr("%29d  : %s\n", it->first, it->second.c_str()));
    }
    v.push_back(strpr("--------------------------------\n"));
    v.push_back(strpr("********************************\n"));
    return v;
}
References forwardMap, reverseMap, and nnp::strpr().
Referenced by nnp::Structure::info().
compareAtomicNumber()
bool nnp::ElementMap::compareAtomicNumber (std::string const & symbol1, std::string const & symbol2) inline static private
Check if arguments are sorted according to atomic number.
Parameters
[in] symbol1 Element symbol 1.
[in] symbol2 Element symbol 2.
Returns
true if atomic number of element 1 is smaller than atomic number of element 2, false otherwise.
Used for sorting in registerElements().
Definition at line 150 of file ElementMap.h.
{
    return atomicNumber(symbol1) < atomicNumber(symbol2);
}
References atomicNumber().
Referenced by registerElements().
Member Data Documentation
forwardMap
std::map<std::string, std::size_t> nnp::ElementMap::forwardMap private
Map of elements present and corresponding index number.
Definition at line 107 of file ElementMap.h.
Referenced by deregisterElements(), index(), info(), registerElements(), and size().
reverseMap
std::map<std::size_t, std::string> nnp::ElementMap::reverseMap private
Reverse element map.
Definition at line 109 of file ElementMap.h.
Referenced by deregisterElements(), info(), registerElements(), and symbol().
knownElements
string const ElementMap::knownElements static private
Initial value:
= {
"H" , "He", "Li", "Be", "B" , "C" , "N" , "O" , "F" , "Ne", "Na", "Mg", "Al",
"Si", "P" , "S" , "Cl", "Ar", "K" , "Ca", "Sc", "Ti", "V" , "Cr", "Mn", "Fe",
"Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y" ,
"Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te",
"I" , "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb",
"Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W" , "Re", "Os", "Ir", "Pt",
"Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa",
"U" , "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No"
}
List of element symbols (e.g. "He" for Helium).
Definition at line 111 of file ElementMap.h.
Referenced by atomicNumber(), and symbolFromAtomicNumber().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/ElementMap.h
/home/runner/work/n2p2/n2p2/src/libnnp/ElementMap.cpp