n2p2 - A neural network potential package: nnp::ElementCabana Class Reference
nnp::ElementCabana Class Reference
Derived Cabana class for element-specific data.
#include <ElementCabana.h>
Public Member Functions
ElementCabana (std::size_t const index)
Constructor using index.
~ElementCabana ()
Destructor.
template<class t_SF , class h_t_int >
void addSymmetryFunction (std::string const &parameters, std::vector< std::string > elementStrings, int attype, t_SF SF, double convLength, h_t_int h_numSFperElem)
Add one symmetry function.
void changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
template<class t_SF , class h_t_int >
void sortSymmetryFunctions (t_SF SF, h_t_int h_numSFperElem, int attype)
Sort all symmetry function.
template<class t_SF >
bool compareSF (t_SF SF, int attype, int index1, int index2)
Print symmetry function parameter value information.
template<class t_SF , class h_t_int >
std::vector< std::string > infoSymmetryFunctionParameters (t_SF SF, int attype, h_t_int h_numSFperElem) const
Print symmetry function parameter value information.
template<class t_SF , class t_SFscaling , class h_t_int >
std::vector< std::string > infoSymmetryFunctionScaling (ScalingType scalingType, t_SF SF, t_SFscaling SFscaling, int attype, h_t_int h_numSFperElem) const
Print symmetry function scaling information.
template<class t_SF , class t_SFGmemberlist , class h_t_int >
void setupSymmetryFunctionGroups (t_SF SF, t_SFGmemberlist SFGmemberlist, int attype, h_t_int h_numSFperElem, h_t_int h_numSFGperElem, int maxSFperElem)
Set up symmetry function groups.
template<class t_SF , class t_SFGmemberlist , class h_t_int >
std::vector< std::string > infoSymmetryFunctionGroups (t_SF SF, t_SFGmemberlist SFGmemberlist, int attype, h_t_int h_numSFGperElem) const
Print symmetry function group info.
template<class t_SF , class h_t_int >
void setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha, t_SF SF, int attype, h_t_int h_numSFperElem)
Set cutoff function for all symmetry functions.
template<class t_SF , class t_SFscaling , class h_t_int >
void setScaling (ScalingType scalingType, std::vector< std::string > const &statisticsLine, double minS, double maxS, t_SF SF, t_SFscaling SFscaling, int attype, h_t_int h_numSFperElem) const
Set scaling of all symmetry functions.
template<class h_t_int >
std::size_t numSymmetryFunctions (int attype, h_t_int h_numSFperElem) const
Get number of symmetry functions.
template<class t_SF >
std::size_t getMinNeighbors (int attype, t_SF SF, int nSF) const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
template<class t_SF , class h_t_int >
double getMinCutoffRadius (t_SF SF, int attype, h_t_int h_numSFperElem) const
Get minimum cutoff radius of all symmetry functions.
template<class t_SF , class h_t_int >
double getMaxCutoffRadius (t_SF SF, int attype, h_t_int h_numSFperElem) const
Get maximum cutoff radius of all symmetry functions.
template<class t_SFscaling >
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax, t_SFscaling SFscaling, int attype, int k) const
Symmetry function statistics.
template<class t_SFscaling >
std::string scalingLine (ScalingType scalingType, t_SFscaling SFscaling, int attype, int k) const
Print scaling for one symmetry function.
template<class t_SFscaling >
double unscale (int attype, double value, int k, t_SFscaling SFscaling)
Unscale one symmetry function.
template<class t_SF , class h_t_int >
vector< string > infoSymmetryFunctionParameters (t_SF SF, int attype, h_t_int h_numSFperElem) const
template<class t_SF , class t_SFscaling , class h_t_int >
vector< string > infoSymmetryFunctionScaling (ScalingType scalingType, t_SF SF, t_SFscaling SFscaling, int attype, h_t_int h_numSFperElem) const
template<class t_SF , class t_SFGmemberlist , class h_t_int >
vector< string > infoSymmetryFunctionGroups (t_SF SF, t_SFGmemberlist SFGmemberlist, int attype, h_t_int h_numSFGperElem) const
template<class t_SF >
size_t getMinNeighbors (int attype, t_SF SF, int nSF) const
Public Member Functions inherited from nnp::Element
Element ()
Default constructor.
Element (std::size_t const index, ElementMap const &elementMap)
Constructor using index.
virtual ~Element ()
Destructor.
void clearSymmetryFunctions ()
Clear all symmetry functions and groups.
void setAtomicEnergyOffset (double atomicEnergyOffset)
Set atomicEnergyOffset.
std::size_t getIndex () const
Get index.
std::size_t getAtomicNumber () const
Get atomicNumber.
double getAtomicEnergyOffset () const
Get atomicEnergyOffset.
std::string getSymbol () const
Get symbol.
void addSymmetryFunction (std::string const &parameters, std::size_t const &lineNumber)
Add one symmetry function.
void changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
void sortSymmetryFunctions ()
Sort all symmetry function.
std::vector< std::string > infoSymmetryFunctionParameters () const
Print symmetry function parameter value information.
std::vector< std::string > infoSymmetryFunction (std::size_t index) const
Print symmetry function parameter names and values.
std::vector< std::string > infoSymmetryFunctionScaling () const
Print symmetry function scaling information.
void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
void setupSymmetryFunctionMemory ()
Extract relevant symmetry function combinations for derivative memory.
std::vector< std::string > infoSymmetryFunctionGroups () const
Print symmetry function group info.
void setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha)
Set cutoff function for all symmetry functions.
void setScalingNone () const
Set no scaling of symmetry function.
void setScaling (SymFnc::ScalingType scalingType, std::vector< std::string > const &statisticsLine, double minS, double maxS) const
Set scaling of all symmetry functions.
std::size_t numSymmetryFunctions () const
Get number of symmetry functions.
std::size_t getMinNeighbors () const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
double getMinCutoffRadius () const
Get minimum cutoff radius of all symmetry functions.
double getMaxCutoffRadius () const
Get maximum cutoff radius of all symmetry functions.
std::vector< std::size_t > const & getSymmetryFunctionNumTable () const
Get number of relevant symmetry functions per element.
std::vector< std::vector< std::size_t > > const & getSymmetryFunctionTable () const
Get symmetry function element relevance table.
void calculateSymmetryFunctions (Atom &atom, bool const derivatives) const
Calculate symmetry functions.
void calculateSymmetryFunctionGroups (Atom &atom, bool const derivatives) const
Calculate symmetry functions via groups.
std::size_t updateSymmetryFunctionStatistics (Atom const &atom)
Update symmetry function statistics.
SymFnc const & getSymmetryFunction (std::size_t index) const
Get symmetry function instance.
void setCacheIndices (std::vector< std::vector< SFCacheList >> cacheLists)
Set cache indices for all symmetry functions of this element.
std::vector< std::size_t > getCacheSizes () const
Get cache sizes for each neighbor atom element.
Private Attributes
std::size_t index
Global index of this element.
std::size_t atomicNumber
Atomic number of this element.
double atomicEnergyOffset
Offset energy for every atom of this element.
std::string symbol
Element symbol.
Additional Inherited Members
Public Attributes inherited from nnp::Element
std::map< std::string, NeuralNetwork > neuralNetworks
Neural networks for this element.
SymFncStatistics statistics
Symmetry function statistics.
Protected Attributes inherited from nnp::Element
ElementMap elementMap
Copy of element map.
std::size_t index
Global index of this element.
std::size_t atomicNumber
Atomic number of this element.
double atomicEnergyOffset
Offset energy for every atom of this element.
std::string symbol
Element symbol.
std::vector< std::size_t > symmetryFunctionNumTable
Number of relevant symmetry functions for each neighbor element.
std::vector< std::vector< std::size_t > > symmetryFunctionTable
List of symmetry function indices relevant for each neighbor element.
std::vector< std::vector< SFCacheList > > cacheLists
Symmetry function cache lists.
std::vector< SymFnc * > symmetryFunctions
Vector of pointers to symmetry functions.
std::vector< SymGrp * > symmetryFunctionGroups
Vector of pointers to symmetry function groups.
Detailed Description
Derived Cabana class for element-specific data.
Definition at line 35 of file ElementCabana.h.
Constructor & Destructor Documentation
ElementCabana()
nnp::ElementCabana::ElementCabana (std::size_t const index)
Constructor using index.
Definition at line 31 of file ElementCabana_impl.h.
     : Element()
 {
     index = _index;
     atomicEnergyOffset = 0.0;
     neuralNetwork = NULL;
 }
References nnp::Element::atomicEnergyOffset, and nnp::Element::index.
~ElementCabana()
nnp::ElementCabana::~ElementCabana ()
Destructor.
Definition at line 39 of file ElementCabana_impl.h.
 {}
Member Function Documentation
addSymmetryFunction()
template<class t_SF , class h_t_int > void nnp::ElementCabana::addSymmetryFunction (std::string const & parameters, std::vector< std::string > elementStrings, int attype, t_SF SF, double convLength, h_t_int h_numSFperElem)
Add one symmetry function.
Parameters
[in] parameters String containing settings for symmetry function.
[in] lineNumber Line number of symmetry function in settings file.
[in] attype Atom type.
[in] SF Kokkos host View of symmetry functions.
[in] convLength Length unit conversion factor.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
Definition at line 42 of file ElementCabana_impl.h.
 {
     vector<string> args = split( reduce( parameters ) );
     size_t type = (size_t)atoi( args.at( 1 ).c_str() );
     const char *estring;
     int el = 0;
     vector<string> splitLine = split( reduce( parameters ) );
     if ( type == 2 )
     {
         estring = splitLine.at( 0 ).c_str();
         for ( size_t i = 0; i < elementStrings.size(); ++i )
         {
             if ( strcmp( elementStrings[i].c_str(), estring ) == 0 )
                 el = i;
         }
         SF( attype, h_numSFperElem( attype ), 0 ) = el;   // ec
         SF( attype, h_numSFperElem( attype ), 1 ) = type; // type
         estring = splitLine.at( 2 ).c_str();
         for ( size_t i = 0; i < elementStrings.size(); ++i )
         {
             if ( strcmp( elementStrings[i].c_str(), estring ) == 0 )
                 el = i;
         }
         SF( attype, h_numSFperElem( attype ), 2 ) = el; // e1
         // set e2 to arbit high number for ease in creating groups
         SF( attype, h_numSFperElem( attype ), 3 ) = 100000; // e2
         SF( attype, h_numSFperElem( attype ), 4 ) =
             atof( splitLine.at( 3 ).c_str() ) /
             ( convLength * convLength ); // eta
         SF( attype, h_numSFperElem( attype ), 8 ) =
             atof( splitLine.at( 4 ).c_str() ) * convLength; // rs
         SF( attype, h_numSFperElem( attype ), 7 ) =
             atof( splitLine.at( 5 ).c_str() ) * convLength; // rc
         SF( attype, h_numSFperElem( attype ), 13 ) = h_numSFperElem( attype );
         h_numSFperElem( attype )++;
     }
     else if ( type == 3 )
     {
         if ( type != (size_t)atoi( splitLine.at( 1 ).c_str() ) )
             throw runtime_error( "ERROR: Incorrect symmetry function type.\n" );
         estring = splitLine.at( 0 ).c_str();
         for ( size_t i = 0; i < elementStrings.size(); ++i )
         {
             if ( strcmp( elementStrings[i].c_str(), estring ) == 0 )
                 el = i;
         }
         SF( attype, h_numSFperElem( attype ), 0 ) = el;   // ec
         SF( attype, h_numSFperElem( attype ), 1 ) = type; // type
         estring = splitLine.at( 2 ).c_str();
         for ( size_t i = 0; i < elementStrings.size(); ++i )
         {
             if ( strcmp( elementStrings[i].c_str(), estring ) == 0 )
                 el = i;
         }
         SF( attype, h_numSFperElem( attype ), 2 ) = el; // e1
         estring = splitLine.at( 3 ).c_str();
         for ( size_t i = 0; i < elementStrings.size(); ++i )
         {
             if ( strcmp( elementStrings[i].c_str(), estring ) == 0 )
                 el = i;
         }
         SF( attype, h_numSFperElem( attype ), 3 ) = el; // e2
         SF( attype, h_numSFperElem( attype ), 4 ) =
             atof( splitLine.at( 4 ).c_str() ) /
             ( convLength * convLength ); // eta
         SF( attype, h_numSFperElem( attype ), 5 ) =
             atof( splitLine.at( 5 ).c_str() ); // lambda
         SF( attype, h_numSFperElem( attype ), 6 ) =
             atof( splitLine.at( 6 ).c_str() ); // zeta
         SF( attype, h_numSFperElem( attype ), 7 ) =
             atof( splitLine.at( 7 ).c_str() ) * convLength; // rc
         // Shift parameter is optional.
         if ( splitLine.size() > 8 )
             SF( attype, h_numSFperElem( attype ), 8 ) =
                 atof( splitLine.at( 8 ).c_str() ) * convLength; // rs
         T_INT e1 = SF( attype, h_numSFperElem( attype ), 2 );
         T_INT e2 = SF( attype, h_numSFperElem( attype ), 3 );
         if ( e1 > e2 )
         {
             size_t tmp = e1;
             e1 = e2;
             e2 = tmp;
         }
         SF( attype, h_numSFperElem( attype ), 2 ) = e1;
         SF( attype, h_numSFperElem( attype ), 3 ) = e2;
         T_FLOAT zeta = SF( attype, h_numSFperElem( attype ), 6 );
         T_INT zetaInt = round( zeta );
         if ( fabs( zeta - zetaInt ) <= numeric_limits<double>::min() )
             SF( attype, h_numSFperElem( attype ), 9 ) = 1;
         else
             SF( attype, h_numSFperElem( attype ), 9 ) = 0;
         SF( attype, h_numSFperElem( attype ), 13 ) = h_numSFperElem( attype );
         h_numSFperElem( attype )++;
     }
     // TODO: Add this later
     else if ( type == 9 )
     {
     }
     else if ( type == 12 )
     {
     }
     else if ( type == 13 )
     {
     }
     else
     {
         throw runtime_error( "ERROR: Unknown symmetry function type.\n" );
     }
     return;
 }
References nnp::reduce(), and nnp::split().
changeLengthUnitSymmetryFunctions()
void nnp::ElementCabana::changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
Parameters
[in] convLength Length unit conversion factor.
sortSymmetryFunctions()
template<class t_SF , class h_t_int > void nnp::ElementCabana::sortSymmetryFunctions (t_SF SF, h_t_int h_numSFperElem, int attype)
Sort all symmetry function.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
[in] attype Atom type.
Definition at line 169 of file ElementCabana_impl.h.
 {
     int size = h_numSFperElem( attype );
     h_t_int h_SFsort( "SortSort", size );
     for ( int i = 0; i < size; ++i )
         h_SFsort( i ) = i;
     // naive insertion sort
     int i, j, tmp;
     for ( i = 1; i < size; ++i )
     {
         j = i;
         // explicit condition for sort
         while ( j > 0 &&
                 compareSF( SF, attype, h_SFsort( j - 1 ), h_SFsort( j ) ) )
         {
             tmp = h_SFsort( j );
             h_SFsort( j ) = h_SFsort( j - 1 );
             h_SFsort( j - 1 ) = tmp;
             --j;
         }
     }
     int tmpindex;
     for ( int i = 0; i < size; ++i )
     {
         SF( attype, i, 13 ) = h_SFsort( i );
         tmpindex = SF( attype, i, 13 );
         SF( attype, tmpindex, 14 ) = i;
     }
     return;
 }
References compareSF().
compareSF()
template<class t_SF > bool nnp::ElementCabana::compareSF (t_SF SF, int attype, int index1, int index2)
Print symmetry function parameter value information.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] attype Atom type.
[in] index1 First symmetry function index.
[in] index2 Second symmetry function index.
Definition at line 205 of file ElementCabana_impl.h.
 {
     if ( SF( attype, index2, 0 ) < SF( attype, index1, 0 ) )
         return true; // ec
     else if ( SF( attype, index2, 0 ) > SF( attype, index1, 0 ) )
         return false;
     if ( SF( attype, index2, 1 ) < SF( attype, index1, 1 ) )
         return true; // type
     else if ( SF( attype, index2, 1 ) > SF( attype, index1, 1 ) )
         return false;
     if ( SF( attype, index2, 11 ) < SF( attype, index1, 11 ) )
         return true; // cutofftype
     else if ( SF( attype, index2, 11 ) > SF( attype, index1, 11 ) )
         return false;
     if ( SF( attype, index2, 12 ) < SF( attype, index1, 12 ) )
         return true; // cutoffalpha
     else if ( SF( attype, index2, 12 ) > SF( attype, index1, 12 ) )
         return false;
     if ( SF( attype, index2, 7 ) < SF( attype, index1, 7 ) )
         return true; // rc
     else if ( SF( attype, index2, 7 ) > SF( attype, index1, 7 ) )
         return false;
     if ( SF( attype, index2, 4 ) < SF( attype, index1, 4 ) )
         return true; // eta
     else if ( SF( attype, index2, 4 ) > SF( attype, index1, 4 ) )
         return false;
     if ( SF( attype, index2, 8 ) < SF( attype, index1, 8 ) )
         return true; // rs
     else if ( SF( attype, index2, 8 ) > SF( attype, index1, 8 ) )
         return false;
     if ( SF( attype, index2, 6 ) < SF( attype, index1, 6 ) )
         return true; // zeta
     else if ( SF( attype, index2, 6 ) > SF( attype, index1, 6 ) )
         return false;
     if ( SF( attype, index2, 5 ) < SF( attype, index1, 5 ) )
         return true; // lambda
     else if ( SF( attype, index2, 5 ) > SF( attype, index1, 5 ) )
         return false;
     if ( SF( attype, index2, 2 ) < SF( attype, index1, 2 ) )
         return true; // e1
     else if ( SF( attype, index2, 2 ) > SF( attype, index1, 2 ) )
         return false;
     if ( SF( attype, index2, 3 ) < SF( attype, index1, 3 ) )
         return true; // e2
     else if ( SF( attype, index2, 3 ) > SF( attype, index1, 3 ) )
         return false;
     else
         return false;
 }
Referenced by sortSymmetryFunctions().
infoSymmetryFunctionParameters() [1/2]
template<class t_SF , class h_t_int > std::vector<std::string> nnp::ElementCabana::infoSymmetryFunctionParameters (t_SF SF, int attype, h_t_int h_numSFperElem) const
Print symmetry function parameter value information.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
infoSymmetryFunctionScaling() [1/2]
template<class t_SF , class t_SFscaling , class h_t_int > std::vector<std::string> nnp::ElementCabana::infoSymmetryFunctionScaling (ScalingType scalingType, t_SF SF, t_SFscaling SFscaling, int attype, h_t_int h_numSFperElem) const
Print symmetry function scaling information.
Parameters
[in] scalingType Type of scaling see SymmetryFunction::ScalingType.
[in] SF Kokkos host View of symmetry functions.
[in] SFscaling Kokkos host View of symmetry function scaling.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
setupSymmetryFunctionGroups()
template<class t_SF , class t_SFGmemberlist , class h_t_int > void nnp::ElementCabana::setupSymmetryFunctionGroups (t_SF SF, t_SFGmemberlist SFGmemberlist, int attype, h_t_int h_numSFperElem, h_t_int h_numSFGperElem, int maxSFperElem)
Set up symmetry function groups.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] SFGmemberlist Kokkos host View of symmetry function groups.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
[in] h_numSFGperElem Kokkos host View of number of symmetry function groups per element.
[in] maxSFperElem Maximum number of symmetry functions per element.
Definition at line 308 of file ElementCabana_impl.h.
 {
     int num_group = h_numSFperElem.extent( 0 );
     h_t_int h_numGR( "RadialCounter", num_group );
     h_t_int h_numGA( "AngularCounter", num_group );
     int SFindex;
     for ( int k = 0; k < h_numSFperElem( attype ); ++k )
     {
         bool createNewGroup = true;
         SFindex = SF( attype, k, 13 );
         for ( int l = 0; l < h_numSFGperElem( attype ); ++l )
         {
             if ( ( SF( attype, SFindex, 0 ) ==
                    SF( attype, SFGmemberlist( attype, l, 0 ),
                        0 ) ) && // same ec
                  ( SF( attype, SFindex, 2 ) ==
                    SF( attype, SFGmemberlist( attype, l, 0 ),
                        2 ) ) && // same e1
                  ( SF( attype, SFindex, 3 ) ==
                    SF( attype, SFGmemberlist( attype, l, 0 ),
                        3 ) ) && // same e2
                  ( SF( attype, SFindex, 7 ) ==
                    SF( attype, SFGmemberlist( attype, l, 0 ),
                        7 ) ) && // same rc
                  ( SF( attype, SFindex, 11 ) ==
                    SF( attype, SFGmemberlist( attype, l, 0 ),
                        11 ) ) && // same cutoffType
                  ( SF( attype, SFindex, 12 ) ==
                    SF( attype, SFGmemberlist( attype, l, 0 ),
                        12 ) ) ) // same cutoffAlpha
             {
                 createNewGroup = false;
                 if ( SF( attype, SFindex, 1 ) == 2 )
                 {
                     SFGmemberlist( attype, l, h_numGR( l ) ) = SFindex;
                     h_numGR( l )++;
                     SFGmemberlist( attype, l, maxSFperElem )++;
                     break;
                 }
                 else if ( SF( attype, SFindex, 1 ) == 3 )
                 {
                     SFGmemberlist( attype, l, h_numGA( l ) ) = SFindex;
                     h_numGA( l )++;
                     SFGmemberlist( attype, l, maxSFperElem )++;
                     break;
                 }
             }
         }
         if ( createNewGroup )
         {
             int l = h_numSFGperElem( attype );
             h_numSFGperElem( attype )++;
             if ( SF( attype, SFindex, 1 ) == 2 )
             {
                 SFGmemberlist( attype, l, 0 ) = SFindex;
                 if ( l >= (int)h_numGR.extent( 0 ) )
                     Kokkos::resize( h_numGR, l+1 );
                 h_numGR( l ) = 1;
                 SFGmemberlist( attype, l, maxSFperElem )++;
             }
             else if ( SF( attype, SFindex, 1 ) == 3 )
             {
                 SFGmemberlist( attype, l, 0 ) = SFindex;
                 if ( l >= (int)h_numGA.extent( 0 ) )
                     Kokkos::resize( h_numGA, l+1 );
                 h_numGA( l ) = 1;
                 SFGmemberlist( attype, l, maxSFperElem )++;
             }
         }
     }
     return;
 }
infoSymmetryFunctionGroups() [1/2]
template<class t_SF , class t_SFGmemberlist , class h_t_int > std::vector<std::string> nnp::ElementCabana::infoSymmetryFunctionGroups (t_SF SF, t_SFGmemberlist SFGmemberlist, int attype, h_t_int h_numSFGperElem) const
Print symmetry function group info.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] SFGmemberlist Kokkos host View of symmetry function groups.
[in] attype Atom type.
[in] h_numSFGperElem Kokkos host View of number of symmetry function groups per element.
setCutoffFunction()
template<class t_SF , class h_t_int > void nnp::ElementCabana::setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha, t_SF SF, int attype, h_t_int h_numSFperElem)
Set cutoff function for all symmetry functions.
Parameters
[in] cutoffType Type of cutoff function.
[in] cutoffAlpha Cutoff parameter for all functions.
[in] SF Kokkos host View of symmetry functions.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
Definition at line 412 of file ElementCabana_impl.h.
 {
     for ( int k = 0; k < h_numSFperElem( attype ); ++k )
     {
         SF( attype, k, 10 ) = cutoffType;
         SF( attype, k, 11 ) = cutoffAlpha;
     }
     return;
 }
setScaling()
template<class t_SF , class t_SFscaling , class h_t_int > void nnp::ElementCabana::setScaling (ScalingType scalingType, std::vector< std::string > const & statisticsLine, double minS, double maxS, t_SF SF, t_SFscaling SFscaling, int attype, h_t_int h_numSFperElem) const
Set scaling of all symmetry functions.
Parameters
[in] scalingType Type of scaling, see SymmetryFunction::ScalingType.
[in] statisticsLine Vector of strings containing statistics for all symmetry functions.
[in] minS Minimum for scaling range.
[in] maxS Maximum for scaling range.
[in] SF Kokkos host View of symmetry functions.
[in] SFscaling Kokkos host View of symmetry function scaling.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
Definition at line 425 of file ElementCabana_impl.h.
 {
     int index;
     for ( int k = 0; k < h_numSFperElem( attype ); ++k )
     {
         index = SF( attype, k, 13 );
         setScalingType( scalingType, statisticsLine.at( k ), Smin, Smax,
                         SFscaling, attype, index );
     }
     // TODO: groups
     // for (int k = 0; k < h_numSFperElem(attype); ++k)
     //    setScalingFactors(SF,attype,k);
     return;
 }
References nnp::Element::index, and setScalingType().
numSymmetryFunctions()
template<class h_t_int > std::size_t nnp::ElementCabana::numSymmetryFunctions (int attype, h_t_int h_numSFperElem) const inline
Get number of symmetry functions.
Parameters
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
Returns
Number of symmetry functions.
Definition at line 278 of file ElementCabana.h.
 {
     return h_numSFperElem( attype );
 }
getMinNeighbors() [1/2]
template<class t_SF > std::size_t nnp::ElementCabana::getMinNeighbors (int attype, t_SF SF, int nSF) const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
Parameters
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
[in] nSF Number of symmetry function for this type.
Returns
Minimum number of neighbors required.
getMinCutoffRadius()
template<class t_SF , class h_t_int > double nnp::ElementCabana::getMinCutoffRadius (t_SF SF, int attype, h_t_int h_numSFperElem) const
Get minimum cutoff radius of all symmetry functions.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
Returns
Minimum cutoff radius.
Definition at line 465 of file ElementCabana_impl.h.
 {
     double minCutoffRadius = numeric_limits<double>::max();
     for ( int k = 0; k < h_numSFperElem( attype ); ++k )
         minCutoffRadius = min( SF( attype, k, 7 ), minCutoffRadius );
     return minCutoffRadius;
 }
getMaxCutoffRadius()
template<class t_SF , class h_t_int > double nnp::ElementCabana::getMaxCutoffRadius (t_SF SF, int attype, h_t_int h_numSFperElem) const
Get maximum cutoff radius of all symmetry functions.
Parameters
[in] SF Kokkos host View of symmetry functions.
[in] attype Atom type.
[in] h_numSFperElem Kokkos host View of number of symmetry functions per element.
Returns
Maximum cutoff radius.
Definition at line 477 of file ElementCabana_impl.h.
 {
     double maxCutoffRadius = 0.0;
     for ( int k = 0; k < h_numSFperElem( attype ); ++k )
         maxCutoffRadius = max( SF( attype, k, 7 ), maxCutoffRadius );
     return maxCutoffRadius;
 }
setScalingType()
template<class t_SFscaling > void nnp::ElementCabana::setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax, t_SFscaling SFscaling, int attype, int k) const inline
Symmetry function statistics.
Set scaling type of one symmetry function
Parameters
[in] scalingType Type of scaling, see SymmetryFunction::ScalingType.
[in] statisticsLine Output string for this symmetry function.
[in] Smin Minimum for scaling range.
[in] Smax Maximum for scaling range.
[in] SFscaling Kokkos host View of symmetry function scaling.
[in] attype Atom type.
[in] k Symmetry function index.
Definition at line 286 of file ElementCabana.h.
 {
     double Gmin, Gmax, Gmean, Gsigma = 0, scalingFactor = 0;
     std::vector<std::string> s = split( reduce( statisticsLine ) );
     Gmin = atof( s.at( 2 ).c_str() );
     Gmax = atof( s.at( 3 ).c_str() );
     Gmean = atof( s.at( 4 ).c_str() );
     SFscaling( attype, k, 0 ) = Gmin;
     SFscaling( attype, k, 1 ) = Gmax;
     SFscaling( attype, k, 2 ) = Gmean;
     // Older versions may not supply sigma.
     if ( s.size() > 5 )
         Gsigma = atof( s.at( 5 ).c_str() );
     SFscaling( attype, k, 3 ) = Gsigma;
     SFscaling( attype, k, 4 ) = Smin;
     SFscaling( attype, k, 5 ) = Smax;
     SFscaling( attype, k, 7 ) = scalingType;
     if ( scalingType == ST_NONE )
         scalingFactor = 1.0;
     else if ( scalingType == ST_SCALE )
         scalingFactor = ( Smax - Smin ) / ( Gmax - Gmin );
     else if ( scalingType == ST_CENTER )
         scalingFactor = 1.0;
     else if ( scalingType == ST_SCALECENTER )
         scalingFactor = ( Smax - Smin ) / ( Gmax - Gmin );
     else if ( scalingType == ST_SCALESIGMA )
         scalingFactor = ( Smax - Smin ) / Gsigma;
     SFscaling( attype, k, 6 ) = scalingFactor;
     return;
 }
References nnp::reduce(), nnp::split(), ST_CENTER, ST_NONE, ST_SCALE, ST_SCALECENTER, and ST_SCALESIGMA.
Referenced by setScaling().
scalingLine()
template<class t_SFscaling > std::string nnp::ElementCabana::scalingLine (ScalingType scalingType, t_SFscaling SFscaling, int attype, int k) const inline
Print scaling for one symmetry function.
Parameters
[in] scalingType Type of scaling, see SymmetryFunction::ScalingType.
[in] SFscaling Kokkos host View of symmetry function scaling.
[in] attype Atom type.
[in] k Symmetry function index.
Definition at line 327 of file ElementCabana.h.
 {
     return strpr( "%4zu %9.2E %9.2E %9.2E %9.2E %9.2E %5.2f %5.2f %d\n",
                   k + 1, SFscaling( attype, k, 0 ),
                   SFscaling( attype, k, 1 ), SFscaling( attype, k, 2 ),
                   SFscaling( attype, k, 3 ), SFscaling( attype, k, 6 ),
                   SFscaling( attype, k, 4 ), SFscaling( attype, k, 5 ),
                   scalingType );
 }
References nnp::strpr().
Referenced by infoSymmetryFunctionScaling().
unscale()
template<class t_SFscaling > double nnp::ElementCabana::unscale (int attype, double value, int k, t_SFscaling SFscaling) inline
Unscale one symmetry function.
Parameters
[in] attype Atom type.
[in] value Unscaled symmetry function value.
[in] k Symmetry function index.
[in] SFscaling Kokkos host View of symmetry function scaling.
Definition at line 340 of file ElementCabana.h.
 {
     double scalingType = SFscaling( attype, k, 7 );
     double scalingFactor = SFscaling( attype, k, 6 );
     double Gmin = SFscaling( attype, k, 0 );
     // double Gmax = SFscaling(attype,k,1);
     double Gmean = SFscaling( attype, k, 2 );
     // double Gsigma = SFscaling(attype,k,3);
     double Smin = SFscaling( attype, k, 4 );
     // double Smax = SFscaling(attype,k,5);
     if ( scalingType == 0.0 )
     {
         return value;
     }
     else if ( scalingType == 1.0 )
     {
         return ( value - Smin ) / scalingFactor + Gmin;
     }
     else if ( scalingType == 2.0 )
     {
         return value + Gmean;
     }
     else if ( scalingType == 3.0 )
     {
         return ( value - Smin ) / scalingFactor + Gmean;
     }
     else if ( scalingType == 4.0 )
     {
         return ( value - Smin ) / scalingFactor + Gmean;
     }
     else
     {
         return 0.0;
     }
 }
infoSymmetryFunctionParameters() [2/2]
template<class t_SF , class h_t_int > vector<string> nnp::ElementCabana::infoSymmetryFunctionParameters (t_SF SF, int attype, h_t_int h_numSFperElem) const
Definition at line 268 of file ElementCabana_impl.h.
 {
     vector<string> v;
     string pushstring = "";
     int index;
     float writestring;
     for ( int i = 0; i < h_numSFperElem( attype ); ++i )
     {
         index = SF( attype, i, 13 );
         // TODO: improve function
         for ( int j = 1; j < 12; ++j )
         {
             writestring = SF( attype, index, j );
             pushstring += to_string( writestring ) + " ";
         }
         pushstring += "\n";
     }
     v.push_back( pushstring );
     return v;
 }
References nnp::Element::index.
infoSymmetryFunctionScaling() [2/2]
template<class t_SF , class t_SFscaling , class h_t_int > vector<string> nnp::ElementCabana::infoSymmetryFunctionScaling (ScalingType scalingType, t_SF SF, t_SFscaling SFscaling, int attype, h_t_int h_numSFperElem) const
Definition at line 293 of file ElementCabana_impl.h.
 {
     vector<string> v;
     int index;
     for ( int k = 0; k < h_numSFperElem( attype ); ++k )
     {
         index = SF( attype, k, 13 );
         v.push_back( scalingLine( scalingType, SFscaling, attype, index ) );
     }
     return v;
 }
References nnp::Element::index, and scalingLine().
infoSymmetryFunctionGroups() [2/2]
template<class t_SF , class t_SFGmemberlist , class h_t_int > vector<string> nnp::ElementCabana::infoSymmetryFunctionGroups (t_SF SF, t_SFGmemberlist SFGmemberlist, int attype, h_t_int h_numSFGperElem) const
Definition at line 390 of file ElementCabana_impl.h.
 {
     vector<string> v;
     string pushstring = "";
     for ( int groupIndex = 0; groupIndex < h_numSFGperElem( attype );
           ++groupIndex )
     {
         // TODO: improve function
         for ( int j = 0; j < 8; ++j )
             pushstring +=
                 to_string(
                     SF( attype, SFGmemberlist( attype, groupIndex, 0 ), j ) ) +
                 " ";
         pushstring += "\n";
     }
     v.push_back( pushstring );
     return v;
 }
getMinNeighbors() [2/2]
template<class t_SF > size_t nnp::ElementCabana::getMinNeighbors (int attype, t_SF SF, int nSF) const
Definition at line 445 of file ElementCabana_impl.h.
 {
     // get max number of minNeighbors
     size_t global_minNeighbors = 0;
     size_t minNeighbors = 0;
     int SFtype;
     for ( int k = 0; k < nSF; ++k )
     {
         SFtype = SF( attype, k, 1 );
         if ( SFtype == 2 )
             minNeighbors = 1;
         else if ( SFtype == 3 )
             minNeighbors = 2;
         global_minNeighbors = max( minNeighbors, global_minNeighbors );
     }
     return global_minNeighbors;
 }
Member Data Documentation
index
std::size_t nnp::Element::index private
Global index of this element.
Definition at line 238 of file Element.h.
atomicNumber
std::size_t nnp::Element::atomicNumber private
Atomic number of this element.
Definition at line 240 of file Element.h.
atomicEnergyOffset
double nnp::Element::atomicEnergyOffset private
Offset energy for every atom of this element.
Definition at line 242 of file Element.h.
symbol
std::string nnp::Element::symbol private
Element symbol.
Definition at line 244 of file Element.h.
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnpif/CabanaMD/ElementCabana.h
/home/runner/work/n2p2/n2p2/src/libnnpif/CabanaMD/ElementCabana_impl.h