n2p2 - A neural network potential package: nnp::CompactFunction Class Reference
nnp::CompactFunction Class Reference
A general function with compact support.
#include <CompactFunction.h>
Public Member Functions
CompactFunction ()
Constructor, initializes to #CoreFunction::Type::POLY2.
void setCoreFunction (CoreFunction::Type const type)
Set type.
void setCenterWidth (double center, double width)
Set center and width.
void setLeftRight (double left, double right)
Set left and right boundary.
CoreFunction::Type getCoreFunctionType () const
Getter for #type.
void setAsymmetric (bool asymmetric)
Set asymmetric property in core function.
bool getAsymmetric () const
Check if asymmetry is enabled in core function.
double getCenter () const
Getter for center.
double getWidth () const
Getter for width.
double getLeft () const
Getter for left.
double getRight () const
Getter for right.
double f (double a) const
Compact function \(f_c\).
double df (double a) const
Derivative of compact function \(\frac{d f_c}{d a}\).
void fdf (double a, double &fa, double &dfa) const
Calculate compact function and derivative at once.
Private Attributes
double center
Center of compact function.
double width
Width of compact function.
double left
Left boundary of compact function.
double right
Right boundary of compact function.
double scale
Inverse width.
CoreFunction core
Core function to be used on either side of compact function.
Detailed Description
A general function with compact support.
Definition at line 27 of file CompactFunction.h.
Constructor & Destructor Documentation
CompactFunction()
CompactFunction::CompactFunction ()
Constructor, initializes to #CoreFunction::Type::POLY2.
Definition at line 24 of file CompactFunction.cpp.
                                 : center    (0.0  ),
                                     width     (0.0  ),
                                     left      (0.0  ),
                                     right     (0.0  ),
                                     scale     (0.0  )
{
    core.setType(CoreFunction::Type::POLY2);
}
References core, nnp::CoreFunction::POLY2, and nnp::CoreFunction::setType().
Member Function Documentation
setCoreFunction()
void nnp::CompactFunction::setCoreFunction (CoreFunction::Type const type) inline
Set type.
Parameters
[in] type Type of core function to use.
Definition at line 131 of file CompactFunction.h.
{
    core.setType(type);
    return;
}
References core, and nnp::CoreFunction::setType().
Referenced by nnp::SymFncBaseComp::setCompactFunction(), nnp::SymFncBaseCompAng::setParameters(), and nnp::SymFncBaseCompAngWeighted::setParameters().
setCenterWidth()
void CompactFunction::setCenterWidth (double center, double width)
Set center and width.
Parameters
[in] center Center of compact function.
[in] width Width of compact function.
Note
Either use setCenterWidth() or setLeftRight() to initialize.
Definition at line 47 of file CompactFunction.cpp.
{
    if (width <= 0.0)
    {
        throw invalid_argument("ERROR: Width <= 0.\n");
    }
    this->center = center;
    this->width  = width;
    this->left   = center - width;
    this->right  = center + width;
    this->scale  = 1.0 / width;
    return;
}
References center, left, right, scale, and width.
setLeftRight()
void CompactFunction::setLeftRight (double left, double right)
Set left and right boundary.
Parameters
[in] left Left boundary of compact function.
[in] right Right boundary of compact function.
Note
Either use setCenterWidth() or setLeftRight() to initialize.
Definition at line 63 of file CompactFunction.cpp.
{
    if (left >= right)
    {
        throw invalid_argument("ERROR: Left >= Right.\n");
    }
    this->left   = left;
    this->right  = right;
    this->center = (right + left) / 2.0;
    this->width  = (right - left) / 2.0;
    this->scale  = 1.0 / width;
    return;
}
References center, left, right, scale, and width.
Referenced by nnp::SymFncBaseCompAng::changeLengthUnit(), nnp::SymFncBaseCompAngWeighted::changeLengthUnit(), nnp::SymFncCompRad::changeLengthUnit(), nnp::SymFncCompRadWeighted::changeLengthUnit(), nnp::SymFncBaseCompAng::setParameters(), nnp::SymFncBaseCompAngWeighted::setParameters(), nnp::SymFncCompRad::setParameters(), and nnp::SymFncCompRadWeighted::setParameters().
getCoreFunctionType()
CoreFunction::Type nnp::CompactFunction::getCoreFunctionType () const inline
Getter for #type.
Returns
Type used.
Definition at line 138 of file CompactFunction.h.
{
    return core.getType();
}
References core, and nnp::CoreFunction::getType().
Referenced by nnp::SymFncBaseCompAng::setParameters(), and nnp::SymFncBaseCompAngWeighted::setParameters().
setAsymmetric()
void CompactFunction::setAsymmetric (bool asymmetric)
Set asymmetric property in core function.
Parameters
[in] asymmetric Whether asymmetry should be activated.
Definition at line 39 of file CompactFunction.cpp.
{
    core.setAsymmetric(asymmetric);
    return;
}
References core, and nnp::CoreFunction::setAsymmetric().
Referenced by nnp::SymFncBaseComp::setCompactFunction().
getAsymmetric()
bool CompactFunction::getAsymmetric () const
Check if asymmetry is enabled in core function.
Returns
Whether asymmetry is activated.
Definition at line 34 of file CompactFunction.cpp.
{
    return core.getAsymmetric();
}
References core, and nnp::CoreFunction::getAsymmetric().
getCenter()
double nnp::CompactFunction::getCenter () const inline
Getter for center.
Returns
Center of compact function.
Definition at line 143 of file CompactFunction.h.
{ return center; }
References center.
getWidth()
double nnp::CompactFunction::getWidth () const inline
Getter for width.
Returns
Width of compact function.
Definition at line 144 of file CompactFunction.h.
{ return width; }
References width.
getLeft()
double nnp::CompactFunction::getLeft () const inline
Getter for left.
Returns
Left boundary of compact function.
Definition at line 145 of file CompactFunction.h.
{ return left; }
References left.
getRight()
double nnp::CompactFunction::getRight () const inline
Getter for right.
Returns
Right boundary of compact function.
Definition at line 146 of file CompactFunction.h.
{ return right; }
References right.
f()
double nnp::CompactFunction::f (double a) const inline
Compact function \(f_c\).
Parameters
[in] a Function argument.
Returns
Function value.
Definition at line 148 of file CompactFunction.h.
{
    a = (a - center) * scale;
    return core.f(std::abs(a));
}
References center, core, nnp::CoreFunction::f(), and scale.
Referenced by nnp::SymFncBaseCompAng::calculateAngularPart(), nnp::SymFncBaseCompAngWeighted::calculateAngularPart(), nnp::SymFncBaseCompAng::calculateRadialPart(), nnp::SymFncBaseCompAngWeighted::calculateRadialPart(), nnp::SymFncCompRad::calculateRadialPart(), and nnp::SymFncCompRadWeighted::calculateRadialPart().
df()
double nnp::CompactFunction::df (double a) const inline
Derivative of compact function \(\frac{d f_c}{d a}\).
Parameters
[in] a Function argument.
Returns
Value of function derivative.
Definition at line 154 of file CompactFunction.h.
{
    a = (a - center) * scale;
    return copysign(scale * core.df(std::abs(a)), a);
}
References center, core, nnp::CoreFunction::df(), and scale.
fdf()
void nnp::CompactFunction::fdf (double a, double & fa, double & dfa) const inline
Calculate compact function and derivative at once.
Parameters
[in] a Function argument.
[out] fa Cutoff function value.
[out] dfa Value of cutoff function derivative.
Definition at line 160 of file CompactFunction.h.
{
    a = (a - center) * scale;
    core.fdf(std::abs(a), fa, dfa);
    dfa *= copysign(scale, a);
    return;
}
References center, core, nnp::CoreFunction::fdf(), and scale.
Referenced by nnp::SymFncCompAngn::calculate(), nnp::SymFncCompAngnWeighted::calculate(), nnp::SymFncCompAngw::calculate(), nnp::SymFncCompAngwWeighted::calculate(), nnp::SymFncCompRad::calculate(), nnp::SymFncCompRadWeighted::calculate(), nnp::SymFncBaseCompAng::getCompactAngle(), nnp::SymFncBaseCompAngWeighted::getCompactAngle(), nnp::SymFncCompRad::getCompactOnly(), nnp::SymFncCompRadWeighted::getCompactOnly(), nnp::SymFncBaseCompAng::getCompactRadial(), and nnp::SymFncBaseCompAngWeighted::getCompactRadial().
Member Data Documentation
center
double nnp::CompactFunction::center private
Center of compact function.
Definition at line 113 of file CompactFunction.h.
Referenced by df(), f(), fdf(), getCenter(), setCenterWidth(), and setLeftRight().
width
double nnp::CompactFunction::width private
Width of compact function.
Definition at line 115 of file CompactFunction.h.
Referenced by getWidth(), setCenterWidth(), and setLeftRight().
left
double nnp::CompactFunction::left private
Left boundary of compact function.
Definition at line 117 of file CompactFunction.h.
Referenced by getLeft(), setCenterWidth(), and setLeftRight().
right
double nnp::CompactFunction::right private
Right boundary of compact function.
Definition at line 119 of file CompactFunction.h.
Referenced by getRight(), setCenterWidth(), and setLeftRight().
scale
double nnp::CompactFunction::scale private
Inverse width.
Definition at line 121 of file CompactFunction.h.
Referenced by df(), f(), fdf(), setCenterWidth(), and setLeftRight().
core
CoreFunction nnp::CompactFunction::core private
Core function to be used on either side of compact function.
Definition at line 123 of file CompactFunction.h.
Referenced by CompactFunction(), df(), f(), fdf(), getAsymmetric(), getCoreFunctionType(), setAsymmetric(), and setCoreFunction().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/CompactFunction.h
/home/runner/work/n2p2/n2p2/src/libnnp/CompactFunction.cpp