n2p2 - A neural network potential package: nnp::SymFncExpAngn Class Reference
nnp::SymFncExpAngn Class Reference
Angular symmetry function (type 3)
#include <SymFncExpAngn.h>
Public Member Functions
SymFncExpAngn (ElementMap const &elementMap)
Constructor, sets type = 3.
virtual bool operator== (SymFnc const &rhs) const
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const
Overload < operator.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
Public Member Functions inherited from nnp::SymFncBaseExpAng
virtual void setParameters (std::string const &parameterString)
Set symmetry function parameters.
virtual void changeLengthUnit (double convLength)
Change length unit.
virtual std::string getSettingsLine () const
Get settings file line from currently set parameters.
virtual std::string parameterLine () const
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
virtual double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
bool getUseIntegerPow () const
Get private useIntegerPow member variable.
std::size_t getE1 () const
Get private e1 member variable.
std::size_t getE2 () const
Get private e2 member variable.
int getZetaInt () const
Get private zetaInt member variable.
double getLambda () const
Get private lambda member variable.
double getEta () const
Get private eta member variable.
double getZeta () const
Get private zeta member variable.
double getRs () const
Get private rs member variable.
Public Member Functions inherited from nnp::SymFncBaseCutoff
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
double getCutoffAlpha () const
Get private cutoffAlpha member variable.
std::string getSubtype () const
Get private subtype member variable.
CutoffFunction::CutoffType getCutoffType () const
Get private cutoffType member variable.
Public Member Functions inherited from nnp::SymFnc
virtual ~SymFnc ()
Virtual destructor.
virtual bool operator== (SymFnc const &rhs) const =0
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const =0
Overload < operator.
bool operator!= (SymFnc const &rhs) const
Overload != operator.
bool operator> (SymFnc const &rhs) const
Overload > operator.
bool operator<= (SymFnc const &rhs) const
Overload <= operator.
bool operator>= (SymFnc const &rhs) const
Overload >= operator.
virtual void setParameters (std::string const &parameterString)=0
Set parameters.
virtual void changeLengthUnit (double convLength)=0
Change length unit.
virtual std::string getSettingsLine () const =0
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate symmetry function for one atom.
virtual std::string parameterLine () const =0
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getConvLength () const
Get private convLength member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
virtual double calculateRadialPart (double distance) const =0
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const =0
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const =0
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
void addCacheIndex (std::size_t element, std::size_t cacheIndex, std::string cacheIdentifier)
Add one cache index for given neighbor element and check identifier.
std::vector< std::vector< std::size_t > > getCacheIndices () const
Getter for cacheIndices.
Additional Inherited Members
Public Types inherited from nnp::SymFnc
enum ScalingType {
ST_NONE , ST_SCALE , ST_CENTER , ST_SCALECENTER ,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymFnc
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymFncBaseExpAng
SymFncBaseExpAng (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFncBaseCutoff
SymFncBaseCutoff (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFnc
SymFnc (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymFnc
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymFncBaseExpAng
bool useIntegerPow
Whether to use integer version of power function (faster).
std::size_t e1
Element index of neighbor atom 1.
std::size_t e2
Element index of neighbor atom 2.
int zetaInt
Integer version of \(\zeta\).
double lambda
Cosine shift factor.
double eta
Width \(\eta\) of gaussian.
double zeta
Exponent \(\zeta\) of cosine term.
double rs
Shift \(r_s\) of gaussian.
Protected Attributes inherited from nnp::SymFncBaseCutoff
double cutoffAlpha
Cutoff parameter \(\alpha\).
std::string subtype
Subtype string (specifies cutoff type).
CutoffFunction fc
Cutoff function used by this symmetry function.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function.
Protected Attributes inherited from nnp::SymFnc
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius \(r_c\).
double scalingFactor
Scaling factor.
double convLength
Data set normalization length conversion factor.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
std::vector< std::vector< std::size_t > > cacheIndices
Cache indices for each element.
Static Protected Attributes inherited from nnp::SymFnc
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Angular symmetry function (type 3)
\[ G^3_i = 2^{1-\zeta} \sum_{\substack{j,k\neq i \\ j < k}} \left(1 + \lambda \cos \theta_{ijk} \right)^\zeta \mathrm{e}^{-\eta((r_{ij}-r_s)^2 + (r_{ik}-r_s)^2 + (r_{jk}-r_s)^2) } f_c(r_{ij}) f_c(r_{ik}) f_c(r_{jk}) \]
Parameter string:
<element-central> 3 <element-neighbor1> <element-neighbor2> <eta> <lambda> <zeta> <rcutoff> <<rshift>>
where
<element-central> ..... element symbol of central atom
<element-neighbor1> ... element symbol of neighbor atom 1
<element-neighbor2> ... element symbol of neighbor atom 2
<eta> ................. \(\eta\)
<lambda> .............. \(\lambda\)
<zeta> ................ \(\zeta\)
<rcutoff> ............. \(r_c\)
<<rshift>> ............ \(r_s\) (optional, default \(r_s = 0\))
Definition at line 54 of file SymFncExpAngn.h.
Constructor & Destructor Documentation
SymFncExpAngn()
SymFncExpAngn::SymFncExpAngn (ElementMap const & elementMap)
Constructor, sets type = 3.
Definition at line 30 of file SymFncExpAngn.cpp.
                                                         :
    SymFncBaseExpAng(3, elementMap)
{
}
Member Function Documentation
operator==()
bool SymFncExpAngn::operator== (SymFnc const & rhs) const virtual
Overload == operator.
Implements nnp::SymFnc.
Definition at line 35 of file SymFncExpAngn.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymFncExpAngn const& c = dynamic_cast<SymFncExpAngn const&>(rhs);
    if (cutoffType  != c.cutoffType ) return false;
    if (cutoffAlpha != c.cutoffAlpha) return false;
    if (rc          != c.rc         ) return false;
    if (eta         != c.eta        ) return false;
    if (zeta        != c.zeta       ) return false;
    if (lambda      != c.lambda     ) return false;
    if (e1          != c.e1         ) return false;
    if (e2          != c.e2         ) return false;
    return true;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFncBaseCutoff::cutoffType, nnp::SymFncBaseExpAng::e1, nnp::SymFncBaseExpAng::e2, nnp::SymFnc::ec, nnp::SymFncBaseExpAng::eta, nnp::SymFnc::getEc(), nnp::SymFnc::getType(), nnp::SymFncBaseExpAng::lambda, nnp::SymFnc::rc, nnp::SymFnc::type, and nnp::SymFncBaseExpAng::zeta.
operator<()
bool SymFncExpAngn::operator< (SymFnc const & rhs) const virtual
Overload < operator.
Implements nnp::SymFnc.
Definition at line 51 of file SymFncExpAngn.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymFncExpAngn const& c = dynamic_cast<SymFncExpAngn const&>(rhs);
    if      (cutoffType  < c.cutoffType ) return true;
    else if (cutoffType  > c.cutoffType ) return false;
    if      (cutoffAlpha < c.cutoffAlpha) return true;
    else if (cutoffAlpha > c.cutoffAlpha) return false;
    if      (rc          < c.rc         ) return true;
    else if (rc          > c.rc         ) return false;
    if      (eta         < c.eta        ) return true;
    else if (eta         > c.eta        ) return false;
    if      (rs          < c.rs         ) return true;
    else if (rs          > c.rs         ) return false;
    if      (zeta        < c.zeta       ) return true;
    else if (zeta        > c.zeta       ) return false;
    if      (lambda      < c.lambda     ) return true;
    else if (lambda      > c.lambda     ) return false;
    if      (e1          < c.e1         ) return true;
    else if (e1          > c.e1         ) return false;
    if      (e2          < c.e2         ) return true;
    else if (e2          > c.e2         ) return false;
    return false;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFncBaseCutoff::cutoffType, nnp::SymFncBaseExpAng::e1, nnp::SymFncBaseExpAng::e2, nnp::SymFnc::ec, nnp::SymFncBaseExpAng::eta, nnp::SymFnc::getEc(), nnp::SymFnc::getType(), nnp::SymFncBaseExpAng::lambda, nnp::SymFnc::rc, nnp::SymFncBaseExpAng::rs, nnp::SymFnc::type, and nnp::SymFncBaseExpAng::zeta.
calculate()
void SymFncExpAngn::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymFnc.
Definition at line 79 of file SymFncExpAngn.cpp.
{
    double const pnorm  = pow(2.0, 1.0 - zeta);
    double const pzl    = zeta * lambda;
    double const rc2    = rc * rc;
    double       result = 0.0;
    size_t numNeighbors = atom.numNeighbors;
    // Prevent problematic condition in loop test below (j < numNeighbors - 1).
    if (numNeighbors == 0) numNeighbors = 1;
    for (size_t j = 0; j < numNeighbors - 1; j++)
    {
        Atom::Neighbor& nj = atom.neighbors[j];
        size_t const nej = nj.element;
        double const rij = nj.d;
        if ((e1 == nej || e2 == nej) && rij < rc)
        {
            double const r2ij   = rij * rij;
            // Calculate cutoff function and derivative.
            double pfcij;
            double pdfcij;
#ifndef N2P2_NO_SF_CACHE
            if (cacheIndices[nej].size() == 0) fc.fdf(rij, pfcij, pdfcij);
            else
            {
                double& cfc = nj.cache[cacheIndices[nej][0]];
                double& cdfc = nj.cache[cacheIndices[nej][1]];
                if (cfc < 0) fc.fdf(rij, cfc, cdfc);
                pfcij = cfc;
                pdfcij = cdfc;
            }
#else
            fc.fdf(rij, pfcij, pdfcij);
#endif
            for (size_t k = j + 1; k < numNeighbors; k++)
            {
                Atom::Neighbor& nk = atom.neighbors[k];
                size_t const nek = nk.element;
                if ((e1 == nej && e2 == nek) ||
                    (e2 == nej && e1 == nek))
                {
                    double const rik = nk.d;
                    if (rik < rc)
                    {
                        Vec3D drjk = nk.dr - nj.dr;
                        double rjk = drjk.norm2();;
                        if (rjk < rc2)
{
                            // Energy calculation.
                            double pfcik;
                            double pdfcik;
#ifndef N2P2_NO_SF_CACHE
                            if (cacheIndices[nej].size() == 0)
{
                                fc.fdf(rik, pfcik, pdfcik);
                            }
                            else
{
                                double& cfc = nk.cache[cacheIndices[nek][0]];
                                double& cdfc = nk.cache[cacheIndices[nek][1]];
                                if (cfc < 0) fc.fdf(rik, cfc, cdfc);
                                pfcik = cfc;
                                pdfcik = cdfc;
                            }
#else
                            fc.fdf(rik, pfcik, pdfcik);
#endif
                            rjk = sqrt(rjk);
                            double pfcjk;
                            double pdfcjk;
                            fc.fdf(rjk, pfcjk, pdfcjk);
                            Vec3D drij = nj.dr;
                            Vec3D drik = nk.dr;
                            double costijk = drij * drik;;
                            double rinvijik = 1.0 / rij / rik;
                            costijk *= rinvijik;
                            double const pfc = pfcij * pfcik * pfcjk;
                            double const r2ik = rik * rik;
                            double const rijs = rij - rs;
                            double const riks = rik - rs;
                            double const rjks = rjk - rs;
                            double const pexp = exp(-eta * (rijs * rijs +
                                                            riks * riks +
                                                            rjks * rjks));
                            double const plambda = 1.0 + lambda * costijk;
                            double       fg = pexp;
                            if (plambda <= 0.0) fg = 0.0;
                            else
{
                                if (useIntegerPow)
{
                                    fg *= pow_int(plambda, zetaInt - 1);
                                }
                                else
{
                                    fg *= pow(plambda, zeta - 1.0);
                                }
                            }
                            result += fg * plambda * pfc;
                            // Force calculation.
                            if (!derivatives) continue;
                            fg       *= pnorm;
                            rinvijik *= pzl;
                            costijk  *= pzl;
                            double const p2etapl = 2.0 * eta * plambda;
                            double const p1 = fg * (pfc * (rinvijik - costijk
                                            / r2ij - p2etapl * rijs / rij)
                                            + pfcik * pfcjk * pdfcij * plambda
                                            / rij);
                            double const p2 = fg * (pfc * (rinvijik - costijk
                                            / r2ik - p2etapl * riks / rik)
                                            + pfcij * pfcjk * pdfcik * plambda
                                            / rik);
                            double const p3 = fg * (pfc * (rinvijik + p2etapl
                                            * rjks / rjk) - pfcij * pfcik
                                            * pdfcjk * plambda / rjk);
                            drij *= p1 * scalingFactor;
                            drik *= p2 * scalingFactor;
                            drjk *= p3 * scalingFactor;
                            // Save force contributions in Atom storage.
                            atom.dGdr[index] += drij + drik;
#ifndef N2P2_FULL_SFD_MEMORY
                            nj.dGdr[indexPerElement[nej]] -= drij + drjk;
                            nk.dGdr[indexPerElement[nek]] -= drik - drjk;
#else
                            nj.dGdr[index] -= drij + drjk;
                            nk.dGdr[index] -= drik - drjk;
#endif
                        } // rjk <= rc
                    } // rik <= rc
                } // elem
            } // k
        } // rij <= rc
    } // j
    result *= pnorm;
    atom.G[index] = scale(result);
    return;
}
References nnp::Atom::Neighbor::cache, nnp::SymFnc::cacheIndices, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::SymFncBaseExpAng::e1, nnp::SymFncBaseExpAng::e2, nnp::Atom::Neighbor::element, nnp::SymFncBaseExpAng::eta, nnp::SymFncBaseCutoff::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymFnc::index, nnp::SymFnc::indexPerElement, nnp::SymFncBaseExpAng::lambda, nnp::Atom::neighbors, nnp::Vec3D::norm2(), nnp::Atom::numNeighbors, nnp::pow_int(), nnp::SymFnc::rc, nnp::SymFncBaseExpAng::rs, nnp::SymFnc::scale(), nnp::SymFnc::scalingFactor, nnp::SymFncBaseExpAng::useIntegerPow, nnp::SymFncBaseExpAng::zeta, and nnp::SymFncBaseExpAng::zetaInt.
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncExpAngn.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncExpAngn.cpp