n2p2 - A neural network potential package: nnp::SymFncCompRadWeighted Class Reference
nnp::SymFncCompRadWeighted Class Reference
Weighted radial symmetry function with compact support (type 23)
#include <SymFncCompRadWeighted.h>
Public Member Functions
SymFncCompRadWeighted (ElementMap const &elementMap)
Constructor, sets type = 23.
virtual bool operator== (SymFnc const &rhs) const
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const
Overload < operator.
virtual void setParameters (std::string const &parameterString)
Set symmetry function parameters.
virtual void changeLengthUnit (double convLength)
Change length unit.
virtual std::string getSettingsLine () const
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
void getCompactOnly (double const x, double &fx, double &dfx) const
virtual std::string parameterLine () const
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
virtual double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
Public Member Functions inherited from nnp::SymFncBaseComp
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setCompactFunction (std::string subtype)
Set radial compact function.
std::string getSubtype () const
Get private subtype member variable.
double getRl () const
Get private rl member variable.
Public Member Functions inherited from nnp::SymFnc
virtual ~SymFnc ()
Virtual destructor.
virtual bool operator== (SymFnc const &rhs) const =0
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const =0
Overload < operator.
bool operator!= (SymFnc const &rhs) const
Overload != operator.
bool operator> (SymFnc const &rhs) const
Overload > operator.
bool operator<= (SymFnc const &rhs) const
Overload <= operator.
bool operator>= (SymFnc const &rhs) const
Overload >= operator.
virtual void setParameters (std::string const &parameterString)=0
Set parameters.
virtual void changeLengthUnit (double convLength)=0
Change length unit.
virtual std::string getSettingsLine () const =0
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate symmetry function for one atom.
virtual std::string parameterLine () const =0
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getConvLength () const
Get private convLength member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
virtual double calculateRadialPart (double distance) const =0
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const =0
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const =0
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
void addCacheIndex (std::size_t element, std::size_t cacheIndex, std::string cacheIdentifier)
Add one cache index for given neighbor element and check identifier.
std::vector< std::vector< std::size_t > > getCacheIndices () const
Getter for cacheIndices.
Additional Inherited Members
Public Types inherited from nnp::SymFnc
enum ScalingType {
ST_NONE , ST_SCALE , ST_CENTER , ST_SCALECENTER ,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymFnc
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymFncBaseComp
SymFncBaseComp (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFnc
SymFnc (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymFnc
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymFncBaseComp
bool asymmetric
If asymmetric version of polynomials should be used.
double rl
Lower bound of compact function, \(r_{l}\).
std::string subtype
Subtype string (specifies e.g. polynom type).
CompactFunction cr
Compact function for radial part.
Protected Attributes inherited from nnp::SymFnc
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius \(r_c\).
double scalingFactor
Scaling factor.
double convLength
Data set normalization length conversion factor.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
std::vector< std::vector< std::size_t > > cacheIndices
Cache indices for each element.
Static Protected Attributes inherited from nnp::SymFnc
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Weighted radial symmetry function with compact support (type 23)
\[ G^{23}_i = \sum_{\substack{j \neq i}} Z_j C(r_{ij}, r_l, r_c), \]
where \(C(x, x_\text{low}, x_\text{high})\) is a function with compact support \(\left[x_\text{low}, x_\text{high}\right]\). \(Z_j\) is defined as the atomic number of the neighbor atom \(j\).
Parameter string:
<element-central> 23 <rlow> <rcutoff> <subtype>
where
<element-central> .... element symbol of central atom
<rlow> ................ low radius boundary \(r_{l}\)
<rcutoff> ............. high radius boundary \(r_{c}\)
<subtype> ............ compact function specifier
See the description of SymFncBaseComp::setCompactFunction() for possible values of the <subtype> argument.
Definition at line 56 of file SymFncCompRadWeighted.h.
Constructor & Destructor Documentation
SymFncCompRadWeighted()
SymFncCompRadWeighted::SymFncCompRadWeighted (ElementMap const & elementMap)
Constructor, sets type = 23.
Definition at line 31 of file SymFncCompRadWeighted.cpp.
                                                                         :
    SymFncBaseComp(23, elementMap)
{
    minNeighbors = 1;
}
References nnp::SymFnc::minNeighbors.
Member Function Documentation
operator==()
bool SymFncCompRadWeighted::operator== (SymFnc const & rhs) const virtual
Overload == operator.
Implements nnp::SymFnc.
Definition at line 37 of file SymFncCompRadWeighted.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymFncCompRadWeighted const& c
        = dynamic_cast<SymFncCompRadWeighted const&>(rhs);
    if (subtype     != c.getSubtype()) return false;
    if (rc          != c.rc          ) return false;
    if (rl          != c.rl          ) return false;
    return true;
}
References nnp::SymFnc::ec, nnp::SymFnc::getEc(), nnp::SymFncBaseComp::getSubtype(), nnp::SymFnc::getType(), nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
operator<()
bool SymFncCompRadWeighted::operator< (SymFnc const & rhs) const virtual
Overload < operator.
Implements nnp::SymFnc.
Definition at line 49 of file SymFncCompRadWeighted.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymFncCompRadWeighted const& c
        = dynamic_cast<SymFncCompRadWeighted const&>(rhs);
    if      (subtype     < c.getSubtype()) return true;
    else if (subtype     > c.getSubtype()) return false;
    if      (rc          < c.rc          ) return true;
    else if (rc          > c.rc          ) return false;
    if      (rl          < c.rl          ) return true;
    else if (rl          > c.rl          ) return false;
    return false;
}
References nnp::SymFnc::ec, nnp::SymFnc::getEc(), nnp::SymFncBaseComp::getSubtype(), nnp::SymFnc::getType(), nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
setParameters()
void SymFncCompRadWeighted::setParameters (std::string const & parameterString) virtual
Set symmetry function parameters.
Parameters
[in] parameterString String containing weighted radial symmetry function parameters.
Implements nnp::SymFnc.
Definition at line 66 of file SymFncCompRadWeighted.cpp.
{
    vector<string> splitLine = split(reduce(parameterString));
    if (type != (size_t)atoi(splitLine.at(1).c_str()))
    {
        throw runtime_error("ERROR: Incorrect symmetry function type.\n");
    }
    ec      = elementMap[splitLine.at(0)];
    rl      = atof(splitLine.at(2).c_str());
    rc      = atof(splitLine.at(3).c_str());
    subtype = splitLine.at(4);
    if (rl > rc)
    {
        throw runtime_error("ERROR: Lower radial boundary >= upper "
                            "radial boundary.\n");
    }
    //if (rl < 0.0 && abs(rl + rc) > numeric_limits<double>::epsilon())
    //{
    //    throw runtime_error("ERROR: Radial function not symmetric "
    //                        "w.r.t. origin.\n");
    //}
    setCompactFunction(subtype);
    cr.setLeftRight(rl,rc);
    return;
}
References nnp::SymFncBaseComp::cr, nnp::SymFnc::ec, nnp::SymFnc::elementMap, nnp::SymFnc::rc, nnp::reduce(), nnp::SymFncBaseComp::rl, nnp::SymFncBaseComp::setCompactFunction(), nnp::CompactFunction::setLeftRight(), nnp::split(), nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
changeLengthUnit()
void SymFncCompRadWeighted::changeLengthUnit (double convLength) virtual
Change length unit.
Parameters
[in] convLength Multiplicative length unit conversion factor.
Implements nnp::SymFnc.
Definition at line 97 of file SymFncCompRadWeighted.cpp.
{
    this->convLength = convLength;
    rl *= convLength;
    rc *= convLength;
    cr.setLeftRight(rl, rc);
    return;
}
References nnp::SymFnc::convLength, nnp::SymFncBaseComp::cr, nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, and nnp::CompactFunction::setLeftRight().
getSettingsLine()
string SymFncCompRadWeighted::getSettingsLine () const virtual
Get settings file line from currently set parameters.
Returns
Settings file string ("symfunction_short ...").
Implements nnp::SymFnc.
Definition at line 108 of file SymFncCompRadWeighted.cpp.
{
    string s = strpr("symfunction_short %2s %2zu %16.8E %16.8E %s\n",
                     elementMap[ec].c_str(),
                     type,
                     rl / convLength,
                     rc / convLength,
                     subtype.c_str());
    return s;
}
References nnp::SymFnc::convLength, nnp::SymFnc::ec, nnp::SymFnc::elementMap, nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::strpr(), nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
calculate()
void SymFncCompRadWeighted::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymFnc.
Definition at line 120 of file SymFncCompRadWeighted.cpp.
{
    double result = 0.0;
    for (size_t j = 0; j < atom.numNeighbors; ++j)
    {
        Atom::Neighbor& n = atom.neighbors[j];
        if (n.d > rl && n.d < rc)
        {
            // Energy calculation.
            size_t const ne = n.element;
            double const rij = n.d;
            double rad;
            double drad;
            double r = rij;
#ifndef N2P2_NO_SF_CACHE
            if (cacheIndices[ne].size() == 0) cr.fdf(r, rad, drad);
            else
            {
                double& crad = n.cache[cacheIndices[ne][0]];
                double& cdrad = n.cache[cacheIndices[ne][1]];
                if (crad < 0) cr.fdf(r, crad, cdrad);
                rad = crad;
                drad = cdrad;
            }
#else
            cr.fdf(r, rad, drad);
#endif
            result += rad * elementMap.atomicNumber(ne);
            // Force calculation.
            if (!derivatives) continue;
            double const p1 = scalingFactor * elementMap.atomicNumber(ne)
                            * drad / rij;
            Vec3D dij = p1 * n.dr;
            // Save force contributions in Atom storage.
            atom.dGdr[index] += dij;
#ifndef N2P2_FULL_SFD_MEMORY
            n.dGdr[indexPerElement[ne]] -= dij;
#else
            n.dGdr[index] -= dij;
#endif
        }
    }
    atom.G[index] = scale(result);
    return;
}
References nnp::ElementMap::atomicNumber(), nnp::Atom::Neighbor::cache, nnp::SymFnc::cacheIndices, nnp::SymFncBaseComp::cr, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::Atom::Neighbor::element, nnp::SymFnc::elementMap, nnp::CompactFunction::fdf(), nnp::Atom::G, nnp::SymFnc::index, nnp::SymFnc::indexPerElement, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::SymFnc::scale(), and nnp::SymFnc::scalingFactor.
getCompactOnly()
void nnp::SymFncCompRadWeighted::getCompactOnly (double const x, double & fx, double & dfx) const inline
Definition at line 140 of file SymFncCompRadWeighted.h.
{
    cr.fdf(x, fx, dfx);
    return;
}
References nnp::SymFncBaseComp::cr, and nnp::CompactFunction::fdf().
Referenced by nnp::SymGrpCompRadWeighted::calculate().
parameterLine()
string SymFncCompRadWeighted::parameterLine () const virtual
Give symmetry function parameters in one line.
Returns
String containing symmetry function parameter values.
Implements nnp::SymFnc.
Definition at line 171 of file SymFncCompRadWeighted.cpp.
{
    return strpr(getPrintFormat().c_str(),
                 index + 1,
                 elementMap[ec].c_str(),
                 type,
                 subtype.c_str(),
                 rl / convLength,
                 rc / convLength,
                 lineNumber + 1);
}
References nnp::SymFnc::convLength, nnp::SymFnc::ec, nnp::SymFnc::elementMap, nnp::SymFnc::getPrintFormat(), nnp::SymFnc::index, nnp::SymFnc::lineNumber, nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::strpr(), nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
parameterInfo()
vector< string > SymFncCompRadWeighted::parameterInfo () const virtual
Get description with parameter names and values.
Returns
Vector of parameter description strings.
Reimplemented from nnp::SymFncBaseComp.
Definition at line 183 of file SymFncCompRadWeighted.cpp.
{
    vector<string> v = SymFncBaseComp::parameterInfo();
    return v;
}
References nnp::SymFncBaseComp::parameterInfo().
calculateRadialPart()
double SymFncCompRadWeighted::calculateRadialPart (double distance) const virtual
Calculate (partial) symmetry function value for one given distance.
Parameters
[in] distance Distance between two atoms.
Returns
\(e^{-\eta (r - r_s)^2} f_c(r)\)
Implements nnp::SymFnc.
Definition at line 190 of file SymFncCompRadWeighted.cpp.
{
    double const& r = distance * convLength;
    return cr.f(r);
}
References nnp::SymFnc::convLength, nnp::SymFncBaseComp::cr, and nnp::CompactFunction::f().
calculateAngularPart()
double SymFncCompRadWeighted::calculateAngularPart (double angle) const virtual
Calculate (partial) symmetry function value for one given angle.
Parameters
[in] angle Angle between triplet of atoms (in radians).
Returns
\(1\)
Implements nnp::SymFnc.
Definition at line 197 of file SymFncCompRadWeighted.cpp.
{
    return 1.0;
}
checkRelevantElement()
bool SymFncCompRadWeighted::checkRelevantElement (std::size_t index) const virtual
Check whether symmetry function is relevant for given element.
Parameters
[in] index Index of given element.
Returns
True if symmetry function is sensitive to given element, false otherwise.
Implements nnp::SymFnc.
Definition at line 202 of file SymFncCompRadWeighted.cpp.
{
    return true;
}
getCacheIdentifiers()
vector< string > SymFncCompRadWeighted::getCacheIdentifiers () const virtual
Get unique cache identifiers.
Returns
Vector of string identifying the type of cache this symmetry function requires.
Reimplemented from nnp::SymFnc.
Definition at line 208 of file SymFncCompRadWeighted.cpp.
{
    vector<string> v;
    string s("");
    s += subtype;
    s += " ";
    s += strpr("rl = %16.8E", rl / convLength);
    s += " ";
    s += strpr("rc = %16.8E", rc / convLength);
    for (size_t i = 0; i < elementMap.size(); ++i)
    {
        v.push_back(strpr("%zu f ", i) + s);
        v.push_back(strpr("%zu df ", i) + s);
    }
    return v;
}
References nnp::SymFnc::convLength, nnp::SymFnc::elementMap, nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::ElementMap::size(), nnp::strpr(), and nnp::SymFncBaseComp::subtype.
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncCompRadWeighted.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncCompRadWeighted.cpp