n2p2 - A neural network potential package: nnp::SymGrpCompRad Class Reference
nnp::SymGrpCompRad Class Reference
Radial symmetry function with compact support (type 20)
#include <SymGrpCompRad.h>
Public Member Functions
SymGrpCompRad (ElementMap const &elementMap)
Constructor, sets type = 20.
virtual bool operator== (SymGrp const &rhs) const
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const
Overload < operator.
virtual bool addMember (SymFnc const *const symmetryFunction)
Potentially add a member to group.
virtual void sortMembers ()
Sort member symmetry functions.
virtual void setScalingFactors ()
Fill scalingFactors with values from member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate all symmetry functions of this group for one atom.
virtual std::vector< std::string > parameterLines () const
Give symmetry function group parameters on multiple lines.
Public Member Functions inherited from nnp::SymGrpBaseComp
double getRmin () const
Getter for rmin.
double getRmax () const
Getter for rmax.
Public Member Functions inherited from nnp::SymGrp
virtual ~SymGrp ()
Virtual destructor.
virtual bool operator== (SymGrp const &rhs) const =0
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const =0
Overload < operator.
bool operator!= (SymGrp const &rhs) const
Overload != operator.
bool operator> (SymGrp const &rhs) const
Overload > operator.
bool operator<= (SymGrp const &rhs) const
Overload <= operator.
bool operator>= (SymGrp const &rhs) const
Overload >= operator.
virtual bool addMember (SymFnc const *const symmetryFunction)=0
Potentially add a member to group.
virtual void sortMembers ()=0
Sort member symmetry functions.
virtual void setScalingFactors ()=0
Fill scalingFactors with values from member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate all symmetry functions of this group for one atom.
virtual std::vector< std::string > parameterLines () const =0
Give symmetry function group parameters on multiple lines.
void setIndex (std::size_t index)
Set private index member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getType () const
Get private type member variable.
std::size_t getEc () const
Get private ec member variable.
Private Attributes
std::size_t e1
Element index of neighbor atom (common feature).
std::vector< SymFncCompRad const * > members
Vector of all group member pointers.
std::vector< double > mrl
Member rl.
std::vector< double > mrc
Member rc.
std::vector< std::vector< std::size_t > > mci
Member cache indices for actual neighbor element.
Additional Inherited Members
Protected Types inherited from nnp::SymGrp
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymGrpBaseComp
SymGrpBaseComp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
Protected Member Functions inherited from nnp::SymGrp
SymGrp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
std::string getPrintFormatCommon () const
Get common parameter line format string.
std::string getPrintFormatMember () const
Get member parameter line format string.
Static Protected Member Functions inherited from nnp::SymGrp
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymGrpBaseComp
double rmin
Minimum radius within group.
double rmax
Maximum radius within group.
Protected Attributes inherited from nnp::SymGrp
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function group index.
std::size_t ec
Element index of center atom (common feature).
double convLength
Data set normalization length conversion factor.
std::vector< size_t > memberIndex
Vector containing indices of all member symmetry functions.
std::vector< double > scalingFactors
Scaling factors of all member symmetry functions.
std::set< std::string > parametersCommon
Set of common parameters IDs.
std::set< std::string > parametersMember
Set of common parameters IDs.
std::vector< std::vector< std::size_t > > memberIndexPerElement
Vector containing per-element indices of all member symmetry functions.
Static Protected Attributes inherited from nnp::SymGrp
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Radial symmetry function with compact support (type 20)
\[ G^{20}_i = \sum_{\substack{j \neq i}} C(r_{ij}, r_l, r_c), \]
where \(C(x, x_\text{low}, x_\text{high})\) is a function with compact support \(\left[x_\text{low}, x_\text{high}\right]\).
Common features:
element of central atom
element of neighbor atom
Definition at line 47 of file SymGrpCompRad.h.
Constructor & Destructor Documentation
SymGrpCompRad()
SymGrpCompRad::SymGrpCompRad (ElementMap const & elementMap)
Constructor, sets type = 20.
Definition at line 31 of file SymGrpCompRad.cpp.
                                            :
    SymGrpBaseComp(20, elementMap),
    e1(0)
{
    parametersCommon.insert("e1");
}
References nnp::SymGrp::parametersCommon.
Member Function Documentation
operator==()
bool SymGrpCompRad::operator== (SymGrp const & rhs) const virtual
Overload == operator.
Implements nnp::SymGrp.
Definition at line 39 of file SymGrpCompRad.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymGrpCompRad const& c = dynamic_cast<SymGrpCompRad const&>(rhs);
    if (e1 != c.e1) return false;
    return true;
}
References e1, nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), and nnp::SymGrp::type.
operator<()
bool SymGrpCompRad::operator< (SymGrp const & rhs) const virtual
Overload < operator.
Implements nnp::SymGrp.
Definition at line 48 of file SymGrpCompRad.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymGrpCompRad const& c = dynamic_cast<SymGrpCompRad const&>(rhs);
    if      (e1 < c.e1) return true;
    else if (e1 > c.e1) return false;
    return false;
}
References e1, nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), and nnp::SymGrp::type.
addMember()
bool SymGrpCompRad::addMember (SymFnc const *const symmetryFunction) virtual
Potentially add a member to group.
Parameters
[in] symmetryFunction Candidate symmetry function.
Returns
If addition was successful.
If symmetry function is compatible with common feature list its pointer will be added to members.
Implements nnp::SymGrp.
Definition at line 60 of file SymGrpCompRad.cpp.
{
    if (symmetryFunction->getType() != type) return false;
    SymFncCompRad const* sf =
        dynamic_cast<SymFncCompRad const*>(symmetryFunction);
    if (members.empty())
    {
        ec          = sf->getEc();
        e1          = sf->getE1();
        convLength  = sf->getConvLength();
    }
    if (sf->getEc()          != ec         ) return false;
    if (sf->getE1()          != e1         ) return false;
    if (sf->getConvLength()  != convLength )
    {
        throw runtime_error("ERROR: Unable to add symmetry function members "
                            "with different conversion factors.\n");
    }
    if (sf->getRl() <= 0.0) rmin = 0.0;
    else rmin = min( rmin, sf->getRl() );
    rmax = max( rmax, sf->getRc() );
    members.push_back(sf);
    return true;
}
References nnp::SymGrp::convLength, e1, nnp::SymGrp::ec, nnp::SymFnc::getConvLength(), nnp::SymFncCompRad::getE1(), nnp::SymFnc::getEc(), nnp::SymFnc::getRc(), nnp::SymFncBaseComp::getRl(), nnp::SymFnc::getType(), members, nnp::SymGrpBaseComp::rmax, nnp::SymGrpBaseComp::rmin, and nnp::SymGrp::type.
sortMembers()
void SymGrpCompRad::sortMembers () virtual
Sort member symmetry functions.
Also allocate and precalculate additional stuff.
Implements nnp::SymGrp.
Definition at line 91 of file SymGrpCompRad.cpp.
{
    sort(members.begin(),
         members.end(),
         comparePointerTargets<SymFncCompRad const>);
    for (size_t i = 0; i < members.size(); i++)
    {
        memberIndex.push_back(members[i]->getIndex());
        memberIndexPerElement.push_back(members[i]->getIndexPerElement());
    }
    mrl.resize(members.size(), 0.0);
    mrc.resize(members.size(), 0.0);
    for (size_t i = 0; i < members.size(); i++)
    {
        mrl.at(i) = members[i]->getRl();
        mrc.at(i) = members[i]->getRc();
    }
#ifndef N2P2_NO_SF_CACHE
    mci.resize(members.size());
    for (size_t k = 0; k < members.size(); ++k)
    {
        mci.at(k) = members.at(k)->getCacheIndices()[e1];
    }
#endif
    return;
}
References e1, nnp::SymGrp::getIndex(), mci, nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, mrc, and mrl.
setScalingFactors()
void SymGrpCompRad::setScalingFactors () virtual
Fill scalingFactors with values from member symmetry functions.
Implements nnp::SymGrp.
Definition at line 122 of file SymGrpCompRad.cpp.
{
    scalingFactors.resize(members.size(), 0.0);
    for (size_t i = 0; i < members.size(); i++)
    {
        scalingFactors.at(i) = members[i]->getScalingFactor();
    }
    return;
}
References members, and nnp::SymGrp::scalingFactors.
calculate()
void SymGrpCompRad::calculate (Atom & atom, bool const derivatives) const virtual
Calculate all symmetry functions of this group for one atom.
Parameters
[in,out] atom Atom for which symmetry functions are caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymGrp.
Definition at line 139 of file SymGrpCompRad.cpp.
{
    double* result = new double[members.size()];
    for (size_t k = 0; k < members.size(); ++k)
    {
        result[k] = 0.0;
    }
    for (size_t j = 0; j < atom.numNeighbors; ++j)
    {
        Atom::Neighbor& n = atom.neighbors[j];
        double const rij = n.d;
        if (e1 == n.element && rij < rmax && rij > rmin)
        {
            // Energy calculation.
            double const* const d1 = n.dr.r;
            for (size_t k = 0; k < members.size(); ++k)
            {
                SymFncCompRad const& sf = *(members[k]);
                if (rij <= mrl[k] || rij >= mrc[k]) continue;
                double rad;
                double drad;
#ifndef N2P2_NO_SF_CACHE
                if (mci[k].size() == 0) sf.getCompactOnly(rij, rad, drad);
                else
                {
                    double& crad = n.cache[mci[k][0]];
                    double& cdrad = n.cache[mci[k][1]];
                    if (crad < 0) sf.getCompactOnly(rij, crad, cdrad);
                    rad = crad;
                    drad = cdrad;
                }
#else
                sf.getCompactOnly(rij, rad, drad);
#endif
                result[k] += rad;
                // Force calculation.
                if (!derivatives || drad == 0.0) continue;
                drad *= scalingFactors[k] / rij;
                // SIMPLE EXPRESSIONS:
                //Vec3D const dij = p1 * atom.neighbors[j].dr;
                double const p1drijx = drad * d1[0];
                double const p1drijy = drad * d1[1];
                double const p1drijz = drad * d1[2];
                // Save force contributions in Atom storage.
#ifndef N2P2_FULL_SFD_MEMORY
                size_t ki = memberIndex[k];
#else
                size_t const ki = memberIndex[k];
#endif
                // SIMPLE EXPRESSIONS:
                //atom.dGdr[ki]              += dij;
                //atom.neighbors[j].dGdr[ki] -= dij;
                double* dGdr = atom.dGdr[ki].r;
                dGdr[0] += p1drijx;
                dGdr[1] += p1drijy;
                dGdr[2] += p1drijz;
#ifndef N2P2_FULL_SFD_MEMORY
                ki = memberIndexPerElement[k][e1];
#endif
                dGdr = n.dGdr[ki].r;
                dGdr[0] -= p1drijx;
                dGdr[1] -= p1drijy;
                dGdr[2] -= p1drijz;
            }
        }
    }
    for (size_t k = 0; k < members.size(); ++k)
    {
        atom.G[memberIndex[k]] = members[k]->scale(result[k]);
    }
    delete[] result;
    return;
}
References nnp::Atom::Neighbor::cache, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, e1, nnp::Atom::Neighbor::element, nnp::Atom::G, nnp::SymFncCompRad::getCompactOnly(), mci, nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, mrc, mrl, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::Vec3D::r, nnp::SymGrpBaseComp::rmin, and nnp::SymGrp::scalingFactors.
parameterLines()
vector< string > SymGrpCompRad::parameterLines () const virtual
Give symmetry function group parameters on multiple lines.
Returns
Vector of string containing symmetry function parameters lines.
Implements nnp::SymGrp.
Definition at line 221 of file SymGrpCompRad.cpp.
{
    vector<string> v;
    v.push_back(strpr(getPrintFormatCommon().c_str(),
                      index + 1,
                      elementMap[ec].c_str(),
                      type,
                      elementMap[e1].c_str(),
                      rmin / convLength,
                      rmax / convLength));
    for (size_t i = 0; i < members.size(); ++i)
    {
        v.push_back(strpr(getPrintFormatMember().c_str(),
                          members[i]->getSubtype().c_str(),
                          members[i]->getRl() / convLength,
                          members[i]->getRc() / convLength,
                          members[i]->getLineNumber() + 1,
                          i + 1,
                          members[i]->getIndex() + 1));
    }
    return v;
}
References nnp::SymGrp::convLength, e1, nnp::SymGrp::ec, nnp::SymGrp::elementMap, nnp::SymGrp::getIndex(), nnp::SymGrp::getPrintFormatCommon(), nnp::SymGrp::getPrintFormatMember(), nnp::SymGrp::index, members, nnp::SymGrpBaseComp::rmax, nnp::SymGrpBaseComp::rmin, nnp::strpr(), and nnp::SymGrp::type.
Member Data Documentation
e1
std::size_t nnp::SymGrpCompRad::e1 private
Element index of neighbor atom (common feature).
Definition at line 92 of file SymGrpCompRad.h.
Referenced by addMember(), calculate(), operator<(), operator==(), parameterLines(), and sortMembers().
members
std::vector<SymFncCompRad const*> nnp::SymGrpCompRad::members private
Vector of all group member pointers.
Definition at line 94 of file SymGrpCompRad.h.
Referenced by addMember(), calculate(), parameterLines(), setScalingFactors(), and sortMembers().
mrl
std::vector<double> nnp::SymGrpCompRad::mrl private
Member rl.
Definition at line 96 of file SymGrpCompRad.h.
Referenced by calculate(), and sortMembers().
mrc
std::vector<double> nnp::SymGrpCompRad::mrc private
Member rc.
Definition at line 98 of file SymGrpCompRad.h.
Referenced by calculate(), and sortMembers().
mci
std::vector<std::vector<std::size_t> > nnp::SymGrpCompRad::mci private
Member cache indices for actual neighbor element.
Definition at line 101 of file SymGrpCompRad.h.
Referenced by calculate(), and sortMembers().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpCompRad.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpCompRad.cpp