n2p2 - A neural network potential package: nnp::Stopwatch Class Reference
nnp::Stopwatch Class Reference
Implements a simple stopwatch on different platforms.
#include <Stopwatch.h>
Public Member Functions
Stopwatch ()
void start (bool newLoop=true)
Start the stopwatch.
double stop ()
Stop and return total time.
double loop ()
Stop and return loop time.
double getTotal () const
Return total time elapsed (of a stopped watch).
double getLoop () const
Return time elapsed in last loop interval (of a stopped watch).
void reset ()
Reset stopwatch (total and loop time zero, clock not running).
Private Types
enum State { STOPPED, RUNNING }
Private Member Functions
void stopTime ()
double updateTime ()
Private Attributes
State state
bool resetLoop
double timeTotal
double timeLoop
Static Private Attributes
static const double NSEC = 1E-9
Detailed Description
Implements a simple stopwatch on different platforms.
Definition at line 38 of file Stopwatch.h.
Member Enumeration Documentation
State
enum nnp::Stopwatch::State private
Enumerator
STOPPED
RUNNING
Definition at line 63 of file Stopwatch.h.
     {
         STOPPED,
         RUNNING
     };
Constructor & Destructor Documentation
Stopwatch()
Stopwatch::Stopwatch ()
Definition at line 24 of file Stopwatch.cpp.
References state, STOPPED, timeLoop, and timeTotal.
 {
     state        = STOPPED;
     timeTotal    = 0.0;
     timeLoop     = 0.0;
 #ifdef N2P2_NO_TIME
     //fprintf(stderr, "WARNING: Stopwatch is using dummy implementation.\n");
 #elif __linux__
     time.tv_sec  = 0;
     time.tv_nsec = 0;
 #elif __MACH__
     time         = 0;
 #endif
 }
Member Function Documentation
start()
void Stopwatch::start (bool newLoop = true)
Start the stopwatch.
Parameters
[in] resetLoop Optional. If true reset loop time, i.e. this start() call is then also the beginning of a new loop. Use false if you want to accumulate further time in the loop timer. Default: true.
Definition at line 40 of file Stopwatch.cpp.
References RUNNING, state, STOPPED, and timeLoop.
Referenced by runTest().
 {
     if (state == STOPPED)
     {
 #ifdef N2P2_NO_TIME
 #elif __linux__
         clock_gettime(CLOCK_MONOTONIC, &time);
 #elif __MACH__
         time = mach_absolute_time();
 #endif
         if (newLoop) timeLoop = 0.0;
         state = RUNNING;
     }
     else
     {
         fprintf(stderr,
                 "WARNING: Unable to start clock, clock already running.\n");
     }
     return;
 }
stop()
double Stopwatch::stop ()
Stop and return total time.
Definition at line 62 of file Stopwatch.cpp.
References getTotal(), and stopTime().
Referenced by runTest().
 {
     stopTime();
     return getTotal();
 }
loop()
double Stopwatch::loop ()
Stop and return loop time.
Definition at line 69 of file Stopwatch.cpp.
References getLoop(), and stopTime().
 {
     stopTime();
     return getLoop();
 }
getTotal()
double nnp::Stopwatch::getTotal () const inline
Return total time elapsed (of a stopped watch).
Definition at line 56 of file Stopwatch.h.
References timeTotal.
Referenced by stop().
 {return timeTotal;};
getLoop()
double nnp::Stopwatch::getLoop () const inline
Return time elapsed in last loop interval (of a stopped watch).
Definition at line 58 of file Stopwatch.h.
References reset(), and timeLoop.
Referenced by loop().
 {return timeLoop;};
reset()
void Stopwatch::reset ()
Reset stopwatch (total and loop time zero, clock not running).
Definition at line 76 of file Stopwatch.cpp.
References state, STOPPED, timeLoop, and timeTotal.
Referenced by getLoop(), and runTest().
 {
     state        = STOPPED;
     timeTotal    = 0.0;
     timeLoop     = 0.0;
 #ifdef N2P2_NO_TIME
 #elif __linux__
     time.tv_sec  = 0;
     time.tv_nsec = 0;
 #elif __MACH__
     time         = 0;
 #endif
     return;
 }
stopTime()
void Stopwatch::stopTime () private
Definition at line 92 of file Stopwatch.cpp.
References state, STOPPED, timeLoop, timeTotal, and updateTime().
Referenced by loop(), and stop().
 {
     double timeInterval = updateTime();
     timeLoop += timeInterval;
     timeTotal += timeInterval;
     state = STOPPED;
     return;
 }
updateTime()
double Stopwatch::updateTime () private
Definition at line 102 of file Stopwatch.cpp.
References NSEC, RUNNING, and state.
Referenced by stopTime().
 {
     if (state == RUNNING)
     {
 #ifdef N2P2_NO_TIME
         return 1.0;
 #elif __linux__
         time_t   secLast  = time.tv_sec;
         long     nsecLast = time.tv_nsec;
         clock_gettime(CLOCK_MONOTONIC, &time);
         return (double)(time.tv_sec  - secLast)
              + (double)(time.tv_nsec - nsecLast) * NSEC;
 #elif __MACH__
         uint64_t                         lastTime = time;
         uint64_t                         time     = mach_absolute_time();
         static mach_timebase_info_data_t info     = {0, 0};
         if (info.denom == 0) mach_timebase_info(&info);
         return ((time - lastTime) * (info.numer / info.denom)) * NSEC;
 #endif
     }
     else
     {
         fprintf(stderr,
                 "WARNING: Unable to update time, clock not running.\n");
         return 0.0;
     }
 }
Member Data Documentation
state
State nnp::Stopwatch::state private
Definition at line 69 of file Stopwatch.h.
Referenced by reset(), start(), stopTime(), Stopwatch(), and updateTime().
resetLoop
bool nnp::Stopwatch::resetLoop private
Definition at line 70 of file Stopwatch.h.
NSEC
const double Stopwatch::NSEC = 1E-9 static private
Definition at line 71 of file Stopwatch.h.
Referenced by updateTime().
timeTotal
double nnp::Stopwatch::timeTotal private
Definition at line 72 of file Stopwatch.h.
Referenced by getTotal(), reset(), stopTime(), and Stopwatch().
timeLoop
double nnp::Stopwatch::timeLoop private
Definition at line 73 of file Stopwatch.h.
Referenced by getLoop(), reset(), start(), stopTime(), and Stopwatch().
The documentation for this class was generated from the following files:
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Stopwatch.h
/home/travis/build/CompPhysVienna/n2p2/src/libnnp/Stopwatch.cpp