n2p2 - A neural network potential package: nnp::SetupAnalysis Class Reference
nnp::SetupAnalysis Class Reference
#include <SetupAnalysis.h>
Public Member Functions
void writeSymmetryFunctionShape (std::size_t numPoints, std::string const fileNameFormat="sf.%03zu.%04zu.out")
Write radial and angular part of symmetry functions to file.
Public Member Functions inherited from nnp::Mode
Mode ()
void initialize ()
Write welcome message with version information.
void loadSettingsFile (std::string const &fileName="input.nn")
Open settings file and load all keywords into memory.
void setupGeneric (bool skipNormalize=false)
Combine multiple setup routines and provide a basic NNP setup.
void setupNormalization (bool standalone=true)
Set up normalization.
virtual void setupElementMap ()
Set up the element map.
virtual void setupElements ()
Set up all Element instances.
void setupCutoff ()
Set up cutoff function for all symmetry functions.
virtual void setupSymmetryFunctions ()
Set up all symmetry functions.
void setupSymmetryFunctionScalingNone ()
Set up "empy" symmetry function scaling.
virtual void setupSymmetryFunctionScaling (std::string const &fileName="scaling.data")
Set up symmetry function scaling from file.
virtual void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
virtual void setupSymmetryFunctionCache (bool verbose=false)
Set up symmetry function cache.
void setupSymmetryFunctionMemory (bool verbose=false)
Extract required memory dimensions for symmetry function derivatives.
void setupSymmetryFunctionStatistics (bool collectStatistics, bool collectExtrapolationWarnings, bool writeExtrapolationWarnings, bool stopOnExtrapolationWarnings)
Set up symmetry function statistics collection.
virtual void setupNeuralNetwork ()
Set up neural networks for all elements.
virtual void setupNeuralNetworkWeights (std::string const &fileNameFormatShort="weights.%03zu.data", std::string const &fileNameFormatCharge="weightse.%03zu.data")
Set up neural network weights from files.
void calculateSymmetryFunctions (Structure &structure, bool const derivatives)
Calculate all symmetry functions for all atoms in given structure.
void calculateSymmetryFunctionGroups (Structure &structure, bool const derivatives)
Calculate all symmetry function groups for all atoms in given structure.
void calculateAtomicNeuralNetworks (Structure &structure, bool const derivatives)
Calculate a single atomic neural network for a given atom and nn type.
void calculateEnergy (Structure &structure) const
Calculate potential energy for a given structure.
void calculateCharge (Structure &structure) const
Calculate total charge for a given structure.
void calculateForces (Structure &structure) const
Calculate forces for all atoms in given structure.
void addEnergyOffset (Structure &structure, bool ref=true)
Add atomic energy offsets to reference energy.
void removeEnergyOffset (Structure &structure, bool ref=true)
Remove atomic energy offsets from reference energy.
double getEnergyOffset (Structure const &structure) const
Get atomic energy offset for given structure.
double getEnergyWithOffset (Structure const &structure, bool ref=true) const
Add atomic energy offsets and return energy.
double normalized (std::string const &property, double value) const
Apply normalization to given property.
double normalizedEnergy (Structure const &structure, bool ref=true) const
Apply normalization to given energy of structure.
double physical (std::string const &property, double value) const
Undo normalization for a given property.
double physicalEnergy (Structure const &structure, bool ref=true) const
Undo normalization for a given energy of structure.
void convertToNormalizedUnits (Structure &structure) const
Convert one structure to normalized units.
void convertToPhysicalUnits (Structure &structure) const
Convert one structure to physical units.
std::size_t getNumExtrapolationWarnings () const
Count total number of extrapolation warnings encountered for all elements and symmetry functions.
void resetExtrapolationWarnings ()
Erase all extrapolation warnings and reset counters.
NNPType getNnpType () const
Getter for Mode::nnpType.
double getMeanEnergy () const
Getter for Mode::meanEnergy.
double getConvEnergy () const
Getter for Mode::convEnergy.
double getConvLength () const
Getter for Mode::convLength.
double getMaxCutoffRadius () const
Getter for Mode::maxCutoffRadius.
std::size_t getNumElements () const
Getter for Mode::numElements.
std::vector< std::size_t > getNumSymmetryFunctions () const
Get number of symmetry functions per element.
bool useNormalization () const
Check if normalization is enabled.
bool settingsKeywordExists (std::string const &keyword) const
Check if keyword was found in settings file.
std::string settingsGetValue (std::string const &keyword) const
Get value for given keyword in Settings instance.
std::vector< std::size_t > pruneSymmetryFunctionsRange (double threshold)
Prune symmetry functions according to their range and write settings file.
std::vector< std::size_t > pruneSymmetryFunctionsSensitivity (double threshold, std::vector< std::vector< double > > sensitivity)
Prune symmetry functions with sensitivity analysis data.
void writePrunedSettingsFile (std::vector< std::size_t > prune, std::string fileName="output.nn") const
Copy settings file but comment out lines provided.
void writeSettingsFile (std::ofstream *const &file) const
Write complete settings file.
Additional Inherited Members
Public Types inherited from nnp::Mode
enum class NNPType { SHORT_ONLY , SHORT_CHARGE_NN }
Public Attributes inherited from nnp::Mode
ElementMap elementMap
Global element map, populated by setupElementMap().
Log log
Global log file.
Protected Member Functions inherited from nnp::Mode
void readNeuralNetworkWeights (std::string const &type, std::string const &fileName)
Read in weights for a specific type of neural network.
Protected Attributes inherited from nnp::Mode
NNPType nnpType
bool normalize
bool checkExtrapolationWarnings
bool useChargeNN
std::size_t numElements
std::vector< std::size_t > minNeighbors
std::vector< double > minCutoffRadius
double maxCutoffRadius
double cutoffAlpha
double meanEnergy
double convEnergy
double convLength
Settings settings
SymFnc::ScalingType scalingType
CutoffFunction::CutoffType cutoffType
std::vector< Element > elements
Detailed Description
Definition at line 26 of file SetupAnalysis.h.
Member Function Documentation
writeSymmetryFunctionShape()
void SetupAnalysis::writeSymmetryFunctionShape (std::size_t numPoints, std::string const fileNameFormat = "sf.%03zu.%04zu.out")
Write radial and angular part of symmetry functions to file.
Parameters
[in] numPoints Number of symmetry function points to plot.
[in] fileNameFormat File name with place holder for element and symmetry function number.
Definition at line 24 of file SetupAnalysis.cpp.
{
    log << "\n";
    log << "*** ANALYSIS: SYMMETRY FUNCTION SHAPE ***"
           "**************************************\n";
    log << "\n";
    log << strpr("Symmetry function file name format: %s\n",
                 fileNameFormat.c_str());
    log << strpr("Number of points                  : %zu\n", numPoints);
    double dr = getMaxCutoffRadius() / numPoints;
    log << strpr("Distance step                     : %f\n", dr);
    double da = M_PI / numPoints;
    log << strpr("Angle step (radians)              : %f\n", da);
    for (size_t i = 0; i < numElements; ++i)
    {
        Element const& e = elements.at(i);
        for (size_t j = 0; j < e.numSymmetryFunctions(); ++j)
        {
            SymFnc const& s = e.getSymmetryFunction(j);
            ofstream file;
            file.open(strpr(fileNameFormat.c_str(),
                            e.getAtomicNumber(),
                            j + 1).c_str());
            vector<string> info = e.infoSymmetryFunction(s.getIndex());
            for (vector<string>::const_iterator it = info.begin();
                 it != info.end(); ++it)
            {
                file << strpr("#SFINFO %s\n", it->c_str());
            }
            // File header.
            vector<string> title;
            vector<string> colName;
            vector<string> colInfo;
            vector<size_t> colSize;
            title.push_back("Symmetry function shape.");
            colSize.push_back(16);
            colName.push_back("distance");
            colInfo.push_back("Distance from center.");
            colSize.push_back(16);
            colName.push_back("sf_radial");
            colInfo.push_back("Radial part of symmetry function at given "
                              "distance.");
            colSize.push_back(16);
            colName.push_back("angle");
            colInfo.push_back("Angle in degrees.");
            colSize.push_back(16);
            colName.push_back("sf_angular");
            colInfo.push_back("Angular part of symmetry function at given "
                              "angle.");
            appendLinesToFile(file,
                              createFileHeader(title,
                                               colSize,
                                               colName,
                                               colInfo));
            for (size_t k = 0; k < numPoints + 1; ++k)
            {
                file << strpr("%16.8E %16.8E %16.8E %16.8E\n",
                              k * dr,
                              s.calculateRadialPart(k * dr),
                              k * da,
                              s.calculateAngularPart(k * da));
            }
            file.close();
        }
    }
    log << "*****************************************"
           "**************************************\n";
    return;
}
References nnp::appendLinesToFile(), nnp::SymFnc::calculateAngularPart(), nnp::SymFnc::calculateRadialPart(), nnp::createFileHeader(), nnp::Mode::elements, nnp::Element::getAtomicNumber(), nnp::SymFnc::getIndex(), nnp::Mode::getMaxCutoffRadius(), nnp::Element::getSymmetryFunction(), nnp::Element::infoSymmetryFunction(), nnp::Mode::log, nnp::Mode::numElements, nnp::Element::numSymmetryFunctions(), and nnp::strpr().
Referenced by main().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SetupAnalysis.h
/home/runner/work/n2p2/n2p2/src/libnnp/SetupAnalysis.cpp