n2p2 - A neural network potential package: nnp::Element Class Reference
nnp::Element Class Reference
Contains element-specific data.
#include <Element.h>
Classes
struct SFCacheList
List of symmetry functions corresponding to one cache identifier.
Public Member Functions
Element ()
Default constructor.
Element (std::size_t const index, ElementMap const &elementMap)
Constructor using index.
virtual ~Element ()
Destructor.
void clearSymmetryFunctions ()
Clear all symmetry functions and groups.
void setAtomicEnergyOffset (double atomicEnergyOffset)
Set atomicEnergyOffset.
std::size_t getIndex () const
Get index.
std::size_t getAtomicNumber () const
Get atomicNumber.
double getAtomicEnergyOffset () const
Get atomicEnergyOffset.
std::string getSymbol () const
Get symbol.
void addSymmetryFunction (std::string const &parameters, std::size_t const &lineNumber)
Add one symmetry function.
void changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
void sortSymmetryFunctions ()
Sort all symmetry function.
std::vector< std::string > infoSymmetryFunctionParameters () const
Print symmetry function parameter value information.
std::vector< std::string > infoSymmetryFunction (std::size_t index) const
Print symmetry function parameter names and values.
std::vector< std::string > infoSymmetryFunctionScaling () const
Print symmetry function scaling information.
void setupSymmetryFunctionGroups ()
Set up symmetry function groups.
void setupSymmetryFunctionMemory ()
Extract relevant symmetry function combinations for derivative memory.
std::vector< std::string > infoSymmetryFunctionGroups () const
Print symmetry function group info.
void setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha)
Set cutoff function for all symmetry functions.
void setScalingNone () const
Set no scaling of symmetry function.
void setScaling (SymFnc::ScalingType scalingType, std::vector< std::string > const &statisticsLine, double minS, double maxS) const
Set scaling of all symmetry functions.
std::size_t numSymmetryFunctions () const
Get number of symmetry functions.
std::size_t getMinNeighbors () const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
double getMinCutoffRadius () const
Get minimum cutoff radius of all symmetry functions.
double getMaxCutoffRadius () const
Get maximum cutoff radius of all symmetry functions.
std::vector< std::size_t > const & getSymmetryFunctionNumTable () const
Get number of relevant symmetry functions per element.
std::vector< std::vector< std::size_t > > const & getSymmetryFunctionTable () const
Get symmetry function element relevance table.
void calculateSymmetryFunctions (Atom &atom, bool const derivatives) const
Calculate symmetry functions.
void calculateSymmetryFunctionGroups (Atom &atom, bool const derivatives) const
Calculate symmetry functions via groups.
std::size_t updateSymmetryFunctionStatistics (Atom const &atom)
Update symmetry function statistics.
SymFnc const & getSymmetryFunction (std::size_t index) const
Get symmetry function instance.
void setCacheIndices (std::vector< std::vector< SFCacheList >> cacheLists)
Set cache indices for all symmetry functions of this element.
std::vector< std::size_t > getCacheSizes () const
Get cache sizes for each neighbor atom element.
Public Attributes
std::map< std::string, NeuralNetwork > neuralNetworks
Neural networks for this element.
SymFncStatistics statistics
Symmetry function statistics.
Protected Attributes
ElementMap elementMap
Copy of element map.
std::size_t index
Global index of this element.
std::size_t atomicNumber
Atomic number of this element.
double atomicEnergyOffset
Offset energy for every atom of this element.
std::string symbol
Element symbol.
std::vector< std::size_t > symmetryFunctionNumTable
Number of relevant symmetry functions for each neighbor element.
std::vector< std::vector< std::size_t > > symmetryFunctionTable
List of symmetry function indices relevant for each neighbor element.
std::vector< std::vector< SFCacheList > > cacheLists
Symmetry function cache lists.
std::vector< SymFnc * > symmetryFunctions
Vector of pointers to symmetry functions.
std::vector< SymGrp * > symmetryFunctionGroups
Vector of pointers to symmetry function groups.
Detailed Description
Contains element-specific data.
Definition at line 38 of file Element.h.
Constructor & Destructor Documentation
Element() [1/2]
nnp::Element::Element () inline
Default constructor.
Definition at line 57 of file Element.h.
 {}
Element() [2/2]
nnp::Element::Element (std::size_t const index, ElementMap const & elementMap)
Constructor using index.
~Element()
Element::~Element () virtual
Destructor.
Necessary because of symmetryFunctions vector of pointers.
Definition at line 65 of file Element.cpp.
 {
     clearSymmetryFunctions();
 }
References clearSymmetryFunctions().
Member Function Documentation
clearSymmetryFunctions()
void Element::clearSymmetryFunctions ()
Clear all symmetry functions and groups.
Definition at line 70 of file Element.cpp.
 {
     for (auto& s : symmetryFunctions) delete s;
     symmetryFunctions.clear();
     for (auto& s : symmetryFunctionGroups) delete s;
     symmetryFunctionGroups.clear();
     return;
 }
References symmetryFunctionGroups, and symmetryFunctions.
Referenced by ~Element().
setAtomicEnergyOffset()
void nnp::Element::setAtomicEnergyOffset (double atomicEnergyOffset) inline
Set atomicEnergyOffset.
Definition at line 263 of file Element.h.
 {
     this->atomicEnergyOffset = atomicEnergyOffset;
     return;
 }
References atomicEnergyOffset.
getIndex()
size_t nnp::Element::getIndex () const inline
Get index.
Definition at line 270 of file Element.h.
 {
     return index;
 }
References index.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
getAtomicNumber()
size_t nnp::Element::getAtomicNumber () const inline
Get atomicNumber.
Definition at line 275 of file Element.h.
 {
     return atomicNumber;
 }
References atomicNumber.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape().
getAtomicEnergyOffset()
double nnp::Element::getAtomicEnergyOffset () const inline
Get atomicEnergyOffset.
Definition at line 280 of file Element.h.
 {
     return atomicEnergyOffset;
 }
References atomicEnergyOffset.
Referenced by nnp::InterfaceLammps::getAtomicEnergy().
getSymbol()
std::string nnp::Element::getSymbol () const inline
Get symbol.
Definition at line 285 of file Element.h.
 {
     return symbol;
 }
References symbol.
Referenced by nnp::Mode::setupNeuralNetwork(), and nnp::Mode::setupSymmetryFunctionCache().
addSymmetryFunction()
void Element::addSymmetryFunction (std::string const & parameters, std::size_t const & lineNumber)
Add one symmetry function.
Parameters
[in] parameters String containing settings for symmetry function.
[in] lineNumber Line number of symmetry function in settings file.
Definition at line 80 of file Element.cpp.
 {
     vector<string> args = split(reduce(parameters));
     size_t         type = (size_t)atoi(args.at(1).c_str());
     if (type == 2)
     {
         symmetryFunctions.push_back(new SymFncExpRad(elementMap));
     }
     else if (type == 3)
     {
         symmetryFunctions.push_back(new SymFncExpAngn(elementMap));
     }
     else if (type == 9)
     {
         symmetryFunctions.push_back(new SymFncExpAngw(elementMap));
     }
     else if (type == 12)
     {
         symmetryFunctions.push_back(new SymFncExpRadWeighted(elementMap));
     }
     else if (type == 13)
     {
         symmetryFunctions.push_back(new SymFncExpAngnWeighted(elementMap));
     }
     else if (type == 20)
     {
         symmetryFunctions.push_back(new SymFncCompRad(elementMap));
     }
     else if (type == 21)
     {
         symmetryFunctions.push_back(new SymFncCompAngn(elementMap));
     }
     else if (type == 22)
     {
         symmetryFunctions.push_back(new SymFncCompAngw(elementMap));
     }
     else if (type == 23)
     {
         symmetryFunctions.push_back(new SymFncCompRadWeighted(elementMap));
     }
     else if (type == 24)
     {
         symmetryFunctions.push_back(new SymFncCompAngnWeighted(elementMap));
     }
     else if (type == 25)
     {
         symmetryFunctions.push_back(new SymFncCompAngwWeighted(elementMap));
     }
     else
     {
         throw runtime_error("ERROR: Unknown symmetry function type.\n");
     }
     symmetryFunctions.back()->setParameters(parameters);
     symmetryFunctions.back()->setLineNumber(lineNumber);
     return;
 }
References elementMap, nnp::reduce(), nnp::split(), and symmetryFunctions.
changeLengthUnitSymmetryFunctions()
void Element::changeLengthUnitSymmetryFunctions (double convLength)
Change length unit for all symmetry functions.
Parameters
[in] convLength Length unit conversion factor.
Definition at line 141 of file Element.cpp.
 {
     for (vector<SymFnc*>::iterator it = symmetryFunctions.begin();
          it != symmetryFunctions.end(); ++it)
     {
         (*it)->changeLengthUnit(convLength);
     }
     return;
 }
References symmetryFunctions.
sortSymmetryFunctions()
void Element::sortSymmetryFunctions ()
Sort all symmetry function.
Definition at line 152 of file Element.cpp.
 {
     sort(symmetryFunctions.begin(),
          symmetryFunctions.end(),
          comparePointerTargets<SymFnc>);
     for (size_t i = 0; i < symmetryFunctions.size(); ++i)
     {
         symmetryFunctions.at(i)->setIndex(i);
     }
     return;
 }
References symmetryFunctions.
infoSymmetryFunctionParameters()
vector< string > Element::infoSymmetryFunctionParameters () const
Print symmetry function parameter value information.
Definition at line 166 of file Element.cpp.
 {
     vector<string> v;
     for (vector<SymFnc*>::const_iterator
          sf = symmetryFunctions.begin(); sf != symmetryFunctions.end(); ++sf)
     {
         v.push_back((*sf)->parameterLine());
     }
     return v;
 }
References symmetryFunctions.
infoSymmetryFunction()
std::vector< std::string > nnp::Element::infoSymmetryFunction (std::size_t index) const inline
Print symmetry function parameter names and values.
Definition at line 303 of file Element.h.
 {
     return symmetryFunctions.at(index)->parameterInfo();
 }
References index, and symmetryFunctions.
Referenced by nnp::SetupAnalysis::writeSymmetryFunctionShape().
infoSymmetryFunctionScaling()
vector< string > Element::infoSymmetryFunctionScaling () const
Print symmetry function scaling information.
Definition at line 179 of file Element.cpp.
 {
     vector<string> v;
     for (vector<SymFnc*>::const_iterator
          sf = symmetryFunctions.begin(); sf != symmetryFunctions.end(); ++sf)
     {
         v.push_back((*sf)->scalingLine());
     }
     return v;
 }
References symmetryFunctions.
setupSymmetryFunctionGroups()
void Element::setupSymmetryFunctionGroups ()
Set up symmetry function groups.
Definition at line 192 of file Element.cpp.
 {
     for (vector<SymFnc*>::const_iterator
          sf = symmetryFunctions.begin(); sf != symmetryFunctions.end(); ++sf)
     {
         bool createNewGroup = true;
         for (vector<SymGrp*>::const_iterator
              sfg = symmetryFunctionGroups.begin();
              sfg != symmetryFunctionGroups.end(); ++sfg)
         {
             if ((*sfg)->addMember((*sf)))
             {
                 createNewGroup = false;
                 break;
             }
         }
         if (createNewGroup)
         {
             if ((*sf)->getType() == 2)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpExpRad(elementMap));
             }
             else if ((*sf)->getType() == 3)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpExpAngn(elementMap));
             }
             else if ((*sf)->getType() == 9)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpExpAngw(elementMap));
             }
             else if ((*sf)->getType() == 12)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpExpRadWeighted(elementMap));
             }
             else if ((*sf)->getType() == 13)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpExpAngnWeighted(elementMap));
             }
             else if ((*sf)->getType() == 20)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpCompRad(elementMap));
             }
             else if ((*sf)->getType() == 21)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpCompAngn(elementMap));
             }
             else if ((*sf)->getType() == 22)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpCompAngw(elementMap));
             }
             else if ((*sf)->getType() == 23)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpCompRadWeighted(elementMap));
             }
             else if ((*sf)->getType() == 24)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpCompAngnWeighted(elementMap));
             }
             else if ((*sf)->getType() == 25)
             {
                 symmetryFunctionGroups.push_back((SymGrp*)
                     new SymGrpCompAngwWeighted(elementMap));
             }
             else
             {
                 throw runtime_error("ERROR: Unknown symmetry function group"
                                     " type.\n");
             }
             symmetryFunctionGroups.back()->addMember(*sf);
         }
     }
     sort(symmetryFunctionGroups.begin(),
          symmetryFunctionGroups.end(),
          comparePointerTargets<SymGrp>);
     for (size_t i = 0; i < symmetryFunctionGroups.size(); ++i)
     {
         symmetryFunctionGroups.at(i)->sortMembers();
         symmetryFunctionGroups.at(i)->setIndex(i);
     }
     return;
 }
References elementMap, symmetryFunctionGroups, and symmetryFunctions.
setupSymmetryFunctionMemory()
void Element::setupSymmetryFunctionMemory ()
Extract relevant symmetry function combinations for derivative memory.
Definition at line 287 of file Element.cpp.
 {
     symmetryFunctionTable.clear();
     symmetryFunctionTable.resize(elementMap.size());
     for (auto const& s : symmetryFunctions)
     {
         for (size_t i = 0; i < elementMap.size(); ++i)
         {
             if (s->checkRelevantElement(i))
             {
                 s->setIndexPerElement(i, symmetryFunctionTable.at(i).size());
                 symmetryFunctionTable.at(i).push_back(s->getIndex());
             }
         }
     }
     symmetryFunctionNumTable.clear();
     for (size_t i = 0; i < elementMap.size(); ++i)
     {
         symmetryFunctionNumTable.push_back(symmetryFunctionTable.at(i).size());
     }
     return;
 }
References elementMap, nnp::ElementMap::size(), symmetryFunctionNumTable, symmetryFunctions, and symmetryFunctionTable.
infoSymmetryFunctionGroups()
vector< string > Element::infoSymmetryFunctionGroups () const
Print symmetry function group info.
Definition at line 311 of file Element.cpp.
 {
     vector<string> v;
     for (vector<SymGrp*>::const_iterator
          it = symmetryFunctionGroups.begin();
          it != symmetryFunctionGroups.end(); ++it)
     {
         vector<string> lines = (*it)->parameterLines();
         v.insert(v.end(), lines.begin(), lines.end());
     }
     return v;
 }
References symmetryFunctionGroups.
setCutoffFunction()
void Element::setCutoffFunction (CutoffFunction::CutoffType const cutoffType, double const cutoffAlpha)
Set cutoff function for all symmetry functions.
Parameters
[in] cutoffType Type of cutoff function.
[in] cutoffAlpha Cutoff parameter for all functions.
Definition at line 326 of file Element.cpp.
 {
     for (vector<SymFnc*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         SymFncBaseCutoff* sfcb = dynamic_cast<SymFncBaseCutoff*>(*it);
         if (sfcb != nullptr)
         {
             sfcb->setCutoffFunction(cutoffType, cutoffAlpha);
         }
     }
     return;
 }
References nnp::SymFncBaseCutoff::setCutoffFunction(), and symmetryFunctions.
setScalingNone()
void Element::setScalingNone () const
Set no scaling of symmetry function.
Still scaling factors need to be initialized.
Definition at line 342 of file Element.cpp.
 {
     for (size_t i = 0; i < symmetryFunctions.size(); ++i)
     {
         string scalingLine = strpr("%d %d 0.0 0.0 0.0 0.0",
                                    symmetryFunctions.at(i)->getEc(),
                                    i + 1);
         symmetryFunctions.at(i)->setScalingType(SymFnc::ST_NONE,
                                                 scalingLine,
                                                 0.0,
                                                 0.0);
     }
     for (size_t i = 0; i < symmetryFunctionGroups.size(); ++i)
     {
         symmetryFunctionGroups.at(i)->setScalingFactors();
     }
     return;
 }
References nnp::SymFnc::ST_NONE, nnp::strpr(), symmetryFunctionGroups, and symmetryFunctions.
setScaling()
void Element::setScaling (SymFnc::ScalingType scalingType, std::vector< std::string > const & statisticsLine, double minS, double maxS) const
Set scaling of all symmetry functions.
Parameters
[in] scalingType Type of scaling, see SymFnc::ScalingType.
[in] statisticsLine Vector of strings containing statistics for all symmetry functions.
[in] minS Minimum for scaling range.
[in] maxS Maximum for scaling range.
Definition at line 362 of file Element.cpp.
 {
     for (size_t i = 0; i < symmetryFunctions.size(); ++i)
     {
         symmetryFunctions.at(i)->setScalingType(scalingType,
                                                 statisticsLine.at(i),
                                                 Smin,
                                                 Smax);
     }
     for (size_t i = 0; i < symmetryFunctionGroups.size(); ++i)
     {
         symmetryFunctionGroups.at(i)->setScalingFactors();
     }
     return;
 }
References symmetryFunctionGroups, and symmetryFunctions.
numSymmetryFunctions()
size_t nnp::Element::numSymmetryFunctions () const inline
Get number of symmetry functions.
Returns
Number of symmetry functions.
Definition at line 308 of file Element.h.
 {
     return symmetryFunctions.size();
 }
References symmetryFunctions.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), nnp::Mode::calculateSymmetryFunctions(), nnp::Mode::setupNeuralNetwork(), nnp::Mode::setupSymmetryFunctionCache(), and nnp::SetupAnalysis::writeSymmetryFunctionShape().
getMinNeighbors()
size_t Element::getMinNeighbors () const
Get maximum of required minimum number of neighbors for all symmetry functions for this element.
Returns
Minimum number of neighbors required.
Definition at line 382 of file Element.cpp.
 {
     size_t minNeighbors = 0;
     for (vector<SymFnc*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         minNeighbors = max((*it)->getMinNeighbors(), minNeighbors);
     }
     return minNeighbors;
 }
References symmetryFunctions.
getMinCutoffRadius()
double Element::getMinCutoffRadius () const
Get minimum cutoff radius of all symmetry functions.
Returns
Minimum cutoff radius.
Definition at line 395 of file Element.cpp.
 {
     double minCutoffRadius = numeric_limits<double>::max();
     // MPB: Hack to work with negative radii
     //      Exploit the fact that all allowed symmetry functions are either
     //      defined for a domain > 0 or have to be symmetric around 0.
     for (vector<SymFnc*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         minCutoffRadius = min((*it)->getRc(), minCutoffRadius);
     }
     return minCutoffRadius;
 }
References symmetryFunctions.
getMaxCutoffRadius()
double Element::getMaxCutoffRadius () const
Get maximum cutoff radius of all symmetry functions.
Returns
Maximum cutoff radius.
Definition at line 412 of file Element.cpp.
 {
     double maxCutoffRadius = 0.0;
     for (vector<SymFnc*>::const_iterator
          it = symmetryFunctions.begin(); it != symmetryFunctions.end(); ++it)
     {
         maxCutoffRadius = max((*it)->getRc(), maxCutoffRadius);
     }
     return maxCutoffRadius;
 }
References symmetryFunctions.
getSymmetryFunctionNumTable()
std::vector< std::size_t > const & nnp::Element::getSymmetryFunctionNumTable () const inline
Get number of relevant symmetry functions per element.
Returns
symmetryFunctionNumTable
Definition at line 291 of file Element.h.
 {
     return symmetryFunctionNumTable;
 }
References symmetryFunctionNumTable.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
getSymmetryFunctionTable()
std::vector< std::vector< std::size_t > > const & nnp::Element::getSymmetryFunctionTable () const inline
Get symmetry function element relevance table.
Returns
symmetryFunctionTable
Definition at line 297 of file Element.h.
 {
     return symmetryFunctionTable;
 }
References symmetryFunctionTable.
calculateSymmetryFunctions()
void Element::calculateSymmetryFunctions (Atom & atom, bool const derivatives) const
Calculate symmetry functions.
Parameters
[in] atom Atom whose symmetry functions are calculated.
[in] derivatives If symmetry function derivatives will be calculated.
Definition at line 425 of file Element.cpp.
 {
     for (vector<SymFnc*>::const_iterator
          it = symmetryFunctions.begin();
          it != symmetryFunctions.end(); ++it)
     {
         //cerr << (*it)->getIndex() << " "
         //     << elementMap[(*it)->getEc()] << " "
         //     << (*it)->getUnique() << "\n";
         //auto cid = (*it)->getCacheIdentifiers();
         //for (auto icid : cid) cerr << icid << "\n";
         //auto ci = (*it)->getCacheIndices();
         //for (auto eci : ci)
         //{
         //    for (auto ici : eci) cerr << ici << " ";
         //    cerr << "\n";
         //}
         (*it)->calculate(atom, derivatives);
     }
     return;
 }
References symmetryFunctions.
Referenced by nnp::Mode::calculateSymmetryFunctions().
calculateSymmetryFunctionGroups()
void Element::calculateSymmetryFunctionGroups (Atom & atom, bool const derivatives) const
Calculate symmetry functions via groups.
Parameters
[in] atom Atom whose symmetry functions are calculated.
[in] derivatives If symmetry function derivatives will be calculated.
Definition at line 449 of file Element.cpp.
 {
     for (vector<SymGrp*>::const_iterator
          it = symmetryFunctionGroups.begin();
          it != symmetryFunctionGroups.end(); ++it)
     {
         (*it)->calculate(atom, derivatives);
     }
     return;
 }
References symmetryFunctionGroups.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups().
updateSymmetryFunctionStatistics()
size_t Element::updateSymmetryFunctionStatistics (Atom const & atom)
Update symmetry function statistics.
Parameters
[in] atom Atom with symmetry function values.
Returns
Number of extrapolation warnings encountered.
This function checks also for extrapolation warnings.
Definition at line 462 of file Element.cpp.
 {
     size_t countExtrapolationWarnings = 0;
     double epsilon = 1000.0 * numeric_limits<double>::epsilon();
     if (atom.element != index)
     {
         throw runtime_error("ERROR: Atom has a different element index.\n");
     }
     if (atom.numSymmetryFunctions != symmetryFunctions.size())
     {
         throw runtime_error("ERROR: Number of symmetry functions"
                             " does not match.\n");
     }
     for (size_t i = 0; i < atom.G.size(); ++i)
     {
         double const Gmin = symmetryFunctions.at(i)->getGmin();
         double const Gmax = symmetryFunctions.at(i)->getGmax();
         double const value = symmetryFunctions.at(i)->unscale(atom.G.at(i));
         size_t const sfindex = symmetryFunctions.at(i)->getIndex();
         size_t const type = symmetryFunctions.at(i)->getType();
         if (statistics.collectStatistics)
         {
             statistics.addValue(sfindex, atom.G.at(i));
         }
         // Avoid "fake" EWs at the boundaries.
         if (value + epsilon < Gmin || value - epsilon > Gmax)
         {
             countExtrapolationWarnings++;
             if (statistics.collectExtrapolationWarnings)
             {
                 statistics.addExtrapolationWarning(sfindex,
                                                    type,
                                                    value,
                                                    Gmin,
                                                    Gmax,
                                                    symbol,
                                                    atom.indexStructure,
                                                    atom.tag);
             }
             if (statistics.writeExtrapolationWarnings)
             {
                 cerr << strpr("### NNP EXTRAPOLATION WARNING ### "
                               "STRUCTURE: %6zu ATOM: %9" PRId64 " ELEMENT: "
                               "%2s SYMFUNC: %4zu TYPE: %2zu VALUE: %10.3E "
                               "MIN: %10.3E MAX: %10.3E\n",
                               atom.indexStructure,
                               atom.tag,
                               symbol.c_str(),
                               sfindex + 1,
                               type,
                               value,
                               Gmin,
                               Gmax);
             }
             if (statistics.stopOnExtrapolationWarnings)
             {
                 throw out_of_range(
                         strpr("### NNP EXTRAPOLATION WARNING ### "
                               "STRUCTURE: %6zu ATOM: %9" PRId64 " ELEMENT: "
                               "%2s SYMFUNC: %4zu TYPE: %2zu VALUE: %10.3E "
                               "MIN: %10.3E MAX: %10.3E\n"
                               "ERROR: Symmetry function value out of range.\n",
                               atom.indexStructure,
                               atom.tag,
                               symbol.c_str(),
                               sfindex + 1,
                               type,
                               value,
                               Gmin,
                               Gmax));
             }
         }
     }
     return countExtrapolationWarnings;
 }
References nnp::SymFncStatistics::addExtrapolationWarning(), nnp::SymFncStatistics::addValue(), nnp::SymFncStatistics::collectExtrapolationWarnings, nnp::SymFncStatistics::collectStatistics, nnp::Atom::element, nnp::Atom::G, index, nnp::Atom::indexStructure, nnp::Atom::numSymmetryFunctions, statistics, nnp::SymFncStatistics::stopOnExtrapolationWarnings, nnp::strpr(), symbol, symmetryFunctions, nnp::Atom::tag, and nnp::SymFncStatistics::writeExtrapolationWarnings.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
getSymmetryFunction()
SymFnc const & nnp::Element::getSymmetryFunction (std::size_t index) const inline
Get symmetry function instance.
Parameters
[in] index Symmetry function index.
Returns
Symmetry function object.
Definition at line 313 of file Element.h.
 {
     return *(symmetryFunctions.at(index));
 }
References index, and symmetryFunctions.
Referenced by nnp::Mode::setupSymmetryFunctionCache(), and nnp::SetupAnalysis::writeSymmetryFunctionShape().
setCacheIndices()
void Element::setCacheIndices (std::vector< std::vector< SFCacheList >> cacheLists)
Set cache indices for all symmetry functions of this element.
Parameters
[in] cacheLists List of cache identifier strings and corresponding SF indices for each neighbor element.
Definition at line 544 of file Element.cpp.
 {
     this->cacheLists = cacheLists;
     for (size_t i = 0; i < cacheLists.size(); ++i)
     {
         for (size_t j = 0; j < cacheLists.at(i).size(); ++j)
         {
             SFCacheList const& c = cacheLists.at(i).at(j);
             for (size_t k = 0; k < c.indices.size(); ++k)
             {
                 SymFnc*& sf = symmetryFunctions.at(c.indices.at(k));
                 sf->addCacheIndex(c.element, j, c.identifier);
             }
         }
     }
     return;
 }
References nnp::SymFnc::addCacheIndex(), cacheLists, nnp::Element::SFCacheList::element, nnp::Element::SFCacheList::identifier, nnp::Element::SFCacheList::indices, and symmetryFunctions.
Referenced by nnp::Mode::setupSymmetryFunctionCache().
getCacheSizes()
vector< size_t > Element::getCacheSizes () const
Get cache sizes for each neighbor atom element.
Returns
Vector with cache sizes.
Definition at line 563 of file Element.cpp.
 {
     vector<size_t> cacheSizes;
     for (auto const& c : cacheLists)
     {
         cacheSizes.push_back(c.size());
     }
     return cacheSizes;
 }
References cacheLists.
Referenced by nnp::Mode::calculateSymmetryFunctionGroups(), and nnp::Mode::calculateSymmetryFunctions().
Member Data Documentation
neuralNetworks
std::map<std::string, NeuralNetwork> nnp::Element::neuralNetworks
Neural networks for this element.
Definition at line 230 of file Element.h.
Referenced by nnp::Mode::setupNeuralNetwork().
statistics
SymFncStatistics nnp::Element::statistics
Symmetry function statistics.
Definition at line 232 of file Element.h.
Referenced by updateSymmetryFunctionStatistics().
elementMap
ElementMap nnp::Element::elementMap protected
Copy of element map.
Definition at line 236 of file Element.h.
Referenced by addSymmetryFunction(), setupSymmetryFunctionGroups(), and setupSymmetryFunctionMemory().
index
std::size_t nnp::Element::index protected
Global index of this element.
Definition at line 238 of file Element.h.
Referenced by nnp::ElementCabana::ElementCabana(), getIndex(), getSymmetryFunction(), infoSymmetryFunction(), nnp::ElementCabana::infoSymmetryFunctionParameters(), nnp::ElementCabana::infoSymmetryFunctionScaling(), nnp::ElementCabana::setScaling(), and updateSymmetryFunctionStatistics().
atomicNumber
std::size_t nnp::Element::atomicNumber protected
Atomic number of this element.
Definition at line 240 of file Element.h.
Referenced by getAtomicNumber().
atomicEnergyOffset
double nnp::Element::atomicEnergyOffset protected
Offset energy for every atom of this element.
Definition at line 242 of file Element.h.
Referenced by nnp::ElementCabana::ElementCabana(), getAtomicEnergyOffset(), and setAtomicEnergyOffset().
symbol
std::string nnp::Element::symbol protected
Element symbol.
Definition at line 244 of file Element.h.
Referenced by getSymbol(), and updateSymmetryFunctionStatistics().
symmetryFunctionNumTable
std::vector<std::size_t> nnp::Element::symmetryFunctionNumTable protected
Number of relevant symmetry functions for each neighbor element.
Definition at line 246 of file Element.h.
Referenced by getSymmetryFunctionNumTable(), and setupSymmetryFunctionMemory().
symmetryFunctionTable
std::vector<std::vector<std::size_t> > nnp::Element::symmetryFunctionTable protected
List of symmetry function indices relevant for each neighbor element.
Definition at line 248 of file Element.h.
Referenced by getSymmetryFunctionTable(), and setupSymmetryFunctionMemory().
cacheLists
std::vector<std::vector<SFCacheList> > nnp::Element::cacheLists protected
Symmetry function cache lists.
Definition at line 251 of file Element.h.
Referenced by getCacheSizes(), and setCacheIndices().
symmetryFunctions
std::vector<SymFnc*> nnp::Element::symmetryFunctions protected
Vector of pointers to symmetry functions.
Definition at line 254 of file Element.h.
Referenced by addSymmetryFunction(), calculateSymmetryFunctions(), changeLengthUnitSymmetryFunctions(), clearSymmetryFunctions(), getMaxCutoffRadius(), getMinCutoffRadius(), getMinNeighbors(), getSymmetryFunction(), infoSymmetryFunction(), infoSymmetryFunctionParameters(), infoSymmetryFunctionScaling(), numSymmetryFunctions(), setCacheIndices(), setCutoffFunction(), setScaling(), setScalingNone(), setupSymmetryFunctionGroups(), setupSymmetryFunctionMemory(), sortSymmetryFunctions(), and updateSymmetryFunctionStatistics().
symmetryFunctionGroups
std::vector<SymGrp*> nnp::Element::symmetryFunctionGroups protected
Vector of pointers to symmetry function groups.
Definition at line 256 of file Element.h.
Referenced by calculateSymmetryFunctionGroups(), clearSymmetryFunctions(), infoSymmetryFunctionGroups(), setScaling(), setScalingNone(), and setupSymmetryFunctionGroups().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/Element.h
/home/runner/work/n2p2/n2p2/src/libnnp/Element.cpp