n2p2 - A neural network potential package: nnp::SymFncExpAngnWeighted Class Reference
nnp::SymFncExpAngnWeighted Class Reference
Weighted angular symmetry function (type 13)
#include <SymFncExpAngnWeighted.h>
Public Member Functions
SymFncExpAngnWeighted (ElementMap const &elementMap)
Constructor, sets type = 13.
virtual bool operator== (SymFnc const &rhs) const
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const
Overload < operator.
virtual void setParameters (std::string const &parameterString)
Set symmetry function parameters.
virtual void changeLengthUnit (double convLength)
Change length unit.
virtual std::string getSettingsLine () const
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
virtual std::string parameterLine () const
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
bool getUseIntegerPow () const
Get private useIntegerPow member variable.
int getZetaInt () const
Get private zetaInt member variable.
double getEta () const
Get private eta member variable.
double getRs () const
Get private rs member variable.
double getLambda () const
Get private lambda member variable.
double getZeta () const
Get private zeta member variable.
virtual double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
Public Member Functions inherited from nnp::SymFncBaseCutoff
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setCutoffFunction (CutoffFunction::CutoffType cutoffType, double cutoffAlpha)
Set cutoff function type and parameter.
double getCutoffAlpha () const
Get private cutoffAlpha member variable.
std::string getSubtype () const
Get private subtype member variable.
CutoffFunction::CutoffType getCutoffType () const
Get private cutoffType member variable.
Public Member Functions inherited from nnp::SymFnc
virtual ~SymFnc ()
Virtual destructor.
virtual bool operator== (SymFnc const &rhs) const =0
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const =0
Overload < operator.
bool operator!= (SymFnc const &rhs) const
Overload != operator.
bool operator> (SymFnc const &rhs) const
Overload > operator.
bool operator<= (SymFnc const &rhs) const
Overload <= operator.
bool operator>= (SymFnc const &rhs) const
Overload >= operator.
virtual void setParameters (std::string const &parameterString)=0
Set parameters.
virtual void changeLengthUnit (double convLength)=0
Change length unit.
virtual std::string getSettingsLine () const =0
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate symmetry function for one atom.
virtual std::string parameterLine () const =0
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getConvLength () const
Get private convLength member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
virtual double calculateRadialPart (double distance) const =0
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const =0
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const =0
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
void addCacheIndex (std::size_t element, std::size_t cacheIndex, std::string cacheIdentifier)
Add one cache index for given neighbor element and check identifier.
std::vector< std::vector< std::size_t > > getCacheIndices () const
Getter for cacheIndices.
Private Attributes
bool useIntegerPow
Whether to use integer version of power function (faster).
int zetaInt
Integer version of \(\zeta\).
double eta
Width \(\eta\) of gaussian.
double rs
Shift \(r_s\) of gaussian.
double lambda
Cosine shift factor.
double zeta
Exponent \(\zeta\) of cosine term.
Additional Inherited Members
Public Types inherited from nnp::SymFnc
enum ScalingType {
ST_NONE , ST_SCALE , ST_CENTER , ST_SCALECENTER ,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymFnc
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymFncBaseCutoff
SymFncBaseCutoff (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFnc
SymFnc (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymFnc
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymFncBaseCutoff
double cutoffAlpha
Cutoff parameter \(\alpha\).
std::string subtype
Subtype string (specifies cutoff type).
CutoffFunction fc
Cutoff function used by this symmetry function.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function.
Protected Attributes inherited from nnp::SymFnc
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius \(r_c\).
double scalingFactor
Scaling factor.
double convLength
Data set normalization length conversion factor.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
std::vector< std::vector< std::size_t > > cacheIndices
Cache indices for each element.
Static Protected Attributes inherited from nnp::SymFnc
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Weighted angular symmetry function (type 13)
\[ G^{13}_i = 2^{1-\zeta} \sum_{\substack{j,k\neq i \\ j < k}} Z_j Z_k \, \left(1 + \lambda \cos \theta_{ijk} \right)^\zeta \mathrm{e}^{-\eta \left[ (r_{ij} - r_s)^2 + (r_{ik} - r_s)^2 + (r_{jk} - r_s)^2 \right] } f_c(r_{ij}) f_c(r_{ik}) f_c(r_{jk}) \]
Parameter string:
<element-central> 13 <eta> <rshift> <lambda> <zeta> <rcutoff>
where
<element-central> ..... element symbol of central atom
<eta> ................. \(\eta\)
<rshift> .............. \(r_s\)
<lambda> .............. \(\lambda\)
<zeta> ................ \(\zeta\)
<rcutoff> ............. \(r_c\)
Definition at line 53 of file SymFncExpAngnWeighted.h.
Constructor & Destructor Documentation
SymFncExpAngnWeighted()
SymFncExpAngnWeighted::SymFncExpAngnWeighted (ElementMap const & elementMap)
Constructor, sets type = 13.
Definition at line 30 of file SymFncExpAngnWeighted.cpp.
                                                                         :
    SymFncBaseCutoff(13, elementMap),
    useIntegerPow(false),
    zetaInt      (0    ),
    eta          (0.0  ),
    rs           (0.0  ),
    lambda       (0.0  ),
    zeta         (0.0  )
{
    minNeighbors = 2;
    parameters.insert("rs/rl");
    parameters.insert("eta");
    parameters.insert("zeta");
    parameters.insert("lambda");
}
References nnp::SymFnc::minNeighbors, and nnp::SymFnc::parameters.
Member Function Documentation
operator==()
bool SymFncExpAngnWeighted::operator== (SymFnc const & rhs) const virtual
Overload == operator.
Implements nnp::SymFnc.
Definition at line 46 of file SymFncExpAngnWeighted.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymFncExpAngnWeighted const& c =
        dynamic_cast<SymFncExpAngnWeighted const&>(rhs);
    if (cutoffType  != c.cutoffType ) return false;
    if (cutoffAlpha != c.cutoffAlpha) return false;
    if (rc          != c.rc         ) return false;
    if (eta         != c.eta        ) return false;
    if (rs          != c.rs         ) return false;
    if (zeta        != c.zeta       ) return false;
    if (lambda      != c.lambda     ) return false;
    return true;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFncBaseCutoff::cutoffType, nnp::SymFnc::ec, eta, nnp::SymFnc::getEc(), nnp::SymFnc::getType(), lambda, nnp::SymFnc::rc, rs, nnp::SymFnc::type, and zeta.
operator<()
bool SymFncExpAngnWeighted::operator< (SymFnc const & rhs) const virtual
Overload < operator.
Implements nnp::SymFnc.
Definition at line 62 of file SymFncExpAngnWeighted.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymFncExpAngnWeighted const& c =
        dynamic_cast<SymFncExpAngnWeighted const&>(rhs);
    if      (cutoffType  < c.cutoffType ) return true;
    else if (cutoffType  > c.cutoffType ) return false;
    if      (cutoffAlpha < c.cutoffAlpha) return true;
    else if (cutoffAlpha > c.cutoffAlpha) return false;
    if      (rc          < c.rc         ) return true;
    else if (rc          > c.rc         ) return false;
    if      (eta         < c.eta        ) return true;
    else if (eta         > c.eta        ) return false;
    if      (rs          < c.rs         ) return true;
    else if (rs          > c.rs         ) return false;
    if      (zeta        < c.zeta       ) return true;
    else if (zeta        > c.zeta       ) return false;
    if      (lambda      < c.lambda     ) return true;
    else if (lambda      > c.lambda     ) return false;
    return false;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFncBaseCutoff::cutoffType, nnp::SymFnc::ec, eta, nnp::SymFnc::getEc(), nnp::SymFnc::getType(), lambda, nnp::SymFnc::rc, rs, nnp::SymFnc::type, and zeta.
setParameters()
void SymFncExpAngnWeighted::setParameters (std::string const & parameterString) virtual
Set symmetry function parameters.
Parameters
[in] parameterString String containing weighted angular symmetry function parameters.
Implements nnp::SymFnc.
Definition at line 87 of file SymFncExpAngnWeighted.cpp.
{
    vector<string> splitLine = split(reduce(parameterString));
    if (type != (size_t)atoi(splitLine.at(1).c_str()))
    {
        throw runtime_error("ERROR: Incorrect symmetry function type.\n");
    }
    ec     = elementMap[splitLine.at(0)];
    eta    = atof(splitLine.at(2).c_str());
    rs     = atof(splitLine.at(3).c_str());
    lambda = atof(splitLine.at(4).c_str());
    zeta   = atof(splitLine.at(5).c_str());
    rc     = atof(splitLine.at(6).c_str());
    fc.setCutoffRadius(rc);
    fc.setCutoffParameter(cutoffAlpha);
    zetaInt = round(zeta);
    if (fabs(zeta - zetaInt) <= numeric_limits<double>::min())
    {
        useIntegerPow = true;
    }
    else
    {
        useIntegerPow = false;
    }
    return;
}
References nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFnc::ec, nnp::SymFnc::elementMap, eta, nnp::SymFncBaseCutoff::fc, lambda, nnp::SymFnc::rc, nnp::reduce(), rs, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::split(), nnp::SymFnc::type, useIntegerPow, zeta, and zetaInt.
changeLengthUnit()
void SymFncExpAngnWeighted::changeLengthUnit (double convLength) virtual
Change length unit.
Parameters
[in] convLength Multiplicative length unit conversion factor.
Implements nnp::SymFnc.
Definition at line 119 of file SymFncExpAngnWeighted.cpp.
{
    this->convLength = convLength;
    eta /= convLength * convLength;
    rs *= convLength;
    rc *= convLength;
    fc.setCutoffRadius(rc);
    fc.setCutoffParameter(cutoffAlpha);
    return;
}
References nnp::SymFnc::convLength, nnp::SymFncBaseCutoff::cutoffAlpha, eta, nnp::SymFncBaseCutoff::fc, nnp::SymFnc::rc, rs, nnp::CutoffFunction::setCutoffParameter(), and nnp::CutoffFunction::setCutoffRadius().
getSettingsLine()
string SymFncExpAngnWeighted::getSettingsLine () const virtual
Get settings file line from currently set parameters.
Returns
Settings file string ("symfunction_short ...").
Implements nnp::SymFnc.
Definition at line 132 of file SymFncExpAngnWeighted.cpp.
{
    string s = strpr("symfunction_short %2s %2zu %16.8E %16.8E %16.8E "
                     "%16.8E %16.8E\n",
                     elementMap[ec].c_str(),
                     type,
                     eta * convLength * convLength,
                     rs / convLength,
                     lambda,
                     zeta,
                     rc / convLength);
    return s;
}
References nnp::SymFnc::convLength, nnp::SymFnc::ec, nnp::SymFnc::elementMap, eta, lambda, nnp::SymFnc::rc, rs, nnp::strpr(), nnp::SymFnc::type, and zeta.
calculate()
void SymFncExpAngnWeighted::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymFnc.
Definition at line 147 of file SymFncExpAngnWeighted.cpp.
{
    double const pnorm  = pow(2.0, 1.0 - zeta);
    double const pzl    = zeta * lambda;
    double const rc2    = rc * rc;
    double       result = 0.0;
    size_t numNeighbors = atom.numNeighbors;
    // Prevent problematic condition in loop test below (j < numNeighbors - 1).
    if (numNeighbors == 0) numNeighbors = 1;
    for (size_t j = 0; j < numNeighbors - 1; j++)
    {
        Atom::Neighbor& nj = atom.neighbors[j];
        size_t const nej = nj.element;
        double const rij = nj.d;
        if (rij < rc)
        {
            double const r2ij   = rij * rij;
            // Calculate cutoff function and derivative.
            double pfcij;
            double pdfcij;
#ifndef N2P2_NO_SF_CACHE
            if (cacheIndices[nej].size() == 0) fc.fdf(rij, pfcij, pdfcij);
            else
            {
                double& cfc = nj.cache[cacheIndices[nej][0]];
                double& cdfc = nj.cache[cacheIndices[nej][1]];
                if (cfc < 0) fc.fdf(rij, cfc, cdfc);
                pfcij = cfc;
                pdfcij = cdfc;
            }
#else
            fc.fdf(rij, pfcij, pdfcij);
#endif
            for (size_t k = j + 1; k < numNeighbors; k++)
            {
                Atom::Neighbor& nk = atom.neighbors[k];
                size_t const nek = nk.element;
                double const rik = nk.d;
                if (rik < rc)
                {
                    Vec3D drjk = nk.dr - nj.dr;
                    double rjk = drjk.norm2();;
                    if (rjk < rc2)
                    {
                        // Energy calculation.
                        double pfcik;
                        double pdfcik;
#ifndef N2P2_NO_SF_CACHE
                        if (cacheIndices[nej].size() == 0)
{
                            fc.fdf(rik, pfcik, pdfcik);
                        }
                        else
{
                            double& cfc = nk.cache[cacheIndices[nek][0]];
                            double& cdfc = nk.cache[cacheIndices[nek][1]];
                            if (cfc < 0) fc.fdf(rik, cfc, cdfc);
                            pfcik = cfc;
                            pdfcik = cdfc;
                        }
#else
                        fc.fdf(rik, pfcik, pdfcik);
#endif
                        rjk = sqrt(rjk);
                        double pfcjk;
                        double pdfcjk;
                        fc.fdf(rjk, pfcjk, pdfcjk);
                        Vec3D drij = nj.dr;
                        Vec3D drik = nk.dr;
                        double costijk = drij * drik;;
                        double rinvijik = 1.0 / rij / rik;
                        costijk *= rinvijik;
                        double const pfc = pfcij * pfcik * pfcjk;
                        double const r2ik = rik * rik;
                        double const rijs = rij - rs;
                        double const riks = rik - rs;
                        double const rjks = rjk - rs;
                        double const pexp = elementMap.atomicNumber(nej)
                                          * elementMap.atomicNumber(nek)
                                          * exp(-eta * (rijs * rijs +
                                                        riks * riks +
                                                        rjks * rjks));
                        double const plambda = 1.0 + lambda * costijk;
                        double       fg = pexp;
                        if (plambda <= 0.0) fg = 0.0;
                        else
{
                            if (useIntegerPow)
{
                                fg *= pow_int(plambda, zetaInt - 1);
                            }
                            else
{
                                fg *= pow(plambda, zeta - 1.0);
                            }
                        }
                        result += fg * plambda * pfc;
                        // Force calculation.
                        if (!derivatives) continue;
                        fg       *= pnorm;
                        rinvijik *= pzl;
                        costijk  *= pzl;
                        double const p2etapl = 2.0 * eta * plambda;
                        double const p1 = fg * (pfc * (rinvijik - costijk
                                        / r2ij - p2etapl * rijs / rij) + pfcik
                                        * pfcjk * pdfcij * plambda / rij);
                        double const p2 = fg * (pfc * (rinvijik - costijk
                                        / r2ik - p2etapl * riks / rik) + pfcij
                                        * pfcjk * pdfcik * plambda / rik);
                        double const p3 = fg * (pfc * (rinvijik + p2etapl
                                        * rjks / rjk) - pfcij * pfcik * pdfcjk
                                        * plambda / rjk);
                        drij *= p1 * scalingFactor;
                        drik *= p2 * scalingFactor;
                        drjk *= p3 * scalingFactor;
                        // Save force contributions in Atom storage.
                        atom.dGdr[index] += drij + drik;
#ifndef N2P2_FULL_SFD_MEMORY
                        nj.dGdr[indexPerElement[nj.element]] -= drij + drjk;
                        nk.dGdr[indexPerElement[nk.element]] -= drik - drjk;
#else
                        nj.dGdr[index] -= drij + drjk;
                        nk.dGdr[index] -= drik - drjk;
#endif
                    } // rjk <= rc
                } // rik <= rc
            } // k
        } // rij <= rc
    } // j
    result *= pnorm;
    atom.G[index] = scale(result);
    return;
}
References nnp::ElementMap::atomicNumber(), nnp::Atom::Neighbor::cache, nnp::SymFnc::cacheIndices, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::Atom::Neighbor::element, nnp::SymFnc::elementMap, eta, nnp::SymFncBaseCutoff::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymFnc::index, nnp::SymFnc::indexPerElement, lambda, nnp::Atom::neighbors, nnp::Vec3D::norm2(), nnp::Atom::numNeighbors, nnp::pow_int(), nnp::SymFnc::rc, rs, nnp::SymFnc::scale(), nnp::SymFnc::scalingFactor, useIntegerPow, zeta, and zetaInt.
parameterLine()
string SymFncExpAngnWeighted::parameterLine () const virtual
Give symmetry function parameters in one line.
Returns
String containing symmetry function parameter values.
Implements nnp::SymFnc.
Definition at line 290 of file SymFncExpAngnWeighted.cpp.
{
    return strpr(getPrintFormat().c_str(),
                 index + 1,
                 elementMap[ec].c_str(),
                 type,
                 subtype.c_str(),
                 eta * convLength * convLength,
                 rs / convLength,
                 rc / convLength,
                 lambda,
                 zeta,
                 cutoffAlpha,
                 lineNumber + 1);
}
References nnp::SymFnc::convLength, nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFnc::ec, nnp::SymFnc::elementMap, eta, nnp::SymFnc::getPrintFormat(), nnp::SymFnc::index, lambda, nnp::SymFnc::lineNumber, nnp::SymFnc::rc, rs, nnp::strpr(), nnp::SymFncBaseCutoff::subtype, nnp::SymFnc::type, and zeta.
parameterInfo()
vector< string > SymFncExpAngnWeighted::parameterInfo () const virtual
Get description with parameter names and values.
Returns
Vector of parameter description strings.
Reimplemented from nnp::SymFncBaseCutoff.
Definition at line 306 of file SymFncExpAngnWeighted.cpp.
{
    vector<string> v = SymFncBaseCutoff::parameterInfo();
    string s;
    size_t w = sfinfoWidth;
    s = "eta";
    v.push_back(strpr((pad(s, w) + "%14.8E").c_str(),
                      eta * convLength * convLength));
    s = "lambda";
    v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), lambda));
    s = "zeta";
    v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), zeta));
    s = "rs";
    v.push_back(strpr((pad(s, w) + "%14.8E").c_str(), rs / convLength));
    return v;
}
References nnp::SymFnc::convLength, eta, lambda, nnp::pad(), nnp::SymFncBaseCutoff::parameterInfo(), rs, nnp::SymFnc::sfinfoWidth, nnp::strpr(), and zeta.
getUseIntegerPow()
bool nnp::SymFncExpAngnWeighted::getUseIntegerPow () const inline
Get private useIntegerPow member variable.
Definition at line 165 of file SymFncExpAngnWeighted.h.
{
    return useIntegerPow;
}
References useIntegerPow.
getZetaInt()
int nnp::SymFncExpAngnWeighted::getZetaInt () const inline
Get private zetaInt member variable.
Definition at line 170 of file SymFncExpAngnWeighted.h.
{ return zetaInt; }
References zetaInt.
getEta()
double nnp::SymFncExpAngnWeighted::getEta () const inline
Get private eta member variable.
Definition at line 171 of file SymFncExpAngnWeighted.h.
{ return eta; }
References eta.
getRs()
double nnp::SymFncExpAngnWeighted::getRs () const inline
Get private rs member variable.
Definition at line 172 of file SymFncExpAngnWeighted.h.
{ return rs; }
References rs.
getLambda()
double nnp::SymFncExpAngnWeighted::getLambda () const inline
Get private lambda member variable.
Definition at line 173 of file SymFncExpAngnWeighted.h.
{ return lambda; }
References lambda.
getZeta()
double nnp::SymFncExpAngnWeighted::getZeta () const inline
Get private zeta member variable.
Definition at line 174 of file SymFncExpAngnWeighted.h.
{ return zeta; }
References zeta.
calculateRadialPart()
double SymFncExpAngnWeighted::calculateRadialPart (double distance) const virtual
Calculate (partial) symmetry function value for one given distance.
Parameters
[in] distance Distance between two atoms.
Returns
\(\left(e^{-\eta (r - r_s)^2} f_c(r)\right)^3\)
Implements nnp::SymFnc.
Definition at line 325 of file SymFncExpAngnWeighted.cpp.
{
    double const& r = distance * convLength;
    double const p = exp(-eta * (r - rs) * (r - rs)) * fc.f(r);
    return p * p * p;
}
References nnp::SymFnc::convLength, eta, nnp::CutoffFunction::f(), nnp::SymFncBaseCutoff::fc, p, and rs.
calculateAngularPart()
double SymFncExpAngnWeighted::calculateAngularPart (double angle) const virtual
Calculate (partial) symmetry function value for one given angle.
Parameters
[in] angle Angle between triplet of atoms (in radians).
Returns
\(1\)
Implements nnp::SymFnc.
Definition at line 333 of file SymFncExpAngnWeighted.cpp.
{
    return 2.0 * pow((1.0 + lambda * cos(angle)) / 2.0, zeta);
}
References lambda, and zeta.
checkRelevantElement()
bool SymFncExpAngnWeighted::checkRelevantElement (std::size_t index) const virtual
Check whether symmetry function is relevant for given element.
Parameters
[in] index Index of given element.
Returns
True if symmetry function is sensitive to given element, false otherwise.
Implements nnp::SymFnc.
Definition at line 338 of file SymFncExpAngnWeighted.cpp.
{
    return true;
}
getCacheIdentifiers()
vector< string > SymFncExpAngnWeighted::getCacheIdentifiers () const virtual
Get unique cache identifiers.
Returns
Vector of string identifying the type of cache this symmetry function requires.
Reimplemented from nnp::SymFnc.
Definition at line 344 of file SymFncExpAngnWeighted.cpp.
{
    vector<string> v;
    string s("");
    s += subtype;
    s += " ";
    s += strpr("alpha = %16.8E", cutoffAlpha);
    s += " ";
    s += strpr("rc = %16.8E", rc / convLength);
    for (size_t i = 0; i < elementMap.size(); ++i)
    {
        v.push_back(strpr("%zu f ", i) + s);
        v.push_back(strpr("%zu df ", i) + s);
    }
    return v;
}
References nnp::SymFnc::convLength, nnp::SymFncBaseCutoff::cutoffAlpha, nnp::SymFnc::elementMap, nnp::SymFnc::rc, nnp::ElementMap::size(), nnp::strpr(), and nnp::SymFncBaseCutoff::subtype.
Member Data Documentation
useIntegerPow
bool nnp::SymFncExpAngnWeighted::useIntegerPow private
Whether to use integer version of power function (faster).
Definition at line 148 of file SymFncExpAngnWeighted.h.
Referenced by calculate(), getUseIntegerPow(), and setParameters().
zetaInt
int nnp::SymFncExpAngnWeighted::zetaInt private
Integer version of \(\zeta\).
Definition at line 150 of file SymFncExpAngnWeighted.h.
Referenced by calculate(), getZetaInt(), and setParameters().
eta
double nnp::SymFncExpAngnWeighted::eta private
Width \(\eta\) of gaussian.
Definition at line 152 of file SymFncExpAngnWeighted.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getEta(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
rs
double nnp::SymFncExpAngnWeighted::rs private
Shift \(r_s\) of gaussian.
Definition at line 154 of file SymFncExpAngnWeighted.h.
Referenced by calculate(), calculateRadialPart(), changeLengthUnit(), getRs(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
lambda
double nnp::SymFncExpAngnWeighted::lambda private
Cosine shift factor.
Definition at line 156 of file SymFncExpAngnWeighted.h.
Referenced by calculate(), calculateAngularPart(), getLambda(), getSettingsLine(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
zeta
double nnp::SymFncExpAngnWeighted::zeta private
Exponent \(\zeta\) of cosine term.
Definition at line 158 of file SymFncExpAngnWeighted.h.
Referenced by calculate(), calculateAngularPart(), getSettingsLine(), getZeta(), operator<(), operator==(), parameterInfo(), parameterLine(), and setParameters().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncExpAngnWeighted.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncExpAngnWeighted.cpp