n2p2 - A neural network potential package: nnp::CoreFunction Class Reference
nnp::CoreFunction Class Reference
#include <CoreFunction.h>
Public Types
enum class Type {
POLY1 , POLY2 , POLY3 , POLY4 ,
EXP
}
List of available function types.
Public Member Functions
CoreFunction ()
Constructor, initializes to #Type::POLY2.
void setType (Type const type)
Set function type.
Type getType () const
Getter for type.
void setAsymmetric (bool asymmetric)
Set asymmetric property.
bool getAsymmetric () const
Getter for asymmetric.
double f (double x) const
Calculate function value \(f(x)\).
double df (double x) const
Calculate derivative of function at argument \(\frac{df(x)}{dx}\).
void fdf (double x, double &fx, double &dfx) const
Calculate function and derivative at once.
Private Member Functions
double fPOLY1 (double x) const
double dfPOLY1 (double x) const
void fdfPOLY1 (double x, double &fx, double &dfx) const
double fPOLY2 (double x) const
double dfPOLY2 (double x) const
void fdfPOLY2 (double x, double &fx, double &dfx) const
double fPOLY3 (double x) const
double dfPOLY3 (double x) const
void fdfPOLY3 (double x, double &fx, double &dfx) const
double fPOLY4 (double x) const
double dfPOLY4 (double x) const
void fdfPOLY4 (double x, double &fx, double &dfx) const
double fEXP (double x) const
double dfEXP (double x) const
void fdfEXP (double x, double &fx, double &dfx) const
Private Attributes
Type type
Core function type.
bool asymmetric
Enables asymmetry modification (use with polynomials).
double(CoreFunction::* fPtr)(double x) const
Function pointer to f.
double(CoreFunction::* dfPtr)(double x) const
Function pointer to df.
void(CoreFunction::* fdfPtr)(double x, double &fx, double &dfx) const
Function pointer to fdf.
Static Private Attributes
static double const E = exp(1.0)
Detailed Description
Definition at line 26 of file CoreFunction.h.
Member Enumeration Documentation
Type
enum class nnp::CoreFunction::Type strong
List of available function types.
Enumerator
POLY1
\(f(x) = (2x - 3)x^2 + 1\)
POLY2
\(f(x) = ((15 - 6x)x - 10) x^3 + 1\)
POLY3
\(f(x) = (x(x(20x - 70) + 84) - 35)x^4 + 1\)
POLY4
\(f(x) = (x(x((315 - 70x)x - 540) + 420) - 126)x^5 + 1\)
EXP
\(f(x) = e^{1 - \frac{1}{1 - x^2}}\)
Definition at line 30 of file CoreFunction.h.
    {
        POLY1,
        POLY2,
        POLY3,
        POLY4,
        EXP
    };
Constructor & Destructor Documentation
CoreFunction()
CoreFunction::CoreFunction ()
Constructor, initializes to #Type::POLY2.
Definition at line 26 of file CoreFunction.cpp.
                           : type      (Type::POLY2            ),
#ifndef N2P2_NO_ASYM_POLY
                               asymmetric(false                  ),
#endif
                               fPtr      (&CoreFunction::  fPOLY2),
                               dfPtr     (&CoreFunction:: dfPOLY2),
                               fdfPtr    (&CoreFunction::fdfPOLY2)
{
}
Member Function Documentation
setType()
void CoreFunction::setType (Type const type)
Set function type.
Parameters
[in] type Type of core function used.
Definition at line 36 of file CoreFunction.cpp.
{
    this->type = type;
    if (type == Type::POLY1)
    {
          fPtr = &CoreFunction::  fPOLY1;
         dfPtr = &CoreFunction:: dfPOLY1;
        fdfPtr = &CoreFunction::fdfPOLY1;
    }
    else if (type == Type::POLY2)
    {
          fPtr = &CoreFunction::  fPOLY2;
         dfPtr = &CoreFunction:: dfPOLY2;
        fdfPtr = &CoreFunction::fdfPOLY2;
    }
    else if (type == Type::POLY3)
    {
          fPtr = &CoreFunction::  fPOLY3;
         dfPtr = &CoreFunction:: dfPOLY3;
        fdfPtr = &CoreFunction::fdfPOLY3;
    }
    else if (type == Type::POLY4)
    {
          fPtr = &CoreFunction::  fPOLY4;
         dfPtr = &CoreFunction:: dfPOLY4;
        fdfPtr = &CoreFunction::fdfPOLY4;
    }
    else if (type == Type::EXP)
    {
          fPtr = &CoreFunction::  fEXP;
         dfPtr = &CoreFunction:: dfEXP;
        fdfPtr = &CoreFunction::fdfEXP;
    }
    else
    {
        throw invalid_argument("ERROR: Unknown core function.\n");
    }
    return;
}
References dfEXP(), dfPOLY1(), dfPOLY2(), dfPOLY3(), dfPOLY4(), dfPtr, EXP, fdfEXP(), fdfPOLY1(), fdfPOLY2(), fdfPOLY3(), fdfPOLY4(), fdfPtr, fEXP(), fPOLY1(), fPOLY2(), fPOLY3(), fPOLY4(), fPtr, POLY1, POLY2, POLY3, POLY4, and type.
Referenced by nnp::CompactFunction::CompactFunction(), nnp::CompactFunction::setCoreFunction(), and nnp::CutoffFunction::setCutoffType().
getType()
CoreFunction::Type nnp::CoreFunction::getType () const inline
Getter for type.
Returns
Type used.
Definition at line 137 of file CoreFunction.h.
{
    return type;
}
References type.
Referenced by nnp::CompactFunction::getCoreFunctionType().
setAsymmetric()
void nnp::CoreFunction::setAsymmetric (bool asymmetric) inline
Set asymmetric property.
Parameters
[in] asymmetric Whether asymmetry should be activated.
Definition at line 143 of file CoreFunction.h.
{
    this->asymmetric = asymmetric;
    return;
}
References asymmetric.
Referenced by nnp::CompactFunction::setAsymmetric().
getAsymmetric()
bool nnp::CoreFunction::getAsymmetric () const inline
Getter for asymmetric.
Returns
Whether asymmetry is activated.
Definition at line 150 of file CoreFunction.h.
{
    return asymmetric;
}
References asymmetric.
Referenced by nnp::CompactFunction::getAsymmetric().
f()
double nnp::CoreFunction::f (double x) const inline
Calculate function value \(f(x)\).
Parameters
[in] x Function argument.
Returns
Function value.
Definition at line 156 of file CoreFunction.h.
{
#ifndef N2P2_NO_ASYM_POLY
    if (asymmetric) x = (2.0 - x) * x;
#endif
    return (this->*fPtr)(x);
}
References asymmetric, and fPtr.
Referenced by nnp::CompactFunction::f(), and nnp::CutoffFunction::fCORE().
df()
double nnp::CoreFunction::df (double x) const inline
Calculate derivative of function at argument \(\frac{df(x)}{dx}\).
Parameters
[in] x Function argument.
Returns
Function derivative value.
Definition at line 164 of file CoreFunction.h.
{
#ifndef N2P2_NO_ASYM_POLY
    if (asymmetric) return (2.0 - 2.0 * x) * (this->*dfPtr)((2.0 - x) * x);
    else return (this->*dfPtr)(x);
#else
    return (this->*dfPtr)(x);
#endif
}
References asymmetric, and dfPtr.
Referenced by nnp::CompactFunction::df(), and nnp::CutoffFunction::dfCORE().
fdf()
void nnp::CoreFunction::fdf (double x, double & fx, double & dfx) const inline
Calculate function and derivative at once.
Parameters
[in] x Function argument.
[out] fx Function value.
[out] dfx Derivative value.
Definition at line 174 of file CoreFunction.h.
{
#ifndef N2P2_NO_ASYM_POLY
    if (asymmetric)
    {
        (this->*fdfPtr)((2.0 - x) * x, fx, dfx);
        dfx *= 2.0 - 2.0 * x;
    }
    else (this->*fdfPtr)(x, fx, dfx);
#else
    (this->*fdfPtr)(x, fx, dfx);
#endif
    return;
}
References asymmetric, and fdfPtr.
Referenced by nnp::CompactFunction::fdf(), and nnp::CutoffFunction::fdfCORE().
fPOLY1()
double nnp::CoreFunction::fPOLY1 (double x) const inline private
Definition at line 189 of file CoreFunction.h.
{
    return (2.0 * x - 3.0) * x * x + 1.0;
}
Referenced by setType().
dfPOLY1()
double nnp::CoreFunction::dfPOLY1 (double x) const inline private
Definition at line 194 of file CoreFunction.h.
{
    return x * (6.0 * x - 6.0);
}
Referenced by setType().
fdfPOLY1()
void nnp::CoreFunction::fdfPOLY1 (double x, double & fx, double & dfx) const inline private
Definition at line 199 of file CoreFunction.h.
{
    fx = (2.0 * x - 3.0) * x * x + 1.0;
    dfx = x * (6.0 * x - 6.0);
    return;
}
Referenced by setType().
fPOLY2()
double nnp::CoreFunction::fPOLY2 (double x) const inline private
Definition at line 206 of file CoreFunction.h.
{
    return ((15.0 - 6.0 * x) * x - 10.0) * x * x * x + 1.0;
}
Referenced by setType().
dfPOLY2()
double nnp::CoreFunction::dfPOLY2 (double x) const inline private
Definition at line 211 of file CoreFunction.h.
{
    return x * x * ((60.0 - 30.0 * x) * x - 30.0);
}
Referenced by setType().
fdfPOLY2()
void nnp::CoreFunction::fdfPOLY2 (double x, double & fx, double & dfx) const inline private
Definition at line 216 of file CoreFunction.h.
{
    double const x2 = x * x;
    fx = ((15.0 - 6.0 * x) * x - 10.0) * x * x2 + 1.0;
    dfx = x2 * ((60.0 - 30.0 * x) * x - 30.0);
    return;
}
Referenced by setType().
fPOLY3()
double nnp::CoreFunction::fPOLY3 (double x) const inline private
Definition at line 224 of file CoreFunction.h.
{
    double const x2 = x * x;
    return (x * (x * (20.0 * x - 70.0) + 84.0) - 35.0) * x2 * x2 + 1.0;
}
Referenced by setType().
dfPOLY3()
double nnp::CoreFunction::dfPOLY3 (double x) const inline private
Definition at line 230 of file CoreFunction.h.
{
    return x * x * x * (x * (x * (140.0 * x - 420.0) + 420.0) - 140.0);
}
Referenced by setType().
fdfPOLY3()
void nnp::CoreFunction::fdfPOLY3 (double x, double & fx, double & dfx) const inline private
Definition at line 235 of file CoreFunction.h.
{
    double const x2 = x * x;
    fx = (x * (x * (20.0 * x - 70.0) + 84.0) - 35.0) * x2 * x2 + 1.0;
    dfx = x2 * x * (x * (x * (140.0 * x - 420.0) + 420.0) - 140.0);
    return;
}
Referenced by setType().
fPOLY4()
double nnp::CoreFunction::fPOLY4 (double x) const inline private
Definition at line 243 of file CoreFunction.h.
{
    double const x2 = x * x;
    return (x * (x * ((315.0 - 70.0 * x) * x - 540.0) + 420.0) - 126.0) *
           x2 * x2 * x + 1.0;
}
Referenced by setType().
dfPOLY4()
double nnp::CoreFunction::dfPOLY4 (double x) const inline private
Definition at line 250 of file CoreFunction.h.
{
    double const x2 = x * x;
    return x2 * x2 *
           (x * (x * ((2520.0 - 630.0 * x) * x - 3780.0) + 2520.0) - 630.0);
}
Referenced by setType().
fdfPOLY4()
void nnp::CoreFunction::fdfPOLY4 (double x, double & fx, double & dfx) const inline private
Definition at line 257 of file CoreFunction.h.
{
    double x4 = x * x;
    x4 *= x4;
    fx = (x * (x * ((315.0 - 70.0 * x) * x - 540.0) + 420.0) - 126.0) *
         x * x4 + 1.0;
    dfx = x4 *
          (x * (x * ((2520.0 - 630.0 * x) * x - 3780.0) + 2520.0) - 630.0);
    return;
}
Referenced by setType().
fEXP()
double nnp::CoreFunction::fEXP (double x) const inline private
Definition at line 268 of file CoreFunction.h.
{
    return E * exp(1.0 / (x * x - 1.0));
}
References E.
Referenced by setType().
dfEXP()
double nnp::CoreFunction::dfEXP (double x) const inline private
Definition at line 273 of file CoreFunction.h.
{
    double const temp = 1.0 / (x * x - 1.0);
    return -2.0 * E * x * temp * temp * exp(temp);
}
References E.
Referenced by setType().
fdfEXP()
void nnp::CoreFunction::fdfEXP (double x, double & fx, double & dfx) const inline private
Definition at line 279 of file CoreFunction.h.
{
    double const temp = 1.0 / (x * x - 1.0);
    double const temp2 = exp(temp);
    fc = E * temp2;
    dfc = -2.0 * E * x * temp * temp * temp2;
    return;
}
References E, and fc.
Referenced by setType().
Member Data Documentation
E
double const CoreFunction::E = exp(1.0) static private
Definition at line 95 of file CoreFunction.h.
Referenced by dfEXP(), fdfEXP(), and fEXP().
type
Type nnp::CoreFunction::type private
Core function type.
Definition at line 97 of file CoreFunction.h.
Referenced by getType(), and setType().
asymmetric
bool nnp::CoreFunction::asymmetric private
Enables asymmetry modification (use with polynomials).
Definition at line 100 of file CoreFunction.h.
Referenced by df(), f(), fdf(), getAsymmetric(), and setAsymmetric().
fPtr
double(CoreFunction::* nnp::CoreFunction::fPtr) (double x) const private
Function pointer to f.
Definition at line 103 of file CoreFunction.h.
Referenced by f(), and setType().
dfPtr
double(CoreFunction::* nnp::CoreFunction::dfPtr) (double x) const private
Function pointer to df.
Definition at line 105 of file CoreFunction.h.
Referenced by df(), and setType().
fdfPtr
void(CoreFunction::* nnp::CoreFunction::fdfPtr) (double x, double &fx, double &dfx) const private
Function pointer to fdf.
Definition at line 107 of file CoreFunction.h.
Referenced by fdf(), and setType().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/CoreFunction.h
/home/runner/work/n2p2/n2p2/src/libnnp/CoreFunction.cpp