n2p2 - A neural network potential package: nnp::SymFncCompAngw Class Reference
nnp::SymFncCompAngw Class Reference
Wide angular symmetry function with compact support (type 22)
#include <SymFncCompAngw.h>
Public Member Functions
SymFncCompAngw (ElementMap const &elementMap)
Constructor, sets type = 22.
virtual bool operator== (SymFnc const &rhs) const
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const
Overload < operator.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate symmetry function for one atom.
Public Member Functions inherited from nnp::SymFncBaseCompAng
virtual void setParameters (std::string const &parameterString)
Set symmetry function parameters.
virtual void changeLengthUnit (double convLength)
Change length unit.
virtual std::string getSettingsLine () const
Get settings file line from currently set parameters.
void getCompactAngle (double const x, double &fx, double &dfx) const
void getCompactRadial (double const x, double &fx, double &dfx) const
virtual std::string parameterLine () const
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
std::size_t getE1 () const
Get private e1 member variable.
std::size_t getE2 () const
Get private e2 member variable.
double getAngleLeft () const
Get private angleLeft member variable.
double getAngleRight () const
Get private angleRight member variable.
virtual double calculateRadialPart (double distance) const
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
Public Member Functions inherited from nnp::SymFncBaseComp
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setCompactFunction (std::string subtype)
Set radial compact function.
std::string getSubtype () const
Get private subtype member variable.
double getRl () const
Get private rl member variable.
Public Member Functions inherited from nnp::SymFnc
virtual ~SymFnc ()
Virtual destructor.
virtual bool operator== (SymFnc const &rhs) const =0
Overload == operator.
virtual bool operator< (SymFnc const &rhs) const =0
Overload < operator.
bool operator!= (SymFnc const &rhs) const
Overload != operator.
bool operator> (SymFnc const &rhs) const
Overload > operator.
bool operator<= (SymFnc const &rhs) const
Overload <= operator.
bool operator>= (SymFnc const &rhs) const
Overload >= operator.
virtual void setParameters (std::string const &parameterString)=0
Set parameters.
virtual void changeLengthUnit (double convLength)=0
Change length unit.
virtual std::string getSettingsLine () const =0
Get settings file line from currently set parameters.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate symmetry function for one atom.
virtual std::string parameterLine () const =0
Give symmetry function parameters in one line.
virtual std::vector< std::string > parameterInfo () const
Get description with parameter names and values.
void setScalingType (ScalingType scalingType, std::string statisticsLine, double Smin, double Smax)
Set symmetry function scaling type.
double scale (double value) const
Apply symmetry function scaling and/or centering.
double unscale (double value) const
Undo symmetry function scaling and/or centering.
std::size_t getType () const
Get private type member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getLineNumber () const
Get private lineNumber member variable.
std::size_t getEc () const
Get private ec member variable.
std::size_t getMinNeighbors () const
Get private minNeighbors member variable.
double getRc () const
Get private rc member variable.
double getGmin () const
Get private Gmin member variable.
double getGmax () const
Get private Gmax member variable.
double getScalingFactor () const
Get private scalingFactor member variable.
double getConvLength () const
Get private convLength member variable.
std::set< std::string > getParameters () const
Get private parameters member variable.
std::vector< std::size_t > getIndexPerElement () const
Get private indexPerElement member variable.
void setIndex (std::size_t index)
Set private index member variable.
void setIndexPerElement (std::size_t elementIndex, std::size_t index)
Set private indexPerElement member variable.
void setLineNumber (std::size_t lineNumber)
Set line number.
std::string scalingLine () const
Get string with scaling information.
virtual double calculateRadialPart (double distance) const =0
Calculate (partial) symmetry function value for one given distance.
virtual double calculateAngularPart (double angle) const =0
Calculate (partial) symmetry function value for one given angle.
virtual bool checkRelevantElement (std::size_t index) const =0
Check whether symmetry function is relevant for given element.
virtual std::vector< std::string > getCacheIdentifiers () const
Get unique cache identifiers.
void addCacheIndex (std::size_t element, std::size_t cacheIndex, std::string cacheIdentifier)
Add one cache index for given neighbor element and check identifier.
std::vector< std::vector< std::size_t > > getCacheIndices () const
Getter for cacheIndices.
Additional Inherited Members
Public Types inherited from nnp::SymFnc
enum ScalingType {
ST_NONE , ST_SCALE , ST_CENTER , ST_SCALECENTER ,
ST_SCALESIGMA
}
List of available scaling types.
Protected Types inherited from nnp::SymFnc
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymFncBaseCompAng
SymFncBaseCompAng (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFncBaseComp
SymFncBaseComp (std::size_t type, ElementMap const &)
Constructor, initializes type.
Protected Member Functions inherited from nnp::SymFnc
SymFnc (std::size_t type, ElementMap const &)
Constructor, initializes type.
std::string getPrintFormat () const
Generate format string for symmetry function parameter printing.
Static Protected Member Functions inherited from nnp::SymFnc
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymFncBaseCompAng
std::size_t e1
Element index of neighbor atom 1.
std::size_t e2
Element index of neighbor atom 2.
double angleLeft
Left angle boundary.
double angleRight
Right angle boundary.
double angleLeftRadians
Left angle boundary in radians.
double angleRightRadians
Right angle boundary in radians.
CompactFunction ca
Compact function member for angular part.
Protected Attributes inherited from nnp::SymFncBaseComp
bool asymmetric
If asymmetric version of polynomials should be used.
double rl
Lower bound of compact function, \(r_{l}\).
std::string subtype
Subtype string (specifies e.g. polynom type).
CompactFunction cr
Compact function for radial part.
Protected Attributes inherited from nnp::SymFnc
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function index (per element).
std::size_t lineNumber
Line number.
std::size_t ec
Element index of center atom.
std::size_t minNeighbors
Minimum number of neighbors required.
double Smin
Minimum for scaling range.
double Smax
Maximum for scaling range.
double Gmin
Minimum unscaled symmetry function value.
double Gmax
Maximum unscaled symmetry function value.
double Gmean
Mean unscaled symmetry function value.
double Gsigma
Sigma of unscaled symmetry function values.
double rc
Cutoff radius \(r_c\).
double scalingFactor
Scaling factor.
double convLength
Data set normalization length conversion factor.
ScalingType scalingType
Symmetry function scaling type used by this symmetry function.
std::set< std::string > parameters
Set with symmetry function parameter IDs (lookup for printing).
std::vector< std::size_t > indexPerElement
Per-element index for derivative memory in Atom::Neighbor::dGdr arrays.
std::vector< std::vector< std::size_t > > cacheIndices
Cache indices for each element.
Static Protected Attributes inherited from nnp::SymFnc
static std::size_t const sfinfoWidth = 12
Width of the SFINFO parameter description field (see parameterInfo()).
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Wide angular symmetry function with compact support (type 22)
\[ G^{22}_i = \sum_{\substack{j,k\neq i \\ j < k}} C(r_{ij}, r_l, r_c) C(r_{ik}, r_l, r_c) C(\theta_{ijk}, \theta_l, \theta_r), \]
where \(C(x, x_\text{low}, x_\text{high})\) is a function with compact support \(\left[x_\text{low}, x_\text{high}\right]\).
Parameter string:
<element-central> 22 <element-neighbor1> <element-neighbor2> <rlow> <rcutoff> <left> <right> <subtype>
where
<element-central> ..... element symbol of central atom
<element-neighbor1> ... element symbol of neighbor atom 1
<element-neighbor2> ... element symbol of neighbor atom 2
<rlow> ................ low radius boundary \(r_{l}\)
<rcutoff> ............. high radius boundary \(r_{c}\)
<left> ................ left angle boundary \(\theta_l\)
<right> ............... right angle boundary \(\theta_r\)
<subtype> ............. compact function specifier
See the description of SymFncBaseComp::setCompactFunction() for possible values of the <subtype> argument.
Note
If <subtype> specifies an asymmetric version of a polynomial core function the asymmetry only applies to the radial parts, i.e. "p2a" sets a "p2a" radial compact function and a "p2" angular compact function.
Definition at line 64 of file SymFncCompAngw.h.
Constructor & Destructor Documentation
SymFncCompAngw()
SymFncCompAngw::SymFncCompAngw (ElementMap const & elementMap)
Constructor, sets type = 22.
Definition at line 31 of file SymFncCompAngw.cpp.
                                             :
    SymFncBaseCompAng(22, elementMap)
{
}
Member Function Documentation
operator==()
bool SymFncCompAngw::operator== (SymFnc const & rhs) const virtual
Overload == operator.
Implements nnp::SymFnc.
Definition at line 37 of file SymFncCompAngw.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymFncCompAngw const& c = dynamic_cast<SymFncCompAngw const&>(rhs);
    if (subtype     != c.getSubtype()) return false;
    if (e1          != c.e1          ) return false;
    if (e2          != c.e2          ) return false;
    if (rc          != c.rc          ) return false;
    if (rl          != c.rl          ) return false;
    if (angleLeft   != c.angleLeft   ) return false;
    if (angleRight  != c.angleRight  ) return false;
    return true;
}
References nnp::SymFncBaseCompAng::angleLeft, nnp::SymFncBaseCompAng::angleRight, nnp::SymFncBaseCompAng::e1, nnp::SymFncBaseCompAng::e2, nnp::SymFnc::ec, nnp::SymFnc::getEc(), nnp::SymFncBaseComp::getSubtype(), nnp::SymFnc::getType(), nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
operator<()
bool SymFncCompAngw::operator< (SymFnc const & rhs) const virtual
Overload < operator.
Implements nnp::SymFnc.
Definition at line 52 of file SymFncCompAngw.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymFncCompAngw const& c = dynamic_cast<SymFncCompAngw const&>(rhs);
    if      (subtype     < c.getSubtype()) return true;
    else if (subtype     > c.getSubtype()) return false;
    if      (e1          < c.e1          ) return true;
    else if (e1          > c.e1          ) return false;
    if      (e2          < c.e2          ) return true;
    else if (e2          > c.e2          ) return false;
    if      (rc          < c.rc          ) return true;
    else if (rc          > c.rc          ) return false;
    if      (rl          < c.rl          ) return true;
    else if (rl          > c.rl          ) return false;
    if      (angleLeft   < c.angleLeft   ) return true;
    else if (angleLeft   > c.angleLeft   ) return false;
    if      (angleRight  < c.angleRight  ) return true;
    else if (angleRight  > c.angleRight  ) return false;
    return false;
}
References nnp::SymFncBaseCompAng::angleLeft, nnp::SymFncBaseCompAng::angleRight, nnp::SymFncBaseCompAng::e1, nnp::SymFncBaseCompAng::e2, nnp::SymFnc::ec, nnp::SymFnc::getEc(), nnp::SymFncBaseComp::getSubtype(), nnp::SymFnc::getType(), nnp::SymFnc::rc, nnp::SymFncBaseComp::rl, nnp::SymFncBaseComp::subtype, and nnp::SymFnc::type.
calculate()
void SymFncCompAngw::calculate (Atom & atom, bool const derivatives) const virtual
Calculate symmetry function for one atom.
Parameters
[in,out] atom Atom for which the symmetry function is caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymFnc.
Definition at line 76 of file SymFncCompAngw.cpp.
{
    double       result = 0.0;
    size_t numNeighbors = atom.numNeighbors;
    // Prevent problematic condition in loop test below (j < numNeighbors - 1).
    if (numNeighbors == 0) numNeighbors = 1;
    for (size_t j = 0; j < numNeighbors - 1; j++)
    {
        Atom::Neighbor& nj = atom.neighbors[j];
        size_t const nej = nj.element;
        double const rij = nj.d;
        if ((e1 == nej || e2 == nej) && rij < rc && rij > rl)
        {
            double radij;
            double dradij;
#ifndef N2P2_NO_SF_CACHE
            if (cacheIndices[nej].size() == 0) cr.fdf(rij, radij, dradij);
            else
            {
                double& crad = nj.cache[cacheIndices[nej][0]];
                double& cdrad = nj.cache[cacheIndices[nej][1]];
                if (crad < 0) cr.fdf(rij, crad, cdrad);
                radij = crad;
                dradij = cdrad;
            }
#else
            cr.fdf(rij, radij, dradij);
#endif
            for (size_t k = j + 1; k < numNeighbors; k++)
            {
                Atom::Neighbor& nk = atom.neighbors[k];
                size_t const nek = nk.element;
                if ((e1 == nej && e2 == nek) ||
                    (e2 == nej && e1 == nek))
                {
                    double const rik = nk.d;
                    if (rik < rc && rik > rl)
                    {
                        // Energy calculation.
                        double radik;
                        double dradik;
#ifndef N2P2_NO_SF_CACHE
                        if (cacheIndices[nek].size() == 0)
{
                            cr.fdf(rik, radik, dradik);
                        }
                        else
{
                            double& crad = nk.cache[cacheIndices[nek][0]];
                            double& cdrad = nk.cache[cacheIndices[nek][1]];
                            if (crad < 0) cr.fdf(rik, crad, cdrad);
                            radik = crad;
                            dradik = cdrad;
                        }
#else
                        cr.fdf(rik, radik, dradik);
#endif
                        Vec3D drij = nj.dr;
                        Vec3D drik = nk.dr;
                        Vec3D drjk = drik - drij;
                        double costijk = drij * drik;
                        double rinvijik = 1.0 / rij / rik;
                        costijk *= rinvijik;
                        // By definition, our polynomial is zero at 0 and 180 deg.
                        // Therefore, skip the whole rest which might yield some NaN
                        if (costijk <= -1.0 || costijk >= 1.0) continue;
                        // Regroup later: Get acos(cos)
                        double const acostijk = acos(costijk);
                        // Only go on if we are within our compact support
                        if (acostijk < angleLeftRadians ||
                            acostijk > angleRightRadians) continue;
                        double ang  = 0.0;
                        double dang = 0.0;
                        ca.fdf(acostijk, ang, dang);
                        double const rad  = radij * radik; // product of cutoff fcts
                        result += rad * ang;
                        // Force calculation.
                        if (!derivatives) continue;
                        double const dacostijk = -1.0
                                               / sqrt(1.0 - costijk * costijk);
                        dang *= dacostijk;
                        double const rinvij = rinvijik * rik;
                        double const rinvik = rinvijik * rij;
                        double phiijik = rinvij * (rinvik - rinvij * costijk);
                        double phiikij = rinvik * (rinvij - rinvik * costijk);
                        double psiijik = rinvijik; // careful: sign flip w.r.t. notes due to nj.dGd...
                        phiijik *= dang;
                        phiikij *= dang;
                        psiijik *= dang;
                        // Cutoff function might be a divide by zero, but we screen that case before
                        double const chiij = rinvij * radik * dradij;
                        double const chiik = rinvik * radij * dradik;
                        // rijs/rij due to the shifted radial part of the Gaussian
                        double const p1 = rad * phiijik +  ang * chiij;
                        double const p2 = rad * phiikij +  ang * chiik;
                        double const p3 = rad * psiijik;
                        drij *= p1 * scalingFactor;
                        drik *= p2 * scalingFactor;
                        drjk *= p3 * scalingFactor;
                        // Save force contributions in Atom storage.
                        atom.dGdr[index] += drij + drik;
#ifndef N2P2_FULL_SFD_MEMORY
                        nj.dGdr[indexPerElement[nej]] -= drij + drjk;
                        nk.dGdr[indexPerElement[nek]] -= drik - drjk;
#else
                        nj.dGdr[index] -= drij + drjk;
                        nk.dGdr[index] -= drik - drjk;
#endif
                    } // rik <= rc
                } // elem
            } // k
        } // rij <= rc
    } // j
    atom.G[index] = scale(result);
    return;
}
References nnp::SymFncBaseCompAng::angleLeftRadians, nnp::SymFncBaseCompAng::angleRightRadians, nnp::SymFncBaseCompAng::ca, nnp::Atom::Neighbor::cache, nnp::SymFnc::cacheIndices, nnp::SymFncBaseComp::cr, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::SymFncBaseCompAng::e1, nnp::SymFncBaseCompAng::e2, nnp::Atom::Neighbor::element, nnp::CompactFunction::fdf(), nnp::Atom::G, nnp::SymFnc::index, nnp::SymFnc::indexPerElement, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::SymFncBaseComp::rl, nnp::SymFnc::scale(), and nnp::SymFnc::scalingFactor.
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncCompAngw.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymFncCompAngw.cpp