n2p2 - A neural network potential package: nnp::SymGrpCompAngn Class Reference
nnp::SymGrpCompAngn Class Reference
Narrow angular symmetry function with compact support (type 21)
#include <SymGrpCompAngn.h>
Public Member Functions
SymGrpCompAngn (ElementMap const &elementMap)
Constructor, sets type = 21.
virtual bool operator== (SymGrp const &rhs) const
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const
Overload < operator.
virtual bool addMember (SymFnc const *const symmetryFunction)
Potentially add a member to group.
virtual void sortMembers ()
Sort member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate all symmetry functions of this group for one atom.
Public Member Functions inherited from nnp::SymGrpBaseCompAng
virtual void setScalingFactors ()
Fill scalingFactors with values from member symmetry functions.
virtual std::vector< std::string > parameterLines () const
Give symmetry function group parameters on multiple lines.
Public Member Functions inherited from nnp::SymGrpBaseComp
double getRmin () const
Getter for rmin.
double getRmax () const
Getter for rmax.
Public Member Functions inherited from nnp::SymGrp
virtual ~SymGrp ()
Virtual destructor.
virtual bool operator== (SymGrp const &rhs) const =0
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const =0
Overload < operator.
bool operator!= (SymGrp const &rhs) const
Overload != operator.
bool operator> (SymGrp const &rhs) const
Overload > operator.
bool operator<= (SymGrp const &rhs) const
Overload <= operator.
bool operator>= (SymGrp const &rhs) const
Overload >= operator.
virtual bool addMember (SymFnc const *const symmetryFunction)=0
Potentially add a member to group.
virtual void sortMembers ()=0
Sort member symmetry functions.
virtual void setScalingFactors ()=0
Fill scalingFactors with values from member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate all symmetry functions of this group for one atom.
virtual std::vector< std::string > parameterLines () const =0
Give symmetry function group parameters on multiple lines.
void setIndex (std::size_t index)
Set private index member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getType () const
Get private type member variable.
std::size_t getEc () const
Get private ec member variable.
Private Member Functions
virtual std::vector< SymFncBaseCompAng const * > getMembers () const
Get symmetry function members.
Private Attributes
std::vector< SymFncCompAngn const * > members
Vector of all group member pointers.
Additional Inherited Members
Protected Types inherited from nnp::SymGrp
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymGrpBaseCompAng
SymGrpBaseCompAng (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
virtual std::vector< SymFncBaseCompAng const * > getMembers () const =0
Get symmetry function members.
Protected Member Functions inherited from nnp::SymGrpBaseComp
SymGrpBaseComp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
Protected Member Functions inherited from nnp::SymGrp
SymGrp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
std::string getPrintFormatCommon () const
Get common parameter line format string.
std::string getPrintFormatMember () const
Get member parameter line format string.
Static Protected Member Functions inherited from nnp::SymGrp
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymGrpBaseCompAng
std::size_t e1
Element index of neighbor atom 1 (common feature).
std::size_t e2
Element index of neighbor atom 2 (common feature).
std::vector< bool > calculateComp
Vector indicating whether compact function needs to be recalculated.
std::vector< double > mrl
Member rl.
std::vector< double > mrc
Member rc.
std::vector< double > mal
Member angleLeft.
std::vector< double > mar
Member angleRight.
std::vector< std::vector< std::vector< std::size_t > > > mci
Member cache indices for actual neighbor element.
Protected Attributes inherited from nnp::SymGrpBaseComp
double rmin
Minimum radius within group.
double rmax
Maximum radius within group.
Protected Attributes inherited from nnp::SymGrp
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function group index.
std::size_t ec
Element index of center atom (common feature).
double convLength
Data set normalization length conversion factor.
std::vector< size_t > memberIndex
Vector containing indices of all member symmetry functions.
std::vector< double > scalingFactors
Scaling factors of all member symmetry functions.
std::set< std::string > parametersCommon
Set of common parameters IDs.
std::set< std::string > parametersMember
Set of common parameters IDs.
std::vector< std::vector< std::size_t > > memberIndexPerElement
Vector containing per-element indices of all member symmetry functions.
Static Protected Attributes inherited from nnp::SymGrp
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Narrow angular symmetry function with compact support (type 21)
\[ G^{21}_i = \sum_{\substack{j,k\neq i \\ j < k}} C(r_{ij}, r_l, r_c) C(r_{ik}, r_l, r_c) C(r_{jk}, r_l, r_c) C(\theta_{ijk}, \theta_l, \theta_r), \]
where \(C(x, x_\text{low}, x_\text{high})\) is a function with compact support \(\left[x_\text{low}, x_\text{high}\right]\).
Common features:
element of central atom
element of neighbor atom 1
element of neighbor atom 2
Definition at line 51 of file SymGrpCompAngn.h.
Constructor & Destructor Documentation
SymGrpCompAngn()
SymGrpCompAngn::SymGrpCompAngn (ElementMap const & elementMap)
Constructor, sets type = 21.
Definition at line 30 of file SymGrpCompAngn.cpp.
                                             :
    SymGrpBaseCompAng(21, elementMap)
{
}
Member Function Documentation
operator==()
bool SymGrpCompAngn::operator== (SymGrp const & rhs) const virtual
Overload == operator.
Implements nnp::SymGrp.
Definition at line 36 of file SymGrpCompAngn.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymGrpCompAngn const& c = dynamic_cast<SymGrpCompAngn const&>(rhs);
    if (e1 != c.e1) return false;
    if (e2 != c.e2) return false;
    return true;
}
References nnp::SymGrpBaseCompAng::e1, nnp::SymGrpBaseCompAng::e2, nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), and nnp::SymGrp::type.
operator<()
bool SymGrpCompAngn::operator< (SymGrp const & rhs) const virtual
Overload < operator.
Implements nnp::SymGrp.
Definition at line 46 of file SymGrpCompAngn.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymGrpCompAngn const& c = dynamic_cast<SymGrpCompAngn const&>(rhs);
    if      (e1 < c.e1) return true;
    else if (e1 > c.e1) return false;
    if      (e2 < c.e2) return true;
    else if (e2 > c.e2) return false;
    return false;
}
References nnp::SymGrpBaseCompAng::e1, nnp::SymGrpBaseCompAng::e2, nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), and nnp::SymGrp::type.
addMember()
bool SymGrpCompAngn::addMember (SymFnc const *const symmetryFunction) virtual
Potentially add a member to group.
Parameters
[in] symmetryFunction Candidate symmetry function.
Returns
If addition was successful.
If symmetry function is compatible with common feature list its pointer will be added to members.
Implements nnp::SymGrp.
Definition at line 60 of file SymGrpCompAngn.cpp.
{
    if (symmetryFunction->getType() != type) return false;
    SymFncCompAngn const* sf =
        dynamic_cast<SymFncCompAngn const*>(symmetryFunction);
    if (members.empty())
    {
        ec          = sf->getEc();
        e1          = sf->getE1();
        e2          = sf->getE2();
        convLength  = sf->getConvLength();
    }
    if (sf->getEc()          != ec         ) return false;
    if (sf->getE1()          != e1         ) return false;
    if (sf->getE2()          != e2         ) return false;
    if (sf->getConvLength()  != convLength )
    {
        throw runtime_error("ERROR: Unable to add symmetry function members "
                            "with different conversion factors.\n");
    }
    if (sf->getRl() <= 0.0) rmin = 0.0;
    else rmin = min( rmin, sf->getRl() );
    rmax = max( rmax, sf->getRc() );
    members.push_back(sf);
    return true;
}
References nnp::SymGrp::convLength, nnp::SymGrpBaseCompAng::e1, nnp::SymGrpBaseCompAng::e2, nnp::SymGrp::ec, nnp::SymFnc::getConvLength(), nnp::SymFncBaseCompAng::getE1(), nnp::SymFncBaseCompAng::getE2(), nnp::SymFnc::getEc(), nnp::SymFnc::getRc(), nnp::SymFncBaseComp::getRl(), nnp::SymFnc::getType(), members, nnp::SymGrpBaseComp::rmax, nnp::SymGrpBaseComp::rmin, and nnp::SymGrp::type.
sortMembers()
void SymGrpCompAngn::sortMembers () virtual
Sort member symmetry functions.
Also allocate and precalculate additional stuff.
Implements nnp::SymGrp.
Definition at line 93 of file SymGrpCompAngn.cpp.
{
    sort(members.begin(),
         members.end(),
         comparePointerTargets<SymFncCompAngn const>);
    mrl.resize(members.size(), 0.0);
    mrc.resize(members.size(), 0.0);
    mal.resize(members.size(), 0.0);
    mar.resize(members.size(), 0.0);
    for (size_t i = 0; i < members.size(); i++)
    {
        mrl.at(i) = members[i]->getRl();
        mrc.at(i) = members[i]->getRc();
        mal.at(i) = members[i]->getAngleLeft() * M_PI / 180.0;
        mar.at(i) = members[i]->getAngleRight() * M_PI / 180.0;
        memberIndex.push_back(members[i]->getIndex());
        memberIndexPerElement.push_back(members[i]->getIndexPerElement());
        if (i == 0)
        {
            calculateComp.push_back(true);
        }
        else
        {
            if ( members[i - 1]->getRc() != members[i]->getRc() ||
                 members[i - 1]->getRl() != members[i]->getRl() )
            {
                calculateComp.push_back(true);
            }
            else
            {
                calculateComp.push_back(false);
            }
        }
    }
#ifndef N2P2_NO_SF_CACHE
    mci.resize(members.size());
    for (size_t k = 0; k < members.size(); ++k)
    {
        mci.at(k) = members.at(k)->getCacheIndices();
    }
#endif
    return;
}
References nnp::SymGrpBaseCompAng::calculateComp, nnp::SymGrp::getIndex(), nnp::SymGrpBaseCompAng::mal, nnp::SymGrpBaseCompAng::mar, nnp::SymGrpBaseCompAng::mci, nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, nnp::SymGrpBaseCompAng::mrc, and nnp::SymGrpBaseCompAng::mrl.
calculate()
void SymGrpCompAngn::calculate (Atom & atom, bool const derivatives) const virtual
Calculate all symmetry functions of this group for one atom.
Parameters
[in,out] atom Atom for which symmetry functions are caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymGrp.
Definition at line 146 of file SymGrpCompAngn.cpp.
{
    double* result = new double[members.size()];
    double* radij  = new double[members.size()];
    double* dradij = new double[members.size()];
    for (size_t l = 0; l < members.size(); ++l)
    {
        result[l] = 0.0;
        radij[l]  = 0.0;
        dradij[l] = 0.0;
    }
    double r2min = rmin * rmin;
    double r2max = rmax * rmax;
    size_t numNeighbors = atom.numNeighbors;
    // Prevent problematic condition in loop test below (j < numNeighbors - 1).
    if (numNeighbors == 0) numNeighbors = 1;
    for (size_t j = 0; j < numNeighbors - 1; j++)
    {
        Atom::Neighbor& nj = atom.neighbors[j];
        size_t const nej = nj.element;
        double const rij = nj.d;
        if ((e1 == nej || e2 == nej) && rij < rmax && rij > rmin)
        {
            // Precalculate the radial part for ij
            // Supposedly saves quite a number of operations
            for (size_t l = 0; l < members.size(); ++l)
            {
                if (rij > mrl[l] && rij < mrc[l])
                {
                    SymFncCompAngn const& sf = *(members[l]);
#ifndef N2P2_NO_SF_CACHE
                    if (mci[l][nej].size() == 0)
                    {
                        sf.getCompactRadial(rij, radij[l], dradij[l]);
                    }
                    else
                    {
                        double& crad = nj.cache[mci[l][nej][0]];
                        double& cdrad = nj.cache[mci[l][nej][1]];
                        if (crad < 0) sf.getCompactRadial(rij, crad, cdrad);
                        radij[l] = crad;
                        dradij[l] = cdrad;
                    }
#else
                    sf.getCompactRadial(rij, radij[l], dradij[l]);
#endif
                }
                else radij[l] = 0.0;
            }
            // SIMPLE EXPRESSIONS:
            //Vec3D drij(atom.neighbors[j].dr);
            double const* const dr1 = nj.dr.r;
            for (size_t k = j + 1; k < numNeighbors; k++)
            {
                Atom::Neighbor& nk = atom.neighbors[k];
                size_t const nek = nk.element;
                if ((e1 == nej && e2 == nek) ||
                    (e2 == nej && e1 == nek))
                {
                    double const rik = nk.d;
                    if (rik < rmax && rik > rmin)
                    {
                        // SIMPLE EXPRESSIONS:
                        //Vec3D drik(atom.neighbors[k].dr);
                        //Vec3D drjk = drik - drij;
                        double const* const dr2 = nk.dr.r;
                        double const dr30 = dr2[0] - dr1[0];
                        double const dr31 = dr2[1] - dr1[1];
                        double const dr32 = dr2[2] - dr1[2];
                        double rjk = dr30 * dr30
                                   + dr31 * dr31
                                   + dr32 * dr32;
                        if ((rjk >= r2max) || (rjk <= r2min)) continue;
                        rjk = sqrt(rjk);
                        // Energy calculation.
                        double const rinvijik = 1.0 / (rij * rik);
                        double const costijk = (dr1[0] * dr2[0] +
                                                dr1[1] * dr2[1] +
                                                dr1[2] * dr2[2]) * rinvijik;
                        // By definition, our polynomial is zero at 0 and 180 deg.
                        // Therefore, skip the whole rest which might yield some NaN
                        if (costijk <= -1.0 || costijk >= 1.0) continue;
                        double const acostijk = acos(costijk);
                        double const rinvij   = rinvijik * rik;
                        double const rinvik   = rinvijik * rij;
                        double const rinvjk   = 1.0 / rjk;
                        double const phiijik0 = rinvij
                                              * (rinvik - rinvij * costijk);
                        double const phiikij0 = rinvik
                                              * (rinvij - rinvik * costijk);
                        double dacostijk = 0.0;
                        if (derivatives)
{
                            dacostijk = -1.0 / sqrt(1.0 - costijk * costijk);
                        }
                        bool skip = false;
                        double ang;
                        double dang;
                        double radik;
                        double dradik;
                        double radjk;
                        double dradjk;
                        for (size_t l = 0; l < members.size(); ++l)
{
                            // Break conditions.
                            if (radij[l] == 0.0 ||
                                rik <= mrl[l] || rik >= mrc[l] ||
                                rjk <= mrl[l] || rjk >= mrc[l] ||
                                acostijk <= mal[l] || acostijk >= mar[l])
{
                                // Record if skipped.
                                skip = true;
                                continue;
                            }
                            SymFncCompAngn const& sf = *(members[l]);
#ifndef N2P2_NO_SF_CACHE
                            if (mci[l][nek].size() == 0)
{
                                sf.getCompactRadial(rik, radik, dradik);
                            }
                            else
{
                                double& crad = nk.cache[mci[l][nek][0]];
                                double& cdrad = nk.cache[mci[l][nek][1]];
                                if (crad < 0) sf.getCompactRadial(rik, crad, cdrad);
                                radik = crad;
                                dradik = cdrad;
                            }
#else
                            sf.getCompactRadial(rik, radik, dradik);
#endif
                            // Calculate anyway if skipped previously.
                            if (calculateComp[l] || skip)
{
                                sf.getCompactRadial(rjk, radjk, dradjk);
                                skip = false;
                            }
                            sf.getCompactAngle(acostijk, ang, dang);
                            double rad = radij[l] * radik * radjk;
                            result[l] += rad * ang;
                            // Force calculation.
                            if (!derivatives) continue;
                            dang *= dacostijk;
                            double const phiijik = phiijik0 * dang;
                            double const phiikij = phiikij0 * dang;
                            double const psiijik = rinvijik * dang;
                            double const chiij =  rinvij * dradij[l]
                                               *  radik  * radjk;
                            double const chiik =  rinvik * radij[l]
                                               *  dradik * radjk;
                            double const chijk = -rinvjk * radij[l]
                                               *  radik  * dradjk;
                            double p1;
                            double p2;
                            double p3;
                            if (dang != 0.0 && rad != 0.0)
{
                                rad  *= scalingFactors[l];
                                ang  *= scalingFactors[l];
                                p1 = rad * phiijik +  ang * chiij;
                                p2 = rad * phiikij +  ang * chiik;
                                p3 = rad * psiijik +  ang * chijk;
                            }
                            else if (ang != 0.0)
{
                                ang *= scalingFactors[l];
                                p1 = ang * chiij;
                                p2 = ang * chiik;
                                p3 = ang * chijk;
                            }
                            else continue;
                            // SIMPLE EXPRESSIONS:
                            // Save force contributions in Atom storage.
                            //atom.dGdr[memberIndex[l]] += p1 * drij
                            //                           + p2 * drik;
                            //atom.neighbors[j].
                            //    dGdr[memberIndex[l]] -= p1 * drij
                            //                          + p3 * drjk;
                            //atom.neighbors[k].
                            //    dGdr[memberIndex[l]] -= p2 * drik
                            //                          - p3 * drjk;
                            double const p1drijx = p1 * dr1[0];
                            double const p1drijy = p1 * dr1[1];
                            double const p1drijz = p1 * dr1[2];
                            double const p2drikx = p2 * dr2[0];
                            double const p2driky = p2 * dr2[1];
                            double const p2drikz = p2 * dr2[2];
                            double const p3drjkx = p3 * dr30;
                            double const p3drjky = p3 * dr31;
                            double const p3drjkz = p3 * dr32;
#ifndef N2P2_FULL_SFD_MEMORY
                            size_t li = memberIndex[l];
#else
                            size_t const li = memberIndex[l];
#endif
                            double* dGdr = atom.dGdr[li].r;
                            dGdr[0] += p1drijx + p2drikx;
                            dGdr[1] += p1drijy + p2driky;
                            dGdr[2] += p1drijz + p2drikz;
#ifndef N2P2_FULL_SFD_MEMORY
                            li = memberIndexPerElement[l][nej];
#endif
                            dGdr = nj.dGdr[li].r;
                            dGdr[0] -= p1drijx + p3drjkx;
                            dGdr[1] -= p1drijy + p3drjky;
                            dGdr[2] -= p1drijz + p3drjkz;
#ifndef N2P2_FULL_SFD_MEMORY
                            li = memberIndexPerElement[l][nek];
#endif
                            dGdr = nk.dGdr[li].r;
                            dGdr[0] -= p2drikx - p3drjkx;
                            dGdr[1] -= p2driky - p3drjky;
                            dGdr[2] -= p2drikz - p3drjkz;
                        } // l
                    } // rik <= rc
                } // elem
            } // k
        } // rij <= rc
    } // j
    for (size_t l = 0; l < members.size(); ++l)
    {
        atom.G[memberIndex[l]] = members[l]->scale(result[l]);
    }
    delete[] result;
    delete[] radij;
    delete[] dradij;
    return;
}
References nnp::Atom::Neighbor::cache, nnp::SymGrpBaseCompAng::calculateComp, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::SymGrpBaseCompAng::e1, nnp::SymGrpBaseCompAng::e2, nnp::Atom::Neighbor::element, nnp::Atom::G, nnp::SymFncBaseCompAng::getCompactAngle(), nnp::SymFncBaseCompAng::getCompactRadial(), nnp::SymGrpBaseCompAng::mal, nnp::SymGrpBaseCompAng::mar, nnp::SymGrpBaseCompAng::mci, nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, nnp::SymGrpBaseCompAng::mrc, nnp::SymGrpBaseCompAng::mrl, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::Vec3D::r, nnp::SymGrpBaseComp::rmax, nnp::SymGrpBaseComp::rmin, and nnp::SymGrp::scalingFactors.
getMembers()
std::vector< SymFncBaseCompAng const * > nnp::SymGrpCompAngn::getMembers () const inline private virtual
Get symmetry function members.
Returns
Vector of pointers casted to base class.
Implements nnp::SymGrpBaseCompAng.
Definition at line 96 of file SymGrpCompAngn.h.
{
    std::vector<SymFncBaseCompAng const*> cast;
    for (auto p : members)
    {
        cast.push_back(dynamic_cast<SymFncBaseCompAng const*>(p));
    }
    return cast;
}
References members, and p.
Member Data Documentation
members
std::vector<SymFncCompAngn const*> nnp::SymGrpCompAngn::members private
Vector of all group member pointers.
Definition at line 93 of file SymGrpCompAngn.h.
Referenced by addMember(), calculate(), getMembers(), and sortMembers().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpCompAngn.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpCompAngn.cpp