n2p2 - A neural network potential package: nnp::CutoffFunction Class Reference
nnp::CutoffFunction Class Reference
#include <CutoffFunction.h>
Public Types
enum CutoffType {
CT_HARD , CT_COS , CT_TANHU , CT_TANH ,
CT_EXP , CT_POLY1 , CT_POLY2 , CT_POLY3 ,
CT_POLY4
}
List of available cutoff function types.
Public Member Functions
CutoffFunction ()
Constructor, initializes to ´CT_HARD´.
void setCutoffType (CutoffType const cutoffType)
Set cutoff type.
CutoffType getCutoffType () const
Getter for cutoffType.
void setCutoffRadius (double const cutoffRadius)
Set cutoff radius.
double getCutoffRadius () const
Getter for rc.
void setCutoffParameter (double const alpha)
Set parameter for polynomial cutoff function (CT_POLY).
double getCutoffParameter () const
Getter for alpha.
double f (double r) const
Cutoff function \(f_c\).
double df (double r) const
Derivative of cutoff function \(\frac{d f_c}{d r}\).
void fdf (double r, double &fc, double &dfc) const
Calculate cutoff function \(f_c\) and derivative \(\frac{d f_c}{d r}\).
Private Member Functions
double fHARD (double r) const
double dfHARD (double r) const
void fdfHARD (double r, double &fc, double &dfc) const
double fCOS (double r) const
double dfCOS (double r) const
void fdfCOS (double r, double &fc, double &dfc) const
double fTANHU (double r) const
double dfTANHU (double r) const
void fdfTANHU (double r, double &fc, double &dfc) const
double fTANH (double r) const
double dfTANH (double r) const
void fdfTANH (double r, double &fc, double &dfc) const
double fCORE (double r) const
double dfCORE (double r) const
void fdfCORE (double r, double &fc, double &dfc) const
Private Attributes
CutoffType cutoffType
Cutoff function type.
double rc
Outer cutoff radius \(r_c\).
double rcinv
Inverse cutoff radius \(\frac{1}{r_c}\).
double rci
Inner cutoff for cutoff function types which allow shifting.
double alpha
Cutoff function parameter for CT_POLYn and CT_EXP \(\alpha\).
double iw
Inverse width of cutoff function \(\frac{1}{r_c - r_{ci}}\).
CoreFunction core
Core functions used by POLYN, if any.
double(CutoffFunction::* fPtr)(double r) const
Function pointer to f.
double(CutoffFunction::* dfPtr)(double r) const
Function pointer to df.
void(CutoffFunction::* fdfPtr)(double r, double &fc, double &dfc) const
Function pointer to fdf.
Static Private Attributes
static double const PI = 4.0 * atan(1.0)
static double const PI_2 = 2.0 * atan(1.0)
static double const E = exp(1.0)
static double const TANH_PRE = pow((E + 1 / E) / (E - 1 / E), 3)
Detailed Description
Definition at line 25 of file CutoffFunction.h.
Member Enumeration Documentation
CutoffType
enum nnp::CutoffFunction::CutoffType
List of available cutoff function types.
Most cutoff types allow the definition of an inner cutoff \(r_{ci} := \alpha \, r_c\). Then the cutoff is equal to \(1\) up to the inner cutoff:
\(f_c(r) = \begin{cases} 1, & \text{for } 0 \le r < r_{ci} \\ f(x), & \text{for } r_{ci} \le r < r_c \text{ where } x := \frac{r - r_{ci}}{r_c - r_{ci}} \\ 0 & \text{for } r \geq r_c \end{cases} \)
Enumerator
CT_HARD
\(f(x) = 1\)
CT_COS
\(f(x) = \frac{1}{2} \left[ \cos (\pi x) + 1\right] \)
CT_TANHU
\(f_c(r) = \tanh^3 \left(1 - \frac{r}{r_c} \right) \)
CT_TANH
\(f_c(r) = c \tanh^3 \left(1 - \frac{r}{r_c} \right),\, f(0) = 1 \)
CT_EXP
\(f(x) = e^{1 - \frac{1}{1 - x^2}}\)
CT_POLY1
\(f(x) = (2x - 3)x^2 + 1\)
CT_POLY2
\(f(x) = ((15 - 6x)x - 10) x^3 + 1\)
CT_POLY3
\(f(x) = (x(x(20x - 70) + 84) - 35)x^4 + 1\)
CT_POLY4
\(f(x) = (x(x((315 - 70x)x - 540) + 420) - 126)x^5 + 1\)
Definition at line 42 of file CutoffFunction.h.
    {
        CT_HARD,
        CT_COS,
        CT_TANHU,
        CT_TANH,
        CT_EXP,
        CT_POLY1,
        CT_POLY2,
        CT_POLY3,
        CT_POLY4
    };
Constructor & Destructor Documentation
CutoffFunction()
CutoffFunction::CutoffFunction ()
Constructor, initializes to ´CT_HARD´.
Definition at line 30 of file CutoffFunction.cpp.
                               : cutoffType(CT_HARD                 ),
                                   rc        (0.0                     ),
                                   rcinv     (0.0                     ),
                                   rci       (0.0                     ),
                                   alpha     (0.0                     ),
                                   iw        (0.0                     ),
                                   fPtr      (&CutoffFunction::  fHARD),
                                   dfPtr     (&CutoffFunction:: dfHARD),
                                   fdfPtr    (&CutoffFunction::fdfHARD)
{
}
Member Function Documentation
setCutoffType()
void CutoffFunction::setCutoffType (CutoffType const cutoffType)
Set cutoff type.
Parameters
[in] cutoffType Type of cutoff used.
Definition at line 42 of file CutoffFunction.cpp.
{
    this->cutoffType = cutoffType;
    if (cutoffType == CT_HARD)
    {
          fPtr = &CutoffFunction::  fHARD;
         dfPtr = &CutoffFunction:: dfHARD;
        fdfPtr = &CutoffFunction::fdfHARD;
    }
    else if (cutoffType == CT_COS)
    {
          fPtr = &CutoffFunction::  fCOS;
         dfPtr = &CutoffFunction:: dfCOS;
        fdfPtr = &CutoffFunction::fdfCOS;
    }
    else if (cutoffType == CT_TANHU)
    {
          fPtr = &CutoffFunction::  fTANHU;
         dfPtr = &CutoffFunction:: dfTANHU;
        fdfPtr = &CutoffFunction::fdfTANHU;
    }
    else if (cutoffType == CT_TANH)
    {
          fPtr = &CutoffFunction::  fTANH;
         dfPtr = &CutoffFunction:: dfTANH;
        fdfPtr = &CutoffFunction::fdfTANH;
    }
    else if (cutoffType == CT_POLY1 ||
             cutoffType == CT_POLY2 ||
             cutoffType == CT_POLY3 ||
             cutoffType == CT_POLY4 ||
             cutoffType == CT_EXP)
    {
        using CFT = CoreFunction::Type;
        if      (cutoffType == CT_POLY1) core.setType(CFT::POLY1);
        else if (cutoffType == CT_POLY2) core.setType(CFT::POLY2);
        else if (cutoffType == CT_POLY3) core.setType(CFT::POLY3);
        else if (cutoffType == CT_POLY4) core.setType(CFT::POLY4);
        else if (cutoffType == CT_EXP)   core.setType(CFT::EXP);
          fPtr = &CutoffFunction::  fCORE;
         dfPtr = &CutoffFunction:: dfCORE;
        fdfPtr = &CutoffFunction::fdfCORE;
    }
    else
    {
        throw invalid_argument("ERROR: Unknown cutoff type.\n");
    }
    return;
}
References core, CT_COS, CT_EXP, CT_HARD, CT_POLY1, CT_POLY2, CT_POLY3, CT_POLY4, CT_TANH, CT_TANHU, cutoffType, dfCORE(), dfCOS(), dfHARD(), dfPtr, dfTANH(), dfTANHU(), fCORE(), fCOS(), fdfCORE(), fdfCOS(), fdfHARD(), fdfPtr, fdfTANH(), fdfTANHU(), fHARD(), fPtr, fTANH(), fTANHU(), and nnp::CoreFunction::setType().
Referenced by nnp::SymGrpExpAngn::addMember(), nnp::SymGrpExpAngnWeighted::addMember(), nnp::SymGrpExpAngw::addMember(), nnp::SymGrpExpRad::addMember(), nnp::SymGrpExpRadWeighted::addMember(), runTest(), and nnp::SymFncBaseCutoff::setCutoffFunction().
getCutoffType()
CutoffFunction::CutoffType nnp::CutoffFunction::getCutoffType () const inline
Getter for cutoffType.
Returns
CutoffType used.
Definition at line 183 of file CutoffFunction.h.
{
    return cutoffType;
}
References cutoffType.
setCutoffRadius()
void CutoffFunction::setCutoffRadius (double const cutoffRadius)
Set cutoff radius.
Parameters
[in] cutoffRadius Cutoff radius \(r_c\).
Definition at line 95 of file CutoffFunction.cpp.
{
    rc = cutoffRadius;
    rcinv = 1.0 / cutoffRadius;
    return;
}
References rc, and rcinv.
Referenced by nnp::SymGrpExpAngn::addMember(), nnp::SymGrpExpAngnWeighted::addMember(), nnp::SymGrpExpAngw::addMember(), nnp::SymGrpExpRad::addMember(), nnp::SymGrpExpRadWeighted::addMember(), nnp::SymFncBaseExpAng::changeLengthUnit(), nnp::SymFncExpAngnWeighted::changeLengthUnit(), nnp::SymFncExpRad::changeLengthUnit(), nnp::SymFncExpRadWeighted::changeLengthUnit(), main(), nnp::SymFncBaseExpAng::setParameters(), nnp::SymFncExpAngnWeighted::setParameters(), nnp::SymFncExpRad::setParameters(), and nnp::SymFncExpRadWeighted::setParameters().
getCutoffRadius()
double nnp::CutoffFunction::getCutoffRadius () const inline
Getter for rc.
Returns
Cutoff radius used.
Definition at line 188 of file CutoffFunction.h.
{
    return rc;
}
References rc.
setCutoffParameter()
void CutoffFunction::setCutoffParameter (double const alpha)
Set parameter for polynomial cutoff function (CT_POLY).
Parameters
[in] alpha Width parameter \(\alpha\).
Definition at line 102 of file CutoffFunction.cpp.
{
    if (alpha < 0.0 || alpha >= 1.0)
    {
        throw invalid_argument("ERROR: 0 <= alpha < 1.0 is required.\n");
    }
    this->alpha = alpha;
    rci = rc * alpha;
    iw = 1.0 / (rc - rci);
    return;
}
References alpha, iw, rc, and rci.
Referenced by nnp::SymGrpExpAngn::addMember(), nnp::SymGrpExpAngnWeighted::addMember(), nnp::SymGrpExpAngw::addMember(), nnp::SymGrpExpRad::addMember(), nnp::SymGrpExpRadWeighted::addMember(), nnp::SymFncBaseExpAng::changeLengthUnit(), nnp::SymFncExpAngnWeighted::changeLengthUnit(), nnp::SymFncExpRad::changeLengthUnit(), nnp::SymFncExpRadWeighted::changeLengthUnit(), main(), nnp::SymFncBaseCutoff::setCutoffFunction(), nnp::SymFncBaseExpAng::setParameters(), nnp::SymFncExpAngnWeighted::setParameters(), nnp::SymFncExpRad::setParameters(), and nnp::SymFncExpRadWeighted::setParameters().
getCutoffParameter()
double nnp::CutoffFunction::getCutoffParameter () const inline
Getter for alpha.
Returns
Cutoff parameter used.
Definition at line 193 of file CutoffFunction.h.
{
    return alpha;
}
References alpha.
f()
double nnp::CutoffFunction::f (double r) const inline
Cutoff function \(f_c\).
Parameters
[in] r Distance.
Returns
Cutoff function value.
Definition at line 198 of file CutoffFunction.h.
{
    if (r >= rc) return 0.0;
    return (this->*fPtr)(r);
}
References fPtr, and rc.
Referenced by nnp::SymFncBaseExpAng::calculateRadialPart(), nnp::SymFncExpAngnWeighted::calculateRadialPart(), nnp::SymFncExpRad::calculateRadialPart(), nnp::SymFncExpRadWeighted::calculateRadialPart(), and runTest().
df()
double nnp::CutoffFunction::df (double r) const inline
Derivative of cutoff function \(\frac{d f_c}{d r}\).
Parameters
[in] r Distance.
Returns
Value of cutoff function derivative.
Definition at line 204 of file CutoffFunction.h.
{
    if (r >= rc) return 0.0;
    return (this->*dfPtr)(r);
}
References dfPtr, and rc.
Referenced by runTest().
fdf()
void nnp::CutoffFunction::fdf (double r, double & fc, double & dfc) const inline
Calculate cutoff function \(f_c\) and derivative \(\frac{d f_c}{d r}\).
Parameters
[in] r Distance.
[out] fc Cutoff function value.
[out] dfc Value of cutoff function derivative.
Definition at line 210 of file CutoffFunction.h.
{
    if (r >= rc)
    {
        fc = 0.0;
        dfc = 0.0;
        return;
    }
    (this->*fdfPtr)(r, fc, dfc);
    return;
}
References fc, fdfPtr, and rc.
Referenced by nnp::SymFncExpAngn::calculate(), nnp::SymFncExpAngnWeighted::calculate(), nnp::SymFncExpAngw::calculate(), nnp::SymFncExpRad::calculate(), nnp::SymFncExpRadWeighted::calculate(), nnp::SymGrpExpAngn::calculate(), nnp::SymGrpExpAngnWeighted::calculate(), nnp::SymGrpExpAngw::calculate(), nnp::SymGrpExpRad::calculate(), nnp::SymGrpExpRadWeighted::calculate(), and runTest().
fHARD()
double nnp::CutoffFunction::fHARD (double r) const inline private
Definition at line 222 of file CutoffFunction.h.
{
    return 1.0;
}
Referenced by setCutoffType().
dfHARD()
double nnp::CutoffFunction::dfHARD (double r) const inline private
Definition at line 227 of file CutoffFunction.h.
{
    return 0.0;
}
Referenced by setCutoffType().
fdfHARD()
void nnp::CutoffFunction::fdfHARD (double r, double & fc, double & dfc) const inline private
Definition at line 232 of file CutoffFunction.h.
{
    fc = 1.0;
    dfc = 0.0;
    return;
}
References fc.
Referenced by setCutoffType().
fCOS()
double CutoffFunction::fCOS (double r) const private
Definition at line 114 of file CutoffFunction.cpp.
{
    if (r < rci) return 1.0;
    double const x = (r - rci) * iw;
    return 0.5 * (cos(PI * x) + 1.0);
}
References iw, PI, and rci.
Referenced by setCutoffType().
dfCOS()
double CutoffFunction::dfCOS (double r) const private
Definition at line 121 of file CutoffFunction.cpp.
{
    if (r < rci) return 0.0;
    double const x = (r - rci) * iw;
    return -PI_2 * iw * sin(PI * x);
}
References iw, PI, PI_2, and rci.
Referenced by setCutoffType().
fdfCOS()
void CutoffFunction::fdfCOS (double r, double & fc, double & dfc) const private
Definition at line 128 of file CutoffFunction.cpp.
{
    if (r < rci)
    {
        fc = 1.0;
        dfc = 0.0;
        return;
    }
    double const x = (r - rci) * iw;
    double const temp = cos(PI * x);
    fc = 0.5 * (temp + 1.0);
    dfc = -0.5 * iw * PI * sqrt(1.0 - temp * temp);
    return;
}
References fc, iw, PI, and rci.
Referenced by setCutoffType().
fTANHU()
double CutoffFunction::fTANHU (double r) const private
Definition at line 143 of file CutoffFunction.cpp.
{
    double const temp = tanh(1.0 - r * rcinv);
    return temp * temp * temp;
}
References rcinv.
Referenced by setCutoffType().
dfTANHU()
double CutoffFunction::dfTANHU (double r) const private
Definition at line 149 of file CutoffFunction.cpp.
{
    double temp = tanh(1.0 - r * rcinv);
    temp *= temp;
    return 3.0 * temp * (temp - 1.0) * rcinv;
}
References rcinv.
Referenced by setCutoffType().
fdfTANHU()
void CutoffFunction::fdfTANHU (double r, double & fc, double & dfc) const private
Definition at line 156 of file CutoffFunction.cpp.
{
    double const temp = tanh(1.0 - r * rcinv);
    double const temp2 = temp * temp;
    fc = temp * temp2;
    dfc = 3.0 * temp2 * (temp2 - 1.0) * rcinv;
    return;
}
References fc, and rcinv.
Referenced by setCutoffType().
fTANH()
double CutoffFunction::fTANH (double r) const private
Definition at line 165 of file CutoffFunction.cpp.
{
    double const temp = tanh(1.0 - r * rcinv);
    return TANH_PRE * temp * temp * temp;
}
References rcinv, and TANH_PRE.
Referenced by setCutoffType().
dfTANH()
double CutoffFunction::dfTANH (double r) const private
Definition at line 171 of file CutoffFunction.cpp.
{
    double temp = tanh(1.0 - r * rcinv);
    temp *= temp;
    return 3.0 * TANH_PRE * temp * (temp - 1.0) * rcinv;
}
References rcinv, and TANH_PRE.
Referenced by setCutoffType().
fdfTANH()
void CutoffFunction::fdfTANH (double r, double & fc, double & dfc) const private
Definition at line 178 of file CutoffFunction.cpp.
{
    double const temp = tanh(1.0 - r * rcinv);
    double const temp2 = temp * temp;
    fc = TANH_PRE * temp * temp2;
    dfc = 3.0 * TANH_PRE * temp2 * (temp2 - 1.0) * rcinv;
    return;
}
References fc, rcinv, and TANH_PRE.
Referenced by setCutoffType().
fCORE()
double CutoffFunction::fCORE (double r) const private
Definition at line 187 of file CutoffFunction.cpp.
{
    if (r < rci) return 1.0;
    double const x = (r - rci) * iw;
    return core.f(x);
}
References core, nnp::CoreFunction::f(), iw, and rci.
Referenced by setCutoffType().
dfCORE()
double CutoffFunction::dfCORE (double r) const private
Definition at line 194 of file CutoffFunction.cpp.
{
    if (r < rci) return 0.0;
    double const x = (r - rci) * iw;
    return iw * core.df(x);
}
References core, nnp::CoreFunction::df(), iw, and rci.
Referenced by setCutoffType().
fdfCORE()
void CutoffFunction::fdfCORE (double r, double & fc, double & dfc) const private
Definition at line 201 of file CutoffFunction.cpp.
{
    if (r < rci)
    {
        fc = 1.0;
        dfc = 0.0;
        return;
    }
    double const x = (r - rci) * iw;
    core.fdf(x, fc, dfc);
    dfc *= iw;
    return;
}
References core, fc, nnp::CoreFunction::fdf(), iw, and rci.
Referenced by setCutoffType().
Member Data Documentation
PI
double const CutoffFunction::PI = 4.0 * atan(1.0) static private
Definition at line 129 of file CutoffFunction.h.
Referenced by dfCOS(), fCOS(), and fdfCOS().
PI_2
double const CutoffFunction::PI_2 = 2.0 * atan(1.0) static private
Definition at line 130 of file CutoffFunction.h.
Referenced by dfCOS().
E
double const CutoffFunction::E = exp(1.0) static private
Definition at line 131 of file CutoffFunction.h.
TANH_PRE
double const CutoffFunction::TANH_PRE = pow((E + 1 / E) / (E - 1 / E), 3) static private
Definition at line 132 of file CutoffFunction.h.
Referenced by dfTANH(), fdfTANH(), and fTANH().
cutoffType
CutoffType nnp::CutoffFunction::cutoffType private
Cutoff function type.
Definition at line 135 of file CutoffFunction.h.
Referenced by getCutoffType(), and setCutoffType().
rc
double nnp::CutoffFunction::rc private
Outer cutoff radius \(r_c\).
Definition at line 137 of file CutoffFunction.h.
Referenced by df(), f(), fdf(), getCutoffRadius(), setCutoffParameter(), and setCutoffRadius().
rcinv
double nnp::CutoffFunction::rcinv private
Inverse cutoff radius \(\frac{1}{r_c}\).
Definition at line 139 of file CutoffFunction.h.
Referenced by dfTANH(), dfTANHU(), fdfTANH(), fdfTANHU(), fTANH(), fTANHU(), and setCutoffRadius().
rci
double nnp::CutoffFunction::rci private
Inner cutoff for cutoff function types which allow shifting.
Definition at line 141 of file CutoffFunction.h.
Referenced by dfCORE(), dfCOS(), fCORE(), fCOS(), fdfCORE(), fdfCOS(), and setCutoffParameter().
alpha
double nnp::CutoffFunction::alpha private
Cutoff function parameter for CT_POLYn and CT_EXP \(\alpha\).
Definition at line 143 of file CutoffFunction.h.
Referenced by getCutoffParameter(), and setCutoffParameter().
iw
double nnp::CutoffFunction::iw private
Inverse width of cutoff function \(\frac{1}{r_c - r_{ci}}\).
Definition at line 145 of file CutoffFunction.h.
Referenced by dfCORE(), dfCOS(), fCORE(), fCOS(), fdfCORE(), fdfCOS(), and setCutoffParameter().
core
CoreFunction nnp::CutoffFunction::core private
Core functions used by POLYN, if any.
Definition at line 147 of file CutoffFunction.h.
Referenced by dfCORE(), fCORE(), fdfCORE(), and setCutoffType().
fPtr
double(CutoffFunction::* nnp::CutoffFunction::fPtr) (double r) const private
Function pointer to f.
Definition at line 149 of file CutoffFunction.h.
Referenced by f(), and setCutoffType().
dfPtr
double(CutoffFunction::* nnp::CutoffFunction::dfPtr) (double r) const private
Function pointer to df.
Definition at line 151 of file CutoffFunction.h.
Referenced by df(), and setCutoffType().
fdfPtr
void(CutoffFunction::* nnp::CutoffFunction::fdfPtr) (double r, double &fc, double &dfc) const private
Function pointer to fdf.
Definition at line 153 of file CutoffFunction.h.
Referenced by fdf(), and setCutoffType().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/CutoffFunction.h
/home/runner/work/n2p2/n2p2/src/libnnp/CutoffFunction.cpp