n2p2 - A neural network potential package: nnp::ScreeningFunction Class Reference
nnp::ScreeningFunction Class Reference
A screening functions for use with electrostatics.
#include <ScreeningFunction.h>
Public Member Functions
ScreeningFunction ()
Constructor, initializes to #CoreFunction::Type::POLY2.
void setCoreFunction (CoreFunction::Type const type)
Set functional form of transition region.
void setCoreFunction (std::string const type)
Set functional form of transition region.
void setInnerOuter (double inner, double outer)
Set inner and outer limit of transition region.
CoreFunction::Type getCoreFunctionType () const
Getter for #type.
double getInner () const
Getter for inner.
double getOuter () const
Getter for outer.
void changeLengthUnits (double const conv)
Change length units of screening function.
double f (double r) const
Screening function \(f_\text{screen}\).
double df (double r) const
Derivative of screening function \(\frac{d f_\text{screen}}{d r}\).
void fdf (double r, double &fr, double &dfr) const
Calculate screening function and derivative at once.
std::vector< std::string > info () const
Get string with information of screening function.
Private Attributes
double inner
Inner radius where transition region starts.
double outer
Outer radius where transition region ends.
double scale
Inverse width.
CoreFunction core
Core function to be used in the transition region.
Detailed Description
A screening functions for use with electrostatics.
Definition at line 26 of file ScreeningFunction.h.
Constructor & Destructor Documentation
ScreeningFunction()
ScreeningFunction::ScreeningFunction ()
Constructor, initializes to #CoreFunction::Type::POLY2.
Definition at line 24 of file ScreeningFunction.cpp.
                                     : inner(0.0),
                                         outer(0.0),
                                         scale(0.0)
{
    core.setType(CoreFunction::Type::POLY2);
}
References core, nnp::CoreFunction::POLY2, and nnp::CoreFunction::setType().
Member Function Documentation
setCoreFunction() [1/2]
void nnp::ScreeningFunction::setCoreFunction (CoreFunction::Type const type) inline
Set functional form of transition region.
Parameters
[in] type Type of core function to use.
Definition at line 113 of file ScreeningFunction.h.
{
    core.setType(type);
    return;
}
References core, and nnp::CoreFunction::setType().
Referenced by nnp::Mode::setupElectrostatics().
setCoreFunction() [2/2]
void nnp::ScreeningFunction::setCoreFunction (std::string const type) inline
Set functional form of transition region.
Parameters
[in] typeString Type (string version) of core function to use.
Definition at line 120 of file ScreeningFunction.h.
{
    core.setType(typeString);
    return;
}
References core, and nnp::CoreFunction::setType().
setInnerOuter()
void ScreeningFunction::setInnerOuter (double inner, double outer)
Set inner and outer limit of transition region.
Parameters
[in] inner Inner radius where transition region begins.
[in] outer Outer radius where transition region ends.
Definition at line 31 of file ScreeningFunction.cpp.
{
    if (inner >= outer)
    {
        throw invalid_argument("ERROR: Inner radius of transition region >= "
                               "outer radius.\n");
    }
    this->inner  = inner;
    this->outer  = outer;
    this->scale  = 1.0 / (outer - inner);
    return;
}
References inner, outer, and scale.
Referenced by nnp::Mode::setupElectrostatics().
getCoreFunctionType()
CoreFunction::Type nnp::ScreeningFunction::getCoreFunctionType () const inline
Getter for #type.
Returns
Type used.
Definition at line 127 of file ScreeningFunction.h.
{
    return core.getType();
}
References core, and nnp::CoreFunction::getType().
getInner()
double nnp::ScreeningFunction::getInner () const inline
Getter for inner.
Returns
Inner radius where transition region starts.
Definition at line 132 of file ScreeningFunction.h.
{ return inner; }
References inner.
getOuter()
double nnp::ScreeningFunction::getOuter () const inline
Getter for outer.
Returns
Outer radius where transition region ends.
Definition at line 133 of file ScreeningFunction.h.
{ return outer; }
References outer.
Referenced by nnp::Structure::calculateElectrostaticEnergyDerivatives(), nnp::Training::calculateNeighborLists(), nnp::Structure::calculateScreeningEnergy(), nnp::Mode::evaluateNNP(), nnp::InterfaceLammps::finalizeNeighborList(), nnp::InterfaceLammps::getMaxCutoffRadiusOverall(), and nnp::Mode::setupCutoffMatrix().
changeLengthUnits()
void ScreeningFunction::changeLengthUnits (double const conv)
Change length units of screening function.
Parameters
conv Multiplicative conversion factor.
Definition at line 46 of file ScreeningFunction.cpp.
{
    inner *= conv;
    outer *= conv;
    scale /= conv;
}
References inner, outer, and scale.
Referenced by nnp::Mode::setupElectrostatics().
f()
double nnp::ScreeningFunction::f (double r) const inline
Screening function \(f_\text{screen}\).
Parameters
[in] r Radius argument.
Returns
Function value.
Definition at line 135 of file ScreeningFunction.h.
{
    if      (r >= outer) return 1.0;
    else if (r <= inner) return 0.0;
    else return 1.0 - core.f((r - inner) * scale);
}
References core, nnp::CoreFunction::f(), inner, outer, and scale.
Referenced by nnp::Structure::calculateElectrostaticEnergyDerivatives(), and nnp::Structure::calculateScreeningEnergy().
df()
double nnp::ScreeningFunction::df (double r) const inline
Derivative of screening function \(\frac{d f_\text{screen}}{d r}\).
Parameters
[in] r Radius argument.
Returns
Value of function derivative.
Definition at line 142 of file ScreeningFunction.h.
{
    if (r >= outer || r <= inner) return 0.0;
    else return -scale * core.df((r - inner) * scale);
}
References core, nnp::CoreFunction::df(), inner, outer, and scale.
Referenced by nnp::Structure::calculateElectrostaticEnergyDerivatives().
fdf()
void nnp::ScreeningFunction::fdf (double r, double & fr, double & dfr) const inline
Calculate screening function and derivative at once.
Parameters
[in] r Radius argument.
[out] fr Screening function value.
[out] dfr Value of screening function derivative.
Definition at line 148 of file ScreeningFunction.h.
{
    if (r >= outer)
    {
        fr = 1.0;
        dfr = 0.0;
    }
    else if (r <= inner)
    {
        fr = 0.0;
        dfr = 0.0;
    }
    else
    {
        core.fdf((r - inner) * scale, fr, dfr);
        fr = 1.0 - fr;
        dfr = -scale * dfr;
    }
    return;
}
References core, nnp::CoreFunction::fdf(), inner, outer, and scale.
info()
vector< string > ScreeningFunction::info () const
Get string with information of screening function.
Returns
Information string.
Definition at line 52 of file ScreeningFunction.cpp.
{
    vector<string> v;
    v.push_back("Screening function information:\n");
    v.push_back(strpr("Inner radius : %16.8E\n", inner));
    v.push_back(strpr("Outer radius : %16.8E\n", outer));
    v.push_back("Transition region functional form:\n");
    v.push_back("x     := (r - inner) / (outer - inner)\n");
    v.push_back("fs(x) := 1 - f(x)\n");
    vector<string> ci = core.info();
    v.insert(v.end(), ci.begin(), ci.end());
    return v;
}
References core, nnp::CoreFunction::info(), inner, outer, and nnp::strpr().
Referenced by nnp::Mode::setupElectrostatics().
Member Data Documentation
inner
double nnp::ScreeningFunction::inner private
Inner radius where transition region starts.
Definition at line 99 of file ScreeningFunction.h.
Referenced by changeLengthUnits(), df(), f(), fdf(), getInner(), info(), and setInnerOuter().
outer
double nnp::ScreeningFunction::outer private
Outer radius where transition region ends.
Definition at line 101 of file ScreeningFunction.h.
Referenced by changeLengthUnits(), df(), f(), fdf(), getOuter(), info(), and setInnerOuter().
scale
double nnp::ScreeningFunction::scale private
Inverse width.
Definition at line 103 of file ScreeningFunction.h.
Referenced by changeLengthUnits(), df(), f(), fdf(), and setInnerOuter().
core
CoreFunction nnp::ScreeningFunction::core private
Core function to be used in the transition region.
Definition at line 105 of file ScreeningFunction.h.
Referenced by df(), f(), fdf(), getCoreFunctionType(), info(), ScreeningFunction(), and setCoreFunction().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/ScreeningFunction.h
/home/runner/work/n2p2/n2p2/src/libnnp/ScreeningFunction.cpp