n2p2 - A neural network potential package: nnp::EwaldTruncKolafaFixR Class Reference
nnp::EwaldTruncKolafaFixR Class Reference
#include <EwaldTruncKolafaFixR.h>
Public Member Functions
void calculateParameters (EwaldGlobalSettings const &settings, EwaldStructureData const &sData, EwaldParameters &params) override
bool publishedNewCutoffs () override
bool isEstimateReliable (EwaldGlobalSettings const &settings, EwaldParameters const &params) const override
Public Member Functions inherited from nnp::IEwaldTrunc
virtual void calculateParameters (EwaldGlobalSettings const &settings, EwaldStructureData const &sData, EwaldParameters &params)=0
virtual bool publishedNewCutoffs ()=0
virtual bool isEstimateReliable (EwaldGlobalSettings const &settings, EwaldParameters const &params) const =0
virtual ~IEwaldTrunc ()=default
Private Member Functions
double calculateEta (double const rCut, double const prec) const
double calculateKCut (double const eta, double const prec) const
void calculateC (double const qMax)
Private Attributes
double volume = 0.0
double fourPiEps = 1.0
std::size_t numAtoms = 0
bool newCutoffs = true
bool newCutoffsWerePublished = false
double C = 0.0
Detailed Description
Definition at line 13 of file EwaldTruncKolafaFixR.h.
Member Function Documentation
calculateParameters()
void nnp::EwaldTruncKolafaFixR::calculateParameters (EwaldGlobalSettings const & settings, EwaldStructureData const & sData, EwaldParameters & params) override virtual
Implements nnp::IEwaldTrunc.
Definition at line 12 of file EwaldTruncKolafaFixR.cpp.
    {
        size_t N = sData.getNumAtoms();
        double V = sData.getVolume();
        newCutoffs = (V != volume || N != numAtoms);
        if (!newCutoffs) return;
        newCutoffsWerePublished = false;
        volume = V;
        fourPiEps = settings.fourPiEps;
        numAtoms = N;
        double rCut = params.rCut;
        if (rCut == 0.0)
            throw std::runtime_error("ERROR: Real space cutoff of Ewald "
                                     "summation cannot be zero.");
        calculateC(settings.maxCharge);
        params.eta = calculateEta(rCut, settings.precision);
        params.kCut = calculateKCut(params.eta, settings.precision);
        return;
    }
References calculateC(), calculateEta(), calculateKCut(), nnp::EwaldParameters::eta, fourPiEps, nnp::EwaldGlobalSettings::fourPiEps, nnp::EwaldStructureData::getNumAtoms(), nnp::EwaldStructureData::getVolume(), nnp::EwaldParameters::kCut, nnp::EwaldGlobalSettings::maxCharge, newCutoffs, newCutoffsWerePublished, numAtoms, nnp::EwaldGlobalSettings::precision, nnp::EwaldParameters::rCut, and volume.
publishedNewCutoffs()
bool nnp::EwaldTruncKolafaFixR::publishedNewCutoffs () override virtual
Implements nnp::IEwaldTrunc.
Definition at line 36 of file EwaldTruncKolafaFixR.cpp.
    {
        bool answer = newCutoffsWerePublished;
        newCutoffsWerePublished = true;
        return answer;
    }
References newCutoffsWerePublished.
isEstimateReliable()
bool nnp::EwaldTruncKolafaFixR::isEstimateReliable (EwaldGlobalSettings const & settings, EwaldParameters const & params) const override virtual
Implements nnp::IEwaldTrunc.
Definition at line 42 of file EwaldTruncKolafaFixR.cpp.
    {
        return params.eta >= settings.maxQSigma;
    }
References nnp::EwaldParameters::eta, and nnp::EwaldGlobalSettings::maxQSigma.
calculateEta()
double nnp::EwaldTruncKolafaFixR::calculateEta (double const rCut, double const prec) const private
Definition at line 49 of file EwaldTruncKolafaFixR.cpp.
    {
        double x = sqrt(rCut/2) * prec / C;
        if (x >= 1.0)
            throw runtime_error("ERROR: Bad Ewald precision settings, try a "
                                "smaller value.");
        return rCut / sqrt(-2 * log(x));
    }
References C.
Referenced by calculateParameters().
calculateKCut()
double nnp::EwaldTruncKolafaFixR::calculateKCut (double const eta, double const prec) const private
Definition at line 59 of file EwaldTruncKolafaFixR.cpp.
    {
        double constexpr acceptError = 1.e-10;
        double relXError = 1.0;
        double relYError = 1.0;
        double y = eta * prec / (sqrt(2) * C);
        double kCut = 1.0/eta;
        double kCutOld;
        while (relXError > acceptError || relYError > acceptError)
        {
            kCutOld = kCut;
            kCut -= 2 * kCut / (1 + 2*pow(kCut * eta,2.0))
                    * (-1 + sqrt(kCut) * exp(pow(kCut * eta,2.0)/2) * y);
            // If kCut becomes negative, start with smaller value.
            if (kCut <= 0)
            {
                kCut = kCutOld / 2;
                continue;
            }
            relXError = abs((kCut - kCutOld) / kCut);
            relYError = abs((1/sqrt(kCut)
                        * exp(-pow(kCut * eta,2.0) / 2) - y) / y);
        }
        return kCut;
    }
References C.
Referenced by calculateParameters().
calculateC()
void nnp::EwaldTruncKolafaFixR::calculateC (double const qMax) private
Definition at line 88 of file EwaldTruncKolafaFixR.cpp.
    {
        C = 2 * pow(qMax,2.0) * sqrt(numAtoms/volume) / fourPiEps;
    }
References C, fourPiEps, numAtoms, and volume.
Referenced by calculateParameters().
Member Data Documentation
volume
double nnp::EwaldTruncKolafaFixR::volume = 0.0 private
Definition at line 25 of file EwaldTruncKolafaFixR.h.
Referenced by calculateC(), and calculateParameters().
fourPiEps
double nnp::EwaldTruncKolafaFixR::fourPiEps = 1.0 private
Definition at line 26 of file EwaldTruncKolafaFixR.h.
Referenced by calculateC(), and calculateParameters().
numAtoms
std::size_t nnp::EwaldTruncKolafaFixR::numAtoms = 0 private
Definition at line 27 of file EwaldTruncKolafaFixR.h.
Referenced by calculateC(), and calculateParameters().
newCutoffs
bool nnp::EwaldTruncKolafaFixR::newCutoffs = true private
Definition at line 28 of file EwaldTruncKolafaFixR.h.
Referenced by calculateParameters().
newCutoffsWerePublished
bool nnp::EwaldTruncKolafaFixR::newCutoffsWerePublished = false private
Definition at line 29 of file EwaldTruncKolafaFixR.h.
Referenced by calculateParameters(), and publishedNewCutoffs().
C
double nnp::EwaldTruncKolafaFixR::C = 0.0 private
Definition at line 31 of file EwaldTruncKolafaFixR.h.
Referenced by calculateC(), calculateEta(), and calculateKCut().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldTruncKolafaFixR.h
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldTruncKolafaFixR.cpp