n2p2 - A neural network potential package: nnp::KspaceGrid Class Reference
nnp::KspaceGrid Class Reference
#include <Kspace.h>
Public Member Functions
KspaceGrid ()
Constructor.
void setup (Vec3D box[3], EwaldSetup &ewaldSetup)
Set up reciprocal box vectors and eta.
Public Attributes
double eta
Ewald summation eta parameter.
double kCut
Cutoff in reciprocal space.
double rCut
Cutoff in real space.
double volume
Volume of real box.
double pre
Ewald sum prefactor \(\frac{2\pi}{V}\).
int n [3]
Required box copies in each box vector direction.
Vec3D kbox [3]
Reciprocal box vectors.
std::vector< Kvector > kvectors
Vector containing all k-vectors.
Private Member Functions
void calculatePbcCopies (double cutoffRadius)
Compute box copies in each direction.
Detailed Description
Definition at line 43 of file Kspace.h.
Constructor & Destructor Documentation
KspaceGrid()
KspaceGrid::KspaceGrid ()
Constructor.
Definition at line 38 of file Kspace.cpp.
                       : eta   (0.0),
                           kCut  (0.0),
                           volume(0.0),
                           pre   (0.0)
{
}
Member Function Documentation
setup()
void KspaceGrid::setup (Vec3D box[3], EwaldSetup & ewaldSetup)
Set up reciprocal box vectors and eta.
Parameters
[in] box Real box vectors.
[in] ewaldSetup Settings of ewald summation.
Definition at line 45 of file Kspace.cpp.
{
    volume = fabs(box[0] * (box[1].cross(box[2])));
    pre = 2.0 * M_PI / volume;
    kbox[0] = pre * box[1].cross(box[2]);
    kbox[1] = pre * box[2].cross(box[0]);
    kbox[2] = pre * box[0].cross(box[1]);
    eta = ewaldSetup.params.eta;
    kCut = ewaldSetup.params.kCut;
    // Compute box copies required in each direction.
    calculatePbcCopies(kCut);
    // Compute k-grid (only half sphere because of symmetry)
    for (int i = 0; i <= n[0]; ++i)
    {
        int sj = -n[1];
        if (i == 0) sj = 0;
        for (int j = sj; j <= n[1]; ++j)
        {
            int sk = -n[2];
            if (i == 0 && j == 0) sk = 0;
            for (int k = sk; k <= n[2]; ++k)
            {
                if (i == 0 && j == 0 && k == 0) continue;
                Vec3D kv = i * kbox[0] + j * kbox[1] + k * kbox[2];
                double knorm2 = kv.norm2();
                if (kv.norm2() < kCut * kCut)
                {
                    kvectors.push_back(kv);
                    kvectors.back().knorm2 = knorm2; // TODO: Really necessary?
                    kvectors.back().coeff = exp(-0.5 * eta * eta * knorm2)
                                          * 2.0 * pre / knorm2;
                }
            }
        }
    }
}
References calculatePbcCopies(), nnp::Vec3D::cross(), nnp::EwaldParameters::eta, eta, kbox, nnp::EwaldParameters::kCut, kCut, kvectors, n, nnp::Vec3D::norm2(), nnp::EwaldSetup::params, pre, and volume.
Referenced by nnp::Structure::calculateDAdrQ(), and nnp::Structure::calculateElectrostaticEnergy().
calculatePbcCopies()
void KspaceGrid::calculatePbcCopies (double cutoffRadius) private
Compute box copies in each direction.
Parameters
[in] cutoffRadius Cutoff radius.
TODO: This is code copy from Structure class!
Definition at line 86 of file Kspace.cpp.
{
    Vec3D axb;
    Vec3D axc;
    Vec3D bxc;
    axb = kbox[0].cross(kbox[1]).normalize();
    axc = kbox[0].cross(kbox[2]).normalize();
    bxc = kbox[1].cross(kbox[2]).normalize();
    double proja = fabs(kbox[0] * bxc);
    double projb = fabs(kbox[1] * axc);
    double projc = fabs(kbox[2] * axb);
    n[0] = 0;
    n[1] = 0;
    n[2] = 0;
    while (n[0] * proja <= cutoffRadius) n[0]++;
    while (n[1] * projb <= cutoffRadius) n[1]++;
    while (n[2] * projc <= cutoffRadius) n[2]++;
    return;
}
References nnp::Vec3D::cross(), kbox, n, and nnp::Vec3D::normalize().
Referenced by setup().
Member Data Documentation
eta
double nnp::KspaceGrid::eta
Ewald summation eta parameter.
Definition at line 47 of file Kspace.h.
Referenced by setup().
kCut
double nnp::KspaceGrid::kCut
Cutoff in reciprocal space.
Definition at line 49 of file Kspace.h.
Referenced by setup().
rCut
double nnp::KspaceGrid::rCut
Cutoff in real space.
Definition at line 51 of file Kspace.h.
volume
double nnp::KspaceGrid::volume
Volume of real box.
Definition at line 53 of file Kspace.h.
Referenced by setup().
pre
double nnp::KspaceGrid::pre
Ewald sum prefactor \(\frac{2\pi}{V}\).
Definition at line 55 of file Kspace.h.
Referenced by setup().
n
int nnp::KspaceGrid::n[3]
Required box copies in each box vector direction.
Definition at line 57 of file Kspace.h.
Referenced by calculatePbcCopies(), and setup().
kbox
Vec3D nnp::KspaceGrid::kbox[3]
Reciprocal box vectors.
Definition at line 59 of file Kspace.h.
Referenced by calculatePbcCopies(), and setup().
kvectors
std::vector<Kvector> nnp::KspaceGrid::kvectors
Vector containing all k-vectors.
Definition at line 61 of file Kspace.h.
Referenced by nnp::Structure::calculateDAdrQ(), nnp::Structure::calculateElectrostaticEnergy(), and setup().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/Kspace.h
/home/runner/work/n2p2/n2p2/src/libnnp/Kspace.cpp