n2p2 - A neural network potential package: LAMMPS_NS::PairNNP Class Reference
LAMMPS_NS::PairNNP Class Reference
#include <pair_nnp.h>
Public Member Functions
PairNNP (class LAMMPS *)
virtual ~PairNNP ()
virtual void compute (int, int)
virtual void settings (int, char **)
virtual void coeff (int, char **)
virtual void init_style ()
virtual double init_one (int, int)
virtual void write_restart (FILE *)
virtual void read_restart (FILE *)
virtual void write_restart_settings (FILE *)
virtual void read_restart_settings (FILE *)
Protected Member Functions
virtual void allocate ()
void transferNeighborList ()
void handleExtrapolationWarnings ()
Protected Attributes
bool showew
bool resetew
int showewsum
int maxew
long numExtrapolationWarningsTotal
long numExtrapolationWarningsSummary
double cflength
double cfenergy
double maxCutoffRadius
char * directory
char * emap
nnp::InterfaceLammps interface
Detailed Description
Definition at line 21 of file pair_nnp.h.
Constructor & Destructor Documentation
PairNNP()
PairNNP::PairNNP (class LAMMPS * lmp)
Definition at line 24 of file pair_nnp.cpp.
                            : Pair(lmp)
{
}
~PairNNP()
PairNNP::~PairNNP () virtual
Definition at line 32 of file pair_nnp.cpp.
{
}
Member Function Documentation
compute()
void PairNNP::compute (int eflag, int vflag) virtual
Definition at line 38 of file pair_nnp.cpp.
{
  if(eflag || vflag) ev_setup(eflag,vflag);
  else evflag = vflag_fdotr = eflag_global = eflag_atom = 0;
  // Set number of local atoms and add element.
  interface.setLocalAtoms(atom->nlocal,atom->type);
  // Transfer tags separately. Interface::setLocalTags is overloaded internally
  // to work with both -DLAMMPS_SMALLBIG (tagint = int) and -DLAMMPS_BIGBIG
  // (tagint = int64_t)
  interface.setLocalTags(atom->tag);
  // Transfer local neighbor list to NNP interface.
  transferNeighborList();
  // Compute symmetry functions, atomic neural networks and add up energy.
  interface.process();
  // Do all stuff related to extrapolation warnings.
  if(showew == true || showewsum > 0 || maxew >= 0) {
    handleExtrapolationWarnings();
  }
  // Calculate forces of local and ghost atoms.
  interface.getForces(atom->f);
  // Add energy contribution to total energy.
  if (eflag_global)
     ev_tally(0,0,atom->nlocal,1,interface.getEnergy(),0.0,0.0,0.0,0.0,0.0);
  // Add atomic energy if requested (CAUTION: no physical meaning!).
  if (eflag_atom)
    for (int i = 0; i < atom->nlocal; ++i)
      eatom[i] = interface.getAtomicEnergy(i);
  // If virial needed calculate via F dot r.
  if (vflag_fdotr) virial_fdotr_compute();
}
References nnp::InterfaceLammps::getAtomicEnergy(), nnp::InterfaceLammps::getEnergy(), nnp::InterfaceLammps::getForces(), handleExtrapolationWarnings(), interface, maxew, nnp::InterfaceLammps::process(), nnp::InterfaceLammps::setLocalAtoms(), nnp::InterfaceLammps::setLocalTags(), showew, showewsum, and transferNeighborList().
settings()
void PairNNP::settings (int narg, char ** arg) virtual
Definition at line 81 of file pair_nnp.cpp.
{
  int iarg = 0;
  if (narg == 0) error->all(FLERR,"Illegal pair_style command");
  // default settings
  int len = strlen("nnp/") + 1;
  directory = new char[len];
  strcpy(directory,"nnp/");
  showew = true;
  showewsum = 0;
  maxew = 0;
  resetew = false;
  cflength = 1.0;
  cfenergy = 1.0;
  len = strlen("") + 1;
  emap = new char[len];
  strcpy(emap,"");
  numExtrapolationWarningsTotal = 0;
  numExtrapolationWarningsSummary = 0;
  while(iarg < narg) {
    // set NNP directory
    if (strcmp(arg[iarg],"dir") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      delete[] directory;
      len = strlen(arg[iarg+1]) + 2;
      directory = new char[len];
      sprintf(directory, "%s/", arg[iarg+1]);
      iarg += 2;
    // element mapping
    } else if (strcmp(arg[iarg],"emap") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      delete[] emap;
      len = strlen(arg[iarg+1]) + 1;
      emap = new char[len];
      sprintf(emap, "%s", arg[iarg+1]);
      iarg += 2;
    // show extrapolation warnings
    } else if (strcmp(arg[iarg],"showew") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      if (strcmp(arg[iarg+1],"yes") == 0)
        showew = true;
      else if (strcmp(arg[iarg+1],"no") == 0)
        showew = false;
      else
        error->all(FLERR,"Illegal pair_style command");
      iarg += 2;
    // show extrapolation warning summary
    } else if (strcmp(arg[iarg],"showewsum") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      showewsum = utils::inumeric(FLERR,arg[iarg+1],false,lmp);
      iarg += 2;
    // maximum allowed extrapolation warnings
    } else if (strcmp(arg[iarg],"maxew") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      maxew = utils::inumeric(FLERR,arg[iarg+1],false,lmp);
      iarg += 2;
    // reset extrapolation warning counter
    } else if (strcmp(arg[iarg],"resetew") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      if (strcmp(arg[iarg+1],"yes") == 0)
        resetew = true;
      else if (strcmp(arg[iarg+1],"no") == 0)
        resetew = false;
      else
        error->all(FLERR,"Illegal pair_style command");
      iarg += 2;
    // length unit conversion factor
    } else if (strcmp(arg[iarg],"cflength") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      cflength = utils::numeric(FLERR,arg[iarg+1],false,lmp);
      iarg += 2;
    // energy unit conversion factor
    } else if (strcmp(arg[iarg],"cfenergy") == 0) {
      if (iarg+2 > narg)
        error->all(FLERR,"Illegal pair_style command");
      cfenergy = utils::numeric(FLERR,arg[iarg+1],false,lmp);
      iarg += 2;
    } else error->all(FLERR,"Illegal pair_style command");
  }
}
References cfenergy, cflength, directory, emap, maxew, numExtrapolationWarningsSummary, numExtrapolationWarningsTotal, resetew, showew, and showewsum.
coeff()
void PairNNP::coeff (int narg, char ** arg) virtual
Definition at line 176 of file pair_nnp.cpp.
{
  if (!allocated) allocate();
  if (narg != 3) error->all(FLERR,"Incorrect args for pair coefficients");
  int ilo,ihi,jlo,jhi;
  utils::bounds(FLERR,arg[0],1,atom->ntypes,ilo,ihi,error);
  utils::bounds(FLERR,arg[1],1,atom->ntypes,jlo,jhi,error);
  maxCutoffRadius = utils::numeric(FLERR,arg[2],false,lmp);
  // TODO: Check how this flag is set.
  int count = 0;
  for(int i=ilo; i<=ihi; i++) {
    for(int j=MAX(jlo,i); j<=jhi; j++) {
      setflag[i][j] = 1;
      count++;
    }
  }
  if (count == 0) error->all(FLERR,"Incorrect args for pair coefficients");
}
References allocate(), and maxCutoffRadius.
init_style()
void PairNNP::init_style () virtual
Definition at line 204 of file pair_nnp.cpp.
{
  int irequest = neighbor->request((void *) this);
  neighbor->requests[irequest]->pair = 1;
  neighbor->requests[irequest]->half = 0;
  neighbor->requests[irequest]->full = 1;
  // Return immediately if NNP setup is already completed.
  if (interface.isInitialized()) return;
  // Activate screen and logfile output only for rank 0.
  if (comm->me == 0) {
    if (lmp->screen != NULL)
      interface.log.registerCFilePointer(&(lmp->screen));
    if (lmp->logfile != NULL)
      interface.log.registerCFilePointer(&(lmp->logfile));
  }
  // Initialize interface on all processors.
  interface.initialize(directory,
                       emap,
                       showew,
                       resetew,
                       showewsum,
                       maxew,
                       cflength,
                       cfenergy,
                       maxCutoffRadius,
                       atom->ntypes,
                       comm->me);
  // LAMMPS cutoff radius (given via pair_coeff) should not be smaller than
  // maximum symmetry function cutoff radius.
  if (maxCutoffRadius < interface.getMaxCutoffRadius())
    error->all(FLERR,"Inconsistent cutoff radius");
}
References cfenergy, cflength, directory, emap, nnp::InterfaceLammps::getMaxCutoffRadius(), nnp::InterfaceLammps::initialize(), interface, nnp::InterfaceLammps::isInitialized(), nnp::Mode::log, maxCutoffRadius, maxew, nnp::Log::registerCFilePointer(), resetew, showew, and showewsum.
init_one()
double PairNNP::init_one (int i, int j) virtual
Definition at line 245 of file pair_nnp.cpp.
{
  // TODO: Check how this actually works for different cutoffs.
  return maxCutoffRadius;
}
References maxCutoffRadius.
write_restart()
void PairNNP::write_restart (FILE * fp) virtual
Definition at line 255 of file pair_nnp.cpp.
{
    return;
}
read_restart()
void PairNNP::read_restart (FILE * fp) virtual
Definition at line 264 of file pair_nnp.cpp.
{
    return;
}
write_restart_settings()
void PairNNP::write_restart_settings (FILE * fp) virtual
Definition at line 273 of file pair_nnp.cpp.
{
    return;
}
read_restart_settings()
void PairNNP::read_restart_settings (FILE * fp) virtual
Definition at line 282 of file pair_nnp.cpp.
{
    return;
}
allocate()
void PairNNP::allocate () protected virtual
Definition at line 291 of file pair_nnp.cpp.
{
  allocated = 1;
  int n = atom->ntypes;
  memory->create(setflag,n+1,n+1,"pair:setflag");
  for (int i = 1; i <= n; i++)
    for (int j = i; j <= n; j++)
      setflag[i][j] = 0;
  memory->create(cutsq,n+1,n+1,"pair:cutsq");
}
Referenced by coeff().
transferNeighborList()
void PairNNP::transferNeighborList () protected
Definition at line 304 of file pair_nnp.cpp.
{
  // Transfer neighbor list to NNP.
  double rc2 = maxCutoffRadius * maxCutoffRadius;
  for (int ii = 0; ii < list->inum; ++ii) {
    int i = list->ilist[ii];
    for (int jj = 0; jj < list->numneigh[i]; ++jj) {
      int j = list->firstneigh[i][jj];
      j &= NEIGHMASK;
      double dx = atom->x[i][0] - atom->x[j][0];
      double dy = atom->x[i][1] - atom->x[j][1];
      double dz = atom->x[i][2] - atom->x[j][2];
      double d2 = dx * dx + dy * dy + dz * dz;
      if (d2 <= rc2) {
        // atom->tag[j] will be implicitly converted to int64_t internally.
        interface.addNeighbor(i,j,atom->tag[j],atom->type[j],dx,dy,dz,d2);
      }
    }
  }
}
References nnp::InterfaceLammps::addNeighbor(), interface, and maxCutoffRadius.
Referenced by compute().
handleExtrapolationWarnings()
void PairNNP::handleExtrapolationWarnings () protected
Definition at line 325 of file pair_nnp.cpp.
{
  // Get number of extrapolation warnings for local atoms.
  // TODO: Is the conversion from std::size_t to long ok?
  long numCurrentEW = (long)interface.getNumExtrapolationWarnings();
  // Update (or set, resetew == true) total warnings counter.
  if (resetew) numExtrapolationWarningsTotal = numCurrentEW;
  else numExtrapolationWarningsTotal += numCurrentEW;
  // Update warnings summary counter.
  if(showewsum > 0) {
    numExtrapolationWarningsSummary += numCurrentEW;
  }
  // If requested write extrapolation warnings.
  // Requires communication of all symmetry functions statistics entries to
  // rank 0.
  if(showew > 0) {
    // First collect an overview of extrapolation warnings per process.
    long* numEWPerProc = NULL;
    if(comm->me == 0) numEWPerProc = new long[comm->nprocs];
    MPI_Gather(&numCurrentEW, 1, MPI_LONG, numEWPerProc, 1, MPI_LONG, 0, world);
    if(comm->me == 0) {
      for(int i=1;i<comm->nprocs;i++) {
        if(numEWPerProc[i] > 0) {
          long bs = 0;
          MPI_Status ms;
          // Get buffer size.
          MPI_Recv(&bs, 1, MPI_LONG, i, 0, world, &ms);
          char* buf = new char[bs];
          // Receive buffer.
          MPI_Recv(buf, bs, MPI_BYTE, i, 0, world, &ms);
          interface.extractEWBuffer(buf, bs);
          delete[] buf;
        }
      }
      interface.writeExtrapolationWarnings();
    }
    else if(numCurrentEW > 0) {
      // Get desired buffer length for all extrapolation warning entries.
      long bs = interface.getEWBufferSize();
      // Allocate and fill buffer.
      char* buf = new char[bs];
      interface.fillEWBuffer(buf, bs);
      // Send buffer size and buffer.
      MPI_Send(&bs, 1, MPI_LONG, 0, 0, world);
      MPI_Send(buf, bs, MPI_BYTE, 0, 0, world);
      delete[] buf;
    }
    if(comm->me == 0) delete[] numEWPerProc;
  }
  // If requested gather number of warnings to display summary.
  if(showewsum > 0 && update->ntimestep % showewsum == 0) {
    long globalEW = 0;
    // Communicate the sum over all processors to proc 0.
    MPI_Reduce(&numExtrapolationWarningsSummary,
               &globalEW, 1, MPI_LONG, MPI_SUM, 0, world);
    // Write to screen or logfile.
    if(comm->me == 0) {
      if(screen) {
        fprintf(screen,
                "### NNP EW SUMMARY ### TS: %10ld EW %10ld EWPERSTEP %10.3E\n",
                update->ntimestep,
                globalEW,
                double(globalEW) / showewsum);
      }
      if(logfile) {
        fprintf(logfile,
                "### NNP EW SUMMARY ### TS: %10ld EW %10ld EWPERSTEP %10.3E\n",
                update->ntimestep,
                globalEW,
                double(globalEW) / showewsum);
      }
    }
    // Reset summary counter.
    numExtrapolationWarningsSummary = 0;
  }
  // Stop if maximum number of extrapolation warnings is exceeded.
  if (numExtrapolationWarningsTotal > maxew) {
    error->one(FLERR,"Too many extrapolation warnings");
  }
  // Reset internal extrapolation warnings counters.
  interface.clearExtrapolationWarnings();
}
References nnp::InterfaceLammps::clearExtrapolationWarnings(), nnp::InterfaceLammps::extractEWBuffer(), nnp::InterfaceLammps::fillEWBuffer(), nnp::InterfaceLammps::getEWBufferSize(), nnp::Mode::getNumExtrapolationWarnings(), interface, maxew, numExtrapolationWarningsSummary, numExtrapolationWarningsTotal, resetew, showew, showewsum, and nnp::InterfaceLammps::writeExtrapolationWarnings().
Referenced by compute().
Member Data Documentation
showew
bool LAMMPS_NS::PairNNP::showew protected
Definition at line 43 of file pair_nnp.h.
Referenced by compute(), handleExtrapolationWarnings(), init_style(), and settings().
resetew
bool LAMMPS_NS::PairNNP::resetew protected
Definition at line 44 of file pair_nnp.h.
Referenced by handleExtrapolationWarnings(), init_style(), and settings().
showewsum
int LAMMPS_NS::PairNNP::showewsum protected
Definition at line 45 of file pair_nnp.h.
Referenced by compute(), handleExtrapolationWarnings(), init_style(), and settings().
maxew
int LAMMPS_NS::PairNNP::maxew protected
Definition at line 46 of file pair_nnp.h.
Referenced by compute(), handleExtrapolationWarnings(), init_style(), and settings().
numExtrapolationWarningsTotal
long LAMMPS_NS::PairNNP::numExtrapolationWarningsTotal protected
Definition at line 47 of file pair_nnp.h.
Referenced by handleExtrapolationWarnings(), and settings().
numExtrapolationWarningsSummary
long LAMMPS_NS::PairNNP::numExtrapolationWarningsSummary protected
Definition at line 48 of file pair_nnp.h.
Referenced by handleExtrapolationWarnings(), and settings().
cflength
double LAMMPS_NS::PairNNP::cflength protected
Definition at line 49 of file pair_nnp.h.
Referenced by init_style(), and settings().
cfenergy
double LAMMPS_NS::PairNNP::cfenergy protected
Definition at line 50 of file pair_nnp.h.
Referenced by init_style(), and settings().
maxCutoffRadius
double LAMMPS_NS::PairNNP::maxCutoffRadius protected
Definition at line 51 of file pair_nnp.h.
Referenced by coeff(), init_one(), init_style(), and transferNeighborList().
directory
char* LAMMPS_NS::PairNNP::directory protected
Definition at line 52 of file pair_nnp.h.
Referenced by init_style(), and settings().
emap
char* LAMMPS_NS::PairNNP::emap protected
Definition at line 53 of file pair_nnp.h.
Referenced by init_style(), and settings().
interface
nnp::InterfaceLammps LAMMPS_NS::PairNNP::interface protected
Definition at line 54 of file pair_nnp.h.
Referenced by compute(), handleExtrapolationWarnings(), init_style(), and transferNeighborList().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/interface/LAMMPS/src/USER-NNP/pair_nnp.h
/home/runner/work/n2p2/n2p2/src/interface/LAMMPS/src/USER-NNP/pair_nnp.cpp