n2p2 - A neural network potential package: nnp::SymGrpCompRadWeighted Class Reference
nnp::SymGrpCompRadWeighted Class Reference
Weighted radial symmetry function with compact support (type 23)
#include <SymGrpCompRadWeighted.h>
Public Member Functions
SymGrpCompRadWeighted (ElementMap const &elementMap)
Constructor, sets type = 23.
virtual bool operator== (SymGrp const &rhs) const
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const
Overload < operator.
virtual bool addMember (SymFnc const *const symmetryFunction)
Potentially add a member to group.
virtual void sortMembers ()
Sort member symmetry functions.
virtual void setScalingFactors ()
Fill scalingFactors with values from member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate all symmetry functions of this group for one atom.
virtual std::vector< std::string > parameterLines () const
Give symmetry function group parameters on multiple lines.
Public Member Functions inherited from nnp::SymGrpBaseComp
double getRmin () const
Getter for rmin.
double getRmax () const
Getter for rmax.
Public Member Functions inherited from nnp::SymGrp
virtual ~SymGrp ()
Virtual destructor.
bool operator!= (SymGrp const &rhs) const
Overload != operator.
bool operator> (SymGrp const &rhs) const
Overload > operator.
bool operator<= (SymGrp const &rhs) const
Overload <= operator.
bool operator>= (SymGrp const &rhs) const
Overload >= operator.
void setIndex (std::size_t index)
Set private index member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getType () const
Get private type member variable.
std::size_t getEc () const
Get private ec member variable.
Private Attributes
std::vector< SymFncCompRadWeighted const * > members
Vector of all group member pointers.
std::vector< double > mrl
Member rl.
std::vector< double > mrc
Member rc.
Additional Inherited Members
Protected Types inherited from nnp::SymGrp
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymGrpBaseComp
SymGrpBaseComp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
Protected Member Functions inherited from nnp::SymGrp
SymGrp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
std::string getPrintFormatCommon () const
Get common parameter line format string.
std::string getPrintFormatMember () const
Get member parameter line format string.
Static Protected Member Functions inherited from nnp::SymGrp
static const PrintFormat initializePrintFormat ()
Initialize static print format map for all possible parameters.
static const PrintOrder initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymGrpBaseComp
double rmin
Minimum radius within group.
double rmax
Maximum radius within group.
Protected Attributes inherited from nnp::SymGrp
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function group index.
std::size_t ec
Element index of center atom (common feature).
double convLength
Data set normalization length conversion factor.
std::vector< size_t > memberIndex
Vector containing indices of all member symmetry functions.
std::vector< double > scalingFactors
Scaling factors of all member symmetry functions.
std::set< std::string > parametersCommon
Set of common parameters IDs.
std::set< std::string > parametersMember
Set of common parameters IDs.
std::vector< std::vector< std::size_t > > memberIndexPerElement
Vector containing per-element indices of all member symmetry functions.
Static Protected Attributes inherited from nnp::SymGrp
static const PrintFormat printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static const PrintOrder printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Weighted radial symmetry function with compact support (type 23)
\[ G^{23}_i = \sum_{\substack{j \neq i}} Z_j C(r_{ij}, r_l, r_c) \]
where \(C(x, x_\text{low}, x_\text{high})\) is a function with compact support \(\left[x_\text{low}, x_\text{high}\right]\). \(Z_j\) is defined as the atomic number of the neighbor atom \(j\).
Common features:
element of central atom
Definition at line 48 of file SymGrpCompRadWeighted.h.
Constructor & Destructor Documentation
SymGrpCompRadWeighted()
SymGrpCompRadWeighted::SymGrpCompRadWeighted (ElementMap const & elementMap)
Constructor, sets type = 23.
Definition at line 32 of file SymGrpCompRadWeighted.cpp.
                                                     :
     SymGrpBaseComp(23, elementMap)
 {
 }
Member Function Documentation
operator==()
bool SymGrpCompRadWeighted::operator== (SymGrp const & rhs) const virtual
Overload == operator.
Implements nnp::SymGrp.
Definition at line 37 of file SymGrpCompRadWeighted.cpp.
 {
     if (ec   != rhs.getEc()  ) return false;
     if (type != rhs.getType()) return false;
     return true;
 }
References nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), and nnp::SymGrp::type.
operator<()
bool SymGrpCompRadWeighted::operator< (SymGrp const & rhs) const virtual
Overload < operator.
Implements nnp::SymGrp.
Definition at line 44 of file SymGrpCompRadWeighted.cpp.
 {
     if      (ec   < rhs.getEc()  ) return true;
     else if (ec   > rhs.getEc()  ) return false;
     if      (type < rhs.getType()) return true;
     else if (type > rhs.getType()) return false;
     return false;
 }
References nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), and nnp::SymGrp::type.
addMember()
bool SymGrpCompRadWeighted::addMember (SymFnc const *const symmetryFunction) virtual
Potentially add a member to group.
Parameters
[in] symmetryFunction Candidate symmetry function.
Returns
If addition was successful.
If symmetry function is compatible with common feature list its pointer will be added to members.
Implements nnp::SymGrp.
Definition at line 53 of file SymGrpCompRadWeighted.cpp.
 {
     if (symmetryFunction->getType() != type) return false;
     SymFncCompRadWeighted const* sf =
         dynamic_cast<SymFncCompRadWeighted const*>(symmetryFunction);
     if (members.empty())
     {
         ec          = sf->getEc();
         convLength  = sf->getConvLength();
     }
     if (sf->getEc()          != ec         ) return false;
     if (sf->getConvLength()  != convLength )
     {
         throw runtime_error("ERROR: Unable to add symmetry function members "
                             "with different conversion factors.\n");
     }
     if (sf->getRl() <= 0.0) rmin = 0.0;
     else rmin = min( rmin, sf->getRl() );
     rmax = max( rmax, sf->getRc() );
     members.push_back(sf);
     return true;
 }
References nnp::SymGrp::convLength, nnp::SymGrp::ec, nnp::SymFnc::getConvLength(), nnp::SymFnc::getEc(), nnp::SymFnc::getRc(), nnp::SymFncBaseComp::getRl(), nnp::SymFnc::getType(), members, nnp::SymGrpBaseComp::rmax, nnp::SymGrpBaseComp::rmin, and nnp::SymGrp::type.
sortMembers()
void SymGrpCompRadWeighted::sortMembers () virtual
Sort member symmetry functions.
Also allocate and precalculate additional stuff.
Implements nnp::SymGrp.
Definition at line 82 of file SymGrpCompRadWeighted.cpp.
 {
     sort(members.begin(),
          members.end(),
          comparePointerTargets<SymFncCompRadWeighted const>);
     for (size_t i = 0; i < members.size(); i++)
     {
         memberIndex.push_back(members[i]->getIndex());
         memberIndexPerElement.push_back(members[i]->getIndexPerElement());
     }
     mrl.resize(members.size(), 0.0);
     mrc.resize(members.size(), 0.0);
     for (size_t i = 0; i < members.size(); i++)
     {
         mrl.at(i) = members[i]->getRl();
         mrc.at(i) = members[i]->getRc();
     }
     return;
 }
References nnp::SymGrp::getIndex(), nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, mrc, and mrl.
setScalingFactors()
void SymGrpCompRadWeighted::setScalingFactors () virtual
Fill scalingFactors with values from member symmetry functions.
Implements nnp::SymGrp.
Definition at line 105 of file SymGrpCompRadWeighted.cpp.
 {
     scalingFactors.resize(members.size(), 0.0);
     for (size_t i = 0; i < members.size(); i++)
     {
         scalingFactors.at(i) = members[i]->getScalingFactor();
     }
     return;
 }
References members, and nnp::SymGrp::scalingFactors.
calculate()
void SymGrpCompRadWeighted::calculate (Atom & atom, bool const derivatives) const virtual
Calculate all symmetry functions of this group for one atom.
Parameters
[in,out] atom Atom for which symmetry functions are caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymGrp.
Definition at line 122 of file SymGrpCompRadWeighted.cpp.
 {
     double* result = new double[members.size()];
     for (size_t k = 0; k < members.size(); ++k)
     {
         result[k] = 0.0;
     }
     for (size_t j = 0; j < atom.numNeighbors; ++j)
     {
         Atom::Neighbor& n = atom.neighbors[j];
         double const rij = n.d;
         if (rij < rmax && rij > rmin)
         {
             // Energy calculation.
             double const* const d1 = n.dr.r;
             size_t const        ne = n.element;
             for (size_t k = 0; k < members.size(); ++k)
             {
                 SymFncCompRadWeighted const& sf = *(members[k]);
                 if (rij <= mrl[k] || rij >= mrc[k]) continue;
                 double rad;
                 double drad;
 #ifndef N2P2_NO_SF_CACHE
                 auto ci = sf.getCacheIndices();
                 if (ci[ne].size() == 0) sf.getCompactOnly(rij, rad, drad);
                 else
                 {
                     double& crad = n.cache[ci[ne][0]];
                     double& cdrad = n.cache[ci[ne][1]];
                     if (crad < 0) sf.getCompactOnly(rij, crad, cdrad);
                     rad = crad;
                     drad = cdrad;
                 }
 #else
                 sf.getCompactOnly(rij, rad, drad);
 #endif
                 result[k] += elementMap.atomicNumber(ne) * rad;
                 // Force calculation.
                 if (!derivatives || drad == 0.0) continue;
                 drad *= elementMap.atomicNumber(ne) * scalingFactors[k] / rij;
                 // SIMPLE EXPRESSIONS:
                 //Vec3D const dij = p1 * atom.neighbors[j].dr;
                 double const p1drijx = drad * d1[0];
                 double const p1drijy = drad * d1[1];
                 double const p1drijz = drad * d1[2];
                 // Save force contributions in Atom storage.
 #ifndef N2P2_FULL_SFD_MEMORY
                 size_t ki = memberIndex[k];
 #else
                 size_t const ki = memberIndex[k];
 #endif
                 // SIMPLE EXPRESSIONS:
                 //atom.dGdr[ki]              += dij;
                 //atom.neighbors[j].dGdr[ki] -= dij;
                 double* dGdr = atom.dGdr[ki].r;
                 dGdr[0] += p1drijx;
                 dGdr[1] += p1drijy;
                 dGdr[2] += p1drijz;
 #ifndef N2P2_FULL_SFD_MEMORY
                 ki = memberIndexPerElement[k][ne];
 #endif
                 dGdr = n.dGdr[ki].r;
                 dGdr[0] -= p1drijx;
                 dGdr[1] -= p1drijy;
                 dGdr[2] -= p1drijz;
             }
         }
     }
     for (size_t k = 0; k < members.size(); ++k)
     {
         atom.G[memberIndex[k]] = members[k]->scale(result[k]);
     }
     delete[] result;
     return;
 }
References nnp::ElementMap::atomicNumber(), nnp::Atom::Neighbor::cache, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::Atom::Neighbor::element, nnp::SymGrp::elementMap, nnp::Atom::G, nnp::SymFnc::getCacheIndices(), nnp::SymFncCompRadWeighted::getCompactOnly(), nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, mrc, mrl, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::Vec3D::r, nnp::SymGrpBaseComp::rmin, and nnp::SymGrp::scalingFactors.
parameterLines()
vector< string > SymGrpCompRadWeighted::parameterLines () const virtual
Give symmetry function group parameters on multiple lines.
Returns
Vector of string containing symmetry function parameters lines.
Implements nnp::SymGrp.
Definition at line 206 of file SymGrpCompRadWeighted.cpp.
 {
     vector<string> v;
     v.push_back(strpr(getPrintFormatCommon().c_str(),
                       index + 1,
                       elementMap[ec].c_str(),
                       type,
                       rmin / convLength,
                       rmax / convLength));
     for (size_t i = 0; i < members.size(); ++i)
     {
         v.push_back(strpr(getPrintFormatMember().c_str(),
                           members[i]->getSubtype().c_str(),
                           members[i]->getRl() / convLength,
                           members[i]->getRc() / convLength,
                           members[i]->getLineNumber() + 1,
                           i + 1,
                           members[i]->getIndex() + 1));
     }
     return v;
 }
References nnp::SymGrp::convLength, nnp::SymGrp::ec, nnp::SymGrp::elementMap, nnp::SymGrp::getIndex(), nnp::SymGrp::getPrintFormatCommon(), nnp::SymGrp::getPrintFormatMember(), nnp::SymGrp::index, members, nnp::SymGrpBaseComp::rmax, nnp::SymGrpBaseComp::rmin, nnp::strpr(), and nnp::SymGrp::type.
Member Data Documentation
members
std::vector<SymFncCompRadWeighted const*> nnp::SymGrpCompRadWeighted::members private
Vector of all group member pointers.
Definition at line 93 of file SymGrpCompRadWeighted.h.
Referenced by addMember(), calculate(), parameterLines(), setScalingFactors(), and sortMembers().
mrl
std::vector<double> nnp::SymGrpCompRadWeighted::mrl private
Member rl.
Definition at line 95 of file SymGrpCompRadWeighted.h.
Referenced by calculate(), and sortMembers().
mrc
std::vector<double> nnp::SymGrpCompRadWeighted::mrc private
Member rc.
Definition at line 97 of file SymGrpCompRadWeighted.h.
Referenced by calculate(), and sortMembers().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpCompRadWeighted.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpCompRadWeighted.cpp