n2p2 - A neural network potential package: nnp::EwaldStructureData Class Reference
nnp::EwaldStructureData Class Reference
#include <IEwaldTrunc.h>
Public Member Functions
EwaldStructureData (double const V, std::size_t const N)
~EwaldStructureData ()=default
double getVolume () const
std::size_t getNumAtoms () const
Private Attributes
double volume = 0.0
std::size_t numAtoms = 0
Detailed Description
Definition at line 22 of file IEwaldTrunc.h.
Constructor & Destructor Documentation
EwaldStructureData()
nnp::EwaldStructureData::EwaldStructureData (double const V, std::size_t const N) inline
Definition at line 25 of file IEwaldTrunc.h.
                : volume{V}, numAtoms{N}
        {};
~EwaldStructureData()
nnp::EwaldStructureData::~EwaldStructureData () default
Member Function Documentation
getVolume()
double nnp::EwaldStructureData::getVolume () const inline
Definition at line 30 of file IEwaldTrunc.h.
{ return volume; };
References volume.
Referenced by nnp::EwaldTruncJackson::calculateParameters(), nnp::EwaldTruncKolafaFixR::calculateParameters(), and nnp::EwaldTruncKolafaOptEta::calculateParameters().
getNumAtoms()
std::size_t nnp::EwaldStructureData::getNumAtoms () const inline
Definition at line 31 of file IEwaldTrunc.h.
{ return numAtoms; };
References numAtoms.
Referenced by nnp::EwaldTruncKolafaFixR::calculateParameters(), and nnp::EwaldTruncKolafaOptEta::calculateParameters().
Member Data Documentation
volume
double nnp::EwaldStructureData::volume = 0.0 private
Definition at line 33 of file IEwaldTrunc.h.
Referenced by getVolume().
numAtoms
std::size_t nnp::EwaldStructureData::numAtoms = 0 private
Definition at line 34 of file IEwaldTrunc.h.
Referenced by getNumAtoms().
The documentation for this class was generated from the following file:
/home/runner/work/n2p2/n2p2/src/libnnp/IEwaldTrunc.h