n2p2 - A neural network potential package: nnp::EwaldSetup Class Reference
nnp::EwaldSetup Class Reference
Setup data for Ewald summation.
#include <EwaldSetup.h>
Public Member Functions
EwaldSetup ()
Default constructor.
void setTruncMethod (EWALDTruncMethod const m)
EWALDTruncMethod getTruncMethod () const
double getMaxCharge () const
double getPrecision () const
void setMaxQSigma (double const maxWidth)
Setter for maximum width of charges.
void readFromArgs (std::vector< std::string > const &args)
Setup parameters from argument vector.
void toNormalizedUnits (double const convEnergy, double const convLength)
Convert cutoff parameters to normalized units.
void calculateParameters (double const newVolume, size_t const newNumAtoms)
Compute eta, rCut and kCut.
void logEwaldCutoffs (Log &log, double const lengthConversion) const
Use after Ewald summation!
Public Attributes
EwaldParameters params
Private Member Functions
bool publishedNewCutoffs () const
bool isEstimateReliable () const
Private Attributes
EWALDTruncMethod truncMethod
Method for determining real and k space cutoffs.
EwaldGlobalSettings GlobSett
std::unique_ptr< IEwaldTrunc > truncImpl
Detailed Description
Setup data for Ewald summation.
Definition at line 37 of file EwaldSetup.h.
Constructor & Destructor Documentation
EwaldSetup()
EwaldSetup::EwaldSetup ()
Default constructor.
Definition at line 29 of file EwaldSetup.cpp.
                       : params     (                                ),
                           truncMethod(EWALDTruncMethod::JACKSON_CATLOW),
                           GlobSett   (                                ),
                           truncImpl  (nullptr                         )
{
}
References nnp::JACKSON_CATLOW.
Member Function Documentation
setTruncMethod()
void nnp::EwaldSetup::setTruncMethod (EWALDTruncMethod const m) inline
Definition at line 93 of file EwaldSetup.h.
{
    truncMethod = m;
}
References truncMethod.
Referenced by nnp::Mode::setupElectrostatics().
getTruncMethod()
EWALDTruncMethod nnp::EwaldSetup::getTruncMethod () const inline
Definition at line 43 of file EwaldSetup.h.
{return truncMethod;};
References truncMethod.
Referenced by nnp::Mode::setupElectrostatics().
getMaxCharge()
double nnp::EwaldSetup::getMaxCharge () const inline
Definition at line 44 of file EwaldSetup.h.
{return GlobSett.maxCharge;};
References GlobSett, and nnp::EwaldGlobalSettings::maxCharge.
Referenced by nnp::Mode::setupElectrostatics().
getPrecision()
double nnp::EwaldSetup::getPrecision () const inline
Definition at line 45 of file EwaldSetup.h.
{return GlobSett.precision;};
References GlobSett, and nnp::EwaldGlobalSettings::precision.
Referenced by nnp::Mode::setupElectrostatics().
setMaxQSigma()
void nnp::EwaldSetup::setMaxQSigma (double const maxWidth) inline
Setter for maximum width of charges.
Parameters
maxWidth Maximum width of gaussian charges.
Definition at line 88 of file EwaldSetup.h.
{
    GlobSett.maxQSigma = maxWidth;
}
References GlobSett, and nnp::EwaldGlobalSettings::maxQSigma.
Referenced by nnp::Mode::setupElectrostatics().
readFromArgs()
void EwaldSetup::readFromArgs (std::vector< std::string > const & args)
Setup parameters from argument vector.
Parameters
[in] args Vector containing arguments of input file.
Definition at line 36 of file EwaldSetup.cpp.
{
    bool argConsistent = false;
    if (truncMethod ==
        EWALDTruncMethod::JACKSON_CATLOW)
        argConsistent = (args.size() == 1);
    else
        argConsistent = (args.size() >= 1 && args.size() <= 3);
    if (!argConsistent)
        throw runtime_error("ERROR: Number of arguments for ewald_prec is "
                            "not consistent with "
                            "ewald_truncation_error_method.");
    GlobSett.precision = atof(args.at(0).c_str());
    if (GlobSett.precision <= 0.0)
        throw runtime_error("ERROR: Ewald precision must be positive.");
    if (truncMethod == EWALDTruncMethod::JACKSON_CATLOW)
    {
        truncImpl.reset(new EwaldTruncJackson{});
    }
    else
    {
        if (args.size() >= 2)
            GlobSett.maxCharge = atof(args.at(1).c_str());
        if (args.size() == 2)
        {
            truncImpl.reset(new EwaldTruncKolafaOptEta{});
        }
        if (args.size() == 3)
        {
            params.rCut = atof(args.at(2).c_str());
            truncImpl.reset(new EwaldTruncKolafaFixR{});
        }
    }
}
References GlobSett, nnp::JACKSON_CATLOW, nnp::EwaldGlobalSettings::maxCharge, params, nnp::EwaldGlobalSettings::precision, nnp::EwaldParameters::rCut, truncImpl, and truncMethod.
Referenced by nnp::Mode::setupElectrostatics().
toNormalizedUnits()
void EwaldSetup::toNormalizedUnits (double const convEnergy, double const convLength)
Convert cutoff parameters to normalized units.
Parameters
convEnergy Conversion factor for energy.
convLength Conversion factor for length.
Definition at line 74 of file EwaldSetup.cpp.
{
    if (truncMethod == EWALDTruncMethod::KOLAFA_PERRAM)
    {
        // in KOLAFA_PERRAM method precision has unit of a force.
        GlobSett.precision *= convEnergy / convLength;
        GlobSett.fourPiEps /= convLength * convEnergy;
        // GlobSett.maxQSigma is already normalized
        params = params.toNormalizedUnits(convLength);
        // Other variables are already normalized.
    }
}
References nnp::EwaldGlobalSettings::fourPiEps, GlobSett, nnp::KOLAFA_PERRAM, params, nnp::EwaldGlobalSettings::precision, nnp::EwaldParameters::toNormalizedUnits(), and truncMethod.
Referenced by nnp::Mode::setupElectrostatics().
calculateParameters()
void EwaldSetup::calculateParameters (double const newVolume, size_t const newNumAtoms)
Compute eta, rCut and kCut.
Parameters
[in] newVolume Volume of the real space cell.
[in] newNumAtoms Number of atoms in system.
Definition at line 88 of file EwaldSetup.cpp.
{
    if (truncImpl == nullptr)
        throw runtime_error("ERROR: Undefined Ewald truncation method.");
    EwaldStructureData sData{volume, numAtoms};
    truncImpl->calculateParameters(GlobSett, sData, params);
}
References GlobSett, params, and truncImpl.
Referenced by nnp::Structure::calculateMaxCutoffRadiusOverall().
logEwaldCutoffs()
void EwaldSetup::logEwaldCutoffs (Log & log, double const lengthConversion) const
Use after Ewald summation!
Returns
Definition at line 95 of file EwaldSetup.cpp.
{
    if (!publishedNewCutoffs())
    {
        EwaldParameters ewaldParams = params.toPhysicalUnits(lengthConversion);
        log << "-----------------------------------------"
               "--------------------------------------\n";
        log << "Ewald parameters for this structure changed:\n";
        log << strpr("Real space cutoff:         %16.8E\n",
                     ewaldParams.rCut);
        log << strpr("Reciprocal space cutoff:   %16.8E\n",
                     ewaldParams.kCut);
        log << strpr("Ewald screening parameter: %16.8E\n",
                     ewaldParams.eta);
        if (!isEstimateReliable())
            log << strpr("WARNING: Ewald truncation error estimate may not be "
                         "reliable, better compare it\n"
                         "         with high accuracy settings.\n");
    }
}
References nnp::EwaldParameters::eta, isEstimateReliable(), nnp::EwaldParameters::kCut, params, publishedNewCutoffs(), nnp::EwaldParameters::rCut, nnp::strpr(), and nnp::EwaldParameters::toPhysicalUnits().
Referenced by nnp::Mode::logEwaldCutoffs(), and nnp::InterfaceLammps::process().
publishedNewCutoffs()
bool EwaldSetup::publishedNewCutoffs () const private
Definition at line 115 of file EwaldSetup.cpp.
{
    return truncImpl->publishedNewCutoffs();
}
References truncImpl.
Referenced by logEwaldCutoffs().
isEstimateReliable()
bool EwaldSetup::isEstimateReliable () const private
Definition at line 119 of file EwaldSetup.cpp.
{
    return truncImpl->isEstimateReliable(GlobSett, params);
}
References GlobSett, params, and truncImpl.
Referenced by logEwaldCutoffs().
Member Data Documentation
params
EwaldParameters nnp::EwaldSetup::params
Definition at line 39 of file EwaldSetup.h.
Referenced by nnp::Structure::calculateDAdrQ(), nnp::Structure::calculateElectrostaticEnergy(), nnp::Structure::calculateMaxCutoffRadiusOverall(), calculateParameters(), isEstimateReliable(), logEwaldCutoffs(), readFromArgs(), nnp::KspaceGrid::setup(), and toNormalizedUnits().
truncMethod
EWALDTruncMethod nnp::EwaldSetup::truncMethod private
Method for determining real and k space cutoffs.
Definition at line 79 of file EwaldSetup.h.
Referenced by getTruncMethod(), readFromArgs(), setTruncMethod(), and toNormalizedUnits().
GlobSett
EwaldGlobalSettings nnp::EwaldSetup::GlobSett private
Definition at line 80 of file EwaldSetup.h.
Referenced by calculateParameters(), getMaxCharge(), getPrecision(), isEstimateReliable(), readFromArgs(), setMaxQSigma(), and toNormalizedUnits().
truncImpl
std::unique_ptr<IEwaldTrunc> nnp::EwaldSetup::truncImpl private
Definition at line 82 of file EwaldSetup.h.
Referenced by calculateParameters(), isEstimateReliable(), publishedNewCutoffs(), and readFromArgs().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldSetup.h
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldSetup.cpp