n2p2 - A neural network potential package: nnp::SymGrpExpRadWeighted Class Reference
nnp::SymGrpExpRadWeighted Class Reference
Weighted radial symmetry function group (type 12)
#include <SymGrpExpRadWeighted.h>
Public Member Functions
SymGrpExpRadWeighted (ElementMap const &elementMap)
Constructor, sets type = 12.
virtual bool operator== (SymGrp const &rhs) const
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const
Overload < operator.
virtual bool addMember (SymFnc const *const symmetryFunction)
Potentially add a member to group.
virtual void sortMembers ()
Sort member symmetry functions.
virtual void setScalingFactors ()
Fill scalingFactors with values from member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const
Calculate all symmetry functions of this group for one atom.
virtual std::vector< std::string > parameterLines () const
Give symmetry function group parameters on multiple lines.
Public Member Functions inherited from nnp::SymGrpBaseCutoff
double getRc () const
Get private rc member variable.
Public Member Functions inherited from nnp::SymGrp
virtual ~SymGrp ()
Virtual destructor.
virtual bool operator== (SymGrp const &rhs) const =0
Overload == operator.
virtual bool operator< (SymGrp const &rhs) const =0
Overload < operator.
bool operator!= (SymGrp const &rhs) const
Overload != operator.
bool operator> (SymGrp const &rhs) const
Overload > operator.
bool operator<= (SymGrp const &rhs) const
Overload <= operator.
bool operator>= (SymGrp const &rhs) const
Overload >= operator.
virtual bool addMember (SymFnc const *const symmetryFunction)=0
Potentially add a member to group.
virtual void sortMembers ()=0
Sort member symmetry functions.
virtual void setScalingFactors ()=0
Fill scalingFactors with values from member symmetry functions.
virtual void calculate (Atom &atom, bool const derivatives) const =0
Calculate all symmetry functions of this group for one atom.
virtual std::vector< std::string > parameterLines () const =0
Give symmetry function group parameters on multiple lines.
void setIndex (std::size_t index)
Set private index member variable.
std::size_t getIndex () const
Get private index member variable.
std::size_t getType () const
Get private type member variable.
std::size_t getEc () const
Get private ec member variable.
Private Attributes
std::vector< SymFncExpRadWeighted const * > members
Vector of all group member pointers.
std::vector< double > eta
Vector containing values of all member symmetry functions.
std::vector< double > rs
Vector containing values of all member symmetry functions.
Additional Inherited Members
Protected Types inherited from nnp::SymGrp
typedef std::map< std::string, std::pair< std::string, std::string > > PrintFormat
typedef std::vector< std::string > PrintOrder
Protected Member Functions inherited from nnp::SymGrpBaseCutoff
SymGrpBaseCutoff (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
Protected Member Functions inherited from nnp::SymGrp
SymGrp (std::size_t type, ElementMap const &elementMap)
Constructor, sets type.
std::string getPrintFormatCommon () const
Get common parameter line format string.
std::string getPrintFormatMember () const
Get member parameter line format string.
Static Protected Member Functions inherited from nnp::SymGrp
static PrintFormat const initializePrintFormat ()
Initialize static print format map for all possible parameters.
static PrintOrder const initializePrintOrder ()
Initialize static print order vector for all possible parameters.
Protected Attributes inherited from nnp::SymGrpBaseCutoff
double rc
Cutoff radius \(r_c\) (common feature).
double cutoffAlpha
Cutoff function parameter \(\alpha\) (common feature).
std::string subtype
Subtype string (specifies cutoff type) (common feature).
CutoffFunction fc
Cutoff function used by this symmetry function group.
CutoffFunction::CutoffType cutoffType
Cutoff type used by this symmetry function group (common feature).
Protected Attributes inherited from nnp::SymGrp
std::size_t type
Symmetry function type.
ElementMap elementMap
Copy of element map.
std::size_t index
Symmetry function group index.
std::size_t ec
Element index of center atom (common feature).
double convLength
Data set normalization length conversion factor.
std::vector< size_t > memberIndex
Vector containing indices of all member symmetry functions.
std::vector< double > scalingFactors
Scaling factors of all member symmetry functions.
std::set< std::string > parametersCommon
Set of common parameters IDs.
std::set< std::string > parametersMember
Set of common parameters IDs.
std::vector< std::vector< std::size_t > > memberIndexPerElement
Vector containing per-element indices of all member symmetry functions.
Static Protected Attributes inherited from nnp::SymGrp
static PrintFormat const printFormat = initializePrintFormat()
Map of parameter format strings and empty strings.
static PrintOrder const printOrder = initializePrintOrder()
Vector of parameters in order of printing.
Detailed Description
Weighted radial symmetry function group (type 12)
\[ G^{12}_i = \sum_{j \neq i} Z_j \mathrm{e}^{-\eta(r_{ij} - r_\mathrm{s})^2} f_c(r_{ij}) \]
Common features:
element of central atom
cutoff type
\(r_c\)
\(\alpha\)
Definition at line 45 of file SymGrpExpRadWeighted.h.
Constructor & Destructor Documentation
SymGrpExpRadWeighted()
SymGrpExpRadWeighted::SymGrpExpRadWeighted (ElementMap const & elementMap)
Constructor, sets type = 12.
Definition at line 30 of file SymGrpExpRadWeighted.cpp.
                                                                       :
    SymGrpBaseCutoff(12, elementMap)
{
    parametersMember.insert("eta");
    parametersMember.insert("rs/rl");
    parametersMember.insert("mindex");
    parametersMember.insert("sfindex");
}
References nnp::SymGrp::parametersMember.
Member Function Documentation
operator==()
bool SymGrpExpRadWeighted::operator== (SymGrp const & rhs) const virtual
Overload == operator.
Implements nnp::SymGrp.
Definition at line 39 of file SymGrpExpRadWeighted.cpp.
{
    if (ec   != rhs.getEc()  ) return false;
    if (type != rhs.getType()) return false;
    SymGrpExpRadWeighted const& c =
        dynamic_cast<SymGrpExpRadWeighted const&>(rhs);
    if (cutoffType  != c.cutoffType ) return false;
    if (cutoffAlpha != c.cutoffAlpha) return false;
    if (rc          != c.rc         ) return false;
    return true;
}
References nnp::SymGrpBaseCutoff::cutoffAlpha, nnp::SymGrpBaseCutoff::cutoffType, nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), nnp::SymGrpBaseCutoff::rc, and nnp::SymGrp::type.
operator<()
bool SymGrpExpRadWeighted::operator< (SymGrp const & rhs) const virtual
Overload < operator.
Implements nnp::SymGrp.
Definition at line 51 of file SymGrpExpRadWeighted.cpp.
{
    if      (ec   < rhs.getEc()  ) return true;
    else if (ec   > rhs.getEc()  ) return false;
    if      (type < rhs.getType()) return true;
    else if (type > rhs.getType()) return false;
    SymGrpExpRadWeighted const& c =
        dynamic_cast<SymGrpExpRadWeighted const&>(rhs);
    if      (cutoffType  < c.cutoffType ) return true;
    else if (cutoffType  > c.cutoffType ) return false;
    if      (cutoffAlpha < c.cutoffAlpha) return true;
    else if (cutoffAlpha > c.cutoffAlpha) return false;
    if      (rc          < c.rc         ) return true;
    else if (rc          > c.rc         ) return false;
    return false;
}
References nnp::SymGrpBaseCutoff::cutoffAlpha, nnp::SymGrpBaseCutoff::cutoffType, nnp::SymGrp::ec, nnp::SymGrp::getEc(), nnp::SymGrp::getType(), nnp::SymGrpBaseCutoff::rc, and nnp::SymGrp::type.
addMember()
bool SymGrpExpRadWeighted::addMember (SymFnc const *const symmetryFunction) virtual
Potentially add a member to group.
Parameters
[in] symmetryFunction Candidate symmetry function.
Returns
If addition was successful.
If symmetry function is compatible with common feature list its pointer will be added to members.
Implements nnp::SymGrp.
Definition at line 68 of file SymGrpExpRadWeighted.cpp.
{
    if (symmetryFunction->getType() != type) return false;
    SymFncExpRadWeighted const* sf =
        dynamic_cast<SymFncExpRadWeighted const*>(symmetryFunction);
    if (members.empty())
    {
        cutoffType  = sf->getCutoffType();
        subtype     = sf->getSubtype();
        cutoffAlpha = sf->getCutoffAlpha();
        ec          = sf->getEc();
        rc          = sf->getRc();
        convLength  = sf->getConvLength();
        fc.setCutoffType(cutoffType);
        fc.setCutoffRadius(rc);
        fc.setCutoffParameter(cutoffAlpha);
    }
    if (sf->getCutoffType()  != cutoffType ) return false;
    if (sf->getCutoffAlpha() != cutoffAlpha) return false;
    if (sf->getEc()          != ec         ) return false;
    if (sf->getRc()          != rc         ) return false;
    if (sf->getConvLength()  != convLength )
    {
        throw runtime_error("ERROR: Unable to add symmetry function members "
                            "with different conversion factors.\n");
    }
    members.push_back(sf);
    return true;
}
References nnp::SymGrp::convLength, nnp::SymGrpBaseCutoff::cutoffAlpha, nnp::SymGrpBaseCutoff::cutoffType, nnp::SymGrp::ec, nnp::SymGrpBaseCutoff::fc, nnp::SymFnc::getConvLength(), nnp::SymFncBaseCutoff::getCutoffAlpha(), nnp::SymFncBaseCutoff::getCutoffType(), nnp::SymFnc::getEc(), nnp::SymFnc::getRc(), nnp::SymFncBaseCutoff::getSubtype(), nnp::SymFnc::getType(), members, nnp::SymGrpBaseCutoff::rc, nnp::CutoffFunction::setCutoffParameter(), nnp::CutoffFunction::setCutoffRadius(), nnp::CutoffFunction::setCutoffType(), nnp::SymGrpBaseCutoff::subtype, and nnp::SymGrp::type.
sortMembers()
void SymGrpExpRadWeighted::sortMembers () virtual
Sort member symmetry functions.
Also allocate and precalculate additional stuff.
Implements nnp::SymGrp.
Definition at line 104 of file SymGrpExpRadWeighted.cpp.
{
    sort(members.begin(),
         members.end(),
         comparePointerTargets<SymFncExpRadWeighted const>);
    for (size_t i = 0; i < members.size(); i++)
    {
        memberIndex.push_back(members[i]->getIndex());
        eta.push_back(members[i]->getEta());
        rs.push_back(members[i]->getRs());
        memberIndexPerElement.push_back(members[i]->getIndexPerElement());
    }
    return;
}
References eta, nnp::SymGrp::getIndex(), nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, and rs.
setScalingFactors()
void SymGrpExpRadWeighted::setScalingFactors () virtual
Fill scalingFactors with values from member symmetry functions.
Implements nnp::SymGrp.
Definition at line 121 of file SymGrpExpRadWeighted.cpp.
{
    scalingFactors.resize(members.size(), 0.0);
    for (size_t i = 0; i < members.size(); i++)
    {
        scalingFactors.at(i) = members[i]->getScalingFactor();
    }
    return;
}
References members, and nnp::SymGrp::scalingFactors.
calculate()
void SymGrpExpRadWeighted::calculate (Atom & atom, bool const derivatives) const virtual
Calculate all symmetry functions of this group for one atom.
Parameters
[in,out] atom Atom for which symmetry functions are caluclated.
[in] derivatives If also symmetry function derivatives will be calculated and saved.
Implements nnp::SymGrp.
Definition at line 138 of file SymGrpExpRadWeighted.cpp.
{
#ifndef N2P2_NO_SF_CACHE
    // Can use cache indices of any member because this group is defined via
    // identical symmetry function type and cutoff functions.
    auto cacheIndices = members.at(0)->getCacheIndices();
#endif
    double* result = new double[members.size()];
    for (size_t k = 0; k < members.size(); ++k)
    {
        result[k] = 0.0;
    }
    for (size_t j = 0; j < atom.numNeighbors; ++j)
    {
        Atom::Neighbor& n = atom.neighbors[j];
        if (n.d < rc)
        {
            // Energy calculation.
            double const rij = n.d;
            size_t const nej = n.element;
            // Calculate cutoff function and derivative.
            double pfc;
            double pdfc;
#ifndef N2P2_NO_SF_CACHE
            if (cacheIndices[nej].size() == 0) fc.fdf(rij, pfc, pdfc);
            else
            {
                double& cfc = n.cache[cacheIndices[nej][0]];
                double& cdfc = n.cache[cacheIndices[nej][1]];
                if (cfc < 0) fc.fdf(rij, cfc, cdfc);
                pfc = cfc;
                pdfc = cdfc;
            }
#else
            fc.fdf(rij, pfc, pdfc);
#endif
            double const* const d1 = n.dr.r;
            for (size_t k = 0; k < members.size(); ++k)
            {
                double pexp = elementMap.atomicNumber(nej)
                            * exp(-eta[k] * (rij - rs[k]) * (rij - rs[k]));
                result[k] += pexp * pfc;
                // Force calculation.
                if (!derivatives) continue;
                double const p1 = scalingFactors[k] * (pdfc - 2.0 * eta[k]
                                * (rij - rs[k]) * pfc) * pexp / rij;
                // SIMPLE EXPRESSIONS:
                //Vec3D const dij = p1 * atom.neighbors[j].dr;
                double const p1drijx = p1 * d1[0];
                double const p1drijy = p1 * d1[1];
                double const p1drijz = p1 * d1[2];
                // Save force contributions in Atom storage.
#ifndef N2P2_FULL_SFD_MEMORY
                size_t ki = memberIndex[k];
#else
                size_t const ki = memberIndex[k];
#endif
                // SIMPLE EXPRESSIONS:
                //atom.dGdr[ki]              += dij;
                //atom.neighbors[j].dGdr[ki] -= dij;
                double* dGdr = atom.dGdr[ki].r;
                dGdr[0] += p1drijx;
                dGdr[1] += p1drijy;
                dGdr[2] += p1drijz;
#ifndef N2P2_FULL_SFD_MEMORY
                ki = memberIndexPerElement[k][nej];
#endif
                dGdr = n.dGdr[ki].r;
                dGdr[0] -= p1drijx;
                dGdr[1] -= p1drijy;
                dGdr[2] -= p1drijz;
            }
        }
    }
    for (size_t k = 0; k < members.size(); ++k)
    {
        atom.G[memberIndex[k]] = members[k]->scale(result[k]);
    }
    delete[] result;
    return;
}
References nnp::ElementMap::atomicNumber(), nnp::Atom::Neighbor::cache, nnp::Atom::Neighbor::d, nnp::Atom::Neighbor::dGdr, nnp::Atom::dGdr, nnp::Atom::Neighbor::dr, nnp::Atom::Neighbor::element, nnp::SymGrp::elementMap, eta, nnp::SymGrpBaseCutoff::fc, nnp::CutoffFunction::fdf(), nnp::Atom::G, nnp::SymGrp::memberIndex, nnp::SymGrp::memberIndexPerElement, members, nnp::Atom::neighbors, nnp::Atom::numNeighbors, nnp::Vec3D::r, nnp::SymGrpBaseCutoff::rc, rs, and nnp::SymGrp::scalingFactors.
parameterLines()
vector< string > SymGrpExpRadWeighted::parameterLines () const virtual
Give symmetry function group parameters on multiple lines.
Returns
Vector of string containing symmetry function parameters lines.
Implements nnp::SymGrp.
Definition at line 228 of file SymGrpExpRadWeighted.cpp.
{
    vector<string> v;
    v.push_back(strpr(getPrintFormatCommon().c_str(),
                      index + 1,
                      elementMap[ec].c_str(),
                      type,
                      subtype.c_str(),
                      rc / convLength,
                      cutoffAlpha));
    for (size_t i = 0; i < members.size(); ++i)
    {
        v.push_back(strpr(getPrintFormatMember().c_str(),
                          members[i]->getEta() * convLength * convLength,
                          members[i]->getRs() / convLength,
                          members[i]->getLineNumber() + 1,
                          i + 1,
                          members[i]->getIndex() + 1));
    }
    return v;
}
References nnp::SymGrp::convLength, nnp::SymGrpBaseCutoff::cutoffAlpha, nnp::SymGrp::ec, nnp::SymGrp::elementMap, nnp::SymGrp::getIndex(), nnp::SymGrp::getPrintFormatCommon(), nnp::SymGrp::getPrintFormatMember(), nnp::SymGrp::index, members, nnp::SymGrpBaseCutoff::rc, nnp::strpr(), nnp::SymGrpBaseCutoff::subtype, and nnp::SymGrp::type.
Member Data Documentation
members
std::vector<SymFncExpRadWeighted const*> nnp::SymGrpExpRadWeighted::members private
Vector of all group member pointers.
Definition at line 90 of file SymGrpExpRadWeighted.h.
Referenced by addMember(), calculate(), parameterLines(), setScalingFactors(), and sortMembers().
eta
std::vector<double> nnp::SymGrpExpRadWeighted::eta private
Vector containing values of all member symmetry functions.
Definition at line 92 of file SymGrpExpRadWeighted.h.
Referenced by calculate(), and sortMembers().
rs
std::vector<double> nnp::SymGrpExpRadWeighted::rs private
Vector containing values of all member symmetry functions.
Definition at line 94 of file SymGrpExpRadWeighted.h.
Referenced by calculate(), and sortMembers().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpExpRadWeighted.h
/home/runner/work/n2p2/n2p2/src/libnnp/SymGrpExpRadWeighted.cpp