n2p2 - A neural network potential package: nnp::Log Class Reference
nnp::Log Class Reference
Logging class for library output.
#include <Log.h>
Public Member Functions
Log ()
Constructor.
Log & operator<< (std::string const &entry)
Overload << operator.
Log & operator<< (std::vector< std::string > const &entries)
Overload << operator.
void addLogEntry (std::string const &entry)
Add string as new log entry.
void addMultipleLogEntries (std::vector< std::string > const &entries)
Add multiple log entries at once.
void registerCFilePointer (FILE **const &filePointer)
Register new C-style FILE* pointer for output.
void registerStreamPointer (std::ofstream *const &streamPointer)
Register new C++ ofstream pointer.
std::vector< std::string > getLog () const
Get complete log memory.
Public Attributes
bool writeToStdout
Turn on/off output to stdout.
bool silent
Completely silence output.
Private Attributes
std::vector< std::string > memory
Memory with all log entries.
std::vector< FILE ** > cFilePointers
Storage for C-style FILE* pointers.
std::vector< std::ofstream * > streamPointers
Storage for C++ ofstream pointers.
Detailed Description
Logging class for library output.
Log entries are saved in internal memory and may be redirected to multiple destinations: existing C-style FILE pointer or existing C++ stream.
Definition at line 33 of file Log.h.
Constructor & Destructor Documentation
Log()
Log::Log ()
Constructor.
Default output to stdout.
Definition at line 23 of file Log.cpp.
         : writeToStdout(true ),
             silent       (false)
{
}
Member Function Documentation
operator<<() [1/2]
Log & Log::operator<< (std::string const & entry)
Overload << operator.
Parameters
[in] entry New log entry.
Returns
Reference to log itself.
Definition at line 28 of file Log.cpp.
{
    addLogEntry(entry);
    return *this;
}
References addLogEntry().
operator<<() [2/2]
Log & Log::operator<< (std::vector< std::string > const & entries)
Overload << operator.
Parameters
[in] entries Vector with log entries.
Returns
Reference to log itself.
Definition at line 34 of file Log.cpp.
{
    addMultipleLogEntries(entries);
    return *this;
}
References addMultipleLogEntries().
addLogEntry()
void Log::addLogEntry (std::string const & entry)
Add string as new log entry.
Parameters
[in] entry New log entry.
Definition at line 40 of file Log.cpp.
{
    if (silent) return;
    memory.push_back(entry);
    if (writeToStdout)
    {
        cout << entry;
        cout.flush();
    }
    for (vector<FILE**>::const_iterator it = cFilePointers.begin();
         it != cFilePointers.end(); ++it)
    {
        if ((**it) != 0)
        {
            fprintf((**it), "%s", entry.c_str());
            fflush((**it));
        }
    }
    for (vector<ofstream*>::const_iterator it = streamPointers.begin();
         it != streamPointers.end(); ++it)
    {
        if ((**it).is_open())
        {
            (**it) << entry;
            (**it).flush();
        }
    }
    return;
}
References cFilePointers, memory, silent, streamPointers, and writeToStdout.
Referenced by addMultipleLogEntries(), and operator<<().
addMultipleLogEntries()
void Log::addMultipleLogEntries (std::vector< std::string > const & entries)
Add multiple log entries at once.
Parameters
[in] entries Vector with log entries.
Definition at line 74 of file Log.cpp.
{
    for (vector<string>::const_iterator it = entries.begin();
         it != entries.end(); ++it)
    {
        addLogEntry(*it);
    }
    return;
}
References addLogEntry().
Referenced by operator<<().
registerCFilePointer()
void Log::registerCFilePointer (FILE **const & filePointer)
Register new C-style FILE* pointer for output.
Parameters
[in] filePointer Address of C-style file pointer (FILE*).
Definition at line 85 of file Log.cpp.
{
    cFilePointers.push_back(filePointer);
    return;
}
References cFilePointers.
Referenced by LAMMPS_NS::PairNNP::init_style().
registerStreamPointer()
void Log::registerStreamPointer (std::ofstream *const & streamPointer)
Register new C++ ofstream pointer.
Parameters
[in] streamPointer Address of C++ ofstream pointer.
Definition at line 91 of file Log.cpp.
{
    streamPointers.push_back(streamPointer);
    return;
}
References streamPointers.
Referenced by main().
getLog()
vector< string > Log::getLog () const
Get complete log memory.
Returns
Log memory.
Definition at line 97 of file Log.cpp.
{
    return memory;
}
References memory.
Member Data Documentation
writeToStdout
bool nnp::Log::writeToStdout
Turn on/off output to stdout.
Definition at line 85 of file Log.h.
Referenced by addLogEntry(), nnp::InterfaceLammps::initialize(), and main().
silent
bool nnp::Log::silent
Completely silence output.
Definition at line 87 of file Log.h.
Referenced by addLogEntry(), and nnp::Training::dataSetNormalization().
memory
std::vector<std::string> nnp::Log::memory private
Memory with all log entries.
Definition at line 91 of file Log.h.
Referenced by addLogEntry(), and getLog().
cFilePointers
std::vector<FILE**> nnp::Log::cFilePointers private
Storage for C-style FILE* pointers.
Definition at line 93 of file Log.h.
Referenced by addLogEntry(), and registerCFilePointer().
streamPointers
std::vector<std::ofstream*> nnp::Log::streamPointers private
Storage for C++ ofstream pointers.
Definition at line 95 of file Log.h.
Referenced by addLogEntry(), and registerStreamPointer().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/Log.h
/home/runner/work/n2p2/n2p2/src/libnnp/Log.cpp