n2p2 - A neural network potential package: nnp::EwaldTruncKolafaOptEta Class Reference
nnp::EwaldTruncKolafaOptEta Class Reference
#include <EwaldTruncKolafaOptEta.h>
Public Member Functions
void calculateParameters (EwaldGlobalSettings const &settings, EwaldStructureData const &sData, EwaldParameters &params) override
bool publishedNewCutoffs () override
virtual bool isEstimateReliable (EwaldGlobalSettings const &, EwaldParameters const &) const override
Public Member Functions inherited from nnp::IEwaldTrunc
virtual void calculateParameters (EwaldGlobalSettings const &settings, EwaldStructureData const &sData, EwaldParameters &params)=0
virtual bool publishedNewCutoffs ()=0
virtual bool isEstimateReliable (EwaldGlobalSettings const &settings, EwaldParameters const &params) const =0
virtual ~IEwaldTrunc ()=default
Private Member Functions
void calculateEta ()
double calculateRCut ()
double calculateKCut ()
void calculateS ()
void calculateC (double const qMax)
Private Attributes
bool newCutoffs = true
bool newCutoffsWerePublished = false
double C = 0.0
double s = 1.0
double eta = 1.0
double prec = 1.e-6
double volume = 0.0
double fourPiEps = 1.0
std::size_t numAtoms = 0
Detailed Description
Definition at line 13 of file EwaldTruncKolafaOptEta.h.
Member Function Documentation
calculateParameters()
void nnp::EwaldTruncKolafaOptEta::calculateParameters (EwaldGlobalSettings const & settings, EwaldStructureData const & sData, EwaldParameters & params) override virtual
Implements nnp::IEwaldTrunc.
Definition at line 16 of file EwaldTruncKolafaOptEta.cpp.
    {
        size_t N = sData.getNumAtoms();
        double V = sData.getVolume();
        newCutoffs = (volume != V || numAtoms != N);
        if (!newCutoffs) return;
        newCutoffsWerePublished = false;
        volume = V;
        numAtoms = N;
        prec = settings.precision;
        fourPiEps = settings.fourPiEps;
        calculateC(settings.maxCharge);
        calculateEta();
        eta = std::max(eta,settings.maxQSigma);
        params.eta = eta;
        params.rCut = calculateRCut();
        params.kCut = calculateKCut();
    }
References calculateC(), calculateEta(), calculateKCut(), calculateRCut(), eta, nnp::EwaldParameters::eta, fourPiEps, nnp::EwaldGlobalSettings::fourPiEps, nnp::EwaldStructureData::getNumAtoms(), nnp::EwaldStructureData::getVolume(), nnp::EwaldParameters::kCut, nnp::EwaldGlobalSettings::maxCharge, nnp::EwaldGlobalSettings::maxQSigma, newCutoffs, newCutoffsWerePublished, numAtoms, prec, nnp::EwaldGlobalSettings::precision, nnp::EwaldParameters::rCut, and volume.
publishedNewCutoffs()
bool nnp::EwaldTruncKolafaOptEta::publishedNewCutoffs () override virtual
Implements nnp::IEwaldTrunc.
Definition at line 39 of file EwaldTruncKolafaOptEta.cpp.
    {
        bool answer = newCutoffsWerePublished;
        newCutoffsWerePublished = true;
        return answer;
    }
References newCutoffsWerePublished.
isEstimateReliable()
virtual bool nnp::EwaldTruncKolafaOptEta::isEstimateReliable (EwaldGlobalSettings const & , EwaldParameters const &) const inline override virtual
Implements nnp::IEwaldTrunc.
Definition at line 20 of file EwaldTruncKolafaOptEta.h.
                                                        { return true; };
calculateEta()
void nnp::EwaldTruncKolafaOptEta::calculateEta () private
Definition at line 46 of file EwaldTruncKolafaOptEta.cpp.
    {
        double constexpr acceptError = 1.e-10;
        // Initial approximation
        double eta0 = pow(1 / TrOverTk * pow(volume, 2.0)
                    / pow(2 * M_PI, 3.0), 1.0 / 6.0);
        // Selfconsistent calculation of eta
        eta = eta0;
        double oldEta;
        double relError = 1.0;
        s = 1.0;
        while (relError > acceptError)
        {
            calculateS();
            oldEta = eta;
            eta = eta0 * pow((1 + 1 / (2 * pow(s, 2))), 1.0 / 6.0);
            relError = abs(oldEta - eta) / eta;
        }
    }
References calculateS(), eta, s, nnp::TrOverTk, and volume.
Referenced by calculateParameters().
calculateRCut()
double nnp::EwaldTruncKolafaOptEta::calculateRCut () private
Definition at line 67 of file EwaldTruncKolafaOptEta.cpp.
    {
        return sqrt(2)*eta*s;
    }
References eta, and s.
Referenced by calculateParameters().
calculateKCut()
double nnp::EwaldTruncKolafaOptEta::calculateKCut () private
Definition at line 72 of file EwaldTruncKolafaOptEta.cpp.
    {
        return sqrt(2)*s / eta;
    }
References eta, and s.
Referenced by calculateParameters().
calculateS()
void nnp::EwaldTruncKolafaOptEta::calculateS () private
Definition at line 77 of file EwaldTruncKolafaOptEta.cpp.
    {
        double constexpr acceptError = 1.e-10;
        double relXError = 1.0;
        double relYError = 1.0;
        double y = prec / C * sqrt(eta/2);
        if (s <= 0.0) s = 0.5;
        double step;
        while (relXError > acceptError || relYError > acceptError)
        {
            step = 2*s / (4*pow(s,2.0) + 1)
                   * (1 - sqrt(s) / exp(-pow(s,2.0)) * y);
            // If s would become negative, try smaller start value.
            if (s <= -step)
            {
                s /= 2;
                step = 1.0;
                continue;
            }
            s += step;
            relYError = abs((exp(-pow(s,2.0)) / sqrt(s) - y) / y);
            relXError = abs(step/s);
        }
    }
References C, eta, prec, and s.
Referenced by calculateEta().
calculateC()
void nnp::EwaldTruncKolafaOptEta::calculateC (double const qMax) private
Definition at line 105 of file EwaldTruncKolafaOptEta.cpp.
    {
        C = pow(2, 3.0/4) * pow(qMax,2.0) * sqrt(numAtoms/volume) / fourPiEps;
    }
References C, fourPiEps, numAtoms, and volume.
Referenced by calculateParameters().
Member Data Documentation
newCutoffs
bool nnp::EwaldTruncKolafaOptEta::newCutoffs = true private
Definition at line 24 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateParameters().
newCutoffsWerePublished
bool nnp::EwaldTruncKolafaOptEta::newCutoffsWerePublished = false private
Definition at line 25 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateParameters(), and publishedNewCutoffs().
C
double nnp::EwaldTruncKolafaOptEta::C = 0.0 private
Definition at line 26 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateC(), and calculateS().
s
double nnp::EwaldTruncKolafaOptEta::s = 1.0 private
Definition at line 27 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateEta(), calculateKCut(), calculateRCut(), and calculateS().
eta
double nnp::EwaldTruncKolafaOptEta::eta = 1.0 private
Definition at line 28 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateEta(), calculateKCut(), calculateParameters(), calculateRCut(), and calculateS().
prec
double nnp::EwaldTruncKolafaOptEta::prec = 1.e-6 private
Definition at line 29 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateParameters(), and calculateS().
volume
double nnp::EwaldTruncKolafaOptEta::volume = 0.0 private
Definition at line 30 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateC(), calculateEta(), and calculateParameters().
fourPiEps
double nnp::EwaldTruncKolafaOptEta::fourPiEps = 1.0 private
Definition at line 31 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateC(), and calculateParameters().
numAtoms
std::size_t nnp::EwaldTruncKolafaOptEta::numAtoms = 0 private
Definition at line 32 of file EwaldTruncKolafaOptEta.h.
Referenced by calculateC(), and calculateParameters().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldTruncKolafaOptEta.h
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldTruncKolafaOptEta.cpp