n2p2 - A neural network potential package: nnp::EwaldTruncJackson Class Reference
nnp::EwaldTruncJackson Class Reference
#include <EwaldTruncJackson.h>
Public Member Functions
void calculateParameters (EwaldGlobalSettings const &settings, EwaldStructureData const &sData, EwaldParameters &params) override
bool publishedNewCutoffs () override
virtual bool isEstimateReliable (EwaldGlobalSettings const &, EwaldParameters const &) const override
Public Member Functions inherited from nnp::IEwaldTrunc
virtual void calculateParameters (EwaldGlobalSettings const &settings, EwaldStructureData const &sData, EwaldParameters &params)=0
virtual bool publishedNewCutoffs ()=0
virtual bool isEstimateReliable (EwaldGlobalSettings const &settings, EwaldParameters const &params) const =0
virtual ~IEwaldTrunc ()=default
Private Member Functions
double calculateEta () const
double calculateRCut (double const eta, double const prec) const
double calculateKCut (double const eta, double const prec) const
Private Attributes
bool newCutoffs = true
bool newCutoffsWerePublished = false
double volume = 0.0
Detailed Description
Definition at line 11 of file EwaldTruncJackson.h.
Member Function Documentation
calculateParameters()
void nnp::EwaldTruncJackson::calculateParameters (EwaldGlobalSettings const & settings, EwaldStructureData const & sData, EwaldParameters & params) override virtual
Implements nnp::IEwaldTrunc.
Definition at line 12 of file EwaldTruncJackson.cpp.
    {
        double V = sData.getVolume();
        newCutoffs = (V != volume);
        if (!newCutoffs) return;
        newCutoffsWerePublished = false;
        volume = V;
        if ( settings.precision >= 1.0 )
            throw std::runtime_error("ERROR: Ewald truncation method 0 "
                                     "(Jackson) requires precision < 1.0");
        params.eta = calculateEta();
        if ( params.eta <= 0.0 )
            throw std::runtime_error("ERROR: Ewald screening parameter eta is "
                                     "not positive, is the unit cell volume "
                                     "correct?");
        params.rCut = calculateRCut(params.eta, settings.precision);
        params.kCut = calculateKCut(params.eta, settings.precision);
        return;
    }
References calculateEta(), calculateKCut(), calculateRCut(), nnp::EwaldParameters::eta, nnp::EwaldStructureData::getVolume(), nnp::EwaldParameters::kCut, newCutoffs, newCutoffsWerePublished, nnp::EwaldGlobalSettings::precision, nnp::EwaldParameters::rCut, and volume.
publishedNewCutoffs()
bool nnp::EwaldTruncJackson::publishedNewCutoffs () override virtual
Implements nnp::IEwaldTrunc.
Definition at line 35 of file EwaldTruncJackson.cpp.
    {
        bool answer = newCutoffsWerePublished;
        newCutoffsWerePublished = true;
        return answer;
    }
References newCutoffsWerePublished.
isEstimateReliable()
virtual bool nnp::EwaldTruncJackson::isEstimateReliable (EwaldGlobalSettings const & , EwaldParameters const &) const inline override virtual
Implements nnp::IEwaldTrunc.
Definition at line 18 of file EwaldTruncJackson.h.
                                                       {return true;};
calculateEta()
double nnp::EwaldTruncJackson::calculateEta () const private
Definition at line 42 of file EwaldTruncJackson.cpp.
    {
        // Matrix version of eta.
        return 1.0 / sqrt(2.0 * M_PI) * pow(volume, 1.0 / 3.0);
    }
References volume.
Referenced by calculateParameters().
calculateRCut()
double nnp::EwaldTruncJackson::calculateRCut (double const eta, double const prec) const private
Definition at line 48 of file EwaldTruncJackson.cpp.
    {
        return sqrt(-2.0 * log(prec)) * eta;
    }
Referenced by calculateParameters().
calculateKCut()
double nnp::EwaldTruncJackson::calculateKCut (double const eta, double const prec) const private
Definition at line 54 of file EwaldTruncJackson.cpp.
    {
        return sqrt(-2.0 * log(prec)) / eta;
    }
Referenced by calculateParameters().
Member Data Documentation
newCutoffs
bool nnp::EwaldTruncJackson::newCutoffs = true private
Definition at line 22 of file EwaldTruncJackson.h.
Referenced by calculateParameters().
newCutoffsWerePublished
bool nnp::EwaldTruncJackson::newCutoffsWerePublished = false private
Definition at line 23 of file EwaldTruncJackson.h.
Referenced by calculateParameters(), and publishedNewCutoffs().
volume
double nnp::EwaldTruncJackson::volume = 0.0 private
Definition at line 24 of file EwaldTruncJackson.h.
Referenced by calculateEta(), and calculateParameters().
The documentation for this class was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldTruncJackson.h
/home/runner/work/n2p2/n2p2/src/libnnp/EwaldTruncJackson.cpp