n2p2 - A neural network potential package: nnp Namespace Reference
nnp Namespace Reference
Namespaces
namespace settings
Classes
struct Atom
Storage for a single atom.
class CompactFunction
A general function with compact support.
class CoreFunction
class CutoffFunction
class Dataset
Collect and process large data sets.
class Element
Contains element-specific data.
class ElementCabana
Derived Cabana class for element-specific data.
class ElementMap
Contains element map.
struct ErfcBuf
Helper class to store previously calculated values of erfc() that are needed during the charge equilibration.
struct EwaldGlobalSettings
struct EwaldParameters
class EwaldSetup
Setup data for Ewald summation.
class EwaldStructureData
class EwaldTruncJackson
class EwaldTruncKolafaFixR
class EwaldTruncKolafaOptEta
class GradientDescent
Weight updates based on simple gradient descent methods.
class IEwaldTrunc
class InterfaceLammps
class KalmanFilter
Implementation of the Kalman filter method.
class KspaceGrid
class Kvector
class Log
Logging class for library output.
class Mode
Base class for all NNP applications.
class ModeCabana
Derived Cabana main NNP class.
class NeuralNetwork
This class implements a feed-forward neural network.
class Prediction
class ScreeningFunction
A screening functions for use with electrostatics.
class SetupAnalysis
class Stopwatch
Implements a simple stopwatch on different platforms.
struct Structure
Storage for one atomic configuration.
class SymFnc
Symmetry function base class.
class SymFncBaseComp
Symmetry function base class for SFs with compact support.
class SymFncBaseCompAng
Intermediate symmetry function class for angular SFs with compact support.
class SymFncBaseCompAngWeighted
Intermediate symmetry function class for weighted angular compact SFs.
class SymFncBaseCutoff
Intermediate class for SFs based on cutoff functions.
class SymFncBaseExpAng
Intermediate class for angular SFs based on cutoffs and exponentials.
class SymFncCompAngn
Narrow angular symmetry function with compact support (type 21)
class SymFncCompAngnWeighted
Weighted narrow angular symmetry function with compact support (type 24)
class SymFncCompAngw
Wide angular symmetry function with compact support (type 22)
class SymFncCompAngwWeighted
Weighted wide angular symmetry function with compact support (type 25)
class SymFncCompRad
Radial symmetry function with compact support (type 20)
class SymFncCompRadWeighted
Weighted radial symmetry function with compact support (type 23)
class SymFncExpAngn
Angular symmetry function (type 3)
class SymFncExpAngnWeighted
Weighted angular symmetry function (type 13)
class SymFncExpAngw
Angular symmetry function (type 9)
class SymFncExpRad
Radial symmetry function (type 2)
class SymFncExpRadWeighted
Weighted radial symmetry function (type 12)
class SymFncStatistics
class SymGrp
class SymGrpBaseComp
class SymGrpBaseCompAng
class SymGrpBaseCompAngWeighted
class SymGrpBaseCutoff
class SymGrpBaseExpAng
class SymGrpCompAngn
Narrow angular symmetry function with compact support (type 21)
class SymGrpCompAngnWeighted
Weighted narrow angular symmetry function with compact support (type 24)
class SymGrpCompAngw
Wide angular symmetry function with compact support (type 22)
class SymGrpCompAngwWeighted
Weighted wide angular symmetry function with compact support (type 25)
class SymGrpCompRad
Radial symmetry function with compact support (type 20)
class SymGrpCompRadWeighted
Weighted radial symmetry function with compact support (type 23)
class SymGrpExpAngn
Angular symmetry function group (type 3)
class SymGrpExpAngnWeighted
Weighted angular symmetry function group (type 13)
class SymGrpExpAngw
Angular symmetry function group (type 3)
class SymGrpExpRad
Radial symmetry function group (type 2)
class SymGrpExpRadWeighted
Weighted radial symmetry function group (type 12)
class Training
Training methods.
class Updater
Base class for different weight update methods.
struct Vec3D
Vector in 3 dimensional real space.
Enumerations
enum class EWALDTruncMethod { JACKSON_CATLOW , KOLAFA_PERRAM }
Functions
NeuralNetwork::ActivationFunction activationFromString (std::string c)
Convert string to activation function.
vector< string > split (std::string const &input, char delimiter=' ')
Split string at each delimiter.
string trim (std::string const &line, std::string const &whitespace=" \t")
Remove leading and trailing whitespaces from string.
string reduce (std::string const &line, std::string const &whitespace=" \t", std::string const &fill=" ")
Replace multiple whitespaces with fill.
string pad (string const &input, size_t num, char fill, bool right)
string strpr (const char *format,...)
String version of printf function.
string cap (std::string word)
Capitalize first letter of word.
vector< string > createFileHeader (vector< string > const &title, vector< size_t > const &colSize, vector< string > const &colName, vector< string > const &colInfo, char const &commentChar)
void appendLinesToFile (std::ofstream &file, std::vector< std::string > const lines)
Append multiple lines of strings to open file stream.
void appendLinesToFile (FILE *const &file, std::vector< std::string > const lines)
Append multiple lines of strings to open file pointer.
map< size_t, vector< double > > readColumnsFromFile (string fileName, vector< size_t > columns, char comment)
double pow_int (double x, int n)
Integer version of power function, "fast exponentiation algorithm".
std::string pad (std::string const &input, std::size_t num, char fill=' ', bool right=true)
Pad string to given length with fill character.
std::vector< std::string > createFileHeader (std::vector< std::string > const &title, std::vector< std::size_t > const &colLength, std::vector< std::string > const &colName, std::vector< std::string > const &colInfo, char const &commentChar='#')
Generate output file header with info section and column labels.
std::map< std::size_t, std::vector< double > > readColumnsFromFile (std::string fileName, std::vector< std::size_t > columns, char comment='#')
Read multiple columns of data from file.
template<typename K , typename V >
V const & safeFind (std::map< K, V > const &stdMap, typename std::map< K, V >::key_type const &key)
Safely access map entry.
template<typename T >
bool vectorContains (std::vector< T > const &stdVec, T value)
Test if vector contains specified value.
template<typename T , typename U >
bool unorderedMapContainsKey (std::unordered_map< T, U > const &stdMap, T key)
Test if unordered map contains specified key.
template<typename T >
bool comparePointerTargets (T *lhs, T *rhs)
Compare pointer targets.
Vec3D operator+ (Vec3D lhs, Vec3D const &rhs)
Overload + operator to implement vector addition.
Vec3D operator- (Vec3D lhs, Vec3D const &rhs)
Overload - operator to implement vector subtraction.
Vec3D operator- (Vec3D v)
Overload - operator to implement vector sign change.
Vec3D operator* (Vec3D v, double const a)
Overload * operator to implement multiplication with scalar.
Vec3D operator* (Vec3D const (&A)[3], Vec3D v)
Overload * operator to implement (left) multiplication with a matrix.
Vec3D operator/ (Vec3D v, double const a)
Overload / operator to implement division by scalar.
Vec3D operator* (double const a, Vec3D v)
Overload * operator to implement multiplication with scalar (scalar first).
Variables
double constexpr TrOverTk = 3.676
Enumeration Type Documentation
EWALDTruncMethod
enum class nnp::EWALDTruncMethod strong
Enumerator
JACKSON_CATLOW
Method 0: Used by RuNNer (DOI: 10.1080/08927028808080944).
KOLAFA_PERRAM
Method 1: Optimized in n2p2 (DOI: 10.1080/08927029208049126).
Definition at line 29 of file EwaldSetup.h.
{
    JACKSON_CATLOW,
    KOLAFA_PERRAM
};
Function Documentation
activationFromString()
NeuralNetwork::ActivationFunction nnp::activationFromString (std::string c)
Convert string to activation function.
Parameters
[in] letter String representing activation function.
Returns
Activation corresponding to string.
Definition at line 1078 of file NeuralNetwork.cpp.
{
    NeuralNetwork::ActivationFunction a;
    if      (c == "l") a = NeuralNetwork::AF_IDENTITY;
    else if (c == "t") a = NeuralNetwork::AF_TANH;
    else if (c == "s") a = NeuralNetwork::AF_LOGISTIC;
    else if (c == "p") a = NeuralNetwork::AF_SOFTPLUS;
    else if (c == "r") a = NeuralNetwork::AF_RELU;
    else if (c == "g") a = NeuralNetwork::AF_GAUSSIAN;
    else if (c == "c") a = NeuralNetwork::AF_COS;
    else if (c == "S") a = NeuralNetwork::AF_REVLOGISTIC;
    else if (c == "e") a = NeuralNetwork::AF_EXP;
    else if (c == "h") a = NeuralNetwork::AF_HARMONIC;
    else
    {
        throw runtime_error("ERROR: Unknown activation function.\n");
    }
    return a;
}
References nnp::NeuralNetwork::AF_COS, nnp::NeuralNetwork::AF_EXP, nnp::NeuralNetwork::AF_GAUSSIAN, nnp::NeuralNetwork::AF_HARMONIC, nnp::NeuralNetwork::AF_IDENTITY, nnp::NeuralNetwork::AF_LOGISTIC, nnp::NeuralNetwork::AF_RELU, nnp::NeuralNetwork::AF_REVLOGISTIC, nnp::NeuralNetwork::AF_SOFTPLUS, and nnp::NeuralNetwork::AF_TANH.
Referenced by nnp::Mode::setupNeuralNetwork().
split()
std::vector< std::string > nnp::split (std::string const & input, char delimiter = ' ')
Split string at each delimiter.
Parameters
[in] input Input string.
[in] delimiter Delimiter character (default ' ').
Returns
Vector containing the string parts.
Definition at line 33 of file utility.cpp.
{
    vector<string> parts;
    stringstream ss;
    ss.str(input);
    string item;
    while (getline(ss, item, delimiter)) {
        parts.push_back(item);
    }
    return parts;
}
Referenced by nnp::SymFnc::addCacheIndex(), nnp::Element::addSymmetryFunction(), nnp::ElementCabana::addSymmetryFunction(), nnp::Training::dataSetNormalization(), nnp::Dataset::getNumStructures(), nnp::InterfaceLammps::initialize(), main(), readColumnsFromFile(), nnp::Structure::readFromFile(), nnp::Structure::readFromLines(), nnp::ElementMap::registerElements(), nnp::SymFncBaseCompAng::setParameters(), nnp::SymFncBaseCompAngWeighted::setParameters(), nnp::SymFncBaseExpAng::setParameters(), nnp::SymFncCompRad::setParameters(), nnp::SymFncCompRadWeighted::setParameters(), nnp::SymFncExpAngnWeighted::setParameters(), nnp::SymFncExpRad::setParameters(), nnp::SymFncExpRadWeighted::setParameters(), nnp::SymFnc::setScalingType(), nnp::ElementCabana::setScalingType(), nnp::Mode::setupCutoff(), nnp::Mode::setupElectrostatics(), nnp::ModeCabana< t_device >::setupElementMap(), nnp::Mode::setupElements(), nnp::ModeCabana< t_device >::setupElements(), nnp::Training::setupFileOutput(), nnp::Mode::setupNeuralNetwork(), nnp::ModeCabana< t_device >::setupNeuralNetwork(), nnp::ModeCabana< t_device >::setupNeuralNetworkWeights(), nnp::Training::setupSelectionMode(), nnp::Mode::setupSymmetryFunctionCache(), nnp::Mode::setupSymmetryFunctions(), nnp::ModeCabana< t_device >::setupSymmetryFunctions(), and nnp::Structure::writeToFilePoscar().
trim()
std::string nnp::trim (std::string const & line, std::string const & whitespace = " \t")
Remove leading and trailing whitespaces from string.
Parameters
[in] line Input string.
[in] whitespace All characters identified as whitespace (default: " \t").
Returns
String without leading and trailing whitespaces.
Definition at line 47 of file utility.cpp.
{
    size_t const begin = line.find_first_not_of(whitespace);
    if (begin == string::npos)
    {
        return "";
    }
    size_t const end = line.find_last_not_of(whitespace);
    size_t const range = end - begin + 1;
    return line.substr(begin, range);
}
Referenced by nnp::InterfaceLammps::initialize(), and reduce().
reduce()
std::string nnp::reduce (std::string const & line, std::string const & whitespace = " \t", std::string const & fill = " ")
Replace multiple whitespaces with fill.
Parameters
[in] line Input string.
[in] whitespace All characters identified as whitespace (default: " \t").
[in] fill Replacement character (default: " ").
Returns
String with fill replacements.
Calls trim() at the beginning.
Definition at line 60 of file utility.cpp.
{
    string result = trim(line, whitespace);
    size_t begin = result.find_first_of(whitespace);
    while (begin != string::npos)
    {
        size_t const end = result.find_first_not_of(whitespace, begin);
        size_t const range = end - begin;
        result.replace(begin, range, fill);
        size_t const newBegin = begin + fill.length();
        begin = result.find_first_of(whitespace, newBegin);
    }
    return result;
}
References trim().
Referenced by nnp::Element::addSymmetryFunction(), nnp::ElementCabana::addSymmetryFunction(), nnp::Dataset::getNumStructures(), nnp::InterfaceLammps::initialize(), main(), nnp::settings::Settings::parseLines(), readColumnsFromFile(), nnp::Structure::readFromFile(), nnp::Structure::readFromLines(), nnp::ElementMap::registerElements(), nnp::SymFncBaseCompAng::setParameters(), nnp::SymFncBaseCompAngWeighted::setParameters(), nnp::SymFncBaseExpAng::setParameters(), nnp::SymFncCompRad::setParameters(), nnp::SymFncCompRadWeighted::setParameters(), nnp::SymFncExpAngnWeighted::setParameters(), nnp::SymFncExpRad::setParameters(), nnp::SymFncExpRadWeighted::setParameters(), nnp::SymFnc::setScalingType(), nnp::ElementCabana::setScalingType(), nnp::Mode::setupElectrostatics(), nnp::ModeCabana< t_device >::setupElementMap(), nnp::Mode::setupElements(), nnp::ModeCabana< t_device >::setupElements(), nnp::Training::setupFileOutput(), nnp::Mode::setupNeuralNetwork(), nnp::ModeCabana< t_device >::setupNeuralNetwork(), nnp::ModeCabana< t_device >::setupNeuralNetworkWeights(), nnp::Mode::setupSymmetryFunctions(), and nnp::ModeCabana< t_device >::setupSymmetryFunctions().
pad() [1/2]
string nnp::pad (string const & input, size_t num, char fill, bool right)
Definition at line 79 of file utility.cpp.
{
    string result = input;
    if (input.size() >= num) return result;
    string pad(num - input.size(), fill);
    if (right) return result + pad;
    else return pad + result;
}
References pad().
Referenced by pad(), nnp::SymFnc::parameterInfo(), nnp::SymFncBaseComp::parameterInfo(), nnp::SymFncBaseCompAng::parameterInfo(), nnp::SymFncBaseCompAngWeighted::parameterInfo(), nnp::SymFncBaseCutoff::parameterInfo(), nnp::SymFncBaseExpAng::parameterInfo(), nnp::SymFncCompRad::parameterInfo(), nnp::SymFncExpAngnWeighted::parameterInfo(), nnp::SymFncExpRad::parameterInfo(), and nnp::SymFncExpRadWeighted::parameterInfo().
strpr()
std::string nnp::strpr (const char * format, ...)
String version of printf function.
Definition at line 90 of file utility.cpp.
{
    char buffer[STRPR_MAXBUF];
    va_list args;
    va_start(args, format);
    vsprintf(buffer, format, args);
    va_end(args);
    string s(buffer);
    return s;
}
References STRPR_MAXBUF.
Referenced by nnp::SymFnc::addCacheIndex(), nnp::Training::addTrainingLogEntry(), nnp::Training::allocateArrays(), nnp::Training::calculateError(), nnp::Training::calculateErrorEpoch(), nnp::Training::calculateNeighborLists(), nnp::Mode::calculateSymmetryFunctionGroups(), nnp::Mode::calculateSymmetryFunctions(), nnp::Training::checkSelectionMode(), nnp::Dataset::collectSymmetryFunctionStatistics(), nnp::Dataset::combineFiles(), nnp::Training::dataSetNormalization(), nnp::Dataset::distributeStructures(), nnp::SymFncBaseCompAng::getCacheIdentifiers(), nnp::SymFncBaseCompAngWeighted::getCacheIdentifiers(), nnp::SymFncBaseExpAng::getCacheIdentifiers(), nnp::SymFncCompRad::getCacheIdentifiers(), nnp::SymFncCompRadWeighted::getCacheIdentifiers(), nnp::SymFncExpAngnWeighted::getCacheIdentifiers(), nnp::SymFncExpRad::getCacheIdentifiers(), nnp::SymFncExpRadWeighted::getCacheIdentifiers(), nnp::Atom::getChargeLine(), nnp::ElementMap::getElementsString(), nnp::Structure::getEnergyLine(), nnp::SymFncStatistics::getExtrapolationWarningLines(), nnp::Atom::getForcesLines(), nnp::SymFncBaseCompAng::getSettingsLine(), nnp::SymFncBaseCompAngWeighted::getSettingsLine(), nnp::SymFncBaseExpAng::getSettingsLine(), nnp::SymFncCompRad::getSettingsLine(), nnp::SymFncCompRadWeighted::getSettingsLine(), nnp::SymFncExpAngnWeighted::getSettingsLine(), nnp::SymFncExpRad::getSettingsLine(), nnp::SymFncExpRadWeighted::getSettingsLine(), nnp::Atom::Neighbor::info(), nnp::Atom::info(), nnp::CoreFunction::info(), nnp::ElementMap::info(), nnp::NeuralNetwork::info(), nnp::ScreeningFunction::info(), nnp::Structure::info(), nnp::GradientDescent::info(), nnp::KalmanFilter::info(), nnp::InterfaceLammps::initialize(), nnp::Training::initializeWeightsMemory(), nnp::Mode::loadSettingsFile(), nnp::EwaldSetup::logEwaldCutoffs(), nnp::Training::loop(), main(), nnp::SymFnc::parameterInfo(), nnp::SymFncBaseComp::parameterInfo(), nnp::SymFncBaseCompAng::parameterInfo(), nnp::SymFncBaseCompAngWeighted::parameterInfo(), nnp::SymFncBaseCutoff::parameterInfo(), nnp::SymFncBaseExpAng::parameterInfo(), nnp::SymFncCompRad::parameterInfo(), nnp::SymFncExpAngnWeighted::parameterInfo(), nnp::SymFncExpRad::parameterInfo(), nnp::SymFncExpRadWeighted::parameterInfo(), nnp::SymFncBaseCompAng::parameterLine(), nnp::SymFncBaseCompAngWeighted::parameterLine(), nnp::SymFncBaseExpAng::parameterLine(), nnp::SymFncCompRad::parameterLine(), nnp::SymFncCompRadWeighted::parameterLine(), nnp::SymFncExpAngnWeighted::parameterLine(), nnp::SymFncExpRad::parameterLine(), nnp::SymFncExpRadWeighted::parameterLine(), nnp::SymGrpBaseCompAng::parameterLines(), nnp::SymGrpBaseCompAngWeighted::parameterLines(), nnp::SymGrpBaseExpAng::parameterLines(), nnp::SymGrpCompRad::parameterLines(), nnp::SymGrpCompRadWeighted::parameterLines(), nnp::SymGrpExpAngnWeighted::parameterLines(), nnp::SymGrpExpRad::parameterLines(), nnp::SymGrpExpRadWeighted::parameterLines(), nnp::settings::Settings::parseLines(), nnp::Dataset::prepareNumericForces(), nnp::Training::printEpoch(), nnp::Training::printHeader(), nnp::Training::randomizeNeuralNetworkWeights(), nnp::settings::Settings::readFile(), nnp::Mode::readNeuralNetworkWeights(), runTest(), nnp::settings::Settings::sanityCheck(), nnp::SymFnc::scalingLine(), nnp::ElementCabana::scalingLine(), nnp::Training::selectSets(), nnp::SymFncBaseComp::setCompactFunction(), nnp::SymFncBaseCutoff::setCutoffFunction(), nnp::Element::setScalingNone(), nnp::Training::setStage(), nnp::Mode::setupCutoff(), nnp::Mode::setupElectrostatics(), nnp::Mode::setupElementMap(), nnp::ModeCabana< t_device >::setupElementMap(), nnp::Mode::setupElements(), nnp::ModeCabana< t_device >::setupElements(), nnp::Training::setupFileOutput(), nnp::Dataset::setupMPI(), nnp::Mode::setupNeuralNetwork(), nnp::ModeCabana< t_device >::setupNeuralNetwork(), nnp::ModeCabana< t_device >::setupNeuralNetworkWeights(), nnp::Mode::setupNeuralNetworkWeights(), nnp::Mode::setupNormalization(), nnp::Dataset::setupRandomNumberGenerator(), nnp::Training::setupSelectionMode(), nnp::Mode::setupSymmetryFunctionCache(), nnp::Mode::setupSymmetryFunctionGroups(), nnp::ModeCabana< t_device >::setupSymmetryFunctionGroups(), nnp::Mode::setupSymmetryFunctionMemory(), nnp::Mode::setupSymmetryFunctions(), nnp::ModeCabana< t_device >::setupSymmetryFunctions(), nnp::Mode::setupSymmetryFunctionScaling(), nnp::ModeCabana< t_device >::setupSymmetryFunctionScaling(), nnp::Mode::setupSymmetryFunctionStatistics(), nnp::Training::setupTraining(), nnp::Training::setupUpdatePlan(), nnp::GradientDescent::status(), nnp::KalmanFilter::status(), nnp::ElementMap::symbolFromAtomicNumber(), nnp::Element::updateSymmetryFunctionStatistics(), nnp::Dataset::writeAtomicEnvironmentFile(), nnp::NeuralNetwork::writeConnections(), nnp::Training::writeHardness(), nnp::Training::writeHardnessEpoch(), nnp::Training::writeLearningCurve(), nnp::Dataset::writeNeighborHistogram(), nnp::Dataset::writeNeighborLists(), nnp::Training::writeNeuronStatistics(), nnp::Training::writeNeuronStatisticsEpoch(), nnp::Training::writeSetsToFiles(), nnp::Dataset::writeSymmetryFunctionFile(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), nnp::SetupAnalysis::writeSymmetryFunctionShape(), nnp::Training::writeTimingData(), nnp::Structure::writeToFile(), nnp::Structure::writeToFilePoscar(), nnp::Structure::writeToFileXyz(), nnp::Training::writeUpdaterStatus(), nnp::Training::writeWeights(), and nnp::Training::writeWeightsEpoch().
cap()
std::string nnp::cap (std::string word)
Capitalize first letter of word.
Parameters
[in] word String to capitalize.
Returns
Input string with first letter in capital letters.
Definition at line 104 of file utility.cpp.
{
    word[0] = toupper(word[0]);
    return word;
}
Referenced by nnp::Mode::setupNeuralNetworkWeights().
createFileHeader() [1/2]
vector< string > nnp::createFileHeader (vector< string > const & title, vector< size_t > const & colSize, vector< string > const & colName, vector< string > const & colInfo, char const & commentChar)
Definition at line 111 of file utility.cpp.
{
    size_t const stdWidth = 80;
    vector<string> h;
    if (!(colSize.size() == colName.size() &&
          colName.size() == colInfo.size()))
    {
        throw runtime_error("ERROR: Could not create file header, column sizes"
                            " are not equal.\n");
    }
    size_t numCols = colSize.size();
    // Separator line definition.
    string sepLine(stdWidth, commentChar);
    sepLine += '\n';
    // Start string.
    string startStr(1, commentChar);
    // Add title lines.
    h.push_back(sepLine);
    for (vector<string>::const_iterator it = title.begin();
         it != title.end(); ++it)
    {
        h.push_back(startStr + ' ' + (*it) + '\n');
    }
    h.push_back(sepLine);
    // Determine maximum width of names.
    size_t widthNames = 0;
    for (vector<string>::const_iterator it = colName.begin();
         it != colName.end(); ++it)
    {
        widthNames = max(widthNames, it->size());
    }
    // Column description section.
    stringstream s;
    s << startStr << ' '
      << left << setw(4) << "Col" << ' '
      << left << setw(widthNames) << "Name" << ' '
      << left << "Description\n";
    h.push_back(s.str());
    h.push_back(sepLine);
    for (size_t i = 0; i < numCols; ++i)
    {
        s.clear();
        s.str(string());
        s << startStr << ' '
          << left << setw(4) << i + 1 << ' '
          << left << setw(widthNames) << colName.at(i) << ' '
          << colInfo.at(i) << '\n';
        h.push_back(s.str());
    }
    // Determine total data width.
    size_t widthData = 0;
    for (vector<size_t>::const_iterator it = colSize.begin();
         it != colSize.end(); ++it)
    {
        widthData += (*it) + 1;
    }
    widthData -= 1;
    if (widthData > stdWidth)
    {
        // Long separator line.
        h.push_back(string(widthData, commentChar) + "\n");
    }
    else
    {
        h.push_back(sepLine);
    }
    // Write column number.
    s.clear();
    s.str(string());
    s << startStr;
    for (size_t i = 0; i < numCols; ++i)
    {
        size_t n = colSize.at(i);
        if (i == 0) n -= 2;
        s << ' ' << right << setw(n) << i + 1;
    }
    s << '\n';
    h.push_back(s.str());
    // Write column name.
    s.clear();
    s.str(string());
    s << startStr;
    for (size_t i = 0; i < numCols; ++i)
    {
        size_t n = colSize.at(i);
        if (i == 0) n -= 2;
        string name = colName.at(i);
        if (name.size() > n)
        {
            name.erase(n, string::npos);
        }
        s << ' ' << right << setw(n) << name;
    }
    s << '\n';
    h.push_back(s.str());
    // Long separator line.
    h.push_back(string(widthData, commentChar) + "\n");
    return h;
}
Referenced by nnp::Training::calculateError(), nnp::Training::dataSetNormalization(), main(), nnp::Training::setupTraining(), nnp::GradientDescent::statusHeader(), nnp::KalmanFilter::statusHeader(), nnp::NeuralNetwork::writeConnections(), nnp::Training::writeLearningCurve(), nnp::Dataset::writeNeighborHistogram(), nnp::Training::writeNeuronStatistics(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), nnp::SetupAnalysis::writeSymmetryFunctionShape(), and nnp::Training::writeTimingData().
appendLinesToFile() [1/2]
void nnp::appendLinesToFile (std::ofstream & file, std::vector< std::string > const lines)
Append multiple lines of strings to open file stream.
Parameters
[in,out] file File stream to append lines to.
[in] lines Vector of strings with line content.
Definition at line 225 of file utility.cpp.
{
    for (vector<string>::const_iterator it = lines.begin();
         it != lines.end(); ++it)
    {
        file << (*it);
    }
    return;
}
Referenced by nnp::Training::calculateError(), nnp::Training::dataSetNormalization(), main(), nnp::Training::setupTraining(), nnp::NeuralNetwork::writeConnections(), nnp::Training::writeLearningCurve(), nnp::Dataset::writeNeighborHistogram(), nnp::Training::writeNeuronStatistics(), nnp::Dataset::writeSymmetryFunctionHistograms(), nnp::Dataset::writeSymmetryFunctionScaling(), nnp::SetupAnalysis::writeSymmetryFunctionShape(), nnp::Training::writeTimingData(), and nnp::Training::writeUpdaterStatus().
appendLinesToFile() [2/2]
void nnp::appendLinesToFile (FILE *const & file, std::vector< std::string > const lines)
Append multiple lines of strings to open file pointer.
Parameters
[in,out] file File pointer.
[in] lines Vector of strings with line content.
Definition at line 236 of file utility.cpp.
{
    for (vector<string>::const_iterator it = lines.begin();
         it != lines.end(); ++it)
    {
        fprintf(file, "%s", it->c_str());
    }
    return;
}
readColumnsFromFile() [1/2]
map< size_t, vector< double > > nnp::readColumnsFromFile (string fileName, vector< size_t > columns, char comment)
Definition at line 247 of file utility.cpp.
{
    map<size_t, vector<double>> result;
    sort(columns.begin(), columns.end());
    for (auto col : columns)
    {
        result[col] = vector<double>();
    }
    ifstream file;
    file.open(fileName.c_str());
    if (!file.is_open())
    {
        throw runtime_error("ERROR: Could not open file: \"" + fileName
                            + "\".\n");
    }
    string line;
    while (getline(file, line))
    {
        if (line.size() == 0) continue;
        if (line.at(0) != comment)
        {
            vector<string> splitLine = split(reduce(line));
            for (auto col : columns)
            {
                if (col >= splitLine.size())
                {
                    result[col].push_back(
                        std::numeric_limits<double>::quiet_NaN());
                }
                else
                {
                    result[col].push_back(atof(splitLine.at(col).c_str()));
                }
            }
        }
    }
    file.close();
    return result;
}
References reduce(), and split().
Referenced by nnp::Mode::readNeuralNetworkWeights(), and nnp::Mode::setupElectrostatics().
pow_int()
double nnp::pow_int (double x, int n)
Integer version of power function, "fast exponentiation algorithm".
Parameters
[in] x Base number.
[in] n Integer exponent.
Returns
x^n
Definition at line 292 of file utility.cpp.
{
    // Need an unsigned integer for bit-shift divison.
    unsigned int m;
    // If negative exponent, take the inverse of x and change sign of n.
    if (n < 0)
    {
        x = 1.0 / x;
        m = -n;
    }
    else m = n;
    // Exponentiation by squaring, "fast exponentiation algorithm"
    double result = 1.0;
    do
    {
        if (m & 1) result *= x;
        // Division by 2.
        m >>= 1;
        x *= x;
    }
    while (m);
    return result;
}
Referenced by nnp::SymFncExpAngn::calculate(), nnp::SymFncExpAngnWeighted::calculate(), nnp::SymFncExpAngw::calculate(), nnp::SymGrpExpAngn::calculate(), nnp::SymGrpExpAngnWeighted::calculate(), and nnp::SymGrpExpAngw::calculate().
pad() [2/2]
std::string nnp::pad (std::string const & input, std::size_t num, char fill = ' ', bool right = true)
Pad string to given length with fill character.
Parameters
[in] input Input string.
[in] num Desired width of padded string.
[in] fill Padding character.
[in] right If true, pad right. Pad left otherwise.
Returns
String padded to desired length or original string if length of old string is not shorter than desired length.
createFileHeader() [2/2]
std::vector< std::string > nnp::createFileHeader (std::vector< std::string > const & title, std::vector< std::size_t > const & colLength, std::vector< std::string > const & colName, std::vector< std::string > const & colInfo, char const & commentChar = '#')
Generate output file header with info section and column labels.
Parameters
[in] title Multiple lines of title text.
[in] colLength Length of the individual columns.
[in] colName Names of the individual columns.
[in] colInfo Description of the individual columns.
[in] commentChar Character used for starting each line and to create separator lines.
Returns
Vector of strings, one entry per line.
readColumnsFromFile() [2/2]
std::map< std::size_t, std::vector< double > > nnp::readColumnsFromFile (std::string fileName, std::vector< std::size_t > columns, char comment = '#')
Read multiple columns of data from file.
Parameters
[in] fileName Name of data file.
[in] columns Vector with column indices of interest (starting with 0).
[in] comment Lines starting with comment sign are ignored.
Returns
Map from column index to vector of data.
safeFind()
template<typename K , typename V > V const & nnp::safeFind (std::map< K, V > const & stdMap, typename std::map< K, V >::key_type const & key)
Safely access map entry.
Parameters
[in] stdMap Map to search in.
[in] key Key requested.
The .at() member function of maps is available only for C++11.
Definition at line 144 of file utility.h.
{
    if (stdMap.find(key) == stdMap.end())
    {
        std::stringstream message;
        message << "ERROR: No map entry found for key \"";
        message << key;
        message << "\".\n";
        throw std::range_error(message.str());
    }
    return stdMap.find(key)->second;
}
Referenced by nnp::SymFnc::getPrintFormat(), nnp::SymGrp::getPrintFormatCommon(), nnp::SymGrp::getPrintFormatMember(), nnp::ElementMap::index(), nnp::ElementMap::symbol(), and nnp::Dataset::writeSymmetryFunctionHistograms().
vectorContains()
template<typename T > bool nnp::vectorContains (std::vector< T > const & stdVec, T value)
Test if vector contains specified value.
Parameters
[in] stdVec Vector to search in.
[in] value Value to search for.
Returns
True if value is located in vector.
Definition at line 166 of file utility.h.
{
    return (std::find(stdVec.begin(), stdVec.end(), value) != stdVec.end());
}
Referenced by nnp::Element::getCutoffRadii(), nnp::Mode::setupCutoffMatrix(), and nnp::Structure::setupNeighborCutoffMap().
unorderedMapContainsKey()
template<typename T , typename U > bool nnp::unorderedMapContainsKey (std::unordered_map< T, U > const & stdMap, T key)
Test if unordered map contains specified key.
Parameters
[in] stdMap Map to search in.
[in] key Key to search for.
Returns
True if key is located in map.
Definition at line 179 of file utility.h.
{
    return ( stdMap.find(key) != stdMap.end() );
}
Referenced by nnp::Atom::calculateNumNeighbors(), and nnp::Atom::getStoredMinNumNeighbors().
comparePointerTargets()
template<typename T > bool nnp::comparePointerTargets (T * lhs, T * rhs)
Compare pointer targets.
Parameters
[in] lhs Pointer to left side of comparison.
[in] rhs Pointer to right side of comparison.
Returns
True if dereferenced lhs < dereferenced rhs, False otherwise.
Definition at line 194 of file utility.h.
{
    return ((*lhs) < (*rhs));
}
operator+()
Vec3D nnp::operator+ (Vec3D lhs, Vec3D const & rhs) inline
Overload + operator to implement vector addition.
Returns
Sum of two vectors.
Definition at line 330 of file Vec3D.h.
{
    return lhs += rhs;
}
operator-() [1/2]
Vec3D nnp::operator- (Vec3D lhs, Vec3D const & rhs) inline
Overload - operator to implement vector subtraction.
Returns
Difference between two vectors.
Definition at line 335 of file Vec3D.h.
{
    return lhs -= rhs;
}
operator-() [2/2]
Vec3D nnp::operator- (Vec3D v) inline
Overload - operator to implement vector sign change.
Returns
Negative vector.
Definition at line 340 of file Vec3D.h.
{
    v *= -1.0;
    return v;
}
operator*() [1/3]
Vec3D nnp::operator* (Vec3D v, double const a) inline
Overload * operator to implement multiplication with scalar.
Returns
Vector multiplied with scalar.
Definition at line 346 of file Vec3D.h.
{
    return v *= a;
}
operator*() [2/3]
Vec3D nnp::operator* (Vec3D const (&) A[3], Vec3D v) inline
Overload * operator to implement (left) multiplication with a matrix.
Returns
Vector multiplied with a matrix.
Definition at line 361 of file Vec3D.h.
{
    return v *= A;
}
operator/()
Vec3D nnp::operator/ (Vec3D v, double const a) inline
Overload / operator to implement division by scalar.
Returns
Vector divided by scalar.
Definition at line 351 of file Vec3D.h.
{
    return v /= a;
}
operator*() [3/3]
Vec3D nnp::operator* (double const a, Vec3D v) inline
Overload * operator to implement multiplication with scalar (scalar first).
Returns
Vector multiplied with scalar.
Definition at line 356 of file Vec3D.h.
{
    return v *= a;
}
Variable Documentation
TrOverTk
double constexpr nnp::TrOverTk = 3.676 constexpr
Definition at line 14 of file EwaldTruncKolafaOptEta.cpp.
Referenced by nnp::EwaldTruncKolafaOptEta::calculateEta().