n2p2 - A neural network potential package: /home/runner/work/n2p2/n2p2/src/application/nnp-train.cpp File Reference
nnp-train.cpp File Reference
#include "Training.h"
#include "utility.h"
#include <mpi.h>
#include <cstddef>
#include <cstdlib>
#include <fstream>
#include <string>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 28 of file nnp-train.cpp.
{
    int numProcs = 0;
    int myRank   = 0;
    size_t stage = 0;
    ofstream myLog;
    string suffix = "";
    if (argc > 1)
    {
        stage = (size_t)atoi(argv[1]);
        suffix = strpr(".stage-%zu", stage);
    }
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &numProcs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myRank);
    // Basic setup.
    Training training;
    if (myRank != 0) training.log.writeToStdout = false;
    myLog.open((strpr("nnp-train.log.%04d", myRank) + suffix).c_str());
    training.log.registerStreamPointer(&myLog);
    training.setupMPI();
    training.initialize();
    training.loadSettingsFile();
    training.setStage(stage);
    // If initial-weights-based normalization is enabled skip normalization
    // setup here.
    training.setupGeneric(
        training.settingsKeywordExists("normalize_data_set")
    );
    training.setupSymmetryFunctionScaling();
    training.setupSymmetryFunctionStatistics(false, false, false, false);
    training.setupRandomNumberGenerator();
    // Distribute structures to MPI processes.
    training.distributeStructures(true);
    // Randomly select training/test set and write them to separate files
    // (train.data/test.data, same format as input.data).
    training.selectSets();
    training.writeSetsToFiles();
    // Initialize weights and biases for neural networks.
    training.initializeWeights();
    // Run data set normalization if keyword present.
    if (training.settingsKeywordExists("normalize_data_set"))
    {
        training.dataSetNormalization();
    }
    // Switch to normalized units, convert all structures.
    if (training.useNormalization()) training.toNormalizedUnits();
    // General training settings and weight update routine.
    training.setupTraining();
    // Calculate neighbor lists for all structures.
    training.calculateNeighborLists();
    // The main training loop.
    training.loop();
    myLog.close();
    MPI_Finalize();
    return 0;
}
References nnp::Training::calculateNeighborLists(), nnp::Training::dataSetNormalization(), nnp::Dataset::distributeStructures(), nnp::Mode::initialize(), nnp::Training::initializeWeights(), nnp::Mode::loadSettingsFile(), nnp::Mode::log, nnp::Training::loop(), nnp::Log::registerStreamPointer(), nnp::Training::selectSets(), nnp::Training::setStage(), nnp::Mode::settingsKeywordExists(), nnp::Mode::setupGeneric(), nnp::Dataset::setupMPI(), nnp::Dataset::setupRandomNumberGenerator(), nnp::Mode::setupSymmetryFunctionScaling(), nnp::Mode::setupSymmetryFunctionStatistics(), nnp::Training::setupTraining(), nnp::strpr(), nnp::Dataset::toNormalizedUnits(), nnp::Mode::useNormalization(), nnp::Training::writeSetsToFiles(), and nnp::Log::writeToStdout.