n2p2 - A neural network potential package: /home/runner/work/n2p2/n2p2/src/application/nnp-symfunc.cpp File Reference
nnp-symfunc.cpp File Reference
#include "SetupAnalysis.h"
#include "utility.h"
#include <cstdlib>
#include <iostream>
#include <fstream>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 26 of file nnp-symfunc.cpp.
{
    size_t numPoints = 0;
    ofstream logFile;
    if (argc != 2)
    {
        cout << "USAGE: " << argv[0] << " <npoints>\n"
                "        <npoints> ... Number of data points in symmetry"
                " function files.\n"
                "       Execute in directory with these NNP files present:\n"
             << "       - input.nn (NNP settings)\n";
        return 1;
    }
    numPoints = atof(argv[1]);
    logFile.open("nnp-symfunc.log");
    SetupAnalysis setupAnalysis;
    setupAnalysis.log.registerStreamPointer(&logFile);
    setupAnalysis.initialize();
    setupAnalysis.loadSettingsFile();
    setupAnalysis.setupElementMap();
    setupAnalysis.setupElements();
    setupAnalysis.setupCutoff();
    setupAnalysis.setupSymmetryFunctions();
    setupAnalysis.writeSymmetryFunctionShape(numPoints);
    logFile.close();
    return 0;
}
References nnp::Mode::initialize(), nnp::Mode::loadSettingsFile(), nnp::Mode::log, logFile, nnp::Log::registerStreamPointer(), nnp::Mode::setupCutoff(), nnp::Mode::setupElementMap(), nnp::Mode::setupElements(), nnp::Mode::setupSymmetryFunctions(), and nnp::SetupAnalysis::writeSymmetryFunctionShape().