n2p2 - A neural network potential package: nnp::Training::PropertyMap Struct Reference
nnp::Training::PropertyMap Struct Reference
Map of all training properties.
Public Member Functions
Property & operator[] (std::string const &key)
Overload [] operator to simplify access.
Property const & operator[] (std::string const &key) const
Overload [] operator to simplify access (const version).
bool exists (std::string const &key)
Check if property is present.
Detailed Description
Map of all training properties.
Definition at line 389 of file Training.h.
Member Function Documentation
operator[]() [1/2]
Property& nnp::Training::PropertyMap::operator[] (std::string const & key) inline
Overload [] operator to simplify access.
Definition at line 392 of file Training.h.
 {return this->at(key);}
operator[]() [2/2]
Property const& nnp::Training::PropertyMap::operator[] (std::string const & key) const inline
Overload [] operator to simplify access (const version).
Definition at line 394 of file Training.h.
         {
             return this->at(key);
         }
exists()
bool nnp::Training::PropertyMap::exists (std::string const & key) inline
Check if property is present.
Definition at line 399 of file Training.h.
         {
             return (this->find(key) != this->end());
         }
Referenced by nnp::Training::selectSets(), nnp::Training::setupTraining(), and nnp::Training::setupUpdatePlan().
The documentation for this struct was generated from the following file:
/home/runner/work/n2p2/n2p2/src/libnnptrain/Training.h