n2p2 - A neural network potential package: nnp::ErfcBuf Struct Reference
nnp::ErfcBuf Struct Reference
Helper class to store previously calculated values of erfc() that are needed during the charge equilibration.
#include <ErfcBuf.h>
Public Member Functions
void reset (std::vector< Atom > const &atoms, size_t const valuesPerPair)
Resizes and resets the storage array to fit the current structure.
double getf (size_t const atomIndex, size_t const neighIndex, size_t const valIndex, double const x)
Either returns already stored value erfc(x) or calculates it if not yet stored.
Public Attributes
std::vector< std::vector< double > > f
2d vector to store already calculated results.
size_t numValuesPerPair = 1
Typically one needs erfc(a_i * rij), where the number of a_i's correspond to numValuesPerPair.
Detailed Description
Helper class to store previously calculated values of erfc() that are needed during the charge equilibration.
Definition at line 16 of file ErfcBuf.h.
Member Function Documentation
reset()
void ErfcBuf::reset (std::vector< Atom > const & atoms, size_t const valuesPerPair)
Resizes and resets the storage array to fit the current structure.
Parameters
[in] atoms Vector of atoms of the structure.
[in] valuesPerPair Number of values that are stored for each neighbor pair (intended use is for erfc(rij...)).
Definition at line 10 of file ErfcBuf.cpp.
{
    f.resize(atoms.size());
    for(size_t i = 0; i < atoms.size(); ++i)
    {
        f[i].resize(atoms[i].numNeighbors * valuesPerPair);
        fill(f[i].begin(), f[i].end(), -1.0);
    }
    numValuesPerPair = valuesPerPair;
}
References f, and numValuesPerPair.
Referenced by nnp::Structure::calculateElectrostaticEnergy().
getf()
double ErfcBuf::getf (size_t const atomIndex, size_t const neighIndex, size_t const valIndex, double const x)
Either returns already stored value erfc(x) or calculates it if not yet stored.
Parameters
[in] atomIndex Index of atom.
[in] neighIndex Index of neighbor of this atom.
[in] valIndex Index corresponds to the value that is requested, see numValuesPerPair.
[in] x Corresponds to erfc(x). Only used when result is not stored yet.
Definition at line 21 of file ErfcBuf.cpp.
{
    size_t j = neighIndex * numValuesPerPair + valIndex;
    if (f.at(atomIndex).at(j) == -1.0)
    {
        f[atomIndex][j] = erfc(x);
    }
    return f[atomIndex][j];
}
References f, and numValuesPerPair.
Referenced by nnp::Structure::calculateDAdrQ(), and nnp::Structure::calculateElectrostaticEnergy().
Member Data Documentation
f
std::vector<std::vector<double> > nnp::ErfcBuf::f
2d vector to store already calculated results.
Elements set to -1 indicate that this value has not been calculated yet.
Definition at line 41 of file ErfcBuf.h.
Referenced by getf(), and reset().
numValuesPerPair
size_t nnp::ErfcBuf::numValuesPerPair = 1
Typically one needs erfc(a_i * rij), where the number of a_i's correspond to numValuesPerPair.
Definition at line 44 of file ErfcBuf.h.
Referenced by getf(), and reset().
The documentation for this struct was generated from the following files:
/home/runner/work/n2p2/n2p2/src/libnnp/ErfcBuf.h
/home/runner/work/n2p2/n2p2/src/libnnp/ErfcBuf.cpp